### ISSUE TITLE
rpc error when importing aws_spot_fleet_request

### ISSUE THREAD

**Issue by l-bluejay** [hashicorp/terraform-provider-aws#15239]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```hcl
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/aws v3.7.0
```

### Affected Resource(s)

* aws_spot_fleet_request

### Terraform Configuration Files

```hcl
resource "aws_spot_fleet_request" "zs" {

}
```

### Debug Output

https://gist.github.com/l-bluejay/bb612b8247ec39dcf9e2b9e6cfb9b484

### Expected Behavior

Successful import of spot fleet request

### Actual Behavior

Terraform crash / no import with 
```hcl
Error: rpc error: code = Unavailable desc = transport is closing
```

### Steps to Reproduce

1. `terraform import aws_spot_fleet_request.request <request id>`

### References

none

**Comment by ewbankkit** [comment]
Relevant section of the log:

```
2020-09-21T12:52:40.878+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: 2020/09/21 12:52:40 [DEBUG] Describing AMI "ami-0c115dbd34c69a004" to get root block device name
2020-09-21T12:52:41.005+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: panic: interface conversion: interface {} is nil, not string
2020-09-21T12:52:41.005+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: 
2020-09-21T12:52:41.005+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: goroutine 102 [running]:
2020-09-21T12:52:41.005+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: github.com/terraform-providers/terraform-provider-aws/aws.hashLaunchSpecification(0x59e82e0, 0xc001218780, 0xc000fdc070)
2020-09-21T12:52:41.005+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_spot_fleet_request.go:1618 +0x573
2020-09-21T12:52:41.005+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).hash(0xc000fdc060, 0x59e82e0, 0xc001218780, 0x6706901, 0x4)
2020-09-21T12:52:41.005+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/set.go:251 +0x3d
2020-09-21T12:52:41.005+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).add(0xc000fdc060, 0x59e82e0, 0xc001218780, 0xc000fe3d00, 0x0, 0x0)
2020-09-21T12:52:41.005+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/set.go:231 +0x83
2020-09-21T12:52:41.005+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).Add(...)
2020-09-21T12:52:41.006+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/set.go:75
2020-09-21T12:52:41.006+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: github.com/terraform-providers/terraform-provider-aws/aws.launchSpecsToSet(0xc00000e528, 0x1, 0x1, 0xc0000948b0, 0xc00175d8a0, 0x0, 0x0)
2020-09-21T12:52:41.006+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_spot_fleet_request.go:1263 +0x7b
2020-09-21T12:52:41.006+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsSpotFleetRequestRead(0xc001cfeb00, 0x5b7ae40, 0xc001cf5400, 0xa5fd080, 0x6833388)
2020-09-21T12:52:41.006+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_spot_fleet_request.go:1180 +0x43f
2020-09-21T12:52:41.006+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000465080, 0x72044e0, 0xc001c1c900, 0xc001cfeb00, 0x5b7ae40, 0xc001cf5400, 0x0, 0x0, 0x0)
2020-09-21T12:52:41.006+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:281 +0x88
2020-09-21T12:52:41.006+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000465080, 0x72044e0, 0xc001c1c900, 0xc0011819d0, 0x5b7ae40, 0xc001cf5400, 0xc000095d88, 0x0, 0x0, 0x0)
2020-09-21T12:52:41.006+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:555 +0x1c2
2020-09-21T12:52:41.006+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc000ac7200, 0x72044e0, 0xc001c1c900, 0xc001b7bbc0, 0xc000ac7200, 0xc000ac7210, 0x6833378)
2020-09-21T12:52:41.006+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/internal/helper/plugin/grpc_provider.go:572 +0x42f
2020-09-21T12:52:41.006+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/internal/tfplugin5._Provider_ReadResource_Handler.func1(0x72044e0, 0xc001c1c900, 0x64fa120, 0xc001b7bbc0, 0xc001c1c900, 0x5cf0d80, 0xc001b7bb01, 0xc001cf3240)
2020-09-21T12:52:41.006+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/internal/tfplugin5/tfplugin5.pb.go:3276 +0x86
2020-09-21T12:52:41.006+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/plugin.Serve.func3.1(0x72045a0, 0xc00117a5d0, 0x64fa120, 0xc001b7bbc0, 0xc001cf3220, 0xc001cf3240, 0xc000ee7ba0, 0x108fe18, 0x635f4e0, 0xc00117a5d0)
2020-09-21T12:52:41.006+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/plugin/serve.go:76 +0x87
2020-09-21T12:52:41.006+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/internal/tfplugin5._Provider_ReadResource_Handler(0x65d1ae0, 0xc000ac7200, 0x72045a0, 0xc00117a5d0, 0xc001b7bb60, 0xc0009eb560, 0x72045a0, 0xc00117a5d0, 0xc00183b680, 0x276)
2020-09-21T12:52:41.006+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/internal/tfplugin5/tfplugin5.pb.go:3278 +0x14b
2020-09-21T12:52:41.006+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00003c8c0, 0x7226180, 0xc0000e6480, 0xc0013d2200, 0xc000994510, 0xa5c2e70, 0x0, 0x0, 0x0)
2020-09-21T12:52:41.006+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:1171 +0x50a
2020-09-21T12:52:41.006+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: google.golang.org/grpc.(*Server).handleStream(0xc00003c8c0, 0x7226180, 0xc0000e6480, 0xc0013d2200, 0x0)
2020-09-21T12:52:41.006+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:1494 +0xccd
2020-09-21T12:52:41.006+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000e6ed30, 0xc00003c8c0, 0x7226180, 0xc0000e6480, 0xc0013d2200)
2020-09-21T12:52:41.006+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:834 +0xa1
2020-09-21T12:52:41.006+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-09-21T12:52:41.006+0200 [DEBUG] plugin.terraform-provider-aws_v3.7.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:832 +0x204
```
