### ISSUE TITLE
aws_rds_cluster: fatal crash using s3_import

### ISSUE THREAD

**Issue by nitrocode** [hashicorp/terraform-provider-aws#15325]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.12.29
+ provider.aws v2.70.0
```

also tried

```
Terraform v0.13.3
+ provider registry.terraform.io/-/aws v3.7.0
+ provider registry.terraform.io/hashicorp/aws v2.70.0
```

### Affected Resource(s)

* aws_rds_cluster

### Terraform Configuration Files

This is directly from the [aws_rds_cluster documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#s3-import-options).

```hcl
resource "aws_rds_cluster" "db" {
  engine = "aurora"

  s3_import {
    source_engine         = "mysql"
    source_engine_version = "5.6"
    bucket_name           = "test"
    bucket_prefix         = "test"
    ingestion_role        = module.iam.this_iam_role_arn
  }
}
```

It does not experience a fatal crash if `master_username` and `master_password` args are supplied.

### Debug Output

See debug.log

https://gist.github.com/nitrocode/dcf7fd1315f39478f112fa70f0b5c907

### Panic Output

See crash.log

https://gist.github.com/nitrocode/dcf7fd1315f39478f112fa70f0b5c907

### Expected Behavior

It should have created the rds cluster without panicking. 

### Actual Behavior

Fatal error

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

N/A

### References

N/A

**Comment by ewbankkit** [comment]
Relevant section of the crash log:

```
panic: interface conversion: interface {} is nil, not string
2020-09-23T20:10:35.076-0400 [DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:
2020-09-23T20:10:35.077-0400 [DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: goroutine 142 [running]:
2020-09-23T20:10:35.077-0400 [DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsRDSClusterCreate(0xc00079e540, 0x5cb4fc0, 0xc00042d900, 0x2, 0xa6fa360)
2020-09-23T20:10:35.077-0400 [DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_rds_cluster.go:637 +0x71c2
2020-09-23T20:10:35.077-0400 [DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000753a70, 0xc000d79bd0, 0xc000fbc8a0, 0x5cb4fc0, 0xc00042d900, 0xc000fc7101, 0xc000fca8d0, 0xc000fc71d0)
2020-09-23T20:10:35.077-0400 [DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:310 +0x365
2020-09-23T20:10:35.077-0400 [DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000186280, 0xc0013559c8, 0xc000d79bd0, 0xc000fbc8a0, 0xc000fbb5e8, 0xc0000c7c88, 0x5aba6c0)
2020-09-23T20:10:35.077-0400 [DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:294 +0x99
2020-09-23T20:10:35.077-0400 [DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0005b9870, 0x72219c0, 0xc000fa8d80, 0xc00079e000, 0xc0005b9870, 0xc000fa8d80, 0xc001573b30)
2020-09-23T20:10:35.077-0400 [DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:885 +0x8b4
2020-09-23T20:10:35.077-0400 [DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x668ab20, 0xc0005b9870, 0x72219c0, 0xc000fa8d80, 0xc000a411a0, 0x0, 0x72219c0, 0xc000fa8d80, 0xc000fb4000, 0x930)
2020-09-23T20:10:35.077-0400 [DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3305 +0x217
2020-09-23T20:10:35.077-0400 [DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000cc7080, 0x7246220, 0xc000cc7b00, 0xc000184c00, 0xc0009347b0, 0xa6cd260, 0x0, 0x0, 0x0)
2020-09-23T20:10:35.077-0400 [DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:1024 +0x4f4
2020-09-23T20:10:35.077-0400 [DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: google.golang.org/grpc.(*Server).handleStream(0xc000cc7080, 0x7246220, 0xc000cc7b00, 0xc000184c00, 0x0)
2020-09-23T20:10:35.077-0400 [DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:1313 +0xd97
2020-09-23T20:10:35.077-0400 [DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000cf620, 0xc000cc7080, 0x7246220, 0xc000cc7b00, 0xc000184c00)
2020-09-23T20:10:35.077-0400 [DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:722 +0xbb
2020-09-23T20:10:35.077-0400 [DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-09-23T20:10:35.077-0400 [DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:720 +0xa1
```

**Comment by ewbankkit** [comment]
@nitrocode Thanks for reporting this issue. There is a bug here but you can workaround the crash by ensuring that the `master_username` and `master_password` attributes are set when using `s3_import`.

**Comment by nitrocode** [comment]
Marking this issue as active due to github-actions marking this issue as stale
