### ISSUE TITLE
New resource: aws_cloudwatch_event_archive

### ISSUE THREAD

**Issue by mwarkentin** [hashicorp/terraform-provider-aws#16067]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Looks like there's now an API to enable long-term archival of eventbridge events which can later be replayed: 

* https://aws.amazon.com/blogs/aws/new-archive-and-replay-events-with-amazon-eventbridge/
* https://aws.amazon.com/about-aws/whats-new/2020/11/amazon-eventbridge-introduces-support-for-event-replay/

```
client.create_archive(
    ArchiveName='string',
    EventSourceArn='string',
    Description='string',
    EventPattern='string',
    RetentionDays=123
)
```

### New or Affected Resource(s)

* aws_cloudwatch_event_archive

### Potential Terraform Configuration

```hcl
resource "aws_cloudwatch_event_bus" "messenger" {
  name = "chat-messages"
}

resource "aws_cloudwatch_event_archive" "archive" {
  archive_name = "archive"

  event_source_arn = aws_cloudwatch_event_bus.messenger.arn

  description = "Archive of chat message events"

  event_pattern = <<EOF
{
  "detail-type": [
    "customerCreated"
  ]
}
EOF

  retention_days = 0
}
```

### References

* https://docs.aws.amazon.com/cli/latest/reference/events/create-archive.html
* https://awsapichanges.info/archive/changes/034487-events.html#CreateArchive

**Comment by ewbankkit** [comment]
[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/11/amazon-eventbridge-introduces-support-for-event-replay/).

Requires [AWS SDK v1.35.22](https://github.com/aws/aws-sdk-go/releases/tag/v1.35.22):

* https://github.com/hashicorp/terraform-provider-aws/pull/16071

**Comment by mwarkentin** [comment]
Looks like the SDK is updated in https://github.com/hashicorp/terraform-provider-aws/pull/16085

**Comment by heitorlessa** [comment]
hey @mwarkentin created a PR to add support for that and match what's available in CloudFormation - #17270

**Comment by igorescobar** [comment]
Anyone having this `Error: rpc error: code = Unavailable desc = transport is closing` after an apply? 🤔

**Comment by heitorlessa** [comment]
Hmm can you try with DEBUG enabled?

Didn't see that during my acceptance tests

**Comment by igorescobar** [comment]
@heitorlessa 
```
Error: rpc error: code = Unavailable desc = transport is closing


panic: interface conversion: interface {} is int, not int64
2021-02-22T18:47:03.200Z [DEBUG] plugin.terraform-provider-aws_v3.29.0_x5:
2021-02-22T18:47:03.200Z [DEBUG] plugin.terraform-provider-aws_v3.29.0_x5: goroutine 53 [running]:
2021-02-22T18:47:03.200Z [DEBUG] plugin.terraform-provider-aws_v3.29.0_x5: github.com/terraform-providers/terraform-provider-aws/aws.buildCreateArchiveInputStruct(0xc001213780, 0xc001365770, 0x16976d0, 0xc001365710)
2021-02-22T18:47:03.200Z [DEBUG] plugin.terraform-provider-aws_v3.29.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_cloudwatch_event_archive.go:169 +0x507
2021-02-22T18:47:03.200Z [DEBUG] plugin.terraform-provider-aws_v3.29.0_x5: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsCloudWatchEventArchiveCreate(0xc001213780, 0x6767340, 0xc001281600, 0x0, 0xffffffffffffffff)
2021-02-22T18:47:03.200Z [DEBUG] plugin.terraform-provider-aws_v3.29.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_cloudwatch_event_archive.go:67 +0x55
2021-02-22T18:47:03.200Z [DEBUG] plugin.terraform-provider-aws_v3.29.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000603200, 0x7ecd800, 0xc00030d580, 0xc001213780, 0x6767340, 0xc001281600, 0x0, 0x0, 0x0)
2021-02-22T18:47:03.200Z [DEBUG] plugin.terraform-provider-aws_v3.29.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/resource.go:278 +0x88
2021-02-22T18:47:03.200Z [DEBUG] plugin.terraform-provider-aws_v3.29.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000603200, 0x7ecd800, 0xc00030d580, 0xc0009a1420, 0xc0012039c0, 0x6767340, 0xc001281600, 0x0, 0x0, 0x0, ...)
2021-02-22T18:47:03.200Z [DEBUG] plugin.terraform-provider-aws_v3.29.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/resource.go:396 +0x65b
2021-02-22T18:47:03.200Z [DEBUG] plugin.terraform-provider-aws_v3.29.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00109f620, 0x7ecd800, 0xc00030d580, 0xc0012051d0, 0xc00030d580, 0x0, 0x7ef9860)
2021-02-22T18:47:03.200Z [DEBUG] plugin.terraform-provider-aws_v3.29.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/grpc_provider.go:955 +0x8cf
2021-02-22T18:47:03.200Z [DEBUG] plugin.terraform-provider-aws_v3.29.0_x5: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc0013eb8a0, 0x7ecd800, 0xc00030d580, 0xc0009a11f0, 0xc0013eb8a0, 0xc001232450, 0xc00065aba0)
2021-02-22T18:47:03.200Z [DEBUG] plugin.terraform-provider-aws_v3.29.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:332 +0xae
2021-02-22T18:47:03.200Z [DEBUG] plugin.terraform-provider-aws_v3.29.0_x5: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x725dc40, 0xc0013eb8a0, 0x7ecd8c0, 0xc001232450, 0xc000f8d440, 0x0, 0x7ecd8c0, 0xc001232450, 0xc001226300, 0x17a)
2021-02-22T18:47:03.200Z [DEBUG] plugin.terraform-provider-aws_v3.29.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
2021-02-22T18:47:03.200Z [DEBUG] plugin.terraform-provider-aws_v3.29.0_x5: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00001f340, 0x7ef0ee0, 0xc00135c180, 0xc001224100, 0xc000338c90, 0xb31cb60, 0x0, 0x0, 0x0)
2021-02-22T18:47:03.200Z [DEBUG] plugin.terraform-provider-aws_v3.29.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x522
2021-02-22T18:47:03.200Z [DEBUG] plugin.terraform-provider-aws_v3.29.0_x5: google.golang.org/grpc.(*Server).handleStream(0xc00001f340, 0x7ef0ee0, 0xc00135c180, 0xc001224100, 0x0)
2021-02-22T18:47:03.200Z [DEBUG] plugin.terraform-provider-aws_v3.29.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd05
2021-02-22T18:47:03.200Z [DEBUG] plugin.terraform-provider-aws_v3.29.0_x5: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000bef3d0, 0xc00001f340, 0x7ef0ee0, 0xc00135c180, 0xc001224100)
2021-02-22T18:47:03.200Z [DEBUG] plugin.terraform-provider-aws_v3.29.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xa5
2021-02-22T18:47:03.200Z [DEBUG] plugin.terraform-provider-aws_v3.29.0_x5: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-02-22T18:47:03.200Z [DEBUG] plugin.terraform-provider-aws_v3.29.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
2021/02/22 18:47:03 [DEBUG] module.cazoo_events_forwarder.aws_cloudwatch_event_archive.default: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2021-02-22T18:47:03.205Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-02-22T18:47:03.205Z [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/aws/3.29.0/darwin_amd64/terraform-provider-aws_v3.29.0_x5 pid=79275 error="exit status 2"
2021/02/22 18:47:03 [TRACE] EvalMaybeTainted: module.cazoo_events_forwarder.aws_cloudwatch_event_archive.default encountered an error during creation, so it is now marked as tainted
2021/02/22 18:47:03 [TRACE] EvalWriteState: removing state object for module.cazoo_events_forwarder.aws_cloudwatch_event_archive.default
2021/02/22 18:47:03 [TRACE] EvalApplyProvisioners: aws_cloudwatch_event_archive.default has no state, so skipping provisioners
2021/02/22 18:47:03 [TRACE] EvalMaybeTainted: module.cazoo_events_forwarder.aws_cloudwatch_event_archive.default encountered an error during creation, so it is now marked as tainted
2021/02/22 18:47:03 [TRACE] EvalWriteState: removing state object for module.cazoo_events_forwarder.aws_cloudwatch_event_archive.default
2021/02/22 18:47:03 [TRACE] vertex "module.cazoo_events_forwarder.aws_cloudwatch_event_archive.default": visit complete
2021/02/22 18:47:03 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/hashicorp/aws\"] (close)" errored, so skipping
2021/02/22 18:47:03 [TRACE] dag/walk: upstream of "module.cazoo_events_forwarder (close)" errored, so skipping
2021/02/22 18:47:03 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021/02/22 18:47:03 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021-02-22T18:47:03.235Z [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

I'm going to try upgrading from `v0.14.2`to v0.14.7 and see if I have any luck

**Comment by igorescobar** [comment]
```
panic: interface conversion: interface {} is int, not int64
2021-02-22T18:47:03.200Z [DEBUG] plugin.terraform-provider-aws_v3.29.0_x5:
```

Might have something todo with this ☝️

**Comment by heitorlessa** [comment]
Yep, it seems related to retentionDays property - I had that fixed during
the first round of tests, tho perhaps the tests were flaky then.

input.RetentionDays = aws.Int64(v.(int64))

I’ll try replicating that tomorrow — any chance you could share a sample
resource that you’re using?

Does omitting that property help?

**Comment by heitorlessa** [comment]
Just confirmed @igorescobar - The issue only happens when `retention_days` are set on creation. If you create an archive without the property, then update it... it works -- I'll work on a fix tomorrow (EMEA timezone based).

```hcl
provider "aws" {
  region = "eu-west-1"
}

resource "aws_cloudwatch_event_bus" "sample" {
  name = "tf-sample"
}

resource "aws_cloudwatch_event_archive" "order" {
  name             = "order-archive"
  event_source_arn = aws_cloudwatch_event_bus.sample.arn
  # retention_days   = 7  ## uncomment after apply for updating it
}
```

**Comment by heitorlessa** [comment]
@igorescobar  Fix created as a PR #17754  -- Thanks for reporting it.

**Comment by igorescobar** [comment]
Hey @heitorlessa!
Thanks for the quick fix!

Removing the rentention_days attribute did the trick. Looking forward to the update! 👋

**Comment by heitorlessa** [comment]
@igorescobar merged now! It'll be available in the next release ;)
