### ISSUE TITLE
Release v3.19.0 crashes on Localstack

### ISSUE THREAD

**Issue by rayjlinden** [hashicorp/terraform-provider-aws#16532]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.5

### Affected Resource(s)

* aws_sns_topic_subscription. (maybe others???)

### Terraform Configuration Files

```hcl
provider "aws" {
  region                      = "us-west-2"
  access_key                  = "fake"
  secret_key                  = "fake"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    apigateway     = "http://localstack:4566"
    cloudformation = "http://localstack:4566"
    cloudwatch     = "http://localstack:4566"
    dynamodb       = "http://localstack:4566"
    es             = "http://localstack:4566"
    firehose       = "http://localstack:4566"
    iam            = "http://localstack:4566"
    kinesis        = "http://localstack:4566"
    lambda         = "http://localstack:4566"
    route53        = "http://localstack:4566"
    redshift       = "http://localstack:4566"
    s3             = "http://localstack:4566"
    secretsmanager = "http://localstack:4566"
    ses            = "http://localstack:4566"
    sns            = "http://localstack:4566"
    sqs            = "http://localstack:4566"
    ssm            = "http://localstack:4566"
    stepfunctions  = "http://localstack:4566"
    sts            = "http://localstack:4566"
  }
}

resource "aws_sns_topic" "sns-ecom-events" {
  name = "ecom-events-sandbox"
}

resource "aws_sns_topic_subscription" "ecom-events-webhook-target" {
  topic_arn = aws_sns_topic.sns-ecom-events.arn
  protocol  = "lambda"
  endpoint  = aws_lambda_function.webhook_lambda.arn
}

resource "aws_sns_topic_subscription" "ecom-events-receipt-target" {
  topic_arn = aws_sns_topic.sns-ecom-events.arn
  protocol  = "lambda"
  endpoint  = aws_lambda_function.receipt_lambda.arn

  filter_policy = <<EOF
  {
    "event_name": ["invoice-completed", "receipt-payout-execute-completed"]
  }
  EOF
}

resource "aws_sns_topic_subscription" "ecom-events-payments-target" {
  topic_arn = aws_sns_topic.sns-ecom-events.arn
  protocol  = "sqs"
  endpoint  = aws_sqs_queue.extraction-payments-events.arn

  filter_policy = <<EOF
  {
    "event_name": ["account-created"]
  }
  EOF
}

resource "aws_sns_topic_subscription" "ecom-events-payments-target-delay" {
  topic_arn = aws_sns_topic.sns-ecom-events.arn
  protocol  = "sqs"
  endpoint  = aws_sqs_queue.extraction-payments-events-delay.arn

  filter_policy = <<EOF
  {
    "event_name": ["rebilly-pm-added"]
  }
  EOF
}

resource "aws_sns_topic_subscription" "ecom-events-fraud-target" {
  topic_arn = aws_sns_topic.sns-ecom-events.arn
  protocol  = "sqs"
  endpoint  = aws_sqs_queue.extraction-fraud-events.arn

  filter_policy = <<EOF
  {
    "event_name": ["watchlist-manual-review"]
  }
  EOF
}
resource "aws_sns_topic_subscription" "ecom-events-payout-target" {
  topic_arn = aws_sns_topic.sns-ecom-events.arn
  protocol  = "sqs"
  endpoint  = aws_sqs_queue.extraction-payout-events.arn

  filter_policy = <<EOF
  {
    "event_name": ["payout-invoice-completed"]
  }
  EOF
}

resource "aws_sqs_queue" "extraction-payments-events" {
  name                      = "extraction-payments-events"
  receive_wait_time_seconds = 20
}


resource "aws_sqs_queue" "extraction-fraud-events" {
  name                      = "extraction-fraud-events"
  receive_wait_time_seconds = 20
}

resource "aws_sqs_queue" "extraction-payout-events" {
  name                      = "extraction-payout-events"
  receive_wait_time_seconds = 20
}

resource "aws_sqs_queue" "extraction-payments-events-delay" {
  name                      = "extraction-payments-events-delay"
  delay_seconds             = 1
  receive_wait_time_seconds = 20
}

resource "aws_lambda_event_source_mapping" "rebilly-lambda-event-source-mapping" {
  event_source_arn  = aws_sqs_queue.extraction-payments-events-delay.arn
  enabled           = true
  function_name     = aws_lambda_function.rebilly_lambda.arn
  batch_size        = 1
}
```

### Debug Output

```
aws_sqs_queue.extraction-fraud-events: Creating...
aws_lambda_function.rebilly_lambda: Creating...
aws_sqs_queue.extraction-payments-events-delay: Creating...
aws_sqs_queue.extraction-payout-events: Creating...
aws_sns_topic.sns-ecom-events: Creating...
aws_lambda_function.receipt_lambda: Creating...
aws_sqs_queue.extraction-payments-events: Creating...
aws_lambda_function.webhook_lambda: Creating...
aws_sns_topic.sns-ecom-events: Creation complete after 1s [id=arn:aws:sns:us-west-2:000000000000:ecom-events-sandbox]
aws_sqs_queue.extraction-fraud-events: Creation complete after 1s [id=http://localhost:4566/000000000000/extraction-fraud-events]
aws_sns_topic_subscription.ecom-events-fraud-target: Creating...
aws_sqs_queue.extraction-payments-events: Creation complete after 1s [id=http://localhost:4566/000000000000/extraction-payments-events]
aws_sns_topic_subscription.ecom-events-payments-target: Creating...
aws_sqs_queue.extraction-payments-events-delay: Creation complete after 1s [id=http://localhost:4566/000000000000/extraction-payments-events-delay]
aws_sns_topic_subscription.ecom-events-payments-target-delay: Creating...
aws_sqs_queue.extraction-payout-events: Creation complete after 1s [id=http://localhost:4566/000000000000/extraction-payout-events]
aws_sns_topic_subscription.ecom-events-payout-target: Creating...
aws_sns_topic_subscription.ecom-events-fraud-target: Creation complete after 0s [id=arn:aws:sns:us-west-2:000000000000:ecom-events-sandbox:76524a11-8f3c-4f14-b3fe-fe0b3d024131]
aws_sns_topic_subscription.ecom-events-payments-target: Creation complete after 0s [id=arn:aws:sns:us-west-2:000000000000:ecom-events-sandbox:74655654-52b8-446a-b320-24960cc97545]
aws_sns_topic_subscription.ecom-events-payments-target-delay: Creation complete after 0s [id=arn:aws:sns:us-west-2:000000000000:ecom-events-sandbox:88405d08-1c97-40f6-8cec-65c18e56beed]
aws_sns_topic_subscription.ecom-events-payout-target: Creation complete after 0s [id=arn:aws:sns:us-west-2:000000000000:ecom-events-sandbox:212f21b0-4e02-4f1d-8115-d8185f1622fc]

Error: rpc error: code = Unavailable desc = transport is closing



Error: rpc error: code = Unavailable desc = transport is closing



Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: invalid memory address or nil pointer dereference
2020-12-02T06:46:59.013Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4465b2e]
2020-12-02T06:46:59.013Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5:
2020-12-02T06:46:59.013Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5: goroutine 72 [running]:
2020-12-02T06:46:59.013Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsLambdaFunctionRead(0xc001618080, 0x565ac80, 0xc00018bb80, 0x8bb2c97000, 0x0)
2020-12-02T06:46:59.013Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_lambda_function.go:816 +0x23ee
2020-12-02T06:46:59.013Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsLambdaFunctionCreate(0xc001618080, 0x565ac80, 0xc00018bb80, 0x0, 0x0)
2020-12-02T06:46:59.013Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_lambda_function.go:604 +0x1815
2020-12-02T06:46:59.013Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0008544d0, 0x6ed3d20, 0xc0016c2440, 0xc001618080, 0x565ac80, 0xc00018bb80, 0x0, 0x0, 0x0)
2020-12-02T06:46:59.013Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.3.0/helper/schema/resource.go:268 +0x88
2020-12-02T06:46:59.013Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0008544d0, 0x6ed3d20, 0xc0016c2440, 0xc0016276c0, 0xc000c7ae80, 0x565ac80, 0xc00018bb80, 0x0, 0x0, 0x0, ...)
2020-12-02T06:46:59.013Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.3.0/helper/schema/resource.go:386 +0x681
2020-12-02T06:46:59.013Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000e917e0, 0x6ed3d20, 0xc0016c2440, 0xc000aea190, 0xc0016c2440, 0xc000bed400, 0x6f028e0)
2020-12-02T06:46:59.013Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.3.0/helper/schema/grpc_provider.go:951 +0x8b2
2020-12-02T06:46:59.013Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc0011e3120, 0x6ed3d20, 0xc0016c2440, 0xc001627570, 0xc0011e3120, 0xc00161f9b0, 0xc0015dfba0)
2020-12-02T06:46:59.013Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.1.0/tfprotov5/server/server.go:331 +0xac
2020-12-02T06:46:59.013Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x60ff560, 0xc0011e3120, 0x6ed3de0, 0xc00161f9b0, 0xc000bed4a0, 0x0, 0x6ed3de0, 0xc00161f9b0, 0xc001102000, 0xa26)
2020-12-02T06:46:59.013Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.1.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x217
2020-12-02T06:46:59.013Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001448c0, 0x6ef8a20, 0xc001411080, 0xc00159bc00, 0xc000b594d0, 0xa6f9e20, 0x0, 0x0, 0x0)
2020-12-02T06:46:59.013Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x50a
2020-12-02T06:46:59.013Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5: google.golang.org/grpc.(*Server).handleStream(0xc0001448c0, 0x6ef8a20, 0xc001411080, 0xc00159bc00, 0x0)
2020-12-02T06:46:59.013Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xcfd
2020-12-02T06:46:59.013Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000cff8b0, 0xc0001448c0, 0x6ef8a20, 0xc001411080, 0xc00159bc00)
2020-12-02T06:46:59.013Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xa1
2020-12-02T06:46:59.013Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-12-02T06:46:59.013Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x204
2020/12/02 06:46:59 [DEBUG] aws_lambda_function.webhook_lambda: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2020/12/02 06:46:59 [TRACE] eval: *terraform.EvalMaybeTainted
2020/12/02 06:46:59 [TRACE] EvalMaybeTainted: aws_lambda_function.webhook_lambda encountered an error during creation, so it is now marked as tainted
2020/12/02 06:46:59 [TRACE] eval: *terraform.EvalWriteState
2020/12/02 06:46:59 [TRACE] EvalWriteState: removing state object for aws_lambda_function.webhook_lambda
2020/12/02 06:46:59 [TRACE] eval: *terraform.EvalApplyProvisioners
2020/12/02 06:46:59 [TRACE] EvalApplyProvisioners: aws_lambda_function.webhook_lambda has no state, so skipping provisioners
2020/12/02 06:46:59 [TRACE] eval: *terraform.EvalMaybeTainted
2020/12/02 06:46:59 [TRACE] EvalMaybeTainted: aws_lambda_function.webhook_lambda encountered an error during creation, so it is now marked as tainted
2020/12/02 06:46:59 [TRACE] eval: *terraform.EvalWriteState
2020/12/02 06:46:59 [TRACE] EvalWriteState: removing state object for aws_lambda_function.webhook_lambda
2020/12/02 06:46:59 [TRACE] eval: *terraform.EvalIf
2020/12/02 06:46:59 [TRACE] eval: *terraform.EvalIf
2020/12/02 06:46:59 [TRACE] eval: *terraform.EvalWriteDiff
2020/12/02 06:46:59 [TRACE] eval: *terraform.EvalApplyPost
2020/12/02 06:46:59 [ERROR] eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
2020/12/02 06:46:59 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/12/02 06:46:59 [TRACE] [walkApply] Exiting eval tree: aws_lambda_function.webhook_lambda
2020/12/02 06:46:59 [TRACE] vertex "aws_lambda_function.webhook_lambda": visit complete
2020/12/02 06:46:59 [TRACE] dag/walk: upstream of "aws_sns_topic_subscription.ecom-events-webhook-target" errored, so skipping
2020-12-02T06:46:59.024Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2020/12/02 06:46:59 [DEBUG] aws_lambda_function.receipt_lambda: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2020/12/02 06:46:59 [TRACE] eval: *terraform.EvalMaybeTainted
2020/12/02 06:46:59 [TRACE] EvalMaybeTainted: aws_lambda_function.receipt_lambda encountered an error during creation, so it is now marked as tainted
2020/12/02 06:46:59 [TRACE] eval: *terraform.EvalWriteState
2020/12/02 06:46:59 [TRACE] EvalWriteState: removing state object for aws_lambda_function.receipt_lambda
2020/12/02 06:46:59 [TRACE] eval: *terraform.EvalApplyProvisioners
2020/12/02 06:46:59 [TRACE] EvalApplyProvisioners: aws_lambda_function.receipt_lambda has no state, so skipping provisioners
2020/12/02 06:46:59 [TRACE] eval: *terraform.EvalMaybeTainted
2020/12/02 06:46:59 [TRACE] EvalMaybeTainted: aws_lambda_function.receipt_lambda encountered an error during creation, so it is now marked as tainted
2020/12/02 06:46:59 [TRACE] eval: *terraform.EvalWriteState
2020/12/02 06:46:59 [TRACE] EvalWriteState: removing state object for aws_lambda_function.receipt_lambda
2020/12/02 06:46:59 [TRACE] eval: *terraform.EvalIf
2020/12/02 06:46:59 [TRACE] eval: *terraform.EvalIf
2020/12/02 06:46:59 [TRACE] eval: *terraform.EvalWriteDiff
2020/12/02 06:46:59 [TRACE] eval: *terraform.EvalApplyPost
2020/12/02 06:46:59 [ERROR] eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
2020/12/02 06:46:59 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/12/02 06:46:59 [TRACE] [walkApply] Exiting eval tree: aws_lambda_function.receipt_lambda
2020/12/02 06:46:59 [TRACE] vertex "aws_lambda_function.receipt_lambda": visit complete
2020/12/02 06:46:59 [TRACE] dag/walk: upstream of "aws_sns_topic_subscription.ecom-events-receipt-target" errored, so skipping
2020/12/02 06:46:59 [DEBUG] aws_lambda_function.rebilly_lambda: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2020/12/02 06:46:59 [TRACE] eval: *terraform.EvalMaybeTainted
2020/12/02 06:46:59 [TRACE] EvalMaybeTainted: aws_lambda_function.rebilly_lambda encountered an error during creation, so it is now marked as tainted
2020/12/02 06:46:59 [TRACE] eval: *terraform.EvalWriteState
2020/12/02 06:46:59 [TRACE] EvalWriteState: removing state object for aws_lambda_function.rebilly_lambda
2020/12/02 06:46:59 [TRACE] eval: *terraform.EvalApplyProvisioners
2020/12/02 06:46:59 [TRACE] EvalApplyProvisioners: aws_lambda_function.rebilly_lambda has no state, so skipping provisioners
2020/12/02 06:46:59 [TRACE] eval: *terraform.EvalMaybeTainted
2020/12/02 06:46:59 [TRACE] EvalMaybeTainted: aws_lambda_function.rebilly_lambda encountered an error during creation, so it is now marked as tainted
2020/12/02 06:46:59 [TRACE] eval: *terraform.EvalWriteState
2020/12/02 06:46:59 [TRACE] EvalWriteState: removing state object for aws_lambda_function.rebilly_lambda
2020/12/02 06:46:59 [TRACE] eval: *terraform.EvalIf
2020/12/02 06:46:59 [TRACE] eval: *terraform.EvalIf
2020/12/02 06:46:59 [TRACE] eval: *terraform.EvalWriteDiff
2020/12/02 06:46:59 [TRACE] eval: *terraform.EvalApplyPost
2020/12/02 06:46:59 [ERROR] eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
2020/12/02 06:46:59 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/12/02 06:46:59 [TRACE] [walkApply] Exiting eval tree: aws_lambda_function.rebilly_lambda
2020/12/02 06:46:59 [TRACE] vertex "aws_lambda_function.rebilly_lambda": visit complete
2020/12/02 06:46:59 [TRACE] dag/walk: upstream of "aws_lambda_event_source_mapping.rebilly-lambda-event-source-mapping" errored, so skipping
2020/12/02 06:46:59 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/hashicorp/aws\"] (close)" errored, so skipping
2020/12/02 06:46:59 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2020/12/02 06:46:59 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020/12/02 06:46:59 [TRACE] statemgr.Filesystem: no original state snapshot to back up
2020/12/02 06:46:59 [TRACE] statemgr.Filesystem: state has changed since last snapshot, so incrementing serial to 10
2020/12/02 06:46:59 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2020-12-02T06:46:59.026Z [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/hashicorp/aws/3.19.0/linux_amd64/terraform-provider-aws_v3.19.0_x5 pid=111 error="exit status 2"
2020/12/02 06:46:59 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2020/12/02 06:46:59 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2020-12-02T06:46:59.043Z [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Panic Output

See above

### Expected Behavior

Should not crash.  Should continue to work with Localstack.

### Actual Behavior

Boom

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Running on localstack in our dev environment.

### References

* #0000

**Comment by ewbankkit** [comment]
Relevant code:

https://github.com/hashicorp/terraform-provider-aws/blob/dd72c4b7dc191b2c959ed1b76fca94227c83bfa4/aws/resource_aws_lambda_function.go#L816

`PackageType` must currently be `nil` on localstack.
We should be using `aws.StringValue(function.PackageType)` in the comparison - https://github.com/hashicorp/terraform-provider-aws/issues/12992.
