### ISSUE TITLE
panic: missing field in set: global_secondary_index (non_key_attributes)

### ISSUE THREAD

**Issue by mjjones1** [hashicorp/terraform-provider-aws#17375]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/aws v3.26.0

### Affected Resource(s)

* aws_dynamodb_table

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
  }
  required_version = ">= 0.14.5"
}

resource "aws_dynamodb_table" "basic-dynamodb-table" {
  name           = "GameScores"
  billing_mode   = "PROVISIONED"
  read_capacity  = 20
  write_capacity = 20
  hash_key       = "UserId"
  range_key      = "GameTitle"

  attribute {
    name = "UserId"
    type = "S"
  }

  attribute {
    name = "GameTitle"
    type = "S"
  }

  attribute {
    name = "TopScore"
    type = "N"
  }

  global_secondary_index {
    name               = "GameTitleIndex"
    hash_key           = "GameTitle"
    range_key          = "TopScore"
    write_capacity     = 10
    read_capacity      = 10
    projection_type    = "INCLUDE"
    non_key_attributes = ["abc","def"]
  }
}
```

### Debug Output

Same as Panic Output

### Panic Output

https://gist.github.com/mjjones1/f4fba1ff99a85554d2eb23b3202a3ba4

### Expected Behavior

`terraform plan` should have produced a plan

### Actual Behavior

`terraform plan` crashed

### Steps to Reproduce

1. `terraform plan`. Note that `terraform apply` also fails in the same way

### Important Factoids

The problem is in the `aws_dynamodb_table` `global_secondary_index` `non_key_attributes` field
* If there is one attribute e.g. `non_key_attributes = ["abc"]` then it works
* If there is more than one attribute e.g. `non_key_attributes = ["abc","def"]` then it always crashes
* Interestingly, other people in my team do not see this problem

**Comment by ewbankkit** [comment]
```
2021-02-01T08:42:22.994-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: panic: missing field in set: global_secondary_index.1011896207.non_key_attributes.374767988.374767988
2021-02-01T08:42:22.994-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: 
2021-02-01T08:42:22.994-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: goroutine 132 [running]:
2021-02-01T08:42:22.994-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*DiffFieldReader).readSet(0x12f6c360, 0x12f6d080, 0x3, 0x4, 0x12f68640, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2021-02-01T08:42:22.994-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.1/helper/schema/field_reader_diff.go:212 +0x6e9
2021-02-01T08:42:22.994-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*DiffFieldReader).ReadField(0x12f6c360, 0x12f6d080, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2021-02-01T08:42:22.994-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.1/helper/schema/field_reader_diff.go:74 +0x3b6
2021-02-01T08:42:22.994-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.readObjectField(0xd628cd0, 0x12f6c360, 0x125f03f0, 0x2, 0x2, 0x12f6c1a0, 0x0, 0x0, 0x0, 0x0, ...)
2021-02-01T08:42:22.994-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.1/helper/schema/field_reader.go:236 +0x172
2021-02-01T08:42:22.994-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*DiffFieldReader).ReadField(0x12f6c360, 0x125f03f0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0899e0, ...)
2021-02-01T08:42:22.994-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.1/helper/schema/field_reader_diff.go:76 +0x360
2021-02-01T08:42:22.994-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*DiffFieldReader).readSet(0x12f6c360, 0x125ed208, 0x1, 0x1, 0x12f68500, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2021-02-01T08:42:22.994-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.1/helper/schema/field_reader_diff.go:206 +0x2c0
2021-02-01T08:42:22.994-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*DiffFieldReader).ReadField(0x12f6c360, 0x125ed208, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2021-02-01T08:42:22.994-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.1/helper/schema/field_reader_diff.go:74 +0x3b6
2021-02-01T08:42:22.994-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MultiLevelFieldReader).ReadFieldMerge(0x125f01c0, 0x125ed208, 0x1, 0x1, 0xcddb153, 0x7, 0x0, 0x0, 0x0, 0x0, ...)
2021-02-01T08:42:22.994-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.1/helper/schema/field_reader_multi.go:45 +0x153
2021-02-01T08:42:22.994-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceDiff).get(0x12f6c2e0, 0x125ed208, 0x1, 0x1, 0xcddb153, 0x7, 0x0, 0x0, 0x0, 0x0, ...)
2021-02-01T08:42:22.994-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.1/helper/schema/resource_diff.go:485 +0x5b
2021-02-01T08:42:22.994-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceDiff).GetOk(0x12f6c2e0, 0xce267be, 0x16, 0xccfbfe0, 0x12f6c5e0, 0x0)
2021-02-01T08:42:22.994-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.1/helper/schema/resource_diff.go:384 +0x85
2021-02-01T08:42:22.994-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: github.com/terraform-providers/terraform-provider-aws/aws.validateDynamoDbTableAttributes(0x12f6c2e0, 0x0, 0x0)
2021-02-01T08:42:22.994-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/validators.go:2228 +0x241
2021-02-01T08:42:22.995-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsDynamoDbTable.func2(0xd661fe0, 0x12f43700, 0x12f6c2e0, 0xc2a2960, 0x12f22000, 0x0, 0x0)
2021-02-01T08:42:22.995-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_dynamodb_table.go:44 +0x21
2021-02-01T08:42:22.995-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/customdiff.Sequence.func1(0xd661fe0, 0x12f43700, 0x12f6c2e0, 0xc2a2960, 0x12f22000, 0xd674420, 0x1315b630)
2021-02-01T08:42:22.995-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.1/helper/customdiff/compose.go:68 +0x72
2021-02-01T08:42:22.995-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0x124215c0, 0xd661fe0, 0x12f43700, 0x127ee840, 0x12f4ede0, 0x1200c7f0, 0xc2a2960, 0x12f22000, 0x120a6100, 0xbf326c0, ...)
2021-02-01T08:42:22.995-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.1/helper/schema/schema.go:539 +0x881
2021-02-01T08:42:22.995-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0x12438ba0, 0xd661fe0, 0x12f43700, 0x127ee840, 0x12f4ede0, 0xc2a2960, 0x12f22000, 0x0, 0x0, 0x0)
2021-02-01T08:42:22.995-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.1/helper/schema/resource.go:446 +0x6f
2021-02-01T08:42:22.995-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0x12ab7120, 0xd661fe0, 0x12f43700, 0x12f3ec90, 0x12f43700, 0x0, 0xd67c720)
2021-02-01T08:42:22.995-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.1/helper/schema/grpc_provider.go:693 +0x62e
2021-02-01T08:42:22.995-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).PlanResourceChange(0x122f6920, 0xd661fe0, 0x12f43700, 0x127ee440, 0x122f6920, 0x12f30d01, 0x12f43540)
2021-02-01T08:42:22.995-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:315 +0x8a
2021-02-01T08:42:22.995-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler(0xcceddc0, 0x122f6920, 0xd662040, 0x12f43540, 0x12f3e8d0, 0x0, 0xd662040, 0x12f43540, 0x12f30d80, 0x440)
2021-02-01T08:42:22.995-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:362 +0x195
2021-02-01T08:42:22.995-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: google.golang.org/grpc.(*Server).processUnaryRPC(0x122ea120, 0xd678860, 0x12317900, 0x13153b90, 0x122f6980, 0x10353a14, 0x0, 0x0, 0x0)
2021-02-01T08:42:22.995-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x4df
2021-02-01T08:42:22.995-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: google.golang.org/grpc.(*Server).handleStream(0x122ea120, 0xd678860, 0x12317900, 0x13153b90, 0x0)
2021-02-01T08:42:22.995-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xa7b
2021-02-01T08:42:22.995-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: google.golang.org/grpc.(*Server).serveStreams.func1.2(0x12863400, 0x122ea120, 0xd678860, 0x12317900, 0x13153b90)
2021-02-01T08:42:22.995-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0x8a
2021-02-01T08:42:22.995-0600 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: created by google.golang.org/grpc.(*Server).serveStreams.func1
```

**Comment by ewbankkit** [comment]
[Relevant code](https://github.com/hashicorp/terraform-plugin-sdk/blob/651b26a663d34daed50d135ddd25e170ff6c6aae/helper/schema/field_reader_diff.go#L206-L213):

```
		raw, err := r.ReadField(append(address, idx))
		if err != nil {
			return FieldReadResult{}, err
		}
		if !raw.Exists {
			// This shouldn't happen because we just verified it does exist
			panic("missing field in set: " + k + "." + idx)
		}
```
