### ISSUE TITLE
Crash with bad service_type in aws_vpc_endpoint_service

### ISSUE THREAD

**Issue by gotrevor** [hashicorp/terraform-provider-aws#17419]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/aws v3.26.0
```

### Affected Resource(s)

* data aws_vpc_endpoint_service

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "us-west-2"
}

data "aws_vpc_endpoint_service" "s3-g" {
  count        = 1
  service      = "s3"
  service_type = "gateway" // The 'g' in 'gateway' should be capitalized
}
```

### Debug Output
Skipping.  Trivial to reproduce.

### Panic Output
Relevant lines:
```
2021-02-02T16:49:11.048-0500 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: panic: runtime error: index out of range [0] with length 0
2021-02-02T16:49:11.048-0500 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: 
2021-02-02T16:49:11.048-0500 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: goroutine 119 [running]:
2021-02-02T16:49:11.048-0500 [DEBUG] plugin.terraform-provider-aws_v3.26.0_x5: github.com/terraform-providers/terraform-provider-aws/aws.dataSourceAwsVpcEndpointServiceRead(0xc0016d0400, 0x66ec4c0, 0xc0017bc000, 0xb28c9b0, 0x7513270)
```

### Expected Behavior

A non-crash error indicating that no vpc endpoints were found.  Possibly an error that `service_type` is invalid.  Per the documentation, `Gateway` and `Interface` are valid values.  The crash results from an invalid value.

### Actual Behavior

Crash

### Steps to Reproduce

1. `terraform init`
1. `terraform plan`

**Comment by ewbankkit** [comment]
Fuller stack trace:

```
2021-02-03T08:14:45.984-0500 [DEBUG] plugin: plugin exited
panic: runtime error: index out of range [0] with length 0
2021-02-03T08:14:45.967-0500 [DEBUG] plugin.terraform-provider-aws: 
2021-02-03T08:14:45.967-0500 [DEBUG] plugin.terraform-provider-aws: goroutine 68 [running]:
2021-02-03T08:14:45.968-0500 [DEBUG] plugin.terraform-provider-aws: github.com/terraform-providers/terraform-provider-aws/aws.dataSourceAwsVpcEndpointServiceRead(0xc001953f80, 0x5af8d60, 0xc001b54680, 0xa68cea0, 0x6920d48)
2021-02-03T08:14:45.969-0500 [DEBUG] plugin.terraform-provider-aws: 	/home/kit/wrk/src/github.com/terraform-providers/terraform-provider-aws/aws/data_source_aws_vpc_endpoint_service.go:159 +0x15b1
2021-02-03T08:14:45.970-0500 [DEBUG] plugin.terraform-provider-aws: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0001af8c0, 0x7242b00, 0xc0006dc7c0, 0xc001953f80, 0x5af8d60, 0xc001b54680, 0x0, 0x0, 0x0)
2021-02-03T08:14:45.970-0500 [DEBUG] plugin.terraform-provider-aws: 	/home/kit/wrk/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/resource.go:290 +0x88
2021-02-03T08:14:45.970-0500 [DEBUG] plugin.terraform-provider-aws: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc0001af8c0, 0x7242b00, 0xc0006dc7c0, 0xc0006f9d80, 0x5af8d60, 0xc001b54680, 0xc001b54680, 0xc0006f9d80, 0x0, 0x0)
2021-02-03T08:14:45.971-0500 [DEBUG] plugin.terraform-provider-aws: 	/home/kit/wrk/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/resource.go:498 +0xfd
2021-02-03T08:14:45.971-0500 [DEBUG] plugin.terraform-provider-aws: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc000ecddc0, 0x7242b00, 0xc0006dc7c0, 0xc0006f9a40, 0xc0006dc7c0, 0x634be40, 0x65ea300)
2021-02-03T08:14:45.971-0500 [DEBUG] plugin.terraform-provider-aws: 	/home/kit/wrk/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/grpc_provider.go:1105 +0x4d4
2021-02-03T08:14:45.972-0500 [DEBUG] plugin.terraform-provider-aws: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadDataSource(0xc00151a9c0, 0x7242b00, 0xc0006dc7c0, 0xc001d0bd10, 0xc00151a9c0, 0xc0013a7ce0, 0xc00008eba0)
2021-02-03T08:14:45.972-0500 [DEBUG] plugin.terraform-provider-aws: 	/home/kit/wrk/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:247 +0xe5
2021-02-03T08:14:45.974-0500 [DEBUG] plugin.terraform-provider-aws: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler(0x65ea300, 0xc00151a9c0, 0x7242bc0, 0xc0013a7ce0, 0xc000e54480, 0x0, 0x7242bc0, 0xc0013a7ce0, 0xc0003cb560, 0x103)
2021-02-03T08:14:45.975-0500 [DEBUG] plugin.terraform-provider-aws: 	/home/kit/wrk/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:416 +0x214
2021-02-03T08:14:45.975-0500 [DEBUG] plugin.terraform-provider-aws: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00059ae00, 0x7265aa0, 0xc001340600, 0xc000132600, 0xc0006b4300, 0xa64b7d0, 0x0, 0x0, 0x0)
2021-02-03T08:14:45.975-0500 [DEBUG] plugin.terraform-provider-aws: 	/home/kit/wrk/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x522
2021-02-03T08:14:45.976-0500 [DEBUG] plugin.terraform-provider-aws: google.golang.org/grpc.(*Server).handleStream(0xc00059ae00, 0x7265aa0, 0xc001340600, 0xc000132600, 0x0)
2021-02-03T08:14:45.976-0500 [DEBUG] plugin.terraform-provider-aws: 	/home/kit/wrk/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd05
2021-02-03T08:14:45.976-0500 [DEBUG] plugin.terraform-provider-aws: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000f56160, 0xc00059ae00, 0x7265aa0, 0xc001340600, 0xc000132600)
2021-02-03T08:14:45.977-0500 [DEBUG] plugin.terraform-provider-aws: 	/home/kit/wrk/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xa5
2021-02-03T08:14:45.977-0500 [DEBUG] plugin.terraform-provider-aws: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-02-03T08:14:45.977-0500 [DEBUG] plugin.terraform-provider-aws: 	/home/kit/wrk/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
```

https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/data_source_aws_vpc_endpoint_service.go#L137-L159
