### ISSUE TITLE
tests/cloud_formation_stack_set_instance: Panic at the Terraform v0.15.0-alpha

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#17769]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Acceptance Test

`TestAccAWSCloudFormationStackSetInstance_RetainStack` panics on Terraform v0.15 Alpha 3:

```
    resource_aws_cloudformation_stack_set_instance_test.go:251: Step 5/5 error: Error running destroy: exit status 2
        panic: runtime error: invalid memory address or nil pointer dereference
        [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb173ba]
        
        goroutine 18 [running]:
        github.com/hashicorp/terraform/configs/configload.(*Loader).ImportSourcesFromSnapshot(0xc0004b6b40, 0x0)
        	/home/circleci/project/project/configs/configload/loader.go:143 +0x3a
        github.com/hashicorp/terraform/backend/local.(*Local).context(0xc00056b5f0, 0xc000198b60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        	/home/circleci/project/project/backend/local/backend_local.go:108 +0x8d2
        github.com/hashicorp/terraform/backend/local.(*Local).opApply(0xc00056b5f0, 0x2ca1aa0, 0xc000474e40, 0x2ca1aa0, 0xc000474e80, 0xc000198b60, 0xc000474e00)
        	/home/circleci/project/project/backend/local/backend_apply.go:51 +0x2bf
        github.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc0002e1c50, 0xc0002e1c60, 0xc0002e1c70, 0xc00056b5f0, 0xc0002e1c40, 0x2ca1aa0, 0xc000474e40, 0x2ca1aa0, 0xc000474e80, 0xc000198b60, ...)
        	/home/circleci/project/project/backend/local/backend.go:345 +0xe8
        created by github.com/hashicorp/terraform/backend/local.(*Local).Operation
        	/home/circleci/project/project/backend/local/backend.go:339 +0x36d
--- FAIL: TestAccAWSCloudFormationStackSetInstance_RetainStack (169.59s)
```

### Affected Resources

* aws_cloudformation_stack_set_instance

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_cloudformation_stack_set_instance" "test" {
  depends_on = [aws_iam_role_policy.Administration, aws_iam_role_policy.Execution]

  retain_stack   = true
  stack_set_name = aws_cloudformation_stack_set.test.name
}
```

### References

* https://github.com/hashicorp/terraform/releases/tag/v0.15.0-alpha20210210

**Comment by YakDriver** [comment]
This should be resolved by hashicorp/terraform#27924. Will verify and close if possible.
