### ISSUE TITLE
tests/dx_gateway_association: Panic at the Terraform v0.15.0-alpha

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#17772]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Acceptance Test

`TestAccAwsDxGatewayAssociation_allowedPrefixesVpnGatewayCrossAccount ` panics on Terraform v0.15.0-alpha:

```
Test ended in panic.

--- FAIL: TestAccAwsDxGatewayAssociation_allowedPrefixesVpnGatewayCrossAccount (1923.51s)

------- Stderr: -------
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5c84a2d]

goroutine 7 [running]:
testing.tRunner.func1.1(0x6aee880, 0xc45d630)
	/opt/goenv/versions/1.15.5/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc001c27200)
	/opt/goenv/versions/1.15.5/src/testing/testing.go:1075 +0x41a
panic(0x6aee880, 0xc45d630)
	/opt/goenv/versions/1.15.5/src/runtime/panic.go:969 +0x1b9
github.com/terraform-providers/terraform-provider-aws/aws.testAccCheckAwsDxGatewayAssociationExists.func1(0xc0022f08c0, 0x0, 0x501)
	/opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_dx_gateway_association_test.go:579 +0x2cd
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.ComposeTestCheckFunc.func1(0xc0022f08c0, 0xc001c27200, 0xc00559f688)
	/opt/teamcity-agent/work/2e10e023da0c7520/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/resource/testing.go:633 +0x85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.testStepNewConfig(0x88ab0a0, 0xc001c27200, 0x0, 0xc0023a1750, 0xc001c9dc80, 0x0, 0x0, 0x0, 0x0, 0x7de4328, ...)
	/opt/teamcity-agent/work/2e10e023da0c7520/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/resource/testing_new_config.go:114 +0x184e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.runNewTest(0x88ab0a0, 0xc001c27200, 0x0, 0xc0023a1750, 0xc001c9dc80, 0x0, 0x0, 0x0, 0x0, 0x7de4328, ...)
	/opt/teamcity-agent/work/2e10e023da0c7520/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/resource/testing_new.go:128 +0x3b8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.Test(0x88ab0a0, 0xc001c27200, 0x0, 0xc0023a1750, 0xc001c9dc80, 0x0, 0x0, 0x0, 0x0, 0x7de4328, ...)
	/opt/teamcity-agent/work/2e10e023da0c7520/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/resource/testing.go:558 +0x3e5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.ParallelTest(0x88ab0a0, 0xc001c27200, 0x0, 0xc0023a1750, 0xc001c9dc80, 0x0, 0x0, 0x0, 0x0, 0x7de4328, ...)
	/opt/teamcity-agent/work/2e10e023da0c7520/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/resource/testing.go:496 +0xb8
github.com/terraform-providers/terraform-provider-aws/aws.TestAccAwsDxGatewayAssociation_allowedPrefixesVpnGatewayCrossAccount(0xc001c27200)
	/opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_dx_gateway_association_test.go:445 +0x8f8
testing.tRunner(0xc001c27200, 0x7ddaf88)
	/opt/goenv/versions/1.15.5/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	/opt/goenv/versions/1.15.5/src/testing/testing.go:1168 +0x2b3
```

### Affected Resources

* aws_dx_gateway_association
* aws_dx_gateway_association_proposal

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Creator
resource "aws_dx_gateway_association_proposal" "test" {
  dx_gateway_id               = aws_dx_gateway.test.id
  dx_gateway_owner_account_id = aws_dx_gateway.test.owner_account_id
  associated_gateway_id       = aws_vpn_gateway_attachment.test.vpn_gateway_id

  allowed_prefixes = [
    "10.255.255.0/30",
    "10.255.255.8/30",
  ]
}

# Accepter
resource "aws_dx_gateway_association" "test" {
  provider = "awsalternate"

  proposal_id                         = aws_dx_gateway_association_proposal.test.id
  dx_gateway_id                       = aws_dx_gateway.test.id
  associated_gateway_owner_account_id = data.aws_caller_identity.creator.account_id

  allowed_prefixes = [
    "10.255.255.8/29",
  ]
}
```

### References

* https://github.com/hashicorp/terraform/releases/tag/v0.15.0-alpha20210210

**Comment by YakDriver** [comment]
This should be resolved by hashicorp/terraform#27924. Will verify and close if possible.
