### ISSUE TITLE
tests/rds_cluster_instance: Panic at the Terraform v0.15.0-alpha

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#17775]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Acceptance Test

`TestAccAWSRDSClusterInstance_isAlreadyBeingDeleted` panics on Terraform v0.15.0-alpha:

```
    resource_aws_rds_cluster_instance_test.go:69: Step 2/2 error: Error running destroy: exit status 2
        panic: runtime error: invalid memory address or nil pointer dereference
        [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb173ba]
        
        goroutine 15 [running]:
        github.com/hashicorp/terraform/configs/configload.(*Loader).ImportSourcesFromSnapshot(0xc000646410, 0x0)
        	/home/circleci/project/project/configs/configload/loader.go:143 +0x3a
        github.com/hashicorp/terraform/backend/local.(*Local).context(0xc0000a0f70, 0xc00019a540, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        	/home/circleci/project/project/backend/local/backend_local.go:108 +0x8d2
        github.com/hashicorp/terraform/backend/local.(*Local).opApply(0xc0000a0f70, 0x2ca1aa0, 0xc000150180, 0x2ca1aa0, 0xc000150240, 0xc00019a540, 0xc000150140)
        	/home/circleci/project/project/backend/local/backend_apply.go:51 +0x2bf
        github.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc0001366b0, 0xc0001366c0, 0xc0001366d0, 0xc0000a0f70, 0xc000136630, 0x2ca1aa0, 0xc000150180, 0x2ca1aa0, 0xc000150240, 0xc00019a540, ...)
        	/home/circleci/project/project/backend/local/backend.go:345 +0xe8
        created by github.com/hashicorp/terraform/backend/local.(*Local).Operation
        	/home/circleci/project/project/backend/local/backend.go:339 +0x36d
--- FAIL: TestAccAWSRDSClusterInstance_isAlreadyBeingDeleted (782.92s) 
```

### Affected Resources

* aws_rds_cluster_instance

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
data "aws_rds_orderable_db_instance" "test" {
  engine                     = aws_rds_cluster.default.engine
  engine_version             = aws_rds_cluster.default.engine_version
  preferred_instance_classes = ["db.t3.small", "db.t2.small", "db.t3.medium"]
}

resource "aws_rds_cluster" "default" {
  cluster_identifier = "yakentifier"
  availability_zones = [
    data.aws_availability_zones.available.names[0],
    data.aws_availability_zones.available.names[1],
    data.aws_availability_zones.available.names[2]
  ]
  database_name       = "mydb"
  master_username     = "foo"
  master_password     = "mustbeeightcharacters"
  skip_final_snapshot = true
}

resource "aws_rds_cluster_instance" "cluster_instances" {
  identifier              = "yakstance"
  cluster_identifier      = aws_rds_cluster.default.id
  instance_class          = data.aws_rds_orderable_db_instance.test.instance_class
  db_parameter_group_name = aws_db_parameter_group.bar.name
  promotion_tier          = "3"
}

resource "aws_db_parameter_group" "bar" {
  name   = "yakroup"
  family = "aurora5.6"

  parameter {
    name         = "back_log"
    value        = "32767"
    apply_method = "pending-reboot"
  }

  tags = {
    foo = "bar"
  }
}
```

### References

* https://github.com/hashicorp/terraform/releases/tag/v0.15.0-alpha20210210

**Comment by YakDriver** [comment]
This should be resolved by hashicorp/terraform#27924. Will verify and close if possible.
