### ISSUE TITLE
tests/emr_cluster: Panic at the Terraform v0.15.0-alpha

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#17774]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Acceptance Test

`TestAccAWSEMRCluster_Ec2Attributes_DefaultManagedSecurityGroups` panics on Terraform v0.15.0-alpha:

```
    resource_aws_emr_cluster_test.go:507: Step 2/3, expected an error with pattern, no match on: Error running destroy: exit status 2
        panic: runtime error: invalid memory address or nil pointer dereference
        [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb173ba]
        
        goroutine 9 [running]:
        github.com/hashicorp/terraform/configs/configload.(*Loader).ImportSourcesFromSnapshot(0xc0005795e0, 0x0)
        	/home/circleci/project/project/configs/configload/loader.go:143 +0x3a
        github.com/hashicorp/terraform/backend/local.(*Local).context(0xc00065b1e0, 0xc0001a8b60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        	/home/circleci/project/project/backend/local/backend_local.go:108 +0x8d2
        github.com/hashicorp/terraform/backend/local.(*Local).opApply(0xc00065b1e0, 0x2ca1aa0, 0xc00022be00, 0x2ca1aa0, 0xc00022be40, 0xc0001a8b60, 0xc00022bdc0)
        	/home/circleci/project/project/backend/local/backend_apply.go:51 +0x2bf
        github.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc000577520, 0xc000577530, 0xc000577540, 0xc00065b1e0, 0xc000577510, 0x2ca1aa0, 0xc00022be00, 0x2ca1aa0, 0xc00022be40, 0xc0001a8b60, ...)
        	/home/circleci/project/project/backend/local/backend.go:345 +0xe8
        created by github.com/hashicorp/terraform/backend/local.(*Local).Operation
        	/home/circleci/project/project/backend/local/backend.go:339 +0x36d
    testing_new.go:63: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: Error deleting VPC: DependencyViolation: The vpc 'vpc-017270ddd58c64e5c' has dependencies and cannot be deleted.
        	status code: 400, request id: a9d1c054-31dd-4823-a3f5-96e5f088ddfb
        
        
--- FAIL: TestAccAWSEMRCluster_Ec2Attributes_DefaultManagedSecurityGroups (723.56s)
```

### Affected Resources

* aws_emr_cluster

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_emr_cluster" "tf-test-cluster" {
  applications                      = ["Spark"]
  keep_job_flow_alive_when_no_steps = true
  name                              = "yakuster"
  release_label                     = "emr-5.28.0"
  service_role                      = "EMR_DefaultRole"

  ec2_attributes {
    instance_profile = "EMR_EC2_DefaultRole"
    subnet_id        = aws_subnet.test.id
  }

  master_instance_group {
    instance_type = "m4.large"
  }

  depends_on = [aws_route_table_association.test]
}
```

### References

* https://github.com/hashicorp/terraform/releases/tag/v0.15.0-alpha20210210

**Comment by YakDriver** [comment]
This should be resolved by hashicorp/terraform#27924. Will verify and close if possible.
