### ISSUE TITLE
ImportSourcesFromSnapshot: Panic at the Terraform 0.15-beta

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#17927]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

This should be resolved by hashicorp/terraform#27924 which was not included in 0.15.0-beta1.

### Affected Resources

* aws_db_instance
* aws_cloudfront_distribution
* aws_cloudformation_stack_set_instance
* aws_emr_cluster
* aws_rds_cluster_instance

#### TestAccAWSDBInstance_IsAlreadyBeingDeleted

```hcl
resource "aws_db_instance" "test" {
  allocated_storage   = 5
  engine              = data.aws_rds_orderable_db_instance.test.engine
  identifier          = "yaktest-001"
  instance_class      = data.aws_rds_orderable_db_instance.test.instance_class
  password            = "avoid-plaintext-passwords"
  username            = "tfacctest"
  skip_final_snapshot = true
}
```

#### TestAccAWSCloudFormationStackSetInstance_RetainStack

```hcl
resource "aws_cloudfront_distribution" "test" {
  enabled          = true
  retain_on_delete = true

  default_cache_behavior {
    allowed_methods        = ["GET", "HEAD"]
    cached_methods         = ["GET", "HEAD"]
    target_origin_id       = "test"
    viewer_protocol_policy = "allow-all"

    forwarded_values {
      query_string = false

      cookies {
        forward = "all"
      }
    }
  }

  origin {
    domain_name = "www.example.com"
    origin_id   = "test"

    custom_origin_config {
      http_port              = 80
      https_port             = 443
      origin_protocol_policy = "https-only"
      origin_ssl_protocols   = ["TLSv1.2"]
    }
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  viewer_certificate {
    cloudfront_default_certificate = true
  }
}
```

#### TestAccAWSCloudFormationStackSetInstance_RetainStack

```hcl
resource "aws_cloudformation_stack_set_instance" "test" {
  depends_on = [aws_iam_role_policy.Administration, aws_iam_role_policy.Execution]

  retain_stack   = true
  stack_set_name = aws_cloudformation_stack_set.test.name
}
```

#### TestAccAWSEMRCluster_Ec2Attributes_DefaultManagedSecurityGroups

```hcl
resource "aws_emr_cluster" "tf-test-cluster" {
  applications                      = ["Spark"]
  keep_job_flow_alive_when_no_steps = true
  name                              = "yaktest-001"
  release_label                     = "emr-5.28.0"
  service_role                      = "EMR_DefaultRole"

  ec2_attributes {
    instance_profile = "EMR_EC2_DefaultRole"
    subnet_id        = aws_subnet.test.id
  }

  master_instance_group {
    instance_type = "m4.large"
  }

  depends_on = [aws_route_table_association.test]
}
```

#### TestAccAWSRDSClusterInstance_isAlreadyBeingDeleted

```hcl
resource "aws_rds_cluster" "default" {
  cluster_identifier = "yakluster"
  availability_zones = [
    data.aws_availability_zones.available.names[0],
    data.aws_availability_zones.available.names[1],
    data.aws_availability_zones.available.names[2]
  ]
  database_name       = "mydb"
  master_username     = "foo"
  master_password     = "mustbeeightcharacters"
  skip_final_snapshot = true
}

resource "aws_rds_cluster_instance" "cluster_instances" {
  identifier              = "yakluster-001"
  cluster_identifier      = aws_rds_cluster.default.id
  instance_class          = data.aws_rds_orderable_db_instance.test.instance_class
  db_parameter_group_name = aws_db_parameter_group.bar.name
  promotion_tier          = "3"
}
```

### Panic Output

```
    resource_aws_db_instance_test.go:483: Step 2/2 error: Error running destroy: exit status 2
        panic: runtime error: invalid memory address or nil pointer dereference
        [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc741ba]
        
        goroutine 52 [running]:
        github.com/hashicorp/terraform/configs/configload.(*Loader).ImportSourcesFromSnapshot(0xc0000d54a0, 0x0)
        	/home/circleci/project/project/configs/configload/loader.go:143 +0x3a
        github.com/hashicorp/terraform/backend/local.(*Local).context(0xc0004b92c0, 0xc0004bcb00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        	/home/circleci/project/project/backend/local/backend_local.go:100 +0x819
        github.com/hashicorp/terraform/backend/local.(*Local).opApply(0xc0004b92c0, 0x2bfb3b8, 0xc000320f40, 0x2bfb3b8, 0xc000320f80, 0xc0004bcb00, 0xc000320f00)
        	/home/circleci/project/project/backend/local/backend_apply.go:45 +0x245
        github.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc0000c9710, 0xc0000c9720, 0xc0000c9730, 0xc0004b92c0, 0xc0000c9700, 0x2bfb3b8, 0xc000320f40, 0x2bfb3b8, 0xc000320f80, 0xc0004bcb00, ...)
        	/home/circleci/project/project/backend/local/backend.go:321 +0xe8
        created by github.com/hashicorp/terraform/backend/local.(*Local).Operation
        	/home/circleci/project/project/backend/local/backend.go:315 +0x2f2
```

### References

* #0000

**Comment by YakDriver** [comment]
This appears to be resolved with Terraform 0.15.0-beta2.
