### ISSUE TITLE
Panic at Terraform 0.15.0-rc1: value is not known

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#18532]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.15.0-rc1
AWS provider v3.34.0

### Failing tests

1. TestAccAWSAMI_disappears
1. TestAccAWSAMIFromInstance_disappears
1. TestAccAWSAMILaunchPermission_Disappears_AMI
1. TestAccAWSAPIGatewayDeployment_disappears_RestApi
1. TestAccAWSAPIGatewayRestApi_disappears
1. TestAccAWSAPIGatewayRestApiPolicy_disappears_restApi
1. TestAccAWSAppCookieStickinessPolicy_disappears_ELB
1. TestAccAWSAppsyncGraphqlApi_disappears
1. TestAccAWSBudgetsBudget_basic
1. TestAccAWSBudgetsBudget_disappears
1. TestAccAWSCloudFormationStack_disappears
1. TestAccAWSCloudFrontDistribution_disappears
1. TestAccAWSCodeDeployDeploymentGroup_disappears
1. TestAccAWSCognitoUserPool_disappears
1. TestAccAWSCognitoUserPoolClient_disappears_userPool
1. TestAccAWSDAXCluster_encryption_enabled
1. TestAccAWSDBProxyDefaultTargetGroup_disappears
1. TestAccAWSDefaultRouteTable_disappears_Vpc
1. TestAccAWSDirectoryServiceDirectory_disappears
1. TestAccAwsDxGatewayAssociation_recreateProposal
1. TestAccAwsDxGatewayAssociationProposal_disappears
1. TestAccAWSDynamoDbTable_disappears
1. TestAccAWSDynamoDbTable_disappears_PayPerRequestWithGSI
1. TestAccAwsEc2ClientVpn_serial/NetworkAssociation_disappears
1. TestAccAWSEcsCapacityProvider_disappears
1. TestAccAWSEcsCluster_disappears
1. TestAccAWSEFSAccessPoint_disappears
1. TestAccAWSEFSFileSystem_disappears
1. TestAccAWSEFSMountTarget_disappears
1. TestAccAWSEksNodeGroup_disappears
1. TestAccAWSElasticacheReplicationGroup_disappears
1. TestAccAWSElasticacheReplicationGroup_GlobalReplicationGroupId_disappears
1. TestAccAWSElasticTranscoderPipeline_disappears
1. TestAccAWSELB_disappears
1. TestAccAWSEMRCluster_disappears
1. TestAccAWSEMRInstanceFleet_disappears
1. TestAccAWSEMRInstanceGroup_disappears_EmrCluster
1. TestAccAWSENI_disappears
1. TestAccAWSFsxLustreFileSystem_disappears
1. TestAccAWSFsxWindowsFileSystem_disappears
1. TestAccAWSGameliftFleet_disappears
1. TestAccAwsGlobalAcceleratorAccelerator_disappears
1. TestAccAWSGlueJob_disappears
1. TestAccAWSGlueMLTransform_disappears
1. TestAccAWSIAMInstanceProfile_disappears_role
1. TestAccAWSIAMRole_disappears
1. TestAccAwsImageBuilderImage_disappears
1. TestAccAwsImageBuilderImagePipeline_disappears
1. TestAccAWSInstance_disappears
1. TestAccAWSKinesisAnalyticsV2Application_disappears
1. TestAccAWSKinesisFirehoseDeliveryStream_disappears
1. TestAccAWSLambdaFunction_disappears
1. TestAccAWSLambdaFunctionEventInvokeConfig_disappears_LambdaFunction
1. TestAccAWSLambdaProvisionedConcurrencyConfig_disappears_LambdaFunction
1. TestAccAWSLaunchConfiguration_RootBlockDevice_AmiDisappears
1. TestAccAWSLaunchTemplate_disappears
1. TestAccAWSLBCookieStickinessPolicy_disappears_ELB
1. TestAccAWSLBSSLNegotiationPolicy_disappears
1. TestAccAWSLBTargetGroup_stickinessInvalidALB
1. TestAccAWSLightsailInstance_disapear
1. TestAccAWSLoadBalancerPolicy_disappears
1. TestAccAWSMediaConvertQueue_disappears
1. TestAccAWSMqBroker_disappears
1. TestAccAWSNetworkAcl_disappears
1. TestAccAWSNetworkAclRule_disappears_NetworkAcl
1. TestAccAwsNetworkFirewallFirewall_disappears
1. TestAccAWSRDSCluster_SnapshotIdentifier_MasterUsername
1. TestAccAWSRdsGlobalCluster_disappears
1. TestAccAWSRolePolicyAttachment_disappears_Role
1. TestAccAWSRoute_disappears_RouteTable
1. TestAccAWSRoute53Zone_disappears
1. TestAccAWSRoute53ZoneAssociation_disappears_Zone
1. TestAccAWSRouteTable_disappears
1. TestAccAWSRouteTable_disappears_SubnetAssociation
1. TestAccAWSS3AccessPoint_disappears_Bucket
1. TestAccAWSS3Bucket_shouldFailNotFound
1. TestAccAWSS3BucketOwnershipControls_disappears_Bucket
1. TestAccAWSS3BucketPublicAccessBlock_disappears_Bucket
1. TestAccAWSSagemakerNotebookInstance_disappears
1. TestAccAwsServerlessApplicationRepositoryCloudFormationStack_disappears
1. TestAccAWSSfnStateMachine_disappears
1. TestAccAWSSpotFleetRequest_disappears
1. TestAccAWSSpotInstanceRequest_disappears
1. TestAccAWSSSMAssociation_disappears
1. TestAccAWSSSMDocument_disappears
1. TestAccAWSStorageGatewayGateway_disappears
1. TestAccAWSSubnet_disappears
1. TestAccAWSSyntheticsCanary_disappears
1. TestAccAWSTransferUser_UserName_Validation
1. TestAccAWSVpc_disappears
1. TestAccAWSVpcEndpoint_disappears
1. TestAccAWSVpcEndpointService_disappears
1. TestAccAWSVPCPeeringConnection_plan
1. TestAccAWSVpnConnection_disappears
1. TestAccAwsWorkspacesDirectory_disappears

### Terraform Configuration Files

See individual tests.

### Panic Output

```
resource_aws_ami_from_instance_test.go:89: Step 1/1 error: Error retrieving second post-apply plan: exit status 2
        panic: value is not known
        
        goroutine 1 [running]:
        github.com/zclconf/go-cty/cty.Value.LengthInt(0x2c2d660, 0xc0016304d0, 0x23c9fa0, 0x3ce5e80, 0xc0019eef00)
        	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.1/cty/value_ops.go:1055 +0x2a7
        github.com/hashicorp/terraform/command/jsonplan.sensitiveAsBool(0x2c2d660, 0xc0016304d0, 0x23c9fa0, 0x3ce5e80, 0xc001630fd0, 0x2c2d660, 0xc0016304d0, 0x23c9fa0)
        	/home/circleci/project/project/command/jsonplan/plan.go:525 +0x1a5
        github.com/hashicorp/terraform/command/jsonplan.sensitiveAsBool(0x2c2d628, 0xc001630f90, 0x23f3a00, 0xc001628c90, 0x0, 0x0, 0x0, 0x2c2d628)
        	/home/circleci/project/project/command/jsonplan/plan.go:558 +0x685
        github.com/hashicorp/terraform/command/jsonplan.(*plan).marshalResourceChanges(0xc0001692c0, 0xc0017d8090, 0xc000390580, 0x0, 0x0)
        	/home/circleci/project/project/command/jsonplan/plan.go:241 +0xef9
        github.com/hashicorp/terraform/command/jsonplan.Marshal(0xc000395380, 0xc000b2eaf0, 0xc0017d8480, 0xc000390580, 0x0, 0x0, 0x0, 0x0, 0x0)
        	/home/circleci/project/project/command/jsonplan/plan.go:124 +0x23f
        github.com/hashicorp/terraform/command.(*ShowCommand).Run(0xc000234fc0, 0xc00004c0d0, 0x1, 0x3, 0xc00045f790)
        	/home/circleci/project/project/command/show.go:152 +0x966
        github.com/mitchellh/cli.(*CLI).Run(0xc00078e780, 0xc000704930, 0x27b2949, 0x4)
        	/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x41a
        main.wrappedMain(0x0)
        	/home/circleci/project/project/main.go:379 +0x10e8
        main.realMain(0x0)
        	/home/circleci/project/project/main.go:115 +0x554
        main.main()
        	/home/circleci/project/project/main.go:58 +0x25
```

### References

* hashicorp/terraform#28253

**Comment by YakDriver** [comment]
Closing this as testing on `0.15.0-rc2` did not produce the same error.
