### ISSUE TITLE
Panic at Terraform 0.15.0-rc1: runtime error

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#18555]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.15.0-rc1
AWS provider v3.34.0

### Failing tests

1. TestAccAwsDxGatewayAssociation_allowedPrefixesVpnGatewayCrossAccount

### Terraform Configuration Files

See individual tests.

### Panic Output

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5ed4250]

goroutine 8 [running]:
testing.tRunner.func1.2(0x6d667c0, 0xc5d5790)
	/opt/goenv/versions/1.16.0/src/testing/testing.go:1144 +0x332
testing.tRunner.func1(0xc001cd1980)
	/opt/goenv/versions/1.16.0/src/testing/testing.go:1147 +0x4b6
panic(0x6d667c0, 0xc5d5790)
	/opt/goenv/versions/1.16.0/src/runtime/panic.go:965 +0x1b9
github.com/terraform-providers/terraform-provider-aws/aws.testAccCheckAwsDxGatewayAssociationExists.func1(0xc0077f0850, 0x0, 0x501)
	/opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_dx_gateway_association_test.go:588 +0x2d0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.ComposeTestCheckFunc.func1(0xc0077f0850, 0xc001cd1980, 0xc005851768)
	/opt/teamcity-agent/work/2e10e023da0c7520/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/resource/testing.go:633 +0x85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.testStepNewConfig(0x8b88dd8, 0xc001cd1980, 0x0, 0xc0025ffb60, 0xc001d3cb10, 0x0, 0x0, 0x0, 0x0, 0x80b02c8, ...)
	/opt/teamcity-agent/work/2e10e023da0c7520/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/resource/testing_new_config.go:114 +0x185e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.runNewTest(0x8b88dd8, 0xc001cd1980, 0x0, 0xc0025ffb60, 0xc001d3cb10, 0x0, 0x0, 0x0, 0x0, 0x80b02c8, ...)
	/opt/teamcity-agent/work/2e10e023da0c7520/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/resource/testing_new.go:128 +0x398
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.Test(0x8b88dd8, 0xc001cd1980, 0x0, 0xc0025ffb60, 0xc001d3cb10, 0x0, 0x0, 0x0, 0x0, 0x80b02c8, ...)
	/opt/teamcity-agent/work/2e10e023da0c7520/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/resource/testing.go:558 +0x3e5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.ParallelTest(0x8b88dd8, 0xc001cd1980, 0x0, 0xc0025ffb60, 0xc001d3cb10, 0x0, 0x0, 0x0, 0x0, 0x80b02c8, ...)
	/opt/teamcity-agent/work/2e10e023da0c7520/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/resource/testing.go:496 +0xb8
github.com/terraform-providers/terraform-provider-aws/aws.TestAccAwsDxGatewayAssociation_allowedPrefixesVpnGatewayCrossAccount(0xc001cd1980)
	/opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_dx_gateway_association_test.go:452 +0x978
testing.tRunner(0xc001cd1980, 0x80a6b60)
	/opt/goenv/versions/1.16.0/src/testing/testing.go:1194 +0xef
created by testing.(*T).Run
	/opt/goenv/versions/1.16.0/src/testing/testing.go:1239 +0x2b3
```

### References

* #0000

**Comment by YakDriver** [comment]
Closing this as testing on `0.15.0-rc2` did not produce the same error.
