### ISSUE TITLE
null element in aws_ecs_task_definition container_definitions causes provider panic

### ISSUE THREAD

**Issue by zswanson** [hashicorp/terraform-provider-aws#19531]
In creating a list of json encoded container defintions to pass to a ecs task definition I introduced a `null` default value for an optional side-car container_definition in the task. If that null is not filtered out the aws provider has a panic during terraform plan/apply. This was a user error on my part as I should have run a `compact` on the list but also seems like the provider should better handle possibility of null/empty inputs here.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.15.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.42.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/local v2.1.0

### Affected Resource(s)

* aws_ecs_task_definition

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_ecs_task_definition" "this" {
  container_definitions = jsonencode(flatten([
    var.json_map_container_definitions,
    [module.fluentbit_firelens_container_definition.json_map_object]
  ]))

  cpu                                   = var.task_cpu
  family                               = local.namespace
  memory                           = var.task_memory
  network_mode                = "awsvpc"
  tags                                  = local.tags
  requires_compatibilities = ["FARGATE"]
  execution_role_arn         = aws_iam_role.execution.arn
  task_role_arn                  = aws_iam_role.task.arn
}
```
In the snippet above the `var.json_map_container_definitions` is a list of maps produced by the cloudposse container-definition module as a convenience method to create ECS container definition json and includes 1 null item. The parent module has an optional sidecar pre-defined, but sets the container definition object to `null` if not selected for use. That null persists into the jsonencoding and the provider panics when it tries to access the task environment variables for sorting.

### Panic Output

https://gist.github.com/zswanson/d6e9058e17151066f1fe2de1384abcbb

### Expected Behavior

Output indicating that a null element was found during the plan and terraform to gracefully terminate the plan

### Actual Behavior

Terraform provider panics, plan/apply fails 

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by ewbankkit** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa8 pc=0x516c61b]

goroutine 252 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.containerDefinitions.OrderEnvironmentVariables(0xc001d9e5a0, 0x4, 0x4)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/ecs_task_definition_equivalency.go:107 +0x3b
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsEcsTaskDefinition.func2(0x6387780, 0xc001d8f0b0, 0x15, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_ecs_task_definition.go:83 +0x85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diffString(0xc000b061b0, 0x7a34099, 0x15, 0xc000b09180, 0xc001c35508, 0x8519d70, 0xc001781480, 0x203000, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/schema.go:1375 +0x6e3
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diff(0xc000b061b0, 0x7a34099, 0x15, 0xc000b09180, 0xc001d9e360, 0x8519d70, 0xc001781480, 0xc001a2b900, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/schema.go:957 +0x4e8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc000b061b0, 0x84ff548, 0xc001a50740, 0xc000db8310, 0xc001a7fcb0, 0x7b4b1d0, 0x6c6f040, 0xc001052600, 0xbb4c700, 0x6387780, ...)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/schema.go:522 +0x219
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0xc000a71dc0, 0x84ff548, 0xc001a50740, 0xc000db8310, 0xc001a7fcb0, 0x6c6f040, 0xc001052600, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:506 +0xa5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0xc0007a05b8, 0x84ff548, 0xc001a50740, 0xc0019e1450, 0xc001a50740, 0x77ee4a0, 0xc001a7e900)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/grpc_provider.go:693 +0x7c5
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).PlanResourceChange(0xc002014600, 0x84ff5f0, 0xc001a50740, 0xc000db81c0, 0xc002014600, 0xc001a7e9c0, 0xc001ff1ba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:315 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler(0x77ee4a0, 0xc002014600, 0x84ff5f0, 0xc001a7e9c0, 0xc00128ac60, 0x0, 0x84ff5f0, 0xc001a7e9c0, 0xc001a3e600, 0x10a3)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:362 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0009a5340, 0x85203f8, 0xc00035a600, 0xc0019d6d00, 0xc0013bbec0, 0xbb0a4a8, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0009a5340, 0x85203f8, 0xc00035a600, 0xc0019d6d00, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000efeb40, 0xc0009a5340, 0x85203f8, 0xc00035a600, 0xc0019d6d00)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
```

https://github.com/hashicorp/terraform-provider-aws/blob/d7e16d776d9f9e13945513caf46aa3cab8578442/aws/ecs_task_definition_equivalency.go#L105-L111

**Comment by reskin89** [comment]
I am also experiencing this issue, are there any plans to merge a fix?
