### ISSUE TITLE
Error: Plugin did not respond

### ISSUE THREAD

**Issue by ElSamhaa** [hashicorp/terraform-provider-aws#19601]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.15.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.42.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.2.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

### Affected Resource(s)

* aws_autoscaling_group

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
provider "aws" {
  region = "eu-west-3"
}

resource "aws_vpc" "temp_eks_consul_vpc" {
  cidr_block = "10.255.0.0/16"

  tags = merge(var.tags, {
    Name = "temp_eks_consul_vpc"
  })
}

locals {
  az      = toset( ["eu-west-3a", "eu-west-3b", "eu-west-3c"] )
  az_map  = { for az in local.az : index(tolist(local.az), az) => az }
}

resource "aws_subnet" "temp_eks_consul_subnets" {
  for_each = local.az_map

  vpc_id                  = aws_vpc.temp_eks_consul_vpc.id
  cidr_block              = "10.255.${tonumber(each.key) + 1}.0/24"
  map_public_ip_on_launch = true

  tags = var.tags
}

output "subnets" {
  value = aws_subnet.temp_eks_consul_subnets
}

module "temp_eks_consul_eks" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = "temp_eks_consul_eks"
  subnets         = values(aws_subnet.temp_eks_consul_subnets)[*].id
  vpc_id          = aws_vpc.temp_eks_consul_vpc.id
  cluster_version = "1.20"

  worker_groups = [
    {
      instance_type = "m4.large"
      asg_max_size  = 5
    }
  ]
  tags = var.tags
}
```

### Debug Output

https://gist.github.com/ElSamhaa/c5e78295bfe9134afc292915047836f4

### Expected Behavior

Upon running `terraform destroy -auto-approve`, all resources should have been destroyed.

### Actual Behavior

Upon running `terraform apply -auto-approve`, Terraform gets stuck at the autoscaling group worker creation until it times out. In order to fix this, I've tried running `terraform destroy -auto-approve` to recreate the whole set of resources, which produced this behavior.

### Steps to Reproduce

1. `terraform destroy -auto-approve`

### References

* #0000

**Comment by ewbankkit** [comment]
```
2021-06-01T01:14:03.797+0200 [DEBUG] provider.terraform-provider-aws_v3.42.0_x5: PANIC: interface conversion: interface {} is nil, not *aws.AWSClient
2021-06-01T01:14:03.797+0200 [DEBUG] provider.terraform-provider-aws_v3.42.0_x5: 
2021-06-01T01:14:03.797+0200 [DEBUG] provider.terraform-provider-aws_v3.42.0_x5: goroutine 48 [running]:
2021-06-01T01:14:03.797+0200 [DEBUG] provider.terraform-provider-aws_v3.42.0_x5: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsAutoscalingGroupRead(0xc001ba8b80, 0x0, 0x0, 0xbb4acf0, 0xc000640d80)
2021-06-01T01:14:03.797+0200 [DEBUG] provider.terraform-provider-aws_v3.42.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_autoscaling_group.go:842 +0x270f
2021-06-01T01:14:03.797+0200 [DEBUG] provider.terraform-provider-aws_v3.42.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0004eea80, 0x84ff548, 0xc0021ef100, 0xc001ba8b80, 0x0, 0x0, 0x0, 0x0, 0x0)
2021-06-01T01:14:03.797+0200 [DEBUG] provider.terraform-provider-aws_v3.42.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:335 +0x1ee
2021-06-01T01:14:03.797+0200 [DEBUG] provider.terraform-provider-aws_v3.42.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0004eea80, 0x84ff548, 0xc0021ef100, 0xc001e32150, 0x0, 0x0, 0xc001b1ac80, 0x0, 0x0, 0x0)
2021-06-01T01:14:03.797+0200 [DEBUG] provider.terraform-provider-aws_v3.42.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:624 +0x1cb
2021-06-01T01:14:03.797+0200 [DEBUG] provider.terraform-provider-aws_v3.42.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000308b58, 0x84ff548, 0xc0021ef100, 0xc0021ef140, 0xc0021ef100, 0x100b665, 0x7532c60)
2021-06-01T01:14:03.797+0200 [DEBUG] provider.terraform-provider-aws_v3.42.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/grpc_provider.go:575 +0x43b
2021-06-01T01:14:03.797+0200 [DEBUG] provider.terraform-provider-aws_v3.42.0_x5: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc001f7bc60, 0x84ff5f0, 0xc0021ef100, 0xc001baa5a0, 0xc001f7bc60, 0xc001e268a0, 0xc0020a1ba0)
2021-06-01T01:14:03.797+0200 [DEBUG] provider.terraform-provider-aws_v3.42.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
2021-06-01T01:14:03.797+0200 [DEBUG] provider.terraform-provider-aws_v3.42.0_x5: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x77ee4a0, 0xc001f7bc60, 0x84ff5f0, 0xc001e268a0, 0xc001baa540, 0x0, 0x84ff5f0, 0xc001e268a0, 0xc001e2ce00, 0x679)
2021-06-01T01:14:03.797+0200 [DEBUG] provider.terraform-provider-aws_v3.42.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
2021-06-01T01:14:03.797+0200 [DEBUG] provider.terraform-provider-aws_v3.42.0_x5: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002336c0, 0x85203f8, 0xc0005aa600, 0xc001d34100, 0xc00069a210, 0xbb0a490, 0x0, 0x0, 0x0)
2021-06-01T01:14:03.797+0200 [DEBUG] provider.terraform-provider-aws_v3.42.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
2021-06-01T01:14:03.797+0200 [DEBUG] provider.terraform-provider-aws_v3.42.0_x5: google.golang.org/grpc.(*Server).handleStream(0xc0002336c0, 0x85203f8, 0xc0005aa600, 0xc001d34100, 0x0)
2021-06-01T01:14:03.797+0200 [DEBUG] provider.terraform-provider-aws_v3.42.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
2021-06-01T01:14:03.797+0200 [DEBUG] provider.terraform-provider-aws_v3.42.0_x5: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000794ca0, 0xc0002336c0, 0x85203f8, 0xc0005aa600, 0xc001d34100)
2021-06-01T01:14:03.797+0200 [DEBUG] provider.terraform-provider-aws_v3.42.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
2021-06-01T01:14:03.797+0200 [DEBUG] provider.terraform-provider-aws_v3.42.0_x5: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-06-01T01:14:03.797+0200 [DEBUG] provider.terraform-provider-aws_v3.42.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
```

**Comment by justinretzolk** [comment]
Hi @ElSamhaa 👋 Terraform `v1.0.9` was released yesterday which [includes a fix](https://github.com/hashicorp/terraform/blob/v1.0.9/CHANGELOG.md#109-october-13-2021) that should correct this issue. Can you test again to verify that you're no longer experience this issue?

**Comment by ElSamhaa** [comment]
Hi @justinretzolk, I can't test and confirm in the mean time. So, feel free to close the issue :slightly_smiling_face: .
