### ISSUE TITLE
Terraform crash when running aws_macie2_member from Macie2 module #28841

### ISSUE THREAD

**Issue by anasillo** [hashicorp/terraform-provider-aws#19611]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.7
+ provider registry.terraform.io/hashicorp/aws v3.42.0
```
### Affected Resource(s)

* aws_macie2_member 

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_macie2_account" "example" {
  finding_publishing_frequency = "ONE_HOUR"
  status                       = "ENABLED"
}

resource "aws_macie2_organization_admin_account" "example" {
  admin_account_id = var.security_account_id
  depends_on       = [aws_macie2_account.example]
}

resource "aws_macie2_member" "example" {
  for_each                              = var.aws_accounts
  account_id                            = each.value.account_id
  email                                 = each.value.email
  status                                = "ENABLED"
  invite                                = true
  invitation_message                    = "Joining Macie"
  invitation_disable_email_notification = true
}

resource "aws_macie2_invitation_accepter" "macie_admin" {
  administrator_account_id = var.security_account_id
  depends_on               = [aws_macie2_member.example]
}
```

### https://gist.github.com/anasillo/5f8e4245989461ae78a0b6d1bd3d5721

The Macie module should enable all members without crashing.

### Actual Behavior

The module enables all members but randomly (some members join correctly, others just don't), and after that crashes without reason.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Important Factoids

We have a multi-account strategy, and we're replicating the following AWS recommended architecture. https://aws.amazon.com/es/blogs/architecture/bbva-architecture-for-large-scale-macie-implementation/
### References

* N/A

**Comment by ewbankkit** [comment]
```
panic: interface conversion: interface {} is string, not bool
2021-05-28T19:11:11.345-0300 [DEBUG] plugin.terraform-provider-aws_v3.42.0_x5.exe:
2021-05-28T19:11:11.345-0300 [DEBUG] plugin.terraform-provider-aws_v3.42.0_x5.exe: goroutine 137 [running]:
2021-05-28T19:11:11.345-0300 [DEBUG] plugin.terraform-provider-aws_v3.42.0_x5.exe: github.com/terraform-providers/terraform-provider-aws/aws.resourceMacie2MemberCreate(0x7b11e48, 0xc000957200, 0xc000974900, 0x627f000, 0xc001872000, 0xc0005317b0, 0xb5ba32, 0xc000f87340)
2021-05-28T19:11:11.345-0300 [DEBUG] plugin.terraform-provider-aws_v3.42.0_x5.exe:      /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_macie2_member.go:147 +0x1448
2021-05-28T19:11:11.345-0300 [DEBUG] plugin.terraform-provider-aws_v3.42.0_x5.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000bf41c0, 0x7b11e48, 0xc000957200, 0xc000974900, 0x627f000, 0xc001872000, 0x0, 0x0, 0x0)
2021-05-28T19:11:11.345-0300 [DEBUG] plugin.terraform-provider-aws_v3.42.0_x5.exe:      /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:325 +0xb1
2021-05-28T19:11:11.345-0300 [DEBUG] plugin.terraform-provider-aws_v3.42.0_x5.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000bf41c0, 0x7b11e48, 0xc000957200, 0xc000951420, 0xc000f87340, 0x627f000, 0xc001872000, 0x0, 0x0, 0x0, ...)
2021-05-28T19:11:11.345-0300 [DEBUG] plugin.terraform-provider-aws_v3.42.0_x5.exe:      /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:456 +0x67b
2021-05-28T19:11:11.345-0300 [DEBUG] plugin.terraform-provider-aws_v3.42.0_x5.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00011cdc8, 0x7b11e48, 0xc000957200, 0xc00175a5a0, 0xc000957200, 0x6dfdd80, 0xc001a24500)
2021-05-28T19:11:11.346-0300 [DEBUG] plugin.terraform-provider-aws_v3.42.0_x5.exe:      /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/grpc_provider.go:955 +0x8ef
2021-05-28T19:11:11.346-0300 [DEBUG] plugin.terraform-provider-aws_v3.42.0_x5.exe: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc001b2c180, 0x7b11ef0, 0xc000957200, 0xc0017d09a0, 0xc001b2c180, 0xc001a245a0, 0xc001e31ba0)
2021-05-28T19:11:11.346-0300 [DEBUG] plugin.terraform-provider-aws_v3.42.0_x5.exe:      /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:332 +0xb6
2021-05-28T19:11:11.346-0300 [DEBUG] plugin.terraform-provider-aws_v3.42.0_x5.exe: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x6dfdd80, 0xc001b2c180, 0x7b11ef0, 0xc001a245a0, 0xc0003e2a80, 0x0, 0x7b11ef0, 0xc001a245a0, 0xc001a46000, 0x2cc)
2021-05-28T19:11:11.346-0300 [DEBUG] plugin.terraform-provider-aws_v3.42.0_x5.exe:      /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x222
2021-05-28T19:11:11.346-0300 [DEBUG] plugin.terraform-provider-aws_v3.42.0_x5.exe: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000ad340, 0x7b33398, 0xc0018e8180, 0xc001a84e00, 0xc001274e70, 0xb12f220, 0x0, 0x0, 0x0)
2021-05-28T19:11:11.346-0300 [DEBUG] plugin.terraform-provider-aws_v3.42.0_x5.exe:      /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
2021-05-28T19:11:11.346-0300 [DEBUG] plugin.terraform-provider-aws_v3.42.0_x5.exe: google.golang.org/grpc.(*Server).handleStream(0xc0000ad340, 0x7b33398, 0xc0018e8180, 0xc001a84e00, 0x0)
2021-05-28T19:11:11.346-0300 [DEBUG] plugin.terraform-provider-aws_v3.42.0_x5.exe:      /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
2021-05-28T19:11:11.346-0300 [DEBUG] plugin.terraform-provider-aws_v3.42.0_x5.exe: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000d56160, 0xc0000ad340, 
0x7b33398, 0xc0018e8180, 0xc001a84e00)
2021-05-28T19:11:11.346-0300 [DEBUG] plugin.terraform-provider-aws_v3.42.0_x5.exe:      /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xb2
2021-05-28T19:11:11.346-0300 [DEBUG] plugin.terraform-provider-aws_v3.42.0_x5.exe: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-05-28T19:11:11.346-0300 [DEBUG] plugin.terraform-provider-aws_v3.42.0_x5.exe:      /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
```

**Comment by anasillo** [comment]
Hello team! Do we have any update about this? 
Thank you in advance!
Best,

**Comment by rahul-amzn** [comment]
Just hit it using v3.74.x.  Any update on this please? Thanks! 

```
Stack trace from the terraform-provider-aws_v3.74.1_x5 plugin:

panic: interface conversion: interface {} is string, not bool

Error: The terraform-provider-aws_v3.74.1_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```
