### ISSUE TITLE
Updating connection_arn on aws_cloudwatch_event_api_destination crashes terraform cli

### ISSUE THREAD

**Issue by timo-reymann** [hashicorp/terraform-provider-aws#19628]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```
$ terraform -v
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/aws v3.43.0
```

### Affected Resource(s)

* aws_cloudwatch_event_api_destination

### Terraform Configuration Files

```hcl
resource "aws_cloudwatch_event_connection" "basic_auth_foo" {
  name               = "http-basic-auth-connection"
  description        = "Basic http bin integration"
  authorization_type = "BASIC"

  auth_parameters {
    basic {
      username = "foo"
      password = "bar"
    }
  }
}

resource "aws_cloudwatch_event_connection" "basic_auth_bar" {
  name               = "http-basic-auth-connection"
  description        = "Basic http bin integration"
  authorization_type = "BASIC"

  auth_parameters {
    basic {
      username = "bar"
      password = "foo"
    }
  }
}

resource "aws_cloudwatch_event_api_destination" "http_webhook" {
  name                             = "http-webhook-test"
  description                      = "An webhook Destination"
  invocation_endpoint              = var.webhook_url
  http_method                      = "POST"
  invocation_rate_limit_per_second = 20
  connection_arn                   = aws_cloudwatch_event_connection.basic_auth_bar.arn
}
```

### Trace Output
https://gist.github.com/timo-reymann/67985bee8ca086a09ea0ad54b0eb1755#file-crash-output-on-loglevel-trace

### Expected Behavior

It should recreate the resource or update the connection_arn

### Actual Behavior

Terraform crashes

### Steps to Reproduce

1. `terraform apply`
2. Change `connection_arn` to `aws_cloudwatch_event_connection.basic_auth_foo.arn`
3. Run `terraform apply`
4. Plugin crashes after approving changes

### Important Factoids

none

### Workaround
As a workaround you can taint the resource, so it gets recreated.

**Comment by ewbankkit** [comment]
```
panic: interface conversion: interface {} is int, not int64

goroutine 92 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsCloudWatchEventApiDestinationUpdate(0xc001942180, 0x6e443a0, 0xc002267200, 0x0, 0xffffffffffffffff)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_cloudwatch_event_api_destination.go:151 +0x7b9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc000878a80, 0x8752568, 0xc0019222c0, 0xc001942180, 0x6e443a0, 0xc002267200, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:352 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000878a80, 0x8752568, 0xc0019222c0, 0xc00043bb20, 0xc0010f4ac0, 0x6e443a0, 0xc002267200, 0x0, 0x0, 0x0, ...)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:464 +0x390
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00012a810, 0x8752568, 0xc0019222c0, 0xc0018a5b80, 0xc0019222c0, 0x7a040e0, 0xc0018fbc00)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc00211ac00, 0x8752610, 0xc0019222c0, 0xc00043b8f0, 0xc00211ac00, 0xc0018fbc80, 0xc0005fcba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x7a040e0, 0xc00211ac00, 0x8752610, 0xc0018fbc80, 0xc001918a80, 0x0, 0x8752610, 0xc0018fbc80, 0xc001934000, 0x4d3)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000911340, 0x8773cb8, 0xc002138780, 0xc0018ff100, 0xc001499b90, 0xbe677a0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000911340, 0x8773cb8, 0xc002138780, 0xc0018ff100, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00148e900, 0xc000911340, 0x8773cb8, 0xc002138780, 0xc0018ff100)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
```

https://github.com/hashicorp/terraform-provider-aws/blob/55a32a8590d195138bca036f91fee109894284a5/aws/resource_aws_cloudwatch_event_api_destination.go#L150-L152

Related:

* #19594
* #18905
