### ISSUE TITLE
error running terraform 1.0 destroy on local windows env

### ISSUE THREAD

**Issue by waylew50** [hashicorp/terraform-provider-aws#19807]
Hello, getting the following error when running destroy on local Windows environment

stack trace from the terraform-provider-aws_v3.45.0_x5.exe plugin:
```
panic: interface conversion: interface {} is nil, not *aws.AWSClient

goroutine 183 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsLbTargetGroupRead(0xc00242e680, 0x0, 0x0, 0xc00242b470, 0xc000580000)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_lb_target_group.go:378 +0x967
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0015088c0, 0x80973c8, 0xc002432a00, 0xc00242e680, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:335 +0x1fb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0015088c0, 0x80973c8, 0xc002432a00, 0xc001b38150, 0x0, 0x0, 0xc00243a5d8, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00010adc8, 0x80973c8, 0xc002432a00, 0xc002432a40, 0xc002432a00, 0x6dbeca, 0x7059d80)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/grpc_provider.go:575 +0x45b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc001ec3900, 0x8097470, 0xc002432a00, 0xc00241ccc0, 0xc001ec3900, 0xc002475620, 0xc00218bba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x108
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x732a5e0, 0xc001ec3900, 0x8097470, 0xc002475620, 0xc00241cc60, 0x0, 0x8097470, 0xc002475620, 0xc002476700, 0x334)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x222
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000249500, 0x80b9798, 0xc001f0c600, 0xc00197b200, 0xc001516e40, 0xb831730, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000249500, 0x80b9798, 0xc001f0c600, 0xc00197b200, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000f26210, 0xc000249500, 0x80b9798, 0xc001f0c600, 0xc00197b200)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xb2
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.45.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by ewbankkit** [comment]
Similar:

* #19788
