### ISSUE TITLE
Terraform AWS plugin crashes when destroying items

### ISSUE THREAD

**Issue by admin-edcomet** [hashicorp/terraform-provider-aws#20131]
When running `terraform destroy` on our development environment, we received an error as below
```log
Error: The terraform-provider-aws_v3.48.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```
Hence, we are reporting this for general benefit.

As a work-around, we commented the resources causing the crash, then re-initialized terraform, ran the plan and the applied the plan. This caused the offending resources to be deleted. We then proceeded to destroy the rest of the infrastructure through the regular `terraform destroy` command.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
**Terraform v1.0.0** on windows_amd64
AWS provider from **registry.terraform.io/hashicorp/aws version 3.48.0**

### Affected Resource(s)
The following resources gave error when destroying using the `terraform destroy` command
- aws_launch_template
- aws_alb

### Terraform Configuration Files
Due to size, we cannot post the entire configuration. However, here are the configuration for the specific resources that were reported during the crash.
#### AWS Launch Template
```hcl
resource "aws_launch_template" "this" {
  name_prefix          = "${var.application_name}-launch-template"
  image_id             = data.aws_ami.asg_ami.id
  key_name             = var.asg_key_name
  instance_type        = var.asg_instance_type
  user_data            = var.asg_user_data
  iam_instance_profile {
    name = aws_iam_instance_profile.iam_instance_profile.id
  }

  vpc_security_group_ids = concat([aws_security_group.instance_sg.id], var.asg_security_group_ids)

  lifecycle {
    create_before_destroy = true
  }

  tag_specifications {
    resource_type = "volume"
    tags = merge({
      Name = "${var.application_name}-volume"
    },
    var.base_tags
    )
  }

  tag_specifications {
    resource_type = "instance"
    tags = merge({
      Name = var.application_name
    },
    var.base_tags
    )
  }
}
```
#### ALB
```hcl
resource "aws_alb" "main" {
  name = var.name

  internal        = var.internal
  security_groups = [aws_security_group.alb.id]
  subnets         = var.subnets
  idle_timeout    = var.idle_timeout

  dynamic "access_logs" {
    for_each = var.access_logs
    content {
      bucket  = access_logs.value.bucket
      enabled = access_logs.value.enabled
      prefix  = access_logs.value.prefix
    }
  }

  tags = merge(
    var.common_tags,
    {
      "Name" = var.name
    }
  )
}

```

### Panic Output

https://gist.github.com/admin-edcomet/5c25892d10c5f4737343e38aaa63c2f2

### Expected Behavior

Terraform destroy command should have destroyed all resources successfully

### Actual Behavior

The AWS plugin crashed

### Steps to Reproduce

```shell
terraform destroy
```

### Important Factoids

An auto-scaling group was also created as part of this configuration. After creation, the EC2 instances was not moving to a healthy status in the target group (due to issues not related to Terraform), so we had manually changed the desired number of instances to 0 to avoid scaling activity during investigation. After we found the root cause, we needed to destroy and recreate the configurations. However, while we were destroying, the reported crash occurred.

### References
This is similar to reported issues with other versions of Terraform and AWS provider plugin as well.
* #19807
* #19740

**Comment by ewbankkit** [comment]
```
Stack trace from the terraform-provider-aws_v3.48.0_x5.exe plugin:

panic: interface conversion: interface {} is nil, not *aws.AWSClient

goroutine 53 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsLbRead(0xc0015ab080, 0x0, 0x0, 0xc0017f3360, 0xc000640400)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_lb.go:355 +0x848
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0012f9a40, 0x8666868, 0xc00193e640, 0xc0015ab080, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:335 +0x1fb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0012f9a40, 0x8666868,
0xc00193e640, 0xc0015f0380, 0x0, 0x0, 0xc001f071d0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0000056c8, 0x8666868, 0xc00193e640, 0xc00193e680, 0xc00193e640, 0xbcbeca, 0x760b100)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/grpc_provider.go:575 +0x45b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc001cd7fe0, 0x8666910, 0xc00193e640, 0xc000aecb40, 0xc001cd7fe0, 0xc00194a120, 0xc00160fba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x108
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x78e2f80, 0xc001cd7fe0, 0x8666910, 0xc00194a120, 0xc000aecae0, 0x0, 0x8666910, 0xc00194a120, 0xc000af9500, 0x608)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x222
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000783500, 0x8688c38, 0xc000796d80, 0xc0019d4800, 0xc000b18ab0, 0xbe78a50, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000783500, 0x8688c38, 0xc000796d80, 0xc0019d4800, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000880490, 0xc000783500, 0x8688c38, 0xc000796d80, 0xc0019d4800)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xb2
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
```

**Comment by shiron-babi** [comment]
Happens in version 49 as well. Getting several errors such:
```
│ Error: Plugin did not respond
│
│   with module.backend.module.eks.module.node_groups.aws_launch_template.workers["ng"],
│   on ../../modules/basic_components/eks/node_groups/launch_template.tf line 25, in resource "aws_launch_template" "workers":
│   25: resource "aws_launch_template" "workers" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The
│ plugin logs may contain more details.
╵
```

and at the end:
```
Stack trace from the terraform-provider-aws_v3.49.0_x5 plugin:

panic: interface conversion: interface {} is nil, not *aws.AWSClient

goroutine 136 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsLaunchTemplateRead(0xc00288c000, 0x0, 0x0, 0xc1afb70, 0xc000096900)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_launch_template.go:701 +0x3f2e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000d05b20, 0x895de48, 0xc0004a6680, 0xc00288c000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000d05b20, 0x895de48, 0xc0004a6680, 0xc001f581c0, 0x0, 0x0, 0xc000b4a4f8, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0001af6c8, 0x895de48, 0xc0004a6680, 0xc0004a66c0, 0xc0004a6680, 0x100b665, 0x7900600)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc0022977e0, 0x895def0, 0xc0004a6680, 0xc0004928a0, 0xc0022977e0, 0xc001f52f60, 0xc0004a5ba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x7bd88a0, 0xc0022977e0, 0x895def0, 0xc001f52f60, 0xc000492840, 0x0, 0x895def0, 0xc001f52f60, 0xc001f6d200, 0x826)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00014f340, 0x897fbd8, 0xc0015b6600, 0xc001f48400, 0xc001549b00, 0xc16ed50, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00014f340, 0x897fbd8, 0xc0015b6600, 0xc001f48400, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00037f340, 0xc00014f340, 0x897fbd8, 0xc0015b6600, 0xc001f48400)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.49.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by mbolek** [comment]
got the same with RDS:
```
╷                                                                                                                                            
│ Error: Plugin did not respond                                                                                                              
│                                                             
│   with aws_db_parameter_group.aurora_db_postgres_parameter_group[0],
│   on main.tf line 102, in resource "aws_db_parameter_group" "aurora_db_postgres_parameter_group":
│  102: resource "aws_db_parameter_group" "aurora_db_postgres_parameter_group" {
│          
│ The plugin encountered an error, and failed to respond to the                                                                                                                                                                                                                           
│ plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with aws_db_parameter_group.aurora_db_postgres_parameter_group[0],
│   on main.tf line 102, in resource "aws_db_parameter_group" "aurora_db_postgres_parameter_group":
│  102: resource "aws_db_parameter_group" "aurora_db_postgres_parameter_group" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with aws_rds_cluster_parameter_group.aurora_cluster_postgres_parameter_group[0],
│   on main.tf line 121, in resource "aws_rds_cluster_parameter_group" "aurora_cluster_postgres_parameter_group":
│  121: resource "aws_rds_cluster_parameter_group" "aurora_cluster_postgres_parameter_group" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Request cancelled
│ 
│   with module.db.aws_rds_cluster.this[0],
│   on .terraform/modules/db/main.tf line 50, in resource "aws_rds_cluster" "this":
│   50: resource "aws_rds_cluster" "this" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-aws_v3.48.0_x5 plugin:

panic: interface conversion: interface {} is nil, not *aws.AWSClient

**Comment by joanayma** [comment]
I solved it destroying manually the older launch configuration (lifecycle is create before destroy).

Terraform was able to `plan -destroy` when only there was one launch configuration. I think the provider is having issues when the older LC is not yet deleted and you go to destroy, finding two resources for the same resource.

What I would expect is terraform to handle both launch configurations as both are part of the terraform state.

**Comment by jbragdon1** [comment]
Happening in 3.51_5x - looks like dynamo and secrets manager and vpc
```
Stack trace from the terraform-provider-aws_v3.51.0_x5 plugin:                                                                                                                                                                                                                                                      panic: interface conversion: interface {} is nil, not *aws.AWSClient
                                                                                                                                                                                                                                                goroutine 90 [running]:  
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsRouteTableAssociationRead(0xc0027b8200, 0x0, 0x0, 0xb6b71c0, 0xc00031a800)                   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_route_table_association.go:91 +0x62a   github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000dee1c0, 0x7e14c08, 0xc0027a2100, 0xc0027b8200, 0x0, 0x0, 0x0, 0x0, 0x0)         /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/resource.go:335 +0x1ee                                                                                                                                     github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000dee1c0, 0x7e14c08, 0xc0027a2100, 0xc0027e0070, 0x0, 0x0, 0xc0027ac108, 0x0, 0x0, 0x0)                                                                                                                                    /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/resource.go:624 +0x1cb                                                                                                                                     github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000c678, 0x7e14c08, 0xc0027a2100, 0xc0027a2140, 0xc0027a2100, 0x40b965, 0x6da0ae0)                                                                                                                                       /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/grpc_provider.go:575 +0x43b                                                                                                                                github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc0025cade0, 0x7e14cb0, 0xc0027a2100, 0xc001c8f200, 0xc0025cade0, 0xc001cdb9b0, 0xc002789ba0)                                                                                                                                             /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105           github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x707d4c0, 0xc0025cade0, 0x7e14cb0, 0xc001cdb9b0, 0xc001c8f1a0, 0x0, 0x7e14cb0, 0xc001cdb9b0, 0xc0013335e0, 0x9f)                                                                                                      /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214                                                                                                                                              google.golang.org/grpc.(*Server).processUnaryRPC(0xc00023f6c0, 0x7e36b38, 0xc001825c80, 0xc0022f8700, 0xc0018b58c0, 0xb675f70, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00023f6c0, 0x7e36b38, 0xc001825c80, 0xc0022f8700, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc001878a70, 0xc00023f6c0, 0x7e36b38, 0xc001825c80, 0xc0022f8700)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
panic: interface conversion: interface {} is nil, not *aws.AWSClient

goroutine 98 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsRouteTableAssociationRead(0xc000b66400, 0x0, 0x0, 0xb6b71c0, 0xc0006c0800)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_route_table_association.go:91 +0x62a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000dee1c0, 0x7e14c08, 0xc000b2c240, 0xc000b66400, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000dee1c0, 0x7e14c08, 0xc000b2c240, 0xc000b68150, 0x0, 0x0, 0xc000b36130, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000c678, 0x7e14c08, 0xc000b2c240, 0xc000b2c280, 0xc000b2c240, 0x40b965, 0x6da0ae0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc0025cade0, 0x7e14cb0, 0xc000b2c240, 0xc000b1c3c0, 0xc0025cade0, 0xc000b1eae0, 0xc002713ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x707d4c0, 0xc0025cade0, 0x7e14cb0, 0xc000b1eae0, 0xc000b1c360, 0x0, 0x7e14cb0, 0xc000b1eae0, 0xc000b64000, 0x9f)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00023f6c0, 0x7e36b38, 0xc001825c80, 0xc000b60000, 0xc0018b58c0, 0xb675f70, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00023f6c0, 0x7e36b38, 0xc001825c80, 0xc000b60000, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc001878a70, 0xc00023f6c0, 0x7e36b38, 0xc001825c80, 0xc000b60000)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
```

**Comment by justinretzolk** [comment]
Hi @admin-edcomet 👋 Terraform `v1.0.9` was released yesterday which [includes a fix](https://github.com/hashicorp/terraform/blob/v1.0.9/CHANGELOG.md#109-october-13-2021) that should correct this. Can you test again with this newer version to verify that you're no longer experience this issue?
