### ISSUE TITLE
Error: The terraform-provider-aws_v3.42.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by ASHOK6266** [hashicorp/terraform-provider-aws#20270]
### Affected Resource(s)

* aws_lb_target_group
* aws_subnet
* aws_security_group

### Terraform plugin Error

```hcl

aws_lb_target_group.my-tg (deposed object b0b1fda7): Refreshing state... [id=arn:aws:elasticloadbalancing:us-east-1:974892904047:targetgroup/tf20210721110644165800000001/950166e14a86d8c9]
╷
│ Error: Plugin did not respond
│ 
│   with aws_lb_target_group.my-tg,
│   on main-infra.tf line 101, in resource "aws_lb_target_group" "my-tg":
│  101: resource "aws_lb_target_group" "my-tg" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with aws_subnet.my_subnet_one_public,
│   on main-infra.tf line 176, in resource "aws_subnet" "my_subnet_one_public":
│  176: resource "aws_subnet" "my_subnet_one_public" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with aws_security_group.security_group,
│   on main-infra.tf line 259, in resource "aws_security_group" "security_group":
│  259: resource "aws_security_group" "security_group" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-aws_v3.42.0_x5 plugin:

panic: interface conversion: interface {} is nil, not *aws.AWSClient

goroutine 87 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsLbTargetGroupRead(0xc000760400, 0x0, 0x0, 0xaf47f40, 0xc000100000)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_lb_target_group.go:378 +0x967
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0012cf420, 0x78ffde8, 0xc0007480c0, 0xc000760400, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0012cf420, 0x78ffde8, 0xc0007480c0, 0xc000764150, 0x0, 0x0, 0xc001ce0678, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000ce58, 0x78ffde8, 0xc0007480c0, 0xc000748100, 0xc0007480c0, 0x40b965, 0x6933e00)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc001bf43e0, 0x78ffe90, 0xc0007480c0, 0xc00073e2a0, 0xc001bf43e0, 0xc000750000, 0xc00055cba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x6bef6c0, 0xc001bf43e0, 0x78ffe90, 0xc000750000, 0xc00073e240, 0x0, 0x78ffe90, 0xc000750000, 0xc00074e000, 0x338)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000227500, 0x7920ad8, 0xc000722300, 0xc0019c8400, 0xc0015f8ae0, 0xaf072d0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000227500, 0x7920ad8, 0xc000722300, 0xc0019c8400, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000fb6230, 0xc000227500, 0x7920ad8, 0xc000722300, 0xc0019c8400)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.42.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.


```

### Expected Behavior
terraform destroy should destroy the resources created in AWS.

### Actual Behavior
But we get Error: plugin did not respond.

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. `terraform apply`
4. `terraform destroy`

* #0000

**Comment by ewbankkit** [comment]
Similar to

* #20131
* #19740
* #19601
* #19788

**Comment by ASHOK6266** [comment]
@ewbankkit Thanks!
