### ISSUE TITLE
aws provider v3.53 crashes during provisioning\deleting resources

### ISSUE THREAD

**Issue by fishhead108** [hashicorp/terraform-provider-aws#20485]
Only eu-north-1 region noticed so far.
Already tried:
- cleanup everything using cloud-nuke
- remove the cache
- downgrade AWS plugin (3.30,3.50-53)
- terraform 1.0.3, 1.0.4

```
╷
│ Error: Plugin did not respond
│ 
│   with aws_route53_record.wildcard_main_domain_region[0],
│   on main.tf line 468, in resource "aws_route53_record" "wildcard_main_domain_region":
│  468: resource "aws_route53_record" "wildcard_main_domain_region" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with aws_route53_record.wildcard_region[0],
│   on main.tf line 495, in resource "aws_route53_record" "wildcard_region":
│  495: resource "aws_route53_record" "wildcard_region" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╷
│ Error: Request cancelled
│ 
│   with module.wafv2.aws_wafv2_web_acl.main[0],
│   on .terraform/modules/wafv2/main.tf line 4, in resource "aws_wafv2_web_acl" "main":
│    4: resource "aws_wafv2_web_acl" "main" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.alb.aws_alb_listener.https_acm_certs[0],
│   on .terraform/modules/alb/modules/alb/main.tf line 114, in resource "aws_alb_listener" "https_acm_certs":
│  114: resource "aws_alb_listener" "https_acm_certs" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
```

```
Stack trace from the terraform-provider-aws_v3.53.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 181 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsRoute53RecordBuildSet(0xc001e4cc80, 0xc00169f4d0, 0x12, 0x0, 0x0, 0x1)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_route53_record.go:883 +0x1c2d
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsRoute53RecordCreate(0xc001e4cc80, 0x6532f80, 0xc002680c00, 0x0, 0xffffffffffffffff)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_route53_record.go:406 +0x1e5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0011c90a0, 0x7f0e828, 0xc001e7ec80, 0xc001e4cc80, 0x6532f80, 0xc002680c00, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/resource.go:318 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0011c90a0, 0x7f0e828, 0xc001e7ec80, 0xc001194850, 0xc0021129e0, 0x6532f80, 0xc002680c00, 0x0, 0x0, 0x0, ...)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/resource.go:456 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00011c828, 0x7f0e828, 0xc001e7ec80, 0xc001e4ea50, 0xc001e7ec80, 0x7159860, 0xc002138300)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc000e1be20, 0x7f0e8d0, 0xc001e7ec80, 0xc001194700, 0xc000e1be20, 0xc002138390, 0xc000329ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x7159860, 0xc000e1be20, 0x7f0e8d0, 0xc002138390, 0xc0025f6120, 0x0, 0x7f0e8d0, 0xc002138390, 0xc001d8f680, 0x43c)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000f76c0, 0x7f30878, 0xc002756600, 0xc0024d5100, 0xc001596d80, 0xb7ec320, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0000f76c0, 0x7f30878, 0xc002756600, 0xc0024d5100, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc001994cd0, 0xc0000f76c0, 0x7f30878, 0xc002756600, 0xc0024d5100)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.53.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

ERRO[0122] 1 error occurred:
        * exit status 1
```

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/9a3969f95ecec5ff50e3648dc17a528329684d0f/aws/resource_aws_route53_record.go#L875-L891

**Comment by fishhead108** [comment]
Thank you @ewbankkit !
My issue was with empty string(var.country) in `geolocation_routing_policy`

```
resource "aws_route53_record" "wildcard_main_domain_region" {
  count = var.create_route53_entry && (! var.is_a_continent) ? 1 : 0

  zone_id = data.aws_route53_zone.selected.zone_id
  name    = "*.${var.external_domain_name}"
  type    = "A"

  alias {
    name                   = module.alb.alb_dns_name
    zone_id                = module.alb.alb_hosted_zone_id
    evaluate_target_health = true
  }

  set_identifier = "${var.environment}-${var.aws_region}"

  geolocation_routing_policy {
    country = var.country
  }

  # aws_security_group.lc_security_group in this module sets create_before_destroy to true, which means
  # everything it depends on, including this resource, must set it as well, or you'll get cyclic dependency errors
  # when you try to do a terraform destroy.
  lifecycle {
    create_before_destroy = true
  }
}
```
