### ISSUE TITLE
Plugin crash when running `terraform plan` on example config (from documentation)

### ISSUE THREAD

**Issue by smantzavinos** [hashicorp/terraform-provider-aws#20553]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```sh
vagrant@ubuntu-20:/vagrant/deploy/instances$ terraform -v
Terraform v1.0.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.53.0
```

### Affected Resource(s)

aws_vpc (any any others I have tried)
I started with many more resources defined, but as part of debugging I have removed everything down to just the aws_vpc resource and am still having issues.

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.53.0"
    }
  }
  required_version = "~> 1.0.4"
}

# Configure the AWS Provider
provider "aws" {
  region = "us-east-1"
}

# Create a VPC
resource "aws_vpc" "example" {
  cidr_block = "10.0.0.0/16"
}
```

### Debug Output

https://gist.github.com/smantzavinos/0b48b30a0719e5e672c4798fd8555c20

### Panic Output

N/A

### Expected Behavior

Correct output of `terraform plan`

### Actual Behavior

Error: Could not load plugin

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

I am running this inside a Vagrant virtual machine built from the bento/ubuntu-20.04 base image. This is my first attempt at using Terraform in a project. 

### References

* #0000

**Comment by ewbankkit** [comment]
```
2021-08-13T09:31:31.176Z [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock

Stack trace from the terraform-provider-aws_v3.53.0_x5 plugin:

fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x961af6a pc=0x455d01]

goroutine 1 [running, locked to thread]:
runtime.throw(0x7367987, 0x5)
        /opt/goenv/versions/1.16.0/src/runtime/panic.go:1117 +0x72 fp=0xc000072540 sp=0xc000072510 pc=0x436412
runtime.sigpanic()
        /opt/goenv/versions/1.16.0/src/runtime/signal_unix.go:731 +0x2c8 fp=0xc000072578 sp=0xc000072540 pc=0x44cfe8
runtime.step(0x961af6a, 0x876d6e, 0x876d6e, 0xc0000725f0, 0xc0000725e8, 0x1, 0x0, 0x0, 0x0, 0x0)
        /opt/goenv/versions/1.16.0/src/runtime/symtab.go:975 +0x21 fp=0xc000072598 sp=0xc000072578 pc=0x455d01
runtime.funcMaxSPDelta(0xa2de468, 0xb783f80, 0xb783f80)
        /opt/goenv/versions/1.16.0/src/runtime/symtab.go:918 +0xc6 fp=0xc000072608 sp=0xc000072598 pc=0x455986
runtime.init.5()
        /opt/goenv/versions/1.16.0/src/runtime/preempt.go:319 +0x52 fp=0xc000072638 sp=0xc000072608 pc=0x4375d2
runtime.doInit(0xb7711a0)
        /opt/goenv/versions/1.16.0/src/runtime/proc.go:6265 +0xec fp=0xc000072788 sp=0xc000072638 pc=0x44676c
runtime.main()
        /opt/goenv/versions/1.16.0/src/runtime/proc.go:174 +0x130 fp=0xc0000727e0 sp=0xc000072788 pc=0x438b30
runtime.goexit()
        /opt/goenv/versions/1.16.0/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0000727e8 sp=0xc0000727e0 pc=0x46d021

Error: The terraform-provider-aws_v3.53.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

╷
│ Error: Could not load plugin
│
│
│ Plugin reinitialization required. Please run "terraform init".
│
│ Plugins are external binaries that Terraform uses to access and manipulate
│ resources. The configuration provided requires plugins which can't be located,
│ don't satisfy the version constraints, or are otherwise incompatible.
│
│ Terraform automatically discovers provider requirements from your
│ configuration, including providers used in child modules. To see the
│ requirements and constraints, run "terraform providers".
│
│ failed to instantiate provider "registry.terraform.io/hashicorp/aws" to obtain schema: Unrecognized remote plugin message:
│
│ This usually means that the plugin is either invalid or simply
│ needs to be recompiled to support the latest protocol.
│
╵
2021-08-13T09:31:31.179Z [WARN]  provider: plugin failed to exit gracefully
```

**Comment by smantzavinos** [comment]
I am reasonably confident that the issue is related to the vagrant folder syncing between the host and VM. I tested moving the terraform files somewhere outside of the `/vagrant` folder (which is the synced folder) and terraform commands work as expected.
