### ISSUE TITLE
Terraform provider aws plugin crashed (*GRPCProvider).ApplyResourceChange call

### ISSUE THREAD

**Issue by jtgorny** [hashicorp/terraform-provider-aws#20594]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.54.0

### Affected Resource(s)

* aws_cloudfront_cache_policy

### Terraform Configuration Files

```hcl
resource "aws_cloudfront_cache_policy" "scheduling_cache_policy" {
  name        = "scheduling-cache-policy"
  default_ttl = 86400
  max_ttl     = 31536000
  min_ttl     = 1
  parameters_in_cache_key_and_forwarded_to_origin {
    headers_config {
      header_behavior = "whitelist"
      headers {
        items = [
          "Origin",
          "Access-Control-Request-Method",
          "Access-Control-Request-Headers"]
      }
    }
    cookies_config {
      cookie_behavior = "whitelist"
      cookies {
        items = []
      }
    }
    query_strings_config {
      query_string_behavior = "whitelist"
      query_strings {
        items = []
      }
    }
  }
}

resource "aws_acm_certificate" "Application-Cert" {
  domain_name       = var.AWS-Cert-DomainName
  validation_method = "DNS"

  tags = {
    Name        = "${var.application_name}-${var.environment}-certificate"
    Application = var.application_name
    Environment = var.environment
    Owner       = var.owner
  }

  lifecycle {
    ignore_changes = all
  }
}
```

### Debug Output

https://gist.github.com/jtgorny/09c3cf1a9cbb972cca86c19e94dba354

### Panic Output

panic: interface conversion: interface {} is nil, not map[string]interface {}

### Expected Behavior

TF should have created an `aws_cloudfront_cache_policy` & an `aws_acm_certificate`

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Nothing atypical

### References

None

**Comment by ewbankkit** [comment]
```
tack trace from the terraform-provider-aws_v3.54.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 91 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.expandCloudFrontCachePolicyCookiesConfig(0xc001c5b350, 0xc001c5b2f0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/cloudfront_cache_policy_structure.go:34 +0x1e5
github.com/terraform-providers/terraform-provider-aws/aws.expandCloudFrontCachePolicyParametersConfig(0xc001c5b2f0, 0x748acce)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/cloudfront_cache_policy_structure.go:112 +0xb2
github.com/terraform-providers/terraform-provider-aws/aws.expandCloudFrontCachePolicyConfig(0xc001c70d80, 0xc001993718)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/cloudfront_cache_policy_structure.go:138 +0xb9
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsCloudFrontCachePolicyCreate(0xc001c70d80, 0x6558a80, 0xc00004e600, 0x0, 0xffffffffffffffff)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_cloudfront_cache_policy.go:161 +0x55
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000820620, 0x7f3e5e8, 0xc00137b240, 0xc001c70d80, 0x6558a80, 0xc00004e600, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/resource.go:318 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000820620, 0x7f3e5e8, 0xc00137b240, 0xc001c2c1c0, 0xc001c1af00, 0x6558a80, 0xc00004e600, 0x0, 0x0, 0x0, ...)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/resource.go:456 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000134c78, 0x7f3e5e8, 0xc00137b240, 0xc001c26780, 0xc00137b240, 0x7183ae0, 0xc001c20e00)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc001c84060, 0x7f3e690, 0xc00137b240, 0xc001c2c070, 0xc001c84060, 0xc001c20e40, 0xc001407ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x7183ae0, 0xc001c84060, 0x7f3e690, 0xc001c20e40, 0xc0019d7620, 0x0, 0x7f3e690, 0xc001c20e40, 0xc00121dc00, 0x3f1)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000667880, 0x7f60758, 0xc0013ae000, 0xc002028f00, 0xc001602ae0, 0xb831380, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000667880, 0x7f60758, 0xc0013ae000, 0xc002028f00, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000d761f0, 0xc000667880, 0x7f60758, 0xc0013ae000, 0xc002028f00)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.54.0_x5 plugin crashed!
```

**Comment by ewbankkit** [comment]
Similar: #20589.
