### ISSUE TITLE
EC2 without disks (EBS) causes panic

### ISSUE THREAD

**Issue by XDanny322** [hashicorp/terraform-provider-aws#20821]
## Issue:

It looks like when TF does a run (plan/apply) against an EC2 that "had" ebs volumes... but no longer, TF / TF Provider crashes.  

## Expected Behavior

TF to be able to do a plan.

## Actual Behavior

Terraform crashes.

## Workaround

Create a ebs and attached it to the ec2.  then try plan/apply/destroy, and it should work. 

## Steps to Reproduce

- Create an EC2 via terraform
- Manually on the console / cli, detect all and delete all EBS volumes
  - worth mentioning at this point, you will not be able to start the ec2
  - ![image](https://user-images.githubusercontent.com/8107524/132386188-ca105aba-6db5-4d3a-a209-0ff6936fb636.png)
- Run terraform init / plan
- TF / TF provider, will crash

### Terraform CLI and Terraform AWS Provider Version

Terraform 0.14.9 and 1.0.5
OS; Mac and Linux
Provider; v3.57.0 (Note: have also tried 3.30.0 to v3.57.0)

### Affected Resource(s)

* aws_instance

### Terraform Configuration Files

```tf
resource "aws_instance" "this" {
  ami                    = var.ami_id
  iam_instance_profile   = var.iam_instance_profile
  instance_type          = var.instance_type
  subnet_id              = var.subnet_id
  vpc_security_group_ids = concat([aws_security_group.custom1.id], var.security_group_ids)

  root_block_device {
    delete_on_termination = true
    volume_size           = var.root_disk_size
    volume_type           = "gp3"

    iops       = var.data_disk_iops
    throughput = var.data_disk_throughput
  }

  user_data_base64 = base64encode(local.sshkey)

  tags = var.tags
}
```

### Panic Output

```log
aws_security_group_rule.egress_open: Refreshing state... [id=sgrule-3433072720]
aws_security_group_rule.custom_ports["Default SSH port from internal IP space."]: Refreshing state... [id=sgrule-4109518628]
aws_instance.this: Refreshing state... [id=i-0467c8e5f8d5a0d64]

Stack trace from the terraform-provider-aws_v3.57.0_x5 plugin:

panic: interface conversion: interface {} is nil, not []map[string]interface {}

goroutine 88 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.readBlockDevices(0xc001f74500, 0xc0017b4900, 0xc0022264d8, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_instance.go:1892 +0x799
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsInstanceRead(0xc001f74500, 0x7240b20, 0xc0021e8000, 0xc62def0, 0xc000700000)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_instance.go:1105 +0x1cc6
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000b21420, 0x8c6aba8, 0xc002766b00, 0xc001f74500, 0x7240b20, 0xc0021e8000, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000b21420, 0x8c6aba8, 0xc002766b00, 0xc001b62150, 0x7240b20, 0xc0021e8000, 0xc0020c0b60, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000cf48, 0x8c6aba8, 0xc002766b00, 0xc002766b40, 0xc002766b00, 0x100b665, 0x7b9d1a0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc0022c5200, 0x8c6ac50, 0xc002766b00, 0xc001b56840, 0xc0022c5200, 0xc000adb230, 0xc002007ba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x7e86ca0, 0xc0022c5200, 0x8c6ac50, 0xc000adb230, 0xc001b567e0, 0x0, 0x8c6ac50, 0xc000adb230, 0xc001700000, 0x109f)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00013ba40, 0x8c8d118, 0xc001491500, 0xc00225e100, 0xc00073f8c0, 0xc5ec890, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00013ba40, 0x8c8d118, 0xc001491500, 0xc00225e100, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000744ca0, 0xc00013ba40, 0x8c8d118, 0xc001491500, 0xc00225e100)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.57.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.


2021-09-07 12:04:04,670 fdspip_pyterraform.pyterraform tf_plan - PID: 51778 236 - DEBUG - stderr is:
Error: Plugin did not respond

  with aws_instance.this,
  on ec2.tf line 1, in resource "aws_instance" "this":
   1: resource "aws_instance" "this" {

The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
details.

```

**Comment by ewbankkit** [comment]
Similar:

* https://github.com/hashicorp/terraform-provider-aws/issues/16689
* https://github.com/hashicorp/terraform-provider-aws/issues/17284

**Comment by jdmulloy** [comment]
I'm also seeing this with v3.63.0. I had an instance with all disks detached and it was crashing. Reattaching the root volume fixed the crash.
