### ISSUE TITLE
RDS engine version comparison causes panic

### ISSUE THREAD

**Issue by ajjohnston** [hashicorp/terraform-provider-aws#20860]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```
$ terraform -v
Terraform v1.0.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.57.0
```

### Affected Resource(s)

* `aws_rds_cluster`

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_rds_cluster" "staging-aurora-cluster" {
  port                 = 3306
  engine               = "aurora-mysql"
  engine_mode          = "serverless"
  engine_version       = "5.7.mysql_aurora.2.08.3"

  master_username        = var.staging-mysql-root-un
  master_password        = var.staging-mysql-root-pw
  db_subnet_group_name   = aws_db_subnet_group.rds-subnet-group.name
  vpc_security_group_ids = [aws_security_group.staging-db.id]
  
  skip_final_snapshot     = false
  apply_immediately       = true
  backup_retention_period = 5 # days
  deletion_protection     = true

  scaling_configuration {
    auto_pause               = true
    min_capacity             = 1
    max_capacity             = 16
    seconds_until_auto_pause = 300
    timeout_action           = "RollbackCapacityChange"
  }
}
```

### Panic Output
```
Stack trace from the terraform-provider-aws_v3.57.0_x5 plugin:

panic: runtime error: slice bounds out of range [:35] with capacity 32

goroutine 258 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.compareActualEngineVersion(0xc0027d4e00, 0xc0027e3ef0, 0x22, 0xc000bb1f98, 0x17)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_rds_cluster.go:1513 +0x28a
github.com/terraform-providers/terraform-provider-aws/aws.rdsClusterSetResourceDataEngineVersionFromCluster(0xc0027d4e00, 0xc000c26a00)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_rds_cluster.go:1509 +0x9c
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsRDSClusterRead(0xc0027d4e00, 0x66420e0, 0xc001c08000, 0xba2b140, 0xc001b80000)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_rds_cluster.go:1065 +0xabb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000a9afc0, 0x806b608, 0xc002318200, 0xc0027d4e00, 0x66420e0, 0xc001c08000, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000a9afc0, 0x806b608, 0xc002318200, 0xc000f2cbd0, 0x66420e0, 0xc001c08000, 0xc000692dc0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0001b4ee8, 0x806b608, 0xc002318200, 0xc002318240, 0xc002318200, 0x40b965, 0x6f9e500)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc000fae240, 0x806b6b0, 0xc002318200, 0xc00230fb00, 0xc000fae240, 0xc002305b90, 0xc000b2eba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x7288080, 0xc000fae240, 0x806b6b0, 0xc002305b90, 0xc00230faa0, 0x0, 0x806b6b0, 0xc002305b90, 0xc001ca2e00, 0x6d2)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003ae8c0, 0x808d9b8, 0xc00125ef00, 0xc0027e8800, 0xc0028824e0, 0xb9e96d0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0003ae8c0, 0x808d9b8, 0xc00125ef00, 0xc0027e8800, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0008bf7c0, 0xc0003ae8c0, 0x808d9b8, 0xc00125ef00, 0xc0027e8800)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.57.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior
Version comparison works correctly.

### Actual Behavior
Version comparison causes a crash.

**Comment by ajjohnston** [comment]
Looks like this can happen if `oldVersion` is larger than `newVersion` in the comparison function: https://github.com/hashicorp/terraform-provider-aws/blob/4eb1bd13d47943e1ed98b1151c8effa1c589e33b/aws/resource_aws_rds_cluster.go#L1513
