### ISSUE TITLE
"terraform-provider-aws_v3.57.0_x5 plugin crashed" when calling terraform destroy (EKS cluster)

### ISSUE THREAD

**Issue by Oldrich-Vlasic** [hashicorp/terraform-provider-aws#20941]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
``` shell
> terraform -v
Terraform v1.0.7
on linux_amd64
```

### Affected Resource(s)

* `aws_eks_cluster`
* `aws_eks_node_group`
* NOTE: error message mentions `aws_eks_cluster`, the last command ran was deleting `aws_eks_node_group`

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

* `common.tf`
``` hcl
variable "common_tags" {
  default = {
    Project   = "tutorial Zero to JupyterHub"
    terraform = "true"
  }
}

variable "common_name_prefix" {
  type        = string
  description = "common prefix of resources to prevent name clashes"
  default     = "zero-to-jupyterhub"
}

variable "common_iam_path_prefix" {
  type        = string
  description = "common prefix of IAM role paths to prevent name clashes"
  default     = "/zerotojupyterhub"
}

variable "account_id" {
  type        = string
  description = "AWS account ID"
  default     = "789578028266"
}

variable "region" {
  type        = string
  description = "AWS region"
  default     = "eu-west-1"
}

variable "vpc_cidr" {
  type        = string
  description = "CIDR of the VPC"
  default     = "10.0.0.0/16"
}
```

* `main.tf`
```hcl
locals {
  cluster_name = "${var.common_name_prefix}-eks-cluster"
}

module "eks" {
  source = "github.com/terraform-aws-modules/terraform-aws-eks?ref=v17.19.0"

  cluster_name = local.cluster_name

  vpc_id  = data.terraform_remote_state.networking.outputs.vpc_id
  subnets = data.terraform_remote_state.networking.outputs.private_subnet_ids

  iam_path    = "${var.common_iam_path_prefix}/eks/"

  cluster_create_security_group = true

  cluster_enabled_log_types = [
    "api",
    "audit",
    "authenticator",
    "controllerManager",
    "scheduler",
  ]

  enable_irsa = false

  write_kubeconfig = false

  cluster_log_retention_in_days = 3

  manage_aws_auth       = false

  node_groups = {
    foo = {
      capacity_type = "SPOT"  # testing only anyways...
      instance_types = ["t3.micro"]
      desired_capacity = 1
      max_capacity     = 1
      min_capacity     = 1
    }
  }
}
```

* `providers.tf`
``` hcl
terraform {
  required_version = ">= 0.12"

  backend "s3" {
    bucket = "<bucket-name>"
    key    = "eks/terraform.tfstate"
    region = "eu-west-1"

    dynamodb_table = "<locks>"
    encrypt        = true
  }
}

provider "aws" {
  version = ">= 2.10"

  region              = "eu-west-1"
  profile             = "<profile>"
  allowed_account_ids = ["<account-id>"]

  default_tags {
    tags = var.common_tags
  }
}

data "terraform_remote_state" "networking" {
  backend = "s3"

  config = {
    bucket = "${var.networking_remote_state_bucket}"
    key    = "${var.networking_remote_state_key}"
    region = "${var.networking_remote_state_bucket_region}"
  }
}
```
* NOTE: both `networking` and `eks` share the same bucket for storing state files (different objects&hellip;), the networking is plain setup of VPC in AWS with public and private subnets, passing `vpc_id` and `subnets` parameters should suffice.

### Debug Output

https://gist.github.com/Oldrich-Vlasic/cc8177ab22668a7b594f1615fd7ab5a2

### Panic Output

* see above

### Actual Behavior

plugin crashed

### Steps to Reproduce

Unsure about reproducing as the issue happens during `terraform destroy`. The resources were first created with the exception of node groups that failed with
> NodeGroup "Create failed": Instances failed to join the kubernetes cluster

Then I tried deleting all resources and trying a different approach, however plugin crash occurred.

### References

* #0000

**Comment by ewbankkit** [comment]
```
Stack trace from the terraform-provider-aws_v3.57.0_x5 plugin:

panic: interface conversion: interface {} is nil, not *aws.AWSClient

goroutine 133 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsEksNodeGroupRead(0x806b678, 0xc0013cf020, 0xc0013fa580, 0x0, 0x0, 0xc0022ac420, 0xc001cb3908, 0x40e0f8)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_eks_node_group.go:374 +0x201f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000658c40, 0x806b608, 0xc0013cc500, 0xc0013fa580, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/resource.go:347 +0x17f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000658c40, 0x806b608, 0xc0013cc500, 0xc001e1c150, 0x0, 0x0, 0xc00250c7e0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0003045b8, 0x806b608, 0xc0013cc500, 0xc0013cc540, 0xc0013cc500, 0x40b965, 0x6f9e500)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc00246ad20, 0x806b6b0, 0xc0013cc500, 0xc0013ce7e0, 0xc00246ad20, 0xc0013dd410, 0xc002769ba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x7288080, 0xc00246ad20, 0x806b6b0, 0xc0013dd410, 0xc0013ce780, 0x0, 0x806b6b0, 0xc0013dd410, 0xc001e0b800, 0x583)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00023d880, 0x808d9b8, 0xc0018fb680, 0xc002710800, 0xc000133890, 0xb9e96d0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00023d880, 0x808d9b8, 0xc0018fb680, 0xc002710800, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0012427d0, 0xc00023d880, 0x808d9b8, 0xc0018fb680, 0xc002710800)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.57.0_x5 plugin crashed!
```

**Comment by ewbankkit** [comment]
Similar:

* #20878
* #20461
* #20438
* #20131
* #20015
* #19807
* #19788
* #19740
* #19601

**Comment by justinretzolk** [comment]
Hi @Oldrich-Vlasic 👋 Terraform `v1.0.9` was released yesterday which [includes a fix](https://github.com/hashicorp/terraform/blob/v1.0.9/CHANGELOG.md#109-october-13-2021) that should correct this. Can you test again with this newer version to verify that you're no longer experience this issue?
