### ISSUE TITLE
d/aws_launch_template: Error after update from 3.58 -> 3.59

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#21007]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

AWS Provider version **v3.59.0**.

### Affected Resource(s)

* [`aws_launch_template`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/launch_template)

Relates: https://github.com/hashicorp/terraform-provider-aws/pull/20796#issuecomment-925653206:

> Error: error setting metadata_options: Invalid address to set: []string{"metadata_options", "0", "http_protocol_ipv6"}
>
> on ../module/local/node-group.tf line 59, in data "aws_launch_template" "default":
> 59: data "aws_launch_template" "default" {

The [`flattenLaunchTemplateInstanceMetadataOptions`](https://github.com/hashicorp/terraform-provider-aws/blob/1be601a5086b8f48e793c00c131f26f152170691/aws/resource_aws_launch_template.go#L1142) function is called from both the Launch Template resource and the corresponding data source. However the data source's schema has not been updated with the new `http_protocol_ipv6` attribute.

**Comment by ewbankkit** [comment]
In our nightly CI:

```
Test ended in panic.
------- Stdout: -------
=== RUN   TestAccAWSLaunchTemplateDataSource_metadataOptions
=== PAUSE TestAccAWSLaunchTemplateDataSource_metadataOptions
=== CONT  TestAccAWSLaunchTemplateDataSource_metadataOptions
------- Stderr: -------
panic: Invalid address to set: []string{"metadata_options", "0", "http_protocol_ipv6"}
goroutine 345 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).Set(0xc002878600, 0x8976b91, 0x10, 0x6ff4da0, 0xc002d0e540, 0x0, 0x0)
  /opt/teamcity-agent/work/2e10e023da0c7520/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource_data.go:230 +0x371
github.com/terraform-providers/terraform-provider-aws/aws.dataSourceAwsLaunchTemplateRead(0xc002878600, 0x7a6c460, 0xc003b32600, 0xdc6c850, 0xdc3ca00)
  /opt/teamcity-agent/work/2e10e023da0c7520/src/github.com/terraform-providers/terraform-provider-aws/aws/data_source_aws_launch_template.go:534 +0x1885
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0014a8d20, 0x9ae9b48, 0xc002866440, 0xc002878600, 0x7a6c460, 0xc003b32600, 0x0, 0x0, 0x0)
  /opt/teamcity-agent/work/2e10e023da0c7520/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc0014a8d20, 0x9ae9b48, 0xc002866440, 0xc001e4d200, 0x7a6c460, 0xc003b32600, 0xc003b32600, 0xc001e4d200, 0x0, 0x0)
  /opt/teamcity-agent/work/2e10e023da0c7520/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource.go:558 +0xfd
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc0025a0570, 0x9ae9b48, 0xc002866440, 0xc001e4c8e0, 0xc002866440, 0x40dba5, 0x8423a20)
  /opt/teamcity-agent/work/2e10e023da0c7520/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/grpc_provider.go:1105 +0x4d6
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadDataSource(0xc001050a60, 0x9ae9bf0, 0xc002866440, 0xc003eb54a0, 0xc001050a60, 0xc00284ecc0, 0xc002a84ba0)
  /opt/teamcity-agent/work/2e10e023da0c7520/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:247 +0xe5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler(0x8720fe0, 0xc001050a60, 0x9ae9bf0, 0xc00284ecc0, 0xc0028505a0, 0x0, 0x9ae9bf0, 0xc00284ecc0, 0xc002b07b00, 0x23f)
  /opt/teamcity-agent/work/2e10e023da0c7520/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:416 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc002d7e000, 0x9b15c18, 0xc004e18480, 0xc002836100, 0xc00386c750, 0xdc070d0, 0x0, 0x0, 0x0)
  /opt/teamcity-agent/work/2e10e023da0c7520/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc002d7e000, 0x9b15c18, 0xc004e18480, 0xc002836100, 0x0)
  /opt/teamcity-agent/work/2e10e023da0c7520/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0024f0090, 0xc002d7e000, 0x9b15c18, 0xc004e18480, 0xc002836100)
  /opt/teamcity-agent/work/2e10e023da0c7520/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
  /opt/teamcity-agent/work/2e10e023da0c7520/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
```
