### ISSUE TITLE
terraform destroy gives "Error: The terraform-provider-aws_v3.59.0_x5 plugin crashed!"

### ISSUE THREAD

**Issue by sgpinkus** [hashicorp/terraform-provider-aws#21019]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

Trying to destroy all of this:

```
$ terraform state list
aws_iam_role_policy_attachment.cluster_cloudwatch
aws_vpc_dhcp_options.internal
aws_vpc_dhcp_options_association.default
module.eks.data.aws_ami.eks_worker[0]
module.eks.data.aws_caller_identity.current
module.eks.data.aws_iam_policy_document.cluster_assume_role_policy
module.eks.data.aws_iam_policy_document.cluster_elb_sl_role_creation[0]
module.eks.data.aws_iam_policy_document.workers_assume_role_policy
module.eks.data.aws_partition.current
module.eks.aws_autoscaling_group.workers[0]
module.eks.aws_autoscaling_group.workers[1]
module.eks.aws_autoscaling_group.workers[2]
module.eks.aws_cloudwatch_log_group.this[0]
module.eks.aws_eks_cluster.this[0]
module.eks.aws_iam_instance_profile.workers[0]
module.eks.aws_iam_instance_profile.workers[1]
module.eks.aws_iam_instance_profile.workers[2]
module.eks.aws_iam_policy.cluster_elb_sl_role_creation[0]
module.eks.aws_iam_role.cluster[0]
module.eks.aws_iam_role.workers[0]
module.eks.aws_iam_role_policy_attachment.cluster_AmazonEKSClusterPolicy[0]
module.eks.aws_iam_role_policy_attachment.cluster_AmazonEKSServicePolicy[0]
module.eks.aws_iam_role_policy_attachment.cluster_AmazonEKSVPCResourceControllerPolicy[0]
module.eks.aws_iam_role_policy_attachment.cluster_elb_sl_role_creation[0]
module.eks.aws_iam_role_policy_attachment.workers_AmazonEC2ContainerRegistryReadOnly[0]
module.eks.aws_iam_role_policy_attachment.workers_AmazonEKSWorkerNodePolicy[0]
module.eks.aws_iam_role_policy_attachment.workers_AmazonEKS_CNI_Policy[0]
module.eks.aws_launch_configuration.workers[0]
module.eks.aws_launch_configuration.workers[1]
module.eks.aws_launch_configuration.workers[2]
module.eks.aws_security_group.cluster[0]
module.eks.aws_security_group.workers[0]
module.eks.aws_security_group_rule.cluster_egress_internet[0]
module.eks.aws_security_group_rule.cluster_https_worker_ingress[0]
module.eks.aws_security_group_rule.workers_egress_internet[0]
module.eks.aws_security_group_rule.workers_ingress_cluster[0]
module.eks.aws_security_group_rule.workers_ingress_cluster_https[0]
module.eks.aws_security_group_rule.workers_ingress_self[0]
module.vpc.aws_default_route_table.default[0]
module.vpc.aws_default_security_group.this[0]
module.vpc.aws_eip.nat[0]
module.vpc.aws_internet_gateway.this[0]
module.vpc.aws_nat_gateway.this[0]
module.vpc.aws_route.private_nat_gateway[0]
module.vpc.aws_route.public_internet_gateway[0]
module.vpc.aws_route_table.private[0]
module.vpc.aws_route_table.public[0]
module.vpc.aws_route_table_association.private[0]
module.vpc.aws_route_table_association.private[1]
module.vpc.aws_route_table_association.public[0]
module.vpc.aws_route_table_association.public[1]
module.vpc.aws_subnet.private[0]
module.vpc.aws_subnet.private[1]
module.vpc.aws_subnet.public[0]
module.vpc.aws_subnet.public[1]
module.vpc.aws_vpc.this[0]
module.vpc.aws_vpc_dhcp_options.this[0]
module.vpc.aws_vpc_dhcp_options_association.this[0]
module.vpc.aws_vpn_gateway.this[0]
```

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

https://gist.github.com/sgpinkus/c2615305fbe91393382dc5bca212c9a3

### Panic Output

```
Stack trace from the terraform-provider-aws_v3.59.0_x5 plugin:

panic: interface conversion: interface {} is nil, not *aws.AWSClient

goroutine 129 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsIamRolePolicyAttachmentRead(0xc0005ce400, 0x0, 0x0, 0xbb3a1c0, 0xc000700000)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_iam_role_policy_attachment.go:59 +0x7a9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000b91ea0, 0x81251e8, 0xc0005be140, 0xc0005ce400, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000b91ea0, 0x81251e8, 0xc0005be140, 0xc0005d2150, 0x0, 0x0, 0xc00215e160, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000392f48, 0x81251e8, 0xc0005be140, 0xc0005be180, 0xc0005be140, 0x40b965, 0x703ca80)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc002331800, 0x8125290, 0xc0005be140, 0xc0005b8180, 0xc002331800, 0xc0005ba180, 0xc001b1cba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x732afa0, 0xc002331800, 0x8125290, 0xc0005ba180, 0xc0005b8120, 0x0, 0x8125290, 0xc0005ba180, 0xc0005c8000, 0xee)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000336380, 0x8147a18, 0xc00062c180, 0xc000390500, 0xc00031bcb0, 0xbaf8750, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000336380, 0x8147a18, 0xc00062c180, 0xc000390500, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0016089a0, 0xc000336380, 0x8147a18, 0xc00062c180, 0xc000390500)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.59.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior

Delete all resources.

### Actual Behavior

Panic crash.

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

### Important Factoids

Using EKS

### References

* #0000

**Comment by anGie44** [comment]
Similar:

* #20878
* #20461
* #20438
* #20131
* #20015
* #19807
* #19788
* #19740
* #19601

**Comment by sgpinkus** [comment]
For what it's worth I manage to delete most resource using `-target` on a few resources. But the rest won't go away. Either timeout wait loop or do the panic error. Left with the follow to manually clean up somehow:

```
module.eks.data.aws_ami.eks_worker[0]
module.eks.data.aws_caller_identity.current
module.eks.data.aws_iam_policy_document.cluster_assume_role_policy
module.eks.data.aws_iam_policy_document.cluster_elb_sl_role_creation[0]
module.eks.data.aws_iam_policy_document.workers_assume_role_policy
module.eks.data.aws_partition.current
module.eks.aws_cloudwatch_log_group.this[0]
module.eks.aws_iam_role.cluster[0]
module.eks.aws_iam_role_policy_attachment.cluster_AmazonEKSClusterPolicy[0]
module.eks.aws_iam_role_policy_attachment.cluster_AmazonEKSServicePolicy[0]
module.eks.aws_iam_role_policy_attachment.cluster_AmazonEKSVPCResourceControllerPolicy[0]
module.eks.aws_security_group.cluster[0]
module.eks.aws_security_group.workers[0]
module.eks.aws_security_group_rule.cluster_egress_internet[0]
module.eks.aws_security_group_rule.cluster_https_worker_ingress[0]
module.eks.aws_security_group_rule.workers_egress_internet[0]
module.eks.aws_security_group_rule.workers_ingress_cluster[0]
module.eks.aws_security_group_rule.workers_ingress_cluster_https[0]
module.eks.aws_security_group_rule.workers_ingress_self[0]
module.vpc.aws_internet_gateway.this[0]
module.vpc.aws_subnet.public[0]
module.vpc.aws_subnet.public[1]
module.vpc.aws_vpc.this[0]
```

**Comment by sgpinkus** [comment]
It works now. Note I also bumped hashicorp/aws to 3.54 -> 3.63, so either that or v1.09 fixed it. Thanks!
