### ISSUE TITLE
The terraform-provider-aws_v3.61.0_x5 plugin crashed

### ISSUE THREAD

**Issue by cpal012** [hashicorp/terraform-provider-aws#21215]
I'm trying to run a destroy on a EKS cluster I just built but getting the latest provider crashing

```
Stack trace from the terraform-provider-aws_v3.61.0_x5 plugin:

panic: interface conversion: interface {} is nil, not *aws.AWSClient

goroutine 33 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsIamRolePolicyRead(0xc001499680, 0x0, 0x0, 0xbd49aa0, 0xc000582800)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_iam_role_policy.go:88 +0xb8f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0009e5ea0, 0x8294cc8, 0xc0014deb00, 0xc001499680, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0009e5ea0, 0x8294cc8, 0xc0014deb00, 0xc001495f10, 0x0, 0x0, 0xc0024e8af0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000d518, 0x8294cc8, 0xc0014deb00, 0xc0014deb40, 0xc0014deb00, 0x40b965, 0x7172c80)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc0021d3ec0, 0x8294d70, 0xc0014deb00, 0xc0024dd8c0, 0xc0021d3ec0, 0xc0016810b0, 0xc002241ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x74690a0, 0xc0021d3ec0, 0x8294d70, 0xc0016810b0, 0xc0024dd860, 0x0, 0x8294d70, 0xc0016810b0, 0xc001332d20, 0x1d4)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004ffa40, 0x82b8af8, 0xc001b5e000, 0xc002bfb000, 0xc001664de0, 0xbd07f30, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0004ffa40, 0x82b8af8, 0xc001b5e000, 0xc002bfb000, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0003cddf0, 0xc0004ffa40, 0x82b8af8, 0xc001b5e000, 0xc002bfb000)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.61.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by ewbankkit** [comment]
Relates:

* https://github.com/hashicorp/terraform/issues/29712
* https://github.com/hashicorp/terraform-provider-aws/issues/21181
* https://github.com/hashicorp/terraform-provider-aws/issues/21140
* https://github.com/hashicorp/terraform-provider-aws/issues/21132
* https://github.com/hashicorp/terraform-provider-aws/issues/21079
* https://github.com/hashicorp/terraform-provider-aws/issues/21019
* https://github.com/hashicorp/terraform-provider-aws/issues/20941
* https://github.com/hashicorp/terraform-provider-aws/issues/20878
* https://github.com/hashicorp/terraform-provider-aws/issues/20461
* https://github.com/hashicorp/terraform-provider-aws/issues/20438
* https://github.com/hashicorp/terraform-provider-aws/issues/20131
* https://github.com/hashicorp/terraform-provider-aws/issues/20015
* https://github.com/hashicorp/terraform-provider-aws/issues/19807
* https://github.com/hashicorp/terraform-provider-aws/issues/19788
* https://github.com/hashicorp/terraform-provider-aws/issues/19740
* https://github.com/hashicorp/terraform-provider-aws/issues/19601

**Comment by justinretzolk** [comment]
Hi @cpal012 👋 Terraform `v1.0.9` was released yesterday which [includes a fix](https://github.com/hashicorp/terraform/blob/v1.0.9/CHANGELOG.md#109-october-13-2021) that should correct this. Can you test again with this newer version to verify that you're no longer experience this issue?
