### ISSUE TITLE
provider crash on EFS data search - index out of range [0] with length 0

### ISSUE THREAD

**Issue by hamBank** [hashicorp/terraform-provider-aws#21642]
Hi,

I've got some code that queries for an existing efs filesystem with: 
data "aws_efs_file_system" "saas" {
  tags = {
    Name = "scp-${var.env_name}-efs"
  }
}

It previously worked just fine but when I re-ran yesterday I got a provider crash:

```
Stack trace from the terraform-provider-aws_v3.64.0_x5 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 113 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/efs.dataSourceFileSystemRead(0xc001072c00, 0x6a88d80, 0xc000eda000, 0xc353b60, 0xc00028a000)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/efs/file_system_data_source.go:145 +0xf59
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0001a7b20, 0x860efa8, 0xc000b66900, 0xc001072c00, 0x6a88d80, 0xc000eda000, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc0001a7b20, 0x860efa8, 0xc000b66900, 0xc0020020c0, 0x6a88d80, 0xc000eda000, 0xc000eda000, 0xc0020020c0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource.go:558 +0xfd
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc00000ce70, 0x860efa8, 0xc000b66900, 0xc000c3f300, 0xc000b66900, 0x40b965, 0x746f920)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/grpc_provider.go:1105 +0x4d6
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadDataSource(0xc00142d780, 0x860f050, 0xc000b66900, 0xc0011e8b90, 0xc00142d780, 0xc0013f1410, 0xc00149bba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:247 +0xe5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler(0x7775b00, 0xc00142d780, 0x860f050, 0xc0013f1410, 0xc0011f22a0, 0x0, 0x860f050, 0xc0013f1410, 0xc00061de60, 0x118)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:416 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0005d5880, 0x8632d98, 0xc001138480, 0xc00140a500, 0xc000b1c510, 0xc311cd0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0005d5880, 0x8632d98, 0xc001138480, 0xc00140a500, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000bffaa0, 0xc0005d5880, 0x8632d98, 0xc001138480, 0xc00140a500)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.64.0_x5 plugin crashed!
```

I've tried downgrading the provider version and am seeing the same issue with 3.63 and 3.62.

The data dump from the sdk response (with some attempt at removing sensitive data):

```
2021-11-05T10:32:16.872+1100 [INFO]  provider.terraform-provider-aws_v3.62.0_x5: 2021/11/05 10:32:16 [DEBUG] [aws-sdk-go] {"FileSystems":[{"AvailabilityZoneId":null,"AvailabilityZoneName":null,"CreationTime":1.635170523E9,"CreationToken":"terraform-20211025140202919800000002","Encrypted":false,"FileSystemArn":"arn:aws:elasticfilesystem:eu-w
est-1:010930XXXX:file-system/fs-0f75c859bXXXX","FileSystemId":"fs-0f75c859bXXXX","KmsKeyId":null,"LifeCycleState":"available","Name":"XXXX-efs","NumberOfMountTargets":2,"OwnerId":"010930XXXX","PerformanceMode":"generalPurpose","ProvisionedThroughputInMibps":null,"SizeInBytes":{"Timestamp":1.636068345E9,"Value":733184,"Va
lueInIA":0,"ValueInStandard":733184},"Tags":[{"Key":"Application","Value":"XXXX"},{"Key":"BusinessUnit","Value":"XXXX"},{"Key":"CostCenter","Value":""},{"Key":"Customer","Value":"Multi-Tenant"},{"Key":"Environment","Value":"XXXX"},{"Key":"Name","Value":"XXXX-efs"},{"Key":"SsmBootStrap","Value":"true"},{"Key":"environment",
"Value":"XXXX"},{"Key":"region","Value":"eu-west-1"}],"ThroughputMode":"bursting"},{"AvailabilityZoneId":null,"AvailabilityZoneName":null,"CreationTime":1.631200422E9,"CreationToken":"terraform-20210909151341995400000002","Encrypted":false,"FileSystemArn":"arn:aws:elasticfilesystem:eu-west-1:010930XXXX:file-system/fs-XXXXX","FileSy
stemId":"fs-XXXX","KmsKeyId":null,"LifeCycleState":"available","Name":"XXXX-efs","NumberOfMountTargets":2,"OwnerId":"010930XXXX","PerformanceMode":"generalPurpose","ProvisionedThroughputInMibps":null,"SizeInBytes":{"Timestamp":1.636067874E9,"Value":1365891072,"ValueInIA":1164189696,"ValueInStandard":201701376},"Tags":[{"Key":"
Application","Value":"XXXX"},{"Key":"BusinessUnit","Value":"XXXX"},{"Key":"CostCenter","Value":""},{"Key":"Customer","Value":"Multi-Tenant"},{"Key":"Environment","Value":"XXXX"},{"Key":"Name","Value":"XXXXX-efs"},{"Key":"SsmBootStrap","Value":"true"},{"Key":"environment","Value":"XXXX"},{"Key":"region","Value":"eu-west-
1"}],"ThroughputMode":"bursting"},{"AvailabilityZoneId":null,"AvailabilityZoneName":null,"CreationTime":1.620222384E9,"CreationToken":"terraform-20210505134623952400000002","Encrypted":false,"FileSystemArn":"arn:aws:elasticfilesystem:eu-west-1:010930XXXX:file-system/fs-XXXX","FileSystemId":"fs-XXXX","KmsKeyId":null,"LifeCycleState
":"available","Name":"XXXXX-efs","NumberOfMountTargets":2,"OwnerId":"010930XXXXX","PerformanceMode":"generalPurpose","ProvisionedThroughputInMibps":null,"SizeInBytes":{"Timestamp":1.636067757E9,"Value":26593943552,"ValueInIA":25635057664,"ValueInStandard":958885888},"Tags":[{"Key":"Application","Value":"XXXX"},{"Key":"BusinessUnit",
"Value":"XXXX"},{"Key":"CostCenter","Value":""},{"Key":"Customer","Value":"Multi-Tenant"},{"Key":"Environment","Value":"XXXX"},{"Key":"Name","Value":"XXXX-efs"},{"Key":"SsmBootStrap","Value":"true"},{"Key":"environment","Value":"XXXX"},{"Key":"region","Value":"eu-west-1"}],"ThroughputMode":"bursting"}],"Marker":null,"NextMarker":n
ull}: timestamp=2021-11-05T10:32:16.872+1100
```

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/3345e46f94f0a6104658154312106a79b6c529fc/internal/service/efs/file_system_data_source.go#L119-L145

Relates: #18097.
Relates: #20399.

**Comment by edmundcraske-bjss** [comment]
I've just tried to use an `aws_efs_file_system` data source myself and am hitting the same issue. Is this still an issue for you @hamBank ? I'm not sure what I can do to fix/work around it...

**Comment by veromos** [comment]
@edmundcraske-bjss
I encountered the same error, verify that your tag is corresponding to an existing one. Mine was incorrect.

The plugin should display : data source return nothing instead of a "Error: rpc error: code = Unavailable desc = transport is closing"

**Comment by edmundcraske-bjss** [comment]
Ah yes, I was indeed passing the wrong tag values, so it wasn't finding anything. Thankfully once I fixed my mistake it is working! It really shouldn't crash though if it doesn't find anything?!

**Comment by limratechnologies** [comment]
Just encounter the same issue. It doesn't have to crash if data doesn't return anything

**Comment by limratechnologies** [comment]
This is weird, data crashes even when the tag keys and values are correct in the case of target file system ID is "short" eg., fs-95138ead. However the same thing is able to pull the file system id is long eg., "fs-0c9826306472877b6". Is someone able to replicate this behaviour?

**Comment by ewbankkit** [comment]
Similar:

* https://github.com/hashicorp/terraform-provider-aws/issues/24031
* https://github.com/hashicorp/terraform-provider-aws/issues/23309
