### ISSUE TITLE
panic: interface conversion: interface {} is nil, not []map[string]interface {}

### ISSUE THREAD

**Issue by drorweiss-did** [hashicorp/terraform-provider-aws#21762]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```bash
> terraform -v
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.65.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Affected Resource(s)

I'm seeing these but possibly many more:
* aws_cloudwatch_metric_alarm
* aws_instance

### Terraform Configuration Files

The entire stack (dozens of files) cannot be included.

### Panic Output

```
Stack trace from the terraform-provider-aws_v3.65.0_x5 plugin:

panic: interface conversion: interface {} is nil, not []map[string]interface {}

goroutine 3785 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.readBlockDevices(0xc0025c7500, 0xc000150480, 0xc0003088f0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/ec2/instance.go:1901 +0x799
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.resourceInstanceRead(0xc0025c7500, 0x89413e0, 0xc0004a2400, 0xf3b4810, 0xc0008dc000)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/ec2/instance.go:1114 +0x1ce6
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000c75960, 0xaaab668, 0xc0021d7080, 0xc0025c7500, 0x89413e0, 0xc0004a2400, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000c75960, 0xaaab668, 0xc0021d7080, 0xc001d90d90, 0x89413e0, 0xc0004a2400, 0xc001f6add0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00012d680, 0xaaab668, 0xc0021d7080, 0xc0021d7100, 0xc0021d7080, 0x100b665, 0x954d760)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc0019ec200, 0xaaab710, 0xc0021d7080, 0xc0007f0480, 0xc0019ec200, 0xc001daa0f0, 0xc002a45ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x990b040, 0xc0019ec200, 0xaaab710, 0xc001daa0f0, 0xc0007f0420, 0x0, 0xaaab710, 0xc001daa0f0, 0xc001de0000, 0xcd7)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0008ab880, 0xaad6638, 0xc0015b6600, 0xc001b62800, 0xc00096a990, 0xf3729b0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0008ab880, 0xaad6638, 0xc0015b6600, 0xc001b62800, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0005cacd0, 0xc0008ab880, 0xaad6638, 0xc0015b6600, 0xc001b62800)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.65.0_x5 plugin crashed!
```

### Expected Behavior

`Plan: x to add, y to change, z to destroy.`

### Actual Behavior

Many messages of the following:
```
│ Error: Request cancelled
│ 
│   with module.rnd.module.algo_dev_station__dror_weiss__c3.aws_cloudwatch_metric_alarm.cpu_low,
│   on modules/rnd/algo_dev_station/cloudwatch.tf line 1, in resource "aws_cloudwatch_metric_alarm" "cpu_low":
│    1: resource "aws_cloudwatch_metric_alarm" "cpu_low" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
```

and:
```
╷
│ Error: Request cancelled
│ 
│   with module.rnd.module.arik_s__algo_dev_station__ariks.aws_instance.dev_station,
│   on modules/rnd/algo_dev_station/ec2.tf line 1, in resource "aws_instance" "dev_station":
│    1: resource "aws_instance" "dev_station" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
```

### Steps to Reproduce

The entire stack (dozens of files) cannot be included and so cannot be provided to reproduce.
Action `terraform plan` fails.

### Important Factoids

No

**Comment by ewbankkit** [comment]
Similar: #20821.

**Comment by drorweiss-did** [comment]
@ewbankkit , this is it - an EC2 without volumes! Thank you!!
