### ISSUE TITLE
Provider crashes instead of providing error message when cloudfront_cache_policy isn't configured correctly

### ISSUE THREAD

**Issue by masterqwerty** [hashicorp/terraform-provider-aws#21854]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.11 on linux_amd64
provider registry.terraform.io/hashicorp/aws v3.65.0

### Affected Resource(s)

* aws_cloudfront_cache_policy

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws",
      version = "~> 3.65.0"
    }
  }
}

provider "aws" {
  region = "us-west-2"
}

resource "aws_cloudfront_cache_policy" "my_cache_policy" {
  name        = "my_cache_policy"
  min_ttl     = 300
  default_ttl = 86400
  max_ttl     = 604800

  parameters_in_cache_key_and_forwarded_to_origin {
    cookies_config {
      cookie_behavior = "all"
    }
    headers_config {}
    query_strings_config {
      query_string_behavior = "all"
    }
  }
}
```

### Debug Output

https://gist.github.com/masterqwerty/d8c94b5d70f8c387c1534b8b30c49e72

### Panic Output

https://gist.github.com/masterqwerty/e1b55abeffa28b8fe017b356189352b3

### Expected Behavior

When I apply, Terraform should give me an error message saying that my terraform is invalid because the `headers_config` block is missing required values.

### Actual Behavior

The provider plugin crashes and produces a panic. (See gist link above.)

### Steps to Reproduce

1. `terraform apply`

### References

* #20589

**Comment by masterqwerty** [comment]
Update: Exact same thing happens with provider version 3.66.0

**Comment by kirankumar-grootan** [comment]
@masterqwerty I fixed it by adding at least one arg in each *_config

cookies_config {
  cookie_behavior = "none"
}

headers_config {
  header_behavior = "none"
}

query_strings_config {
  query_string_behavior = "whitelist"

  query_strings {
    items = ["v", "versions"]
  }
}

**Comment by JoshCooley** [comment]
Just ran into this on 5.41.0.

Missing `cookie_behavior` and `query_string_behavior` arguments correctly throw errors

```
╷
│ Error: Missing required argument
│
│   on cloudfront.tf line 16, in resource "aws_cloudfront_cache_policy" "pod":
│   16:     cookies_config {
│
│ The argument "cookie_behavior" is required, but no definition was found.
╵
╷
│ Error: Missing required argument
│
│   on cloudfront.tf line 22, in resource "aws_cloudfront_cache_policy" "pod":
│   22:     query_strings_config {
│
│ The argument "query_string_behavior" is required, but no definition was found.
╵
```

but missing `header_behavior` still panics.

**Comment by ewbankkit** [comment]
Stack dump is:

```
Stack trace from the terraform-provider-aws_v3.65.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 103 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/cloudfront.expandParametersInCacheKeyAndForwardedToOrigin(0xc001b82db0, 0x90bd1ee)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/cloudfront/cache_policy.go:317 +0x3d2
github.com/hashicorp/terraform-provider-aws/internal/service/cloudfront.resourceCachePolicyCreate(0xc001ad3600, 0x7d42040, 0xc00263f200, 0x1, 0xffffffffffffffff)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/cloudfront/cache_policy.go:181 +0x2be
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000a94fc0, 0x9eab748, 0xc00178df40, 0xc001ad3600, 0x7d42040, 0xc00263f200, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource.go:318 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000a94fc0, 0x9eab748, 0xc00178df40, 0xc000a31730, 0xc001625ce0, 0x7d42040, 0xc00263f200, 0x0, 0x0, 0x0, ...)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource.go:456 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000cf00, 0x9eab748, 0xc00178df40, 0xc001a49ef0, 0xc00178df40, 0x8d0bac0, 0xc001acb700)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc0019d18c0, 0x9eab7f0, 0xc00178df40, 0xc000a31340, 0xc0019d18c0, 0xc001acb7a0, 0xc001a1aba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x8d0bac0, 0xc0019d18c0, 0x9eab7f0, 0xc001acb7a0, 0xc001ae2060, 0x0, 0x9eab7f0, 0xc001acb7a0, 0xc001878a80, 0x34f)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000295880, 0x9ed6558, 0xc001a80180, 0xc000308c00, 0xc00061a9c0, 0xe76f840, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000295880, 0x9ed6558, 0xc001a80180, 0xc000308c00, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000e48cd0, 0xc000295880, 0x9ed6558, 0xc001a80180, 0xc000308c00)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.65.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```
