### ISSUE TITLE
Panic ec2.readBlockDevice

### ISSUE THREAD

**Issue by yevgenypats** [hashicorp/terraform-provider-aws#22354]
https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ec2/instance.go#L1901

```
Stack trace from the terraform-provider-aws_v3.70.0_x5 plugin:

panic: interface conversion: interface {} is nil, not []map[string]interface {}

goroutine 1136 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.readBlockDevices(0xc0005eb500, 0xc00014eb40, 0xc002684788, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/ec2/instance.go:1901 +0x799
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.readInstance(0xc0005eb500, 0x8d478a0, 0xc0000d9600, 0x80a9760, 0xc00154a0f0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/ec2/spot_instance_request.go:426 +0x298
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.resourceSpotInstanceRequestRead(0xc0005eb500, 0x8d478a0, 0xc0000d9600, 0xfb1ce20, 0xc00009a480)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/ec2/spot_instance_request.go:355 +0x1079
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000537260, 0xafb8588, 0xc002191e00, 0xc0005eb500, 0x8d478a0, 0xc0000d9600, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0/helper/schema/resource.go:346 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000537260, 0xafb8588, 0xc002191e00, 0xc0021b0d00, 0x8d478a0, 0xc0000d9600, 0xc00000f590, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0/helper/schema/resource.go:635 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00012cfd8, 0xafb8588, 0xc002191e00, 0xc002191e40, 0xc002191e00, 0x100b665, 0x99b33a0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0/helper/schema/grpc_provider.go:576 +0x47d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0021057e0, 0xafb8630, 0xc002191e00, 0xc00219d560, 0xc0021057e0, 0xc00219eed0, 0xc002bc7ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/tf5server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x9d94b60, 0xc0021057e0, 0xafb8630, 0xc00219eed0, 0xc00219d500, 0x0, 0xafb8630, 0xc00219eed0, 0xc0021ae000, 0x7fb)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00032f880, 0xafe5018, 0xc0002c6600, 0xc002184200, 0xc00071c990, 0xfadaf30, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00032f880, 0xafe5018, 0xc0002c6600, 0xc002184200, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0012e61d0, 0xc00032f880, 0xafe5018, 0xc0002c6600, 0xc002184200)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.70.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by apinzo1** [comment]
I have the same issue with the v3.70.0 and then downgrade to v3.68.0 and its the same behavior...

**Comment by ewbankkit** [comment]
@yevgenypats Thanks for raising this issue.
It has already been noticed in #20821. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
