### ISSUE TITLE
Crashing when we try to use the aws_appstream_user_stack_association resource

### ISSUE THREAD

**Issue by Arisfx** [hashicorp/terraform-provider-aws#22468]
Hi team, we are trying to associate users with stacks in our appstream terraform configuration but when it comes to run the   `aws_appstream_user_stack_association` resource - terraform is crashing:

```
Stack trace from the terraform-provider-aws_v3.71.0_x5 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 113 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/appstream.resourceUserStackAssociationRead(0xa3c3e78, 0xc002750480, 0xc002771280, 0x815e340, 0xc001295500, 0x0, 0x0, 0xc002746678)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/appstream/user_stack_association.go:118 +0xa85
github.com/hashicorp/terraform-provider-aws/internal/service/appstream.resourceUserStackAssociationCreate(0xa3c3e78, 0xc002750480, 0xc002771280, 0x815e340, 0xc001295500, 0xc0026bd6d0, 0xabec2a, 0xc002771100)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/appstream/user_stack_association.go:88 +0x8bb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0006a5420, 0xa3c3e78, 0xc002750480, 0xc002771280, 0x815e340, 0xc001295500, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:336 +0xa7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0006a5420, 0xa3c3e78, 0xc002750480, 0xc0027764e0, 0xc002771100, 0x815e340, 0xc001295500, 0x0, 0x0, 0x0, ...)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:467 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000d740, 0xa3c3e78, 0xc002750480, 0xc00275c370, 0x94821ea, 0x12, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:977 +0xacf
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000228980, 0xa3c3f20, 0xc002750480, 0xc000b04000, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x465
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x91ed500, 0xc000228980, 0xa3c3f20, 0xc002748270, 0xc0021b8300, 0x0, 0xa3c3f20, 0xc002748270, 0xc00276c140, 0x134)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000e46000, 0xa3f0278, 0xc0001ca180, 0xc002762000, 0xc00241ca20, 0xeee5aa0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000e46000, 0xa3f0278, 0xc0001ca180, 0xc002762000, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0006a8fa0, 0xc000e46000, 0xa3f0278, 0xc0001ca180, 0xc002762000)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.71.0_x5 plugin crashed!
```

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/d09b50d633d83a78251b77addb6a68d5bbb7e3ab/internal/service/appstream/user_stack_association.go#L99-L118
