### ISSUE TITLE
cloudfront: crash when valuing cache and origin request policies via id in resource

### ISSUE THREAD

**Issue by Fred2VOX** [hashicorp/terraform-provider-aws#22467]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.3
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v3.71.0

### Affected Resource(s)

* aws_cloudfront_origin_request_policy
* aws_cloudfront_cache_policy
* aws_cloudfront_distribution

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
data "aws_cloudfront_cache_policy" "cachingOptimized" {
  name = "Managed-CachingOptimized"
}

data "aws_cloudfront_origin_request_policy" "corsS3Origin" {
  name = "Managed-CORS-S3Origin"
}

resource "aws_cloudfront_distribution" "maintenance" {
  comment             = "Distribution dedicated to the maintenance page"
  price_class         = "PriceClass_100"
  enabled             = true
  http_version        = "http2"
  is_ipv6_enabled     = true
  default_root_object = "index.html"

  origin {
    domain_name       = data.aws_s3_bucket.site.bucket_domain_name
    origin_id         = "maintenance"
    origin_path       = "/maintenance"
    s3_origin_config {
      origin_access_identity = aws_cloudfront_origin_access_identity.site.cloudfront_access_identity_path
    }
  }
  default_cache_behavior {
    allowed_methods         = [ "HEAD", "GET" ]
    cached_methods          = [ "HEAD", "GET" ]
    compress                = true
    smooth_streaming        = false
    target_origin_id        = "maintenance"
    viewer_protocol_policy  = "redirect-to-https"

    cache_policy_id             = data.aws_cloudfront_cache_policy.cachingOptimized.id
    origin_request_policy_id    = data.aws_cloudfront_origin_request_policy.corsS3Origin.id
    response_headers_policy_id  = aws_cloudfront_response_headers_policy.staticSite.id
  }
  viewer_certificate {
    cloudfront_default_certificate  = true
    minimum_protocol_version        = "TLSv1.2_2021"
    ssl_support_method              = "sni-only"
  }
  restrictions {
    geo_restriction {
      restriction_type  = "whitelist"
      locations         = [ "US", "CA", "FR" ]
    }
  }
}
```

### Panic Output

```
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.front.aws_cloudfront_distribution.maintenance to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for
│ .default_cache_behavior[0].origin_request_policy_id: was null, but now cty.StringVal("88a5eaf4-2fd4-4709-b370-b4c650ea3fcf").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.front.aws_cloudfront_distribution.maintenance to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for
│ .default_cache_behavior[0].cache_policy_id: was null, but now cty.StringVal("658327ea-f89d-4fab-a63d-7e88639e58f6").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Expected Behavior

After terraform apply, I expect to see the cache policy and origin request policy correctly valued into the corresponding distributions.

### Actual Behavior

The fields origin_request_policy_id and cache_policy_id are absent from the generated plan, even if the corresponding data actions work correctly.
```
  # module.front.data.aws_cloudfront_cache_policy.cachingOptimized will be read during apply
  # (config refers to values not yet known)
 <= data "aws_cloudfront_cache_policy" "cachingOptimized"  {
      ~ comment                                         = "Default policy when CF compression is enabled" -> (known after apply)
      ~ default_ttl                                     = 86400 -> (known after apply)
      ~ etag                                            = "......." -> (known after apply)
      - id                                              = "658327ea-f89d-4fab-a63d-........" -> null
      ~ max_ttl                                         = 31536000 -> (known after apply)
      ~ min_ttl                                         = 1 -> (known after apply)
        name                                            = "Managed-CachingOptimized"
      ~ parameters_in_cache_key_and_forwarded_to_origin = [
          - {
              - cookies_config                = [
                  - {
                      - cookie_behavior = "none"
                      - cookies         = []
                    },
                ]
              - enable_accept_encoding_brotli = true
              - enable_accept_encoding_gzip   = true
              - headers_config                = [
                  - {
                      - header_behavior = "none"
                      - headers         = []
                    },
                ]
              - query_strings_config          = [
                  - {
                      - query_string_behavior = "none"
                      - query_strings         = []
                    },
                ]
            },
        ] -> (known after apply)
    }

  # module.front.data.aws_cloudfront_origin_request_policy.corsS3Origin will be read during apply
  # (config refers to values not yet known)
 <= data "aws_cloudfront_origin_request_policy" "corsS3Origin"  {
      ~ comment              = "Policy for S3 origin with CORS" -> (known after apply)
      ~ cookies_config       = [
          - {
              - cookie_behavior = "none"
              - cookies         = []
            },
        ] -> (known after apply)
      ~ etag                 = "......." -> (known after apply)
      ~ headers_config       = [
          - {
              - header_behavior = "whitelist"
              - headers         = [
                  - {
                      - items = [
                          - "access-control-request-headers",
                          - "access-control-request-method",
                          - "origin",
                        ]
                    },
                ]
            },
        ] -> (known after apply)
      - id                   = "88a5eaf4-2fd4-4709-b370-......." -> null
        name                 = "Managed-CORS-S3Origin"
      ~ query_strings_config = [
          - {
              - query_string_behavior = "none"
              - query_strings         = []
            },
        ] -> (known after apply)
    }


  # module.front.aws_cloudfront_distribution.maintenance will be created
  + resource "aws_cloudfront_distribution" "maintenance" {
      + arn                            = (known after apply)
      + caller_reference               = (known after apply)
      + comment                        = "Distribution dedicated to the maintenance page"
      + default_root_object            = "index.html"
      + domain_name                    = (known after apply)
      + enabled                        = true
      + etag                           = (known after apply)
      + hosted_zone_id                 = (known after apply)
      + http_version                   = "http2"
      + id                             = (known after apply)
      + in_progress_validation_batches = (known after apply)
      + is_ipv6_enabled                = true
      + last_modified_time             = (known after apply)
      + price_class                    = "PriceClass_100"
      + retain_on_delete               = false
      + status                         = (known after apply)
      + tags_all                       = {
          + "Country" = "France"
          + "Stack"   = "Panel"
        }
      + trusted_key_groups             = (known after apply)
      + trusted_signers                = (known after apply)
      + wait_for_deployment            = true

      + default_cache_behavior {
          + allowed_methods            = [
              + "GET",
              + "HEAD",
            ]
          + cached_methods             = [
              + "GET",
              + "HEAD",
            ]
          + compress                   = true
          + default_ttl                = (known after apply)
          + max_ttl                    = (known after apply)
          + min_ttl                    = 0
          + response_headers_policy_id = "..."
          + smooth_streaming           = false
          + target_origin_id           = "maintenance"
          + trusted_key_groups         = (known after apply)
          + trusted_signers            = (known after apply)
          + viewer_protocol_policy     = "redirect-to-https"
        }

      + origin {
          + connection_attempts = 3
          + connection_timeout  = 10
          + domain_name         = (known after apply)
          + origin_id           = "maintenance"
          + origin_path         = "/maintenance"

          + s3_origin_config {
              + origin_access_identity = "origin-access-identity/cloudfront/..."
            }
        }

      + restrictions {
          + geo_restriction {
              + locations        = [
                  + "CA",
                  + "FR",
                  + "US",
                ]
              + restriction_type = "whitelist"
            }
        }

      + viewer_certificate {
          + cloudfront_default_certificate = true
          + minimum_protocol_version       = "TLSv1.2_2021"
          + ssl_support_method             = "sni-only"
        }
    }

```

### Steps to Reproduce

1. `terraform apply`

### References

* #21688
* #14373

**Comment by domeales-paloit** [comment]
We are getting this issue too and through the dependencies this wanted to recreate a whole bunch of resources.

We are also using the managed policy `Managed-CachingOptimized`, which could be the problem, or it may be an issue with the `aws_cloudfront_cache_policy` resource.

```
data "aws_cloudfront_cache_policy" "managed_caching_optimized" {
  name = "Managed-CachingOptimized"
}
```

To get around this we are using a `-target` option on our plan.

```
# terraform plan -out out.terraform -target 'module.app_instances["main"].data.aws_cloudfront_cache_policy.managed_caching_optimized'
```

It seems that the `-target` on a data source helps to resolve the policy ID earlier in the plan, and therefore not use `null` for the policy ID.

**Comment by rgschmitz1** [comment]
This is still an issue in AWS provider version 4.67.0. I attempted to wrap the data source for "aws_cloudfront_origin_request_policy" in a module thinking that it would help get the version ID, this caused Terraform to crash in a gitlab pipeline.
```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.
When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.
[1]: https://github.com/hashicorp/terraform/issues
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
duplicate checkable objects report for module.cdn_dns.module.origin_request_policy.output.id 
goroutine 778 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x2140e00, 0xc004182fe0})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/hashicorp/terraform/internal/checks.(*State).ReportCheckableObjects(0x23fab00?, {0x2b665a0?, 0xc004215c50}, 0xc0005c2f54?)
	/home/circleci/project/project/internal/checks/state_report.go:29 +0x45d
github.com/hashicorp/terraform/internal/terraform.(*nodeExpandOutput).DynamicExpand(0xc00b12f640, {0x2b7ccb8, 0xc0008f1260})
	/home/circleci/project/project/internal/terraform/node_output.go:[102](https://gitlab.com/sinclair-digital/storyline/nmp/infrastructure/nmp-gamecenter-static-infra/-/jobs/4902630847#L102) +0x2dd
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x240b3e0, 0xc00b12f640})
	/home/circleci/project/project/internal/terraform/graph.go:84 +0x442
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc009e5b860, {0x240b3e0, 0xc00b12f640}, 0xc00b559140)
	/home/circleci/project/project/internal/dag/walk.go:381 +0x2f6
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
	/home/circleci/project/project/internal/dag/walk.go:304 +0xf65
```

**Comment by julian-alarcon** [comment]
I will test this with Terraform 1.5 and AWS Provider 5.46 to see it it still fails.

**Comment by nadav-dux** [comment]
This still happens on provider version 5.60, where we use the following for our CloudFront storage:

```
data "aws_cloudfront_cache_policy" "optimized_s3_cache" {
  name = "Managed-CachingOptimized"
}
```

**Comment by tt-kianhean** [comment]
https://github.com/hashicorp/terraform-provider-aws/issues/29234#issuecomment-2477794192

**Comment by nam054** [comment]
Hi @nadav-dux , thank you for the update. Could you provide what terraform version you're using?

**Comment by nam054** [comment]
Hello, thank you for raising this issue!
I am using the latest provider version 5.83.1 and the latest terraform version 1.10.4 with the configuration mentioned in this issue and was unable to reproduce the error. The plan and apply show/set the `cache_policy_id` and the `origin_request_policy_id` values called from the corresponding datasources. Could you please try with the latest version of the provider and terraform?

**Comment by nam054** [comment]
Since we haven't heard back, I'm going to be closing this issue. If you are still enxperiencing this behavior, please feel free to open a new issue refrencing this one where necessary.
