### ISSUE TITLE
aws_fsx_openzfs_file_system runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by XciD** [hashicorp/terraform-provider-aws#22475]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.0.11
on darwin_arm64
+ provider registry.terraform.io/gavinbunney/kubectl v1.13.1
+ provider registry.terraform.io/hashicorp/aws v3.71.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.1.2
+ provider registry.terraform.io/hashicorp/http v2.1.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.7.1
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

Your version of Terraform is out of date! The latest version
is 1.1.3. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

* aws_fsx_openzfs_file_system

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_fsx_openzfs_file_system" "fs" {
  storage_capacity    = 1024
  subnet_ids          = [module.vpc.private_subnets[0]]
  deployment_type     = "SINGLE_AZ_1"
  throughput_capacity = 64
  security_group_ids  = [aws_security_group.allow_nfs.id]

  root_volume_configuration {
    data_compression_type = "ZSTD"
  }

  automatic_backup_retention_days = 0
  tags                            = local.default_tags
}
```

### Panic Output

https://gist.github.com/XciD/5fca7321430fdc6f75f390271d743753

### Expected Behavior

Create a OpenZFS Filesystem

### Actual Behavior

Create the OpenZFS Filesytem but crash at the end. FS is created, re-apply will create a new FS

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Relates #22234.

**Comment by ewbankkit** [comment]
```
2022-01-07T18:55:39.947+0100 [DEBUG] provider.terraform-provider-aws_v3.71.0_x5: PANIC: runtime error: invalid memory address or nil pointer dereference
2022-01-07T18:55:39.947+0100 [DEBUG] provider.terraform-provider-aws_v3.71.0_x5: [signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x105a01504]
2022-01-07T18:55:39.947+0100 [DEBUG] provider.terraform-provider-aws_v3.71.0_x5:
2022-01-07T18:55:39.947+0100 [DEBUG] provider.terraform-provider-aws_v3.71.0_x5: goroutine 97 [running]:
2022-01-07T18:55:39.947+0100 [DEBUG] provider.terraform-provider-aws_v3.71.0_x5: github.com/hashicorp/terraform-provider-aws/internal/service/fsx.flattenFsxOpenzfsFileNfsExports(0x14000aea3e8, 0x1, 0x1, 0x15, 0x14001edfcb8, 0x10613be15)
2022-01-07T18:55:39.947+0100 [DEBUG] provider.terraform-provider-aws_v3.71.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/fsx/openzfs_file_system.go:778 +0x94
2022-01-07T18:55:39.947+0100 [DEBUG] provider.terraform-provider-aws_v3.71.0_x5: github.com/hashicorp/terraform-provider-aws/internal/service/fsx.flattenFsxOpenzfsRootVolumeConfiguration(0x140000ca980, 0x14002110d80, 0x17, 0x140000ca980)
2022-01-07T18:55:39.947+0100 [DEBUG] provider.terraform-provider-aws_v3.71.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/fsx/openzfs_file_system.go:761 +0x20c
2022-01-07T18:55:39.947+0100 [DEBUG] provider.terraform-provider-aws_v3.71.0_x5: github.com/hashicorp/terraform-provider-aws/internal/service/fsx.resourceOpenzfsFileSystemRead(0x14002100d00, 0x107f2cb60, 0x14000376a80, 0x34630b8a000, 0x140021023c0)
2022-01-07T18:55:39.947+0100 [DEBUG] provider.terraform-provider-aws_v3.71.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/fsx/openzfs_file_system.go:456 +0x9a0
2022-01-07T18:55:39.947+0100 [DEBUG] provider.terraform-provider-aws_v3.71.0_x5: github.com/hashicorp/terraform-provider-aws/internal/service/fsx.resourceOepnzfsFileSystemCreate(0x14002100d00, 0x107f2cb60, 0x14000376a80, 0xffffffffffffffff, 0x14001b876b8)
2022-01-07T18:55:39.947+0100 [DEBUG] provider.terraform-provider-aws_v3.71.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/fsx/openzfs_file_system.go:367 +0xd34
2022-01-07T18:55:39.947+0100 [DEBUG] provider.terraform-provider-aws_v3.71.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x14000cedea0, 0x10976ac58, 0x14002679ac0, 0x14002100d00, 0x107f2cb60, 0x14000376a80, 0x0, 0x0, 0x0)
2022-01-07T18:55:39.947+0100 [DEBUG] provider.terraform-provider-aws_v3.71.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:329 +0x170
2022-01-07T18:55:39.947+0100 [DEBUG] provider.terraform-provider-aws_v3.71.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x14000cedea0, 0x10976ac58, 0x14002679ac0, 0x1400073a000, 0x14002100980, 0x107f2cb60, 0x14000376a80, 0x0, 0x0, 0x0, ...)
2022-01-07T18:55:39.947+0100 [DEBUG] provider.terraform-provider-aws_v3.71.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:467 +0x4ec
2022-01-07T18:55:39.947+0100 [DEBUG] provider.terraform-provider-aws_v3.71.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1400018e198, 0x10976ac58, 0x14002679ac0, 0x14001db4550, 0x1061565f7, 0x12, 0x0)
2022-01-07T18:55:39.947+0100 [DEBUG] provider.terraform-provider-aws_v3.71.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:977 +0x870
2022-01-07T18:55:39.947+0100 [DEBUG] provider.terraform-provider-aws_v3.71.0_x5: github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x140001a2f00, 0x10976ad00, 0x14002679ac0, 0x14001d6cd90, 0x0, 0x0, 0x0)
2022-01-07T18:55:39.947+0100 [DEBUG] provider.terraform-provider-aws_v3.71.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x338
2022-01-07T18:55:39.947+0100 [DEBUG] provider.terraform-provider-aws_v3.71.0_x5: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x108fbbe00, 0x140001a2f00, 0x10976ad00, 0x14001db2d50, 0x14001c9de60, 0x0, 0x10976ad00, 0x14001db2d50, 0x140005e7100, 0x606)
2022-01-07T18:55:39.947+0100 [DEBUG] provider.terraform-provider-aws_v3.71.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x1c8
2022-01-07T18:55:39.947+0100 [DEBUG] provider.terraform-provider-aws_v3.71.0_x5: google.golang.org/grpc.(*Server).processUnaryRPC(0x1400027ee00, 0x1097974d8, 0x140017ed080, 0x14001b28500, 0x14000e4b6b0, 0x10e1e19e0, 0x0, 0x0, 0x0)
2022-01-07T18:55:39.947+0100 [DEBUG] provider.terraform-provider-aws_v3.71.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x3e8
2022-01-07T18:55:39.947+0100 [DEBUG] provider.terraform-provider-aws_v3.71.0_x5: google.golang.org/grpc.(*Server).handleStream(0x1400027ee00, 0x1097974d8, 0x140017ed080, 0x14001b28500, 0x0)
2022-01-07T18:55:39.947+0100 [DEBUG] provider.terraform-provider-aws_v3.71.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xa50
2022-01-07T18:55:39.947+0100 [DEBUG] provider.terraform-provider-aws_v3.71.0_x5: google.golang.org/grpc.(*Server).serveStreams.func1.2(0x14001810800, 0x1400027ee00, 0x1097974d8, 0x140017ed080, 0x14001b28500)
2022-01-07T18:55:39.947+0100 [DEBUG] provider.terraform-provider-aws_v3.71.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0x94
2022-01-07T18:55:39.947+0100 [DEBUG] provider.terraform-provider-aws_v3.71.0_x5: created by google.golang.org/grpc.(*Server).serveStreams.func1
2022-01-07T18:55:39.947+0100 [DEBUG] provider.terraform-provider-aws_v3.71.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1f8
2022-01-07T18:55:39.951+0100 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/aws/3.71.0/darwin_arm64/terraform-provider-aws_v3.71.0_x5 pid=45884 error="exit status 2"
```

**Comment by XciD** [comment]
Yes you are right. 

Will try adding it.

**Comment by ewbankkit** [comment]
cc @awsaxeman.

**Comment by awsaxeman** [comment]
looking into this. Was able to reproduce
