### ISSUE TITLE
Error: The terraform-provider-aws_v3.24.1_x5 plugin crashed!

### ISSUE THREAD

**Issue by wayneworkman** [hashicorp/terraform-provider-aws#22488]
Terraform v1.1.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.0.0
+ provider registry.terraform.io/hashicorp/aws v3.24.1
+ provider registry.terraform.io/hashicorp/random v3.1.0

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.keep_instances_on.aws_lambda_function.keep-instances-running will be updated in-place
  ~ resource "aws_lambda_function" "keep-instances-running" {
        id                             = "keep-instances-running"
      ~ last_modified                  = "2021-09-19T19:23:25.085+0000" -> (known after apply)
      ~ source_code_hash               = "mtv20tM3EgUjMpK8qrqbrszTTt7UB31MmYnQ7fck5vI=" -> "8ANRGfPQU+DkByMXeBn9cjcU4EHvRTkD4K00HsnjZ3A="
        tags                           = {
            "Name"    = "keep_instances_on"
            "Project" = "Common"
        }
        # (16 unchanged attributes hidden)


        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.keep_instances_on.aws_lambda_function.keep-instances-running: Modifying... [id=keep-instances-running]
╷
│ Error: Plugin did not respond
│ 
│   with module.keep_instances_on.aws_lambda_function.keep-instances-running,
│   on .terraform/modules/keep_instances_on/lambda.tf line 73, in resource "aws_lambda_function" "keep-instances-running":
│   73: resource "aws_lambda_function" "keep-instances-running" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
│ more details.
╵

Stack trace from the terraform-provider-aws_v3.24.1_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x47ebdf6]

goroutine 100 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsLambdaFunctionRead(0xc000115b00, 0x5a6dc40, 0xc0018c6000, 0x51eece0, 0xa5048c0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_lambda_function.go:817 +0x2436
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsLambdaFunctionUpdate(0xc000115b00, 0x5a6dc40, 0xc0018c6000, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_lambda_function.go:1163 +0x5e5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc00071d2c0, 0x71935c0, 0xc00128ca00, 0xc000115b00, 0x5a6dc40, 0xc0018c6000, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.0/helper/schema/resource.go:302 +0x88
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00071d2c0, 0x71935c0, 0xc00128ca00, 0xc0011ec2a0, 0xc000cb7aa0, 0x5a6dc40, 0xc0018c6000, 0x0, 0x0, 0x0, ...)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.0/helper/schema/resource.go:404 +0x390
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000fbaa80, 0x71935c0, 0xc00128ca00, 0xc001c3a5f0, 0xc00128ca00, 0x0, 0x71bec00)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.0/helper/schema/grpc_provider.go:955 +0x8cf
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc0017f71c0, 0x71935c0, 0xc00128ca00, 0xc0011ec0e0, 0xc0017f71c0, 0xc001d180c0, 0xc000673ba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.1.0/tfprotov5/server/server.go:331 +0xae
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x654fee0, 0xc0017f71c0, 0x7193680, 0xc001d180c0, 0xc001c10900, 0x0, 0x7193680, 0xc001d180c0, 0xc001b24000, 0xe60)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.1.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00001afc0, 0x71b6380, 0xc000662480, 0xc0012a0900, 0xc0006d6960, 0xa55a0a0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc00001afc0, 0x71b6380, 0xc000662480, 0xc0012a0900, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd05
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00104c160, 0xc00001afc0, 0x71b6380, 0xc000662480, 0xc0012a0900)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.24.1_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by justinretzolk** [comment]
Hey @wayneworkman 👋 Thank you very much for taking the time to file this issue. So that we have all of the necessary information in order to investigate this, can you update the issue description with the rest of the information requested in the [issue template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?

**Comment by anGie44** [comment]
Hi @wayneworkman , @justinretzolk . We're in luck! The line in question
https://github.com/hashicorp/terraform-provider-aws/blob/9a94e4fe535ba7986c1e4985aa68f656d76194c0/aws/resource_aws_lambda_function.go#L817

was updated in `v3.25.0` with the PR https://github.com/hashicorp/terraform-provider-aws/pull/16544, so upgrading to atleast that minor version should prevent the runtime error. I'm going to close this issue but do reach out if you find this issue again in a more recent version of the provider.
