### ISSUE TITLE
Plugin panic on state destruction

### ISSUE THREAD

**Issue by speller** [hashicorp/terraform-provider-aws#22618]
TF version: 1.1.3
AWS Plugin version: 3.72.0

I have a state which has failed multiple times to deploy, then failed multiple times to destroy, and now TF is failing on it. I can't reproduce the issue in other states. Here is the log of the failing state:

```none
2022-01-17T01:35:42.700+0900 [TRACE] readResourceInstanceStateDeposed: reading state for module.vpc.aws_subnet.private2 deposed object fa5571bd
2022-01-17T01:35:42.701+0900 [TRACE] vertex "module.redis.aws_security_group_rule.es-ingress-http": visit complete
2022-01-17T01:35:42.701+0900 [TRACE] NodeAbstractResouceInstance.writeResourceInstanceStateDeposed: writing state object for module.vpc.aws_vpc.app
2022-01-17T01:35:42.701+0900 [TRACE] vertex "module.redis.data.aws_vpc.vpc": starting visit (*terraform.NodePlanDestroyableResourceInstance)
2022-01-17T01:35:42.701+0900 [TRACE] NodeAbstractResourceInstance.refresh for module.vpc.aws_vpc.app (deposed object 98264203)
2022-01-17T01:35:42.701+0900 [TRACE] GRPCProvider: ReadResource
module.vpc.aws_vpc.app (deposed object 98264203): Refreshing state... [id=vpc-0403ad66985e4d744]
2022-01-17T01:35:42.701+0900 [TRACE] upgradeResourceState: schema version of module.vpc.aws_subnet.private2 is still 1; calling provider "aws" for any other minor fixups
2022-01-17T01:35:42.701+0900 [TRACE] GRPCProvider: UpgradeResourceState
2022-01-17T01:35:42.701+0900 [TRACE] writeChange: recorded Delete change for aws_security_group_rule.api-ingress-test
2022-01-17T01:35:42.701+0900 [TRACE] vertex "aws_security_group_rule.api-ingress-test": visit complete
2022-01-17T01:35:42.701+0900 [TRACE] readResourceInstanceState: reading state for module.deployment-domain.aws_acm_certificate_validation.cert
2022-01-17T01:35:42.701+0900 [TRACE] upgradeResourceState: schema version of module.deployment-domain.aws_acm_certificate_validation.cert is still 0; calling provider "aws" for any other minor fixups
2022-01-17T01:35:42.701+0900 [TRACE] GRPCProvider: UpgradeResourceState
2022-01-17T01:35:42.704+0900 [DEBUG] provider.terraform-provider-aws_v3.72.0_x5: PANIC: interface conversion: interface {} is nil, not *conns.AWSClient
2022-01-17T01:35:42.704+0900 [DEBUG] provider.terraform-provider-aws_v3.72.0_x5:
2022-01-17T01:35:42.704+0900 [DEBUG] provider.terraform-provider-aws_v3.72.0_x5: goroutine 145 [running]:
2022-01-17T01:35:42.704+0900 [DEBUG] provider.terraform-provider-aws_v3.72.0_x5: github.com/hashicorp/terraform-provider-aws/internal/service/ec2.resourceSubnetRead(0xc0025d0a80, 0x0, 0x0, 0xf0197b0, 0xc000600000)
2022-01-17T01:35:42.704+0900 [DEBUG] provider.terraform-provider-aws_v3.72.0_x5:        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/ec2/subnet.go:313 +0xe3f
2022-01-17T01:35:42.704+0900 [DEBUG] provider.terraform-provider-aws_v3.72.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000b70a80, 0xa46da58, 0xc00067a8c0, 0xc0025d0a80, 0x0, 0x0, 0x0, 0x0, 0x0)
2022-01-17T01:35:42.704+0900 [DEBUG] provider.terraform-provider-aws_v3.72.0_x5:        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:346 +0x1ee
2022-01-17T01:35:42.704+0900 [DEBUG] provider.terraform-provider-aws_v3.72.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000b70a80, 0xa46da58, 0xc00067a8c0, 0xc0006775f0, 0x0, 0x0, 0xc0022da590, 0x0, 0x0, 0x0)
2022-01-17T01:35:42.704+0900 [DEBUG] provider.terraform-provider-aws_v3.72.0_x5:        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:635 +0x1cb
2022-01-17T01:35:42.704+0900 [DEBUG] provider.terraform-provider-aws_v3.72.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000c7b0, 0xa46da58, 0xc00067a8c0, 0xc00067a900, 0x951b3bc, 0x12, 0x0)
2022-01-17T01:35:42.704+0900 [DEBUG] provider.terraform-provider-aws_v3.72.0_x5:        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:576 +0x47d
2022-01-17T01:35:42.704+0900 [DEBUG] provider.terraform-provider-aws_v3.72.0_x5: github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc00021e780, 0xa46db00, 0xc00067a8c0, 0xc00066efc0, 0x0, 0x0, 0x0)
2022-01-17T01:35:42.704+0900 [DEBUG] provider.terraform-provider-aws_v3.72.0_x5:        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:553 +0x322
2022-01-17T01:35:42.704+0900 [DEBUG] provider.terraform-provider-aws_v3.72.0_x5: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x92849e0, 0xc00021e780, 0xa46db00, 0xc0025878c0, 0xc00066ef60, 0x0, 0xa46db00, 0xc0025878c0, 0xc00017d500, 0x332)
2022-01-17T01:35:42.704+0900 [DEBUG] provider.terraform-provider-aws_v3.72.0_x5:        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
2022-01-17T01:35:42.704+0900 [DEBUG] provider.terraform-provider-aws_v3.72.0_x5: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001b28c0, 0xa49a2d8, 0xc000726180, 0xc0020f2400, 0xc001468a20, 0xefd9a90, 0x0, 0x0, 0x0)
2022-01-17T01:35:42.704+0900 [DEBUG] provider.terraform-provider-aws_v3.72.0_x5:        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
2022-01-17T01:35:42.704+0900 [DEBUG] provider.terraform-provider-aws_v3.72.0_x5: google.golang.org/grpc.(*Server).handleStream(0xc0001b28c0, 0xa49a2d8, 0xc000726180, 0xc0020f2400, 0x0)
2022-01-17T01:35:42.704+0900 [DEBUG] provider.terraform-provider-aws_v3.72.0_x5:        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
2022-01-17T01:35:42.704+0900 [DEBUG] provider.terraform-provider-aws_v3.72.0_x5: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0012c2000, 0xc0001b28c0, 0xa49a2d8, 0xc000726180, 0xc0020f2400)
2022-01-17T01:35:42.704+0900 [DEBUG] provider.terraform-provider-aws_v3.72.0_x5:        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
2022-01-17T01:35:42.704+0900 [DEBUG] provider.terraform-provider-aws_v3.72.0_x5: created by google.golang.org/grpc.(*Server).serveStreams.func1
2022-01-17T01:35:42.704+0900 [DEBUG] provider.terraform-provider-aws_v3.72.0_x5:        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
2022-01-17T01:35:42.706+0900 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/aws/3.72.0/linux_amd64/terraform-provider-aws_v3.72.0_x5 pid=8810 error="exit status 2"
2022-01-17T01:35:42.706+0900 [ERROR] plugin.(*GRPCProvider).UpgradeResourceState: error="rpc error: code = Unavailable desc = transport is closing"
2022-01-17T01:35:42.706+0900 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2022-01-17T01:35:42.706+0900 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2022-01-17T01:35:42.706+0900 [TRACE] vertex "module.app.aws_autoscaling_group.service": visit complete
2022-01-17T01:35:42.706+0900 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2022-01-17T01:35:42.706+0900 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2022-01-17T01:35:42.706+0900 [TRACE] vertex "module.vpc.aws_subnet.public2 (deposed 325ff153)": visit complete
2022-01-17T01:35:42.706+0900 [ERROR] plugin.(*GRPCProvider).UpgradeResourceState: error="rpc error: code = Unavailable desc = transport is closing"
2022-01-17T01:35:42.706+0900 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2022-01-17T01:35:42.706+0900 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2022-01-17T01:35:42.706+0900 [ERROR] plugin.(*GRPCProvider).UpgradeResourceState: error="rpc error: code = Unavailable desc = transport is closing"
2022-01-17T01:35:42.706+0900 [TRACE] vertex "module.vpc.aws_subnet.public1 (deposed f77c193a)": visit complete
2022-01-17T01:35:42.706+0900 [ERROR] plugin.(*GRPCProvider).UpgradeResourceState: error="rpc error: code = Unavailable desc = transport is closing"
2022-01-17T01:35:42.706+0900 [ERROR] plugin.(*GRPCProvider).UpgradeResourceState: error="rpc error: code = Unavailable desc = transport is closing"
2022-01-17T01:35:42.706+0900 [TRACE] vertex "module.vpc.aws_subnet.private2 (deposed fa5571bd)": visit complete
2022-01-17T01:35:42.706+0900 [TRACE] NodePlanDeposedResourceInstanceObject: planning module.redis.aws_security_group.redis deposed object 83bbc210
2022-01-17T01:35:42.706+0900 [TRACE] readResourceInstanceStateDeposed: reading state for module.redis.aws_security_group.redis deposed object 83bbc210
2022-01-17T01:35:42.706+0900 [TRACE] upgradeResourceState: schema version of module.redis.aws_security_group.redis is still 1; calling provider "aws" for any other minor fixups

...


Stack trace from the terraform-provider-aws_v3.72.0_x5 plugin:

panic: interface conversion: interface {} is nil, not *conns.AWSClient

goroutine 145 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.resourceSubnetRead(0xc0025d0a80, 0x0, 0x0, 0xf0197b0, 0xc000600000)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/ec2/subnet.go:313 +0xe3f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000b70a80, 0xa46da58, 0xc00067a8c0, 0xc0025d0a80, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:346 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000b70a80, 0xa46da58, 0xc00067a8c0, 0xc0006775f0, 0x0, 0x0, 0xc0022da590, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:635 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000c7b0, 0xa46da58, 0xc00067a8c0, 0xc00067a900, 0x951b3bc, 0x12, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:576 +0x47d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc00021e780, 0xa46db00, 0xc00067a8c0, 0xc00066efc0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:553 +0x322
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x92849e0, 0xc00021e780, 0xa46db00, 0xc0025878c0, 0xc00066ef60, 0x0, 0xa46db00, 0xc0025878c0, 0xc00017d500, 0x332)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001b28c0, 0xa49a2d8, 0xc000726180, 0xc0020f2400, 0xc001468a20, 0xefd9a90, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
2022-01-17T01:35:42.889+0900 [DEBUG] provider: plugin exited
google.golang.org/grpc.(*Server).handleStream(0xc0001b28c0, 0xa49a2d8, 0xc000726180, 0xc0020f2400, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0012c2000, 0xc0001b28c0, 0xa49a2d8, 0xc000726180, 0xc0020f2400)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.72.0_x5 plugin crashed!
```

Any ideas on how to fix that?

**Comment by ewbankkit** [comment]
Relates: #21215.

**Comment by tmetodie** [comment]
Same here. But when creating VPC peering options cross account. Terraform Plan works but when we confirm the creation , the creation starts and 

> Plan: 2 to add, 0 to change, 0 to destroy.
> aws_vpc_peering_connection_options.req: Creating...
> aws_vpc_peering_connection_options.acc: Creating...
> │ Error: Plugin did not respond

TF version: 1.1.3
AWS Plugin version: 3.72.0

**Comment by gdavison** [comment]
If you are still encountering this problem with a current version of the AWS Provider, please create a new issue that incudes the Terraform configuration that causes this problem as well as a debug log generated using these instructions: https://developer.hashicorp.com/terraform/internals/debugging
