### ISSUE TITLE
panic: interface conversion: interface {} is nil, not []map[string]interface {}

### ISSUE THREAD

**Issue by kylejohnson** [hashicorp/terraform-provider-aws#22660]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.1.3
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v2.18.0
+ provider registry.terraform.io/hashicorp/aws v3.72.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Affected Resource(s)

All of them?  A few specific resources are mentioned during the crash, but when I remove these resources from my configuration, other resources error in their place.

### Terraform Configuration Files

My configuration is 1330 lines and is not in a state to be shared, but I'm unable to narrow it down to any specific resources.  This bug seems to affect any resource regardless of what my configuration looks like.

### Debug Output

Full output available here:  https://gist.github.com/kylejohnson/c2732ed00ca2754d5683df3d00e7d2e8#file-crash-json

```
│ Error: Plugin did not respond
│ 
│   with aws_instance.matomo,
│   on matomo.tf line 89, in resource "aws_instance" "matomo":
│   89: resource "aws_instance" "matomo" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.


Stack trace from the terraform-provider-aws_v3.72.0_x5 plugin:

panic: interface conversion: interface {} is nil, not []map[string]interface {}

goroutine 1387 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.readBlockDevices(0xc001bdb480, 0xc0024d0d80, 0xc00013fb18, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/ec2/instance.go:1906 +0x799
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.resourceInstanceRead(0xc001bdb480, 0x81e77c0, 0xc00022ca80, 0xf0197b0, 0xc000680800)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/ec2/instance.go:1118 +0x1ce6
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000efefc0, 0xa46da58, 0xc00186dc00, 0xc001bdb480, 0x81e77c0, 0xc00022ca80, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:346 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000efefc0, 0xa46da58, 0xc00186dc00, 0xc001e384e0, 0x81e77c0, 0xc00022ca80, 0xc003183dc0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:635 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000135098, 0xa46da58, 0xc00186dc00, 0xc00186dc40, 0x951b3bc, 0x12, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:576 +0x47d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc00019ec80, 0xa46db00, 0xc00186dc00, 0xc000301b00, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:553 +0x322
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x92849e0, 0xc00019ec80, 0xa46db00, 0xc001b6d140, 0xc000301a40, 0x0, 0xa46db00, 0xc001b6d140, 0xc001e2e000, 0x781)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00032a8c0, 0xa49a2d8, 0xc0026fe000, 0xc002bcd300, 0xc001fe29f0, 0xefd9a90, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00032a8c0, 0xa49a2d8, 0xc0026fe000, 0xc002bcd300, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0017acca0, 0xc00032a8c0, 0xa49a2d8, 0xc0026fe000, 0xc002bcd300)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.72.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

### Panic Output

https://gist.github.com/kylejohnson/c2732ed00ca2754d5683df3d00e7d2e8#file-panic-log

### Expected Behavior

Terraform should not crash when running `terraform plan` or `terraform apply`

### Actual Behavior

Terraform is crashing when I run `terraform plan` or `terraform apply`

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`

### Important Factoids

* I was hopping between my linux workstation, and my macbook laptop, doing small changes to the configuration, including running `terraform apply`.  I'm unable to determine exactly which terraform and aws provider version combination caused this bug, but the bug now happens regardless of which versions are at play.
* The aws provider was not pinned to a specific version
* Each machine had a different version of terraform installed
  * linux: Uncertain.  > 1.0 for sure (linux_amd64)
  * mac: 1.0.11 (darwin_amd64)

### References

* #19779
* #17284
* #20821

**Comment by kylejohnson** [comment]
The fix proposed in #17284 solves my issue.
```
kjohnson@kyle-workstation01:~/work/personal/terraform-provider-aws$ git diff
diff --git a/internal/service/ec2/instance.go b/internal/service/ec2/instance.go
index 21add5d93c..2622aefe79 100644
--- a/internal/service/ec2/instance.go
+++ b/internal/service/ec2/instance.go
@@ -1903,7 +1903,7 @@ func readBlockDevices(d *schema.ResourceData, instance *ec2.Instance, conn *ec2.
        // and #readBlockDevicesFromInstance only returns 1 reference to a block-device
        // stored in ibds["root"]
        if _, ok := d.GetOk("ebs_block_device"); ok {
-               if len(ibds["ebs"].([]map[string]interface{})) == 0 {
+               if ibds["ebs"] != nil && len(ibds["ebs"].([]map[string]interface{})) == 0 {
                        ebs := make(map[string]interface{})
                        for k, v := range ibds["root"].(map[string]interface{}) {
                                ebs[k] = v
```
