### ISSUE TITLE
aws_waf_rule_group crashes

### ISSUE THREAD

**Issue by StuShepherdUK** [hashicorp/terraform-provider-aws#22769]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

aws v3.73.0

#### Creating the IP Set tp be defined in AWS WAF 

```hcl
resource "aws_waf_ipset" "ipset" {
   name = "MyFirstipset"
   ip_set_descriptors {
     type = "IPV4"
     value = "10.111.0.0/20"
   }
}
```

#### Creating the AWS WAF rule that will be applied on AWS Web ACL

```hcl
resource "aws_waf_rule" "waf_rule" { 
  depends_on = [aws_waf_ipset.ipset]
  name        = "myFirstwafrulename"
  metric_name = "myFirstwafrulemetrics"
  predicates {
    data_id = aws_waf_ipset.ipset.id
    negated = false
    type    = "IPMatch"
  }
}
```

#### Creating the Rule Group which will be applied on  AWS Web ACL

```hcl
resource "aws_waf_rule_group" "rule_group" {  
  name        = "myFirstwaf_rule_group_name"
  metric_name = "myFirstwafrulemetrics"
  activated_rule {
    action {
      type = "COUNT"
    }
    priority = 50
    rule_id  = aws_waf_rule.waf_rule.id
  }
}
```

### Crashed Output

```
aws_waf_rule_group.rule_group: Creating...
╷
│ Error: Plugin did not respond
│
│   with aws_waf_rule_group.rule_group,
│   on aws-waf.tf line 26, in resource "aws_waf_rule_group" "rule_group":
│   26: resource "aws_waf_rule_group" "rule_group" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-aws_v3.73.0_x5.exe plugin:

panic: interface conversion: interface {} is int, not int64

goroutine 28 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/waf.ExpandActivatedRule(...)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/waf/helpers.go:274
github.com/hashicorp/terraform-provider-aws/internal/service/waf.DiffRuleGroupActivatedRules(0xf4cdb90, 0x0, 0x0, 0xc00296db20, 0x1, 0x1, 0xc00010d1e8, 0xc000b3dd00, 0xc000b3d900)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/waf/helpers.go:246 +0xe33
github.com/hashicorp/terraform-provider-aws/internal/service/waf.updateWafRuleGroupResource.func1(0xc001867c60, 0xf4cdb90, 0xc00010d1e8, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/waf/rule_group.go:244 +0xd3
github.com/hashicorp/terraform-provider-aws/internal/service/waf.(*WafRetryer).RetryWithToken.func1(0x2)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/waf/token_handlers.go:33 +0x206
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.RetryContext.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/resource/wait.go:27 +0x62
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext.func1(0xc0012954a0, 0xc002969570, 0xc0028758c0, 0xc000113500, 0xc000327be8, 0xc000327be0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/resource/state.go:110 +0x309
created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/resource/state.go:83 +0x1d9

Error: The terraform-provider-aws_v3.73.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior

Deployed to AWS WAF

### Actual Behavior

The IP Set and Rule created okay
The Rule Group is created, but no content

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Running, using Windows Terraform 1.0.11

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/ecc0285a35f06c4a9d9ddde12a45fcafdd905159/internal/service/waf/helpers.go#L272-L286

**Comment by ewbankkit** [comment]
@StuShepherdUK Thanks for raising this issue.
It has already been noticed in #22378. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
