### ISSUE TITLE
The terraform-provider-aws_v3.64.0_x5 plugin crashed

### ISSUE THREAD

**Issue by krestivo-kdinfotech** [hashicorp/terraform-provider-aws#22885]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

aws_instance

### Terraform Configuration Files
I can't share this, not my IP

### Debug Output

```
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-aws_v3.64.0_x5 plugin:

panic: interface conversion: interface {} is nil, not []map[string]interface {}

goroutine 1258 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.readBlockDevices(0xc0000b3600, 0xc001659440, 0xc00127e810, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/ec2/instance.go:1901 +0x799
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.resourceInstanceRead(0xc0000b3600, 0x6a88d80, 0xc001bc4000, 0xc353b60, 0xc00007c400)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/ec2/instance.go:1114 +0x1ce6
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000b809a0, 0x860efa8, 0xc00209de80, 0xc0000b3600, 0x6a88d80, 0xc001bc4000, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000b809a0, 0x860efa8, 0xc00209de80, 0xc0026a3880, 0x6a88d80, 0xc001bc4000, 0xc00030a130, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000120de0, 0x860efa8, 0xc00209de80, 0xc00209dec0, 0xc00209de80, 0x40b965, 0x746f920)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc001b06140, 0x860f050, 0xc00209de80, 0xc001183c20, 0xc001b06140, 0xc0022a3200, 0xc001eb5ba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x7775b00, 0xc001b06140, 0x860f050, 0xc0022a3200, 0xc001183bc0, 0x0, 0x860f050, 0xc0022a3200, 0xc00183a000, 0x7d3)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00022d880, 0x8632d98, 0xc0026c4000, 0xc0018d4d00, 0xc0002c4990, 0xc311c70, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00022d880, 0x8632d98, 0xc0026c4000, 0xc0018d4d00, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000358cd0, 0xc00022d880, 0x8632d98, 0xc0026c4000, 0xc0018d4d00)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.64.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

### Expected Behavior

It should have plan'ed or applied

### Actual Behavior
 
crash, see above

### Steps to Reproduce

  
1. `terraform apply` or plan

**Comment by krestivo-kdinfotech** [comment]
I worked around this by upgrading to 3.74.0. Going to close this so it doesn't confuse anyone.
