### ISSUE TITLE
Searching by tag for a non-existant aws_efs_file_system data source crashes the provider

### ISSUE THREAD

**Issue by sljinlet** [hashicorp/terraform-provider-aws#23309]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform -v
Terraform v1.1.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.2.0
```

### Affected Resource(s)

* aws_efs_file_system (data source)

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "us-west-2"
  shared_credentials_files = ["/Users/steve/.aws/credentials"]
  profile = "inlet-dev"
}

data "aws_efs_file_system" "main_fetch_devqa" {
  tags = {
    Name = "Does_Not_Exist"
  }
}
```

### Panic Output

```
Stack trace from the terraform-provider-aws_v4.2.0_x5 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 100 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/efs.dataSourceFileSystemRead(0x68, {0x8276420, 0xc00018aa80})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/efs/file_system_data_source.go:145 +0x997
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x95725bb, {0xa50a4b8, 0xc00207ef00}, 0xc0025dc5a0, {0x8276420, 0xc00018aa80})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:346 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc0008f10a0, {0xa50a4b8, 0xc00207ef00}, 0xc002599000, {0x8276420, 0xc00018aa80})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:569 +0xf7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc000110a20, {0xa50a4b8, 0xc00207ef00}, 0xc00256c920)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:1133 +0x3a8
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc0005cc400, {0xa50a560, 0xc002591950}, 0xc00257fb80)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:478 +0x37b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x93235e0, 0xc0005cc400}, {0xa50a560, 0xc002591950}, 0xc002583c20, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:416 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000df6a80, {0xa5fd2a0, 0xc00037e000}, 0xc00259a500, 0xc001870f00, 0xfb98530, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc000df6a80, {0xa5fd2a0, 0xc00037e000}, 0xc00259a500, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x294

Error: The terraform-provider-aws_v4.2.0_x5 plugin crashed!
```

### Expected Behavior

An error message is emitted noting a non-matching data source reference, as occurs with other data sources that don't match an existing resource.

### Actual Behavior

Kaboom! (See Panic output above)

### Steps to Reproduce

1.  `terraform init`
2. `terraform apply`

### Notes

I took a look at the code.  It's pretty obvious what's directly causing the crash...an attempt to reference the first element of an empty list/array.  

In `terraform-provider-aws/internal/service/efs/file_system_data_source.go` (last line below is line 145):

```
var results []*efs.FileSystemDescription

if len(tagsToMatch) > 0 {

        var fileSystems []*efs.FileSystemDescription

        for _, fileSystem := range describeResp.FileSystems {

                tags := KeyValueTags(fileSystem.Tags)

                if !tags.ContainsAll(tagsToMatch) {
                        continue
                }

                fileSystems = append(fileSystems, fileSystem)
        }

        results = fileSystems
} else {
        results = describeResp.FileSystems
}

if len(results) > 1 {
        return fmt.Errorf("Search returned %d results, please revise so only one is returned", len(results))
}

fs := results[0]
```

That last line is the culprit.  `results` ends up empty, I'm pretty sure, which leads to a kaboom.  Looking at the logic above suggests that it really is as simple as matching against a list of tags and coming up empty.

**Comment by ewbankkit** [comment]
Similar:

* https://github.com/hashicorp/terraform-provider-aws/issues/24031
* https://github.com/hashicorp/terraform-provider-aws/issues/21642
