### ISSUE TITLE
'Error: The terraform-provider-aws_v4.3.0_x5 plugin crashed!' when creating RDS cluster with S3 import

### ISSUE THREAD

**Issue by tonocastillo** [hashicorp/terraform-provider-aws#23634]
### Terraform CLI and Terraform AWS Provider Version

Run hashicorp/setup-terraform@v1.2.1
Latest version is 1.1.7

Provider version: 4.3.0

### Affected Resource(s)

* aws_RDS

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "us-east-1"
}

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.3.0"
    }
  }
}

data "aws_region" "current" {}

resource "aws_rds_cluster" "primary" {
  // provider                        = aws.primary
  engine                              = "aurora-mysql"
  engine_version                      = "5.7.mysql_aurora.2.10.0"
  cluster_identifier                  = "mysql-stage-dbcluster"
  iam_database_authentication_enabled = true
  skip_final_snapshot                 = true
  source_region                       = data.aws_region.current.name
  backup_retention_period             = 35
  vpc_security_group_ids              = [aws_security_group.mysql-security-group.id, aws_security_group.mysql-security-group-1.id]
  db_cluster_parameter_group_name     = aws_rds_cluster_parameter_group.cluster-db-pg.name
  db_subnet_group_name                = aws_db_subnet_group.mysql-stage.name
  s3_import {
    source_engine         = "mysql"
    source_engine_version = "5.7"
    bucket_name           = "mysql-snapshots-replication-destination"
    bucket_prefix         = "replication-test/"
    ingestion_role        = aws_iam_role.rds_s3_import.arn
  }
  port              = 3306
  storage_encrypted = true
  kms_key_id        = "arn:aws:kms:us-east-1:######:key/1223456788-1234-1234-aa12-asdasdasdsdfasd"
  tags              = merge(var.common_tags, { "Name" = "mysql-stage" })

}
```
### Panic Output

https://gist.github.com/tonocastillo/d8fc7195aa7487cf570dec387c6c011c

### Expected Behavior

The creation of a global RDS cluster. 

### Actual Behavior

AWS plugins just dies as soon as it tries to create the rds_cluster, it happens locally or when using github actions.

### Steps to Reproduce

Create an RDS global cluster using s3_import.
AWS accounts: acctA and AcctB
It fails this way when we try to create the rds_cluster in 'acctB' from an RDS export to S3 created in a different AWS account (acctA).
The bucket (acctA) has replication configured with a bucket (acctB), we are using kms encryption.

It seems something specific to `s3_import` as it works fine when I try to create a global RDS cluster sharing snapshots from acctA to acctB.

**Comment by ewbankkit** [comment]
```
Stack trace from the terraform-provider-aws_v4.3.0_x5 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 83 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/rds.resourceClusterCreate(0xc000923280, {0x7697940, 0xc0010a0a80})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/rds/cluster.go:615 +0x4226
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0024e4a50, {0x9930058, 0xc001d79e00}, 0x2, {0x7697940, 0xc0010a0a80})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:329 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000dd0d20, {0x9930058, 0xc001d79e00}, 0xc0016bb380, 0xc000923100, {0x7697940, 0xc0010a0a80})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:467 +0x871
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000d8a8, {0x9930058, 0xc001d79e00}, 0xc0002c1270)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000292e00, {0x9930100, 0xc0014fb6e0}, 0xc000f65810)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x30e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x87453c0, 0xc000292e00}, {0x9930100, 0xc0014fb6e0}, 0xc000fa7e60, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000cbaa80, {0x9a27ee0, 0xc0016e2300}, 0xc0024b5700, 0xc0016d9cb0, 0xefcf3c0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc000cbaa80, {0x9a27ee0, 0xc0016e2300}, 0xc0024b5700, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x294
```

**Comment by ewbankkit** [comment]
@tonocastillo Thanks for raising this issue.
It has already been noticed in #15325. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Comment by ewbankkit** [comment]
The workaround is to ensure that the `master_username` and `master_password` attributes are set when using `s3_import`.
