### ISSUE TITLE
IAM Policy Document panics with empty string in override_policy_documents

### ISSUE THREAD

**Issue by chrisgilmerproj** [hashicorp/terraform-provider-aws#23910]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.1.7
on darwin_amd64
```

With AWS provider `v4.8.0`

### Affected Resource(s)

* aws_iam_policy_document

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
data "aws_iam_policy_document" "supplemental_policy" {
  override_policy_documents = [""]

  # Rest of policy not applicable to error
}
```

### Debug Output

https://gist.github.com/chrisgilmerproj/edaea5c4f421b6f3b7c0d4bbabb2e894

### Panic Output

```
Stack trace from the terraform-provider-aws_v4.8.0_x5 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 139 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/iam.dataSourcePolicyDocumentRead(0x68, {0x80, 0x12369878})
        github.com/hashicorp/terraform-provider-aws/internal/service/iam/policy_document_data_source.go:253 +0x605
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xa748280, {0xa748280, 0xc001b34000}, 0xd, {0x84487e0, 0xc00134c000})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/resource.go:347 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc0008b8540, {0xa748280, 0xc001b34000}, 0xc0018d1300, {0x84487e0, 0xc00134c000})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/resource.go:578 +0x145
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc0002843f0, {0xa7481d8, 0xc0018faec0}, 0xc0012ad2e0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/grpc_provider.go:1179 +0x3ba
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc001883ea0, {0xa748280, 0xc0018b5980}, 0xc001584c30)
        github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/tf5server/server.go:657 +0x45f
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x9511f20, 0xc001883ea0}, {0xa748280, 0xc0018b5980}, 0xc00176f680, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:421 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000d0e00, {0xa842ba0, 0xc000f24820}, 0xc0018db560, 0xc0018918c0, 0xfeab3d0, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0000d0e00, {0xa842ba0, 0xc000f24820}, 0xc0018db560, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1619 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.45.0/server.go:919 +0x294

Error: The terraform-provider-aws_v4.8.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior

This should have done one of the following:

- Failed with an error letting me know not to use empty strings
- Succeeded with no error

### Actual Behavior

Got a panic

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

In 4.X aws provider users are given a deprecation warning. The change often employed looks like:

```diff
diff --git a/main.tf b/main.tf
index 34c1f32..e7bffe5 100644
--- a/main.tf
+++ b/main.tf
@@ -7,7 +7,7 @@ locals {
 
 data "aws_iam_policy_document" "supplemental_policy" {
 
-  override_json = var.custom_bucket_policy
+  override_policy_documents = [var.custom_bucket_policy]
```

Previously an empty string could be passed. Passing an empty string to the list causes the problem.

**Comment by johnkeates** [comment]
Just got exactly the same issue where I had an empty list (the result of a few fall-through try() entries).

````
Stack trace from the terraform-provider-aws_v4.8.0_x5 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 806 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/iam.dataSourcePolicyDocumentRead(0x68, {0x80, 0x123ae5b8})
	github.com/hashicorp/terraform-provider-aws/internal/service/iam/policy_document_data_source.go:140 +0x1194
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xa748280, {0xa748280, 0xc001a33380}, 0xd, {0x84487e0, 0xc0000d0a80})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/resource.go:347 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc000408540, {0xa748280, 0xc001a33380}, 0xc001d2f700, {0x84487e0, 0xc0000d0a80})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/resource.go:578 +0x145
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc00000ca68, {0xa7481d8, 0xc001de0740}, 0xc001ad5c60)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/grpc_provider.go:1179 +0x3ba
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc001818c80, {0xa748280, 0xc001a32c60}, 0xc0002e3ef0)
	github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/tf5server/server.go:657 +0x45f
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x9511f20, 0xc001818c80}, {0xa748280, 0xc001a32c60}, 0xc001170a20, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:421 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00022f180, {0xa842ba0, 0xc000d081a0}, 0xc001adf320, 0xc001824b40, 0xfeab3d0, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc00022f180, {0xa842ba0, 0xc000d081a0}, 0xc001adf320, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1619 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.45.0/server.go:919 +0x294

Error: The terraform-provider-aws_v4.8.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
````

Relevant code:
````
data "aws_iam_policy_document" "combined" {
  count = local.create_role_and_policy ? 1 : 0

  source_policy_documents = concat([try(data.aws_iam_policy_document.argocd_manager_local_assume[0].json, "")], [try(data.aws_iam_policy_document.argocd_manage_upstream_assume[0].json, "")])
}
 ````
In my case neither indices existed so try() ends up with an empty string list.

Only difference is Terraform v1.1.5 on darwin_amd64 instead of 1.1.7.  (Using the same `+ provider registry.terraform.io/hashicorp/aws v4.8.0`)

**Comment by ysb33r** [comment]
Yes, I am also seeing that with at least 4.7.x & 4.8.x of the plugin. Just need `override_policy_documents = [""]` to reproduce the problem.

**Comment by rs-garrick** [comment]
Desired behavior: do nothing when passing in an empty string or null. Please.

**Comment by aaronthebaron** [comment]
Ran into this problem as well.

 If you're looking for a way to mitigate:

`override_policy_documents = ["{}"]`

**Comment by dthauvin** [comment]
Hello same issue with Terraform/1.2.0 and terraform-provider-aws_v4.15.0

``` 
  override_policy_documents = [
    join("",data.aws_iam_policy_document.globaltolocals.*.json),
    join("",data.aws_iam_policy_document.localtoglobal.*.json),
    join("",data.aws_iam_policy_document.legacybisaccess.*.json),
    "{}"
    ]
```

**Comment by chrisgilmerproj** [comment]
Thanks @ewbankkit 🎉
