### ISSUE TITLE
go panic while configure existing launch_template

### ISSUE THREAD

**Issue by jkroepke** [hashicorp/terraform-provider-aws#24009]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_launch_template

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
data "aws_ami" "flatcar" {
  most_recent = true
  owners      = ["aws-marketplace"]

  filter {
    name   = "architecture"
    values = ["x86_64"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  filter {
    name   = "name"
    values = ["Flatcar-alpha-*"]
  }
}

resource "aws_launch_template" "this" {
  name                   = "jkr-k8s-controller-asg-controller-eu-central-1a"
  update_default_version = true

  block_device_mappings {
    device_name = "/dev/sda1"

    ebs {
      volume_size = 20
      volume_type = "gp3"
    }
  }

  credit_specification {
    cpu_credits = "standard"
  }

  disable_api_termination = false
  ebs_optimized           = true

  image_id                             = data.aws_ami.flatcar.id

  instance_market_options {
    market_type = "spot"
    spot_options {

    }
  }

  instance_type = "t2.micro"
  key_name      = "jkr"

  metadata_options {
    http_endpoint               = "enabled"
    http_tokens                 = "optional"
    http_put_response_hop_limit = 1
  }

  network_interfaces {
    associate_public_ip_address = true
    security_groups             = [var.vpc_security_group_id]
  }

  private_dns_name_options {
    hostname_type                        = "resource-name"
    enable_resource_name_dns_a_record    = true
    enable_resource_name_dns_aaaa_record = true
  }

  user_data              = ""

  depends_on = []
}
```

### Panic Output

```
Stack trace from the terraform-provider-aws_v4.8.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 45 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.expandLaunchTemplateInstanceMarketOptionsRequest(0xc001b1d4d0)
	github.com/hashicorp/terraform-provider-aws/internal/service/ec2/launch_template.go:1292 +0x18a
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.expandRequestLaunchTemplateData(0x9775d4f)
	github.com/hashicorp/terraform-provider-aws/internal/service/ec2/launch_template.go:958 +0xfd7
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.resourceLaunchTemplateUpdate(0xc001071680, {0x84487e0, 0xc000217500})
	github.com/hashicorp/terraform-provider-aws/internal/service/ec2/launch_template.go:815 +0x145
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xa748280, {0xa748280, 0xc0028aff20}, 0xd, {0x84487e0, 0xc000217500})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/resource.go:364 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000d9f500, {0xa748280, 0xc0028aff20}, 0xc0018acb60, 0xc001071400, {0x84487e0, 0xc000217500})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/resource.go:482 +0x785
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000132a50, {0xa7481d8, 0xc00185e780}, 0xc001c6e0f0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/grpc_provider.go:1021 +0xdaa
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00172a6e0, {0xa748280, 0xc0028af590}, 0xc002595c00)
	github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/tf5server/server.go:812 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x9511f20, 0xc00172a6e0}, {0xa748280, 0xc0028af590}, 0xc0015eaae0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00029efc0, {0xa842ba0, 0xc000fdb380}, 0xc001874900, 0xc001919920, 0xfeab3a0, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc00029efc0, {0xa842ba0, 0xc000fdb380}, 0xc001874900, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1619 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.45.0/server.go:919 +0x294

Error: The terraform-provider-aws_v4.8.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

2022-04-03T20:24:43.736+0200 [DEBUG] provider: plugin exited
```

### Expected Behavior

* Terraform is able to reconfigure launch template

### Actual Behavior

* go panic from terraform provider

### Steps to Reproduce

1. `terraform apply`

### References

Panic maybe introduced in 

* #23365

since, go panic does not happens on provider version 4.5.0, which not include the PR.

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/2def2996f8dc70054c8c1c437d50290dfffd457e/internal/service/ec2/launch_template.go#L1291-L1293

**Comment by ewbankkit** [comment]
@jkroepke Thanks for reporting this issue.
As a workaround, removing

```hcl
    spot_options {

    }
```

_should_ prevent the crash.

**Comment by sdlarsen** [comment]
@ewbankkit That workaround is not useful if you have conditional spot options (as we have). It's still present in v4.9.0_x5:
```
Stack trace from the terraform-provider-aws_v4.9.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 148 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.expandLaunchTemplateInstanceMarketOptionsRequest(0xc000c239e0)
	github.com/hashicorp/terraform-provider-aws/internal/service/ec2/launch_template.go:1292 +0x18a
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.expandRequestLaunchTemplateData(0x8c6f989)
	github.com/hashicorp/terraform-provider-aws/internal/service/ec2/launch_template.go:958 +0xfd7
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.resourceLaunchTemplateUpdate(0xc00276ed00, {0x7921500, 0xc000744000})
	github.com/hashicorp/terraform-provider-aws/internal/service/ec2/launch_template.go:815 +0x145
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x9c63900, {0x9c63900, 0xc002758ae0}, 0xd, {0x7921500, 0xc000744000})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/resource.go:730 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc001051880, {0x9c63900, 0xc002758ae0}, 0xc00277d860, 0xc00276eb80, {0x7921500, 0xc000744000})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/resource.go:848 +0x785
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0006a00f0, {0x9c63858, 0xc0024bd940}, 0xc002064dc0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000ed3360, {0x9c63900, 0xc002758420}, 0xc002485810)
	github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/tf5server/server.go:812 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x8a08420, 0xc000ed3360}, {0x9c63900, 0xc002758420}, 0xc0018b01e0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001c2fc0, {0x9d60020, 0xc000751380}, 0xc0027547e0, 0xc0017a3f20, 0xf45b400, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0001c2fc0, {0x9d60020, 0xc000751380}, 0xc0027547e0, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1619 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.45.0/server.go:919 +0x294

Error: The terraform-provider-aws_v4.9.0_x5 plugin crashed!
```

Which makes it impossible to apply anything to a running cluster (which is pretty bad...)

**Comment by sdlarsen** [comment]
Any progress on this?

**Comment by sdlarsen** [comment]
I worked around it using ```dynamic```, should anyone end up here...
```
  # Spot price if used
  dynamic "instance_market_options" {
    for_each = var.spot_price != "" ? [1] : []
    content {
      market_type = "spot"
      spot_options {
        max_price          = var.spot_price
        spot_instance_type = "one-time"
      }
    }
  }
```
