### ISSUE TITLE
aws_cloudwatch_event_connection crashes: panic: interface conversion: interface {} is nil, not map[string]interface {}

### ISSUE THREAD

**Issue by grimm26** [hashicorp/terraform-provider-aws#24061]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_cloudwatch_event_connection
* aws_cloudwatch_event_rule

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_cloudwatch_event_rule" "wfm_importer_flush_schedule" {
  provider            = aws.oh
  name                = "${local.service}-${local.product}-${local.environment}-flush"
  description         = "Trigger ${local.service}-${local.product}-${local.environment} run wfm importer flush"
  schedule_expression = "cron(*/15 * * * *)"
  is_enabled          = true
}

resource "aws_cloudwatch_event_api_destination" "wfm_importer_flush" {
  provider            = aws.oh
  name                = "${local.service}-${local.product}-${local.environment}-flush-api"
  description         = "Call API in ${local.environment}"
  invocation_endpoint = "https://mysite.place.com/dostuff"
  http_method         = "POST"
  connection_arn      = aws_cloudwatch_event_connection.call_wfm_importer_flush.arn
}

resource "aws_cloudwatch_event_target" "wfm_importer_flush_event_target" {
  provider = aws.oh
  rule     = aws_cloudwatch_event_rule.wfm_importer_flush_schedule.name
  arn      = resource.aws_cloudwatch_event_api_destination.wfm_importer_flush.arn
}

resource "aws_cloudwatch_event_connection" "call_wfm_importer_flush" {
  provider           = aws.oh
  name               = "call wfm importer flush"
  description        = "call wfm importer flush"
  authorization_type = "BASIC"

  auth_parameters {
    basic {
      username = ""
      password = ""
    }
  }
}
```

### Debug Output

https://gist.github.com/grimm26/3808322101f1d99e4140626ea42f74cc

### Expected Behavior

not a panic.

### Actual Behavior

```
aws_cloudwatch_event_rule.wfm_importer_flush_schedule: Creating...
aws_cloudwatch_event_connection.call_wfm_importer_flush: Creating...
╷
│ Error: Plugin did not respond
│
│   with aws_cloudwatch_event_rule.wfm_importer_flush_schedule,
│   on cloudwatch.tf line 1, in resource "aws_cloudwatch_event_rule" "wfm_importer_flush_schedule":
│    1: resource "aws_cloudwatch_event_rule" "wfm_importer_flush_schedule" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_cloudwatch_event_connection.call_wfm_importer_flush,
│   on cloudwatch.tf line 24, in resource "aws_cloudwatch_event_connection" "call_wfm_importer_flush":
│   24: resource "aws_cloudwatch_event_connection" "call_wfm_importer_flush" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-aws_v4.8.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 31 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/events.expandCreateConnectionBasicAuthRequestParameters({0xc00278b8e0, 0x1, 0x97669b3})
        github.com/hashicorp/terraform-provider-aws/internal/service/events/connection.go:406 +0x208
github.com/hashicorp/terraform-provider-aws/internal/service/events.expandCreateConnectionAuthRequestParameters({0xc00278b750, 0x1, 0xc0005d1250})
        github.com/hashicorp/terraform-provider-aws/internal/service/events/connection.go:370 +0x145
github.com/hashicorp/terraform-provider-aws/internal/service/events.resourceConnectionCreate(0xc001a96f00, {0x84487e0, 0xc001331500})
        github.com/hashicorp/terraform-provider-aws/internal/service/events/connection.go:244 +0x13c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xa748280, {0xa748280, 0xc001aaf9e0}, 0xd, {0x84487e0, 0xc001331500})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/resource.go:330 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000b1d260, {0xa748280, 0xc001aaf9e0}, 0xc0016b05b0, 0xc001a96d80, {0x84487e0, 0xc001331500})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/resource.go:472 +0x9ba
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000133140, {0xa7481d8, 0xc001e1d400}, 0xc002907450)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/grpc_provider.go:1021 +0xdaa
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0018b0140, {0xa748280, 0xc001aaf320}, 0xc0026de4d0)
        github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/tf5server/server.go:812 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x9511f20, 0xc0018b0140}, {0xa748280, 0xc001aaf320}, 0xc001aa8ae0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001fec40, {0xa842ba0, 0xc000ddf1e0}, 0xc001aadb00, 0xc0018a1680, 0xfeab3a0, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0001fec40, {0xa842ba0, 0xc000ddf1e0}, 0xc001aadb00, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1619 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.45.0/server.go:919 +0x294

Error: The terraform-provider-aws_v4.8.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

ERRO[0049] 1 error occurred:
        * exit status 1
```

### Steps to Reproduce

1.  I think it is because the auth username and password are blank, but not sure. That shouldn't cause a panic.
1. `terraform apply`

### References

Looks like this isn't a new issue.
https://github.com/hashicorp/terraform-provider-aws/issues/20492

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/2def2996f8dc70054c8c1c437d50290dfffd457e/internal/service/events/connection.go#L400-L415

**Comment by AdamTylerLynch** [comment]
Bug confirmed, and reproduced. This bug manifests itself as a casting error and a panic, but it is due to improper input validation on the schema.

As per AWS API docs, all credentials used for different types of authentication have a min length of 1 and a matched pattern.

[AWS API Documentation for CreateConnection](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_CreateConnectionBasicAuthRequestParameters.html
)


```
make testacc TESTS=TestAccEventsConnection_basic PKG=events ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/events/... -v -count 1 -parallel 2 -run='TestAccEventsConnection_basic'  -timeout 180m
=== RUN   TestAccEventsConnection_basic
=== PAUSE TestAccEventsConnection_basic
=== CONT  TestAccEventsConnection_basic
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 236 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/events.expandCreateConnectionBasicAuthRequestParameters(...)
        /Users/foo/SourceCode/terraform-provider-aws/internal/service/events/connection.go:406
github.com/hashicorp/terraform-provider-aws/internal/service/events.expandCreateConnectionAuthRequestParameters({0xc00280a830, 0x1, 0xc001b0f1a0?})
        /Users/foo/SourceCode/terraform-provider-aws/internal/service/events/connection.go:370 +0x4bd
github.com/hashicorp/terraform-provider-aws/internal/service/events.resourceConnectionCreate(0xc0012c7800, {0x8978100?, 0xc0004f2000})
        /Users/foo/SourceCode/terraform-provider-aws/internal/service/events/connection.go:244 +0x13c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xa95ead0?, {0xa95ead0?, 0xc0027b40f0?}, 0xd?, {0x8978100?, 0xc0004f2000?})
        /Users/foo/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/resource.go:696 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0007ceb60, {0xa95ead0, 0xc0027b40f0}, 0xc002bb49c0, 0xc0012c7680, {0x8978100, 0xc0004f2000})
        /Users/foo/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/resource.go:838 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc002a92288, {0xa95ea28?, 0xc001d5d9c0?}, 0xc0000ba640)
        /Users/foo/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc001996000, {0xa95ead0?, 0xc0027ad2f0?}, 0xc0012e0bd0)
        /Users/foo/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/tf5server/server.go:812 +0x515
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x9a7cce0?, 0xc001996000}, {0xa95ead0, 0xc0027ad2f0}, 0xc001b240c0, 0x0)
        /Users/foo/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0019da000, {0xa963218, 0xc003490340}, 0xc002bfed80, 0xc002a947e0, 0xf895320, 0x0)
        /Users/foo/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0019da000, {0xa963218, 0xc003490340}, 0xc002bfed80, 0x0)
        /Users/foo/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1619 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /Users/foo/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /Users/foo/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:919 +0x28a
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/events     9.997s
FAIL
make: *** [testacc] Error 1
```

**Comment by AdamTylerLynch** [comment]
I am submitting a PR to fix.
