### ISSUE TITLE
AWS provider 4.11.0 plugin crash

### ISSUE THREAD

**Issue by karendarm11** [hashicorp/terraform-provider-aws#24366]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```
Terraform v1.1.7 
AWS provider v4.11.0
```

### Affected Resource(s)

```
aws_s3_bucket
aws_route53_zone
aws_iam_policy_document
````
### Terraform Configuration Files

```
data "aws_iam_policy_document" "s3_bucket_policy" {
  statement {
    sid = "jenkins-read-write"

    actions = [
      "s3:*",
    ]

    resources = [
      "arn:aws:s3:::${local.bucket_name}",
      "arn:aws:s3:::${local.bucket_name}/*",
    ]

    principals {
      type = "AWS"

      identifiers = [
        "arn:aws:iam::xxxxx:root",
      ] 
    }

  }

  statement {
    sid = "cloudfront read"

    actions = [
      "s3:GetObject",
    ]

    resources = [
      "arn:aws:s3:::${local.bucket_name}",
      "arn:aws:s3:::${local.bucket_name}/*",
    ]

    principals {
      type = "AWS"

      identifiers = [
        join("", aws_cloudfront_origin_access_identity.origin_access_identity.*.iam_arn),
      ]
    }

  }

  source_policy_documents = [var.bucket_policy]
}

data "aws_iam_policy_document" "s3_log_bucket_policy" {
  statement {
    actions = [
      "s3:GetObject",
      "s3:PutObject",
      "s3:GetBucketAcl",
      "s3:PutBucketAcl",
      "s3:*",
    ]

    resources = [
      "arn:aws:s3:::${local.log_bucket_name}",
      "arn:aws:s3:::${local.log_bucket_name}/*",
    ]

    principals {
      type = "AWS"

      identifiers = [
        var.create_origin_access_identity == "false" ? local.origin_access_identity_arn : join("", aws_cloudfront_origin_access_identity.origin_access_identity.*.iam_arn),
      ]
    }
  }

  source_policy_documents = [var.log_bucket_policy]
}
```

### Actual Behavior

```
[2022-04-22T13:57:31.185Z] Terraform has been successfully initialized!
...
[2022-04-22T13:57:34.275Z] ╷
[2022-04-22T13:57:34.280Z] │ Error: Plugin did not respon
[2022-04-22T13:57:34.280Z] │ 
[2022-04-22T13:57:34.280Z] │   with module.acm_certificate.aws_acm_certificate.certificate,
[2022-04-22T13:57:34.280Z] │   on ../../../../../modules/acm_certificate/main.tf line 16, in resource "aws_acm_certificate" "certificate":
[2022-04-22T13:57:34.280Z] │   16: resource "aws_acm_certificate" "certificate" 
[2022-04-22T13:57:34.280Z] │ 
[2022-04-22T13:57:34.280Z] │ The plugin encountered an error, and failed to respond to the
[2022-04-22T13:57:34.280Z] │ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
[2022-04-22T13:57:34.280Z] │ details.
[2022-04-22T13:57:34.280Z] ╵
[2022-04-22T13:57:34.280Z] ╷
[2022-04-22T13:57:34.280Z] │ Error: Plugin did not respond
[2022-04-22T13:57:34.280Z] │ 
[2022-04-22T13:57:34.280Z] │   with module.cross_account_zone.aws_route53_zone.account_subdomain,
[2022-04-22T13:57:34.280Z] │   on ../../../../../modules/route53_cross_account_zone/main.tf line 11, in resource "aws_route53_zone" "account_subdomain":
[2022-04-22T13:57:34.280Z] │   11: resource "aws_route53_zone" "account_subdomain" {
[2022-04-22T13:57:34.280Z] │ 
[2022-04-22T13:57:34.280Z] │ The plugin encountered an error, and failed to respond to the
[2022-04-22T13:57:34.280Z] │ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
[2022-04-22T13:57:34.280Z] │ details.
[2022-04-22T13:57:34.280Z] ╵
[2022-04-22T13:57:34.280Z] ╷
[2022-04-22T13:57:34.280Z] │ Error: Plugin did not respond
[2022-04-22T13:57:34.280Z] │ 
[2022-04-22T13:57:34.280Z] │   with module.s3_cdn.module.s3_log_bucket.aws_s3_bucket.s3_bucket,
[2022-04-22T13:57:34.280Z] │   on ../../../../../modules/s3_bucket/main.tf line 7, in resource "aws_s3_bucket" "s3_bucket":
[2022-04-22T13:57:34.280Z] │    7: resource "aws_s3_bucket" "s3_bucket" {
[2022-04-22T13:57:34.280Z] │ 
[2022-04-22T13:57:34.280Z] │ The plugin encountered an error, and failed to respond to the
[2022-04-22T13:57:34.280Z] │ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
[2022-04-22T13:57:34.280Z] │ details.
[2022-04-22T13:57:34.280Z] ╵
[2022-04-22T13:57:34.280Z] ╷
[2022-04-22T13:57:34.280Z] │ Error: Plugin did not respond
[2022-04-22T13:57:34.280Z] │ 
[2022-04-22T13:57:34.280Z] │   with module.s3_cdn.data.aws_iam_policy_document.s3_bucket_policy,
[2022-04-22T13:57:34.280Z] │   on ../../../../../modules/s3_cdn/main.tf line 38, in data "aws_iam_policy_document" "s3_bucket_policy":
[2022-04-22T13:57:34.280Z] │   38: data "aws_iam_policy_document" "s3_bucket_policy" {
[2022-04-22T13:57:34.280Z] │ 
[2022-04-22T13:57:34.280Z] │ The plugin encountered an error, and failed to respond to the
[2022-04-22T13:57:34.280Z] │ plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain
[2022-04-22T13:57:34.280Z] │ more details.
[2022-04-22T13:57:34.280Z] ╵
[2022-04-22T13:57:34.280Z] ╷
[2022-04-22T13:57:34.280Z] │ Error: Plugin did not respond
[2022-04-22T13:57:34.280Z] │ 
[2022-04-22T13:57:34.280Z] │   with module.s3_cdn.data.aws_iam_policy_document.s3_log_bucket_policy,
[2022-04-22T13:57:34.280Z] │   on ../../../../../modules/s3_cdn/main.tf line 86, in data "aws_iam_policy_document" "s3_log_bucket_policy":
[2022-04-22T13:57:34.280Z] │   86: data "aws_iam_policy_document" "s3_log_bucket_policy" {
[2022-04-22T13:57:34.280Z] │ 
[2022-04-22T13:57:34.280Z] │ The plugin encountered an error, and failed to respond to the
[2022-04-22T13:57:34.280Z] │ plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain
[2022-04-22T13:57:34.280Z] │ more details.
[2022-04-22T13:57:34.280Z] ╵
[2022-04-22T13:57:34.280Z] ╷
[2022-04-22T13:57:34.280Z] │ Error: Plugin did not respond
[2022-04-22T13:57:34.280Z] │ 
[2022-04-22T13:57:34.280Z] │   with module.s3_cdn.aws_s3_bucket.s3_bucket[0],
[2022-04-22T13:57:34.280Z] │   on ../../../../../modules/s3_cdn/main.tf line 114, in resource "aws_s3_bucket" "s3_bucket":
[2022-04-22T13:57:34.280Z] │  114: resource "aws_s3_bucket" "s3_bucket" {
[2022-04-22T13:57:34.280Z] │ 
[2022-04-22T13:57:34.280Z] │ The plugin encountered an error, and failed to respond to the
[2022-04-22T13:57:34.280Z] │ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
[2022-04-22T13:57:34.280Z] │ details.
[2022-04-22T13:57:34.280Z] ╵
[2022-04-22T13:57:34.280Z] 
[2022-04-22T13:57:34.280Z] Stack trace from the terraform-provider-aws_v4.11.0_x5 plugin:
[2022-04-22T13:57:34.280Z] 
[2022-04-22T13:57:34.280Z] panic: interface conversion: interface {} is nil, not string
[2022-04-22T13:57:34.280Z] 
[2022-04-22T13:57:34.280Z] goroutine 331 [running]:
[2022-04-22T13:57:34.280Z] github.com/hashicorp/terraform-provider-aws/internal/service/iam.dataSourcePolicyDocumentRead(0x68, {0x80, 0x7ff1c84ad3c8})
[2022-04-22T13:57:34.280Z] 	github.com/hashicorp/terraform-provider-aws/internal/service/iam/policy_document_data_source.go:140 +0x1194
[2022-04-22T13:57:34.280Z] github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x9d09940, {0x9d09940, 0xc0027ec840}, 0xd, {0x79abd20, 0xc000558a80})
[2022-04-22T13:57:34.280Z] 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:712 +0x178
[2022-04-22T13:57:34.280Z] github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc00069c7e0, {0x9d09940, 0xc0027ec840}, 0xc0018f3f80, {0x79abd20, 0xc000558a80})
[2022-04-22T13:57:34.280Z] 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:943 +0x145
[2022-04-22T13:57:34.280Z] github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc00011ca08, {0x9d09898, 0xc0005a3440}, 0xc0028a75e0)
[2022-04-22T13:57:34.280Z] 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/grpc_provider.go:1179 +0x408
[2022-04-22T13:57:34.280Z] github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc001469c20, {0x9d09940, 0xc0027ec0c0}, 0xc00291d810)
[2022-04-22T13:57:34.280Z] 	github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:657 +0x45f
[2022-04-22T13:57:34.280Z] github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x8aa4700, 0xc001469c20}, {0x9d09940, 0xc0027ec0c0}, 0xc000597320, 0x0)
[2022-04-22T13:57:34.280Z] 	github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:421 +0x170
[2022-04-22T13:57:34.280Z] google.golang.org/grpc.(*Server).processUnaryRPC(0xc000226fc0, {0x9e07590, 0xc00072e820}, 0xc001f2d440, 0xc0011a1860, 0xf5664f0, 0x0)
[2022-04-22T13:57:34.281Z] 	google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
[2022-04-22T13:57:34.281Z] google.golang.org/grpc.(*Server).handleStream(0xc000226fc0, {0x9e07590, 0xc00072e820}, 0xc001f2d440, 0x0)
[2022-04-22T13:57:34.281Z] 	google.golang.org/grpc@v1.45.0/server.go:1619 +0xa2a
[2022-04-22T13:57:34.281Z] google.golang.org/grpc.(*Server).serveStreams.func1.2()
[2022-04-22T13:57:34.281Z] 	google.golang.org/grpc@v1.45.0/server.go:921 +0x98
[2022-04-22T13:57:34.281Z] created by google.golang.org/grpc.(*Server).serveStreams.func1
[2022-04-22T13:57:34.281Z] 	google.golang.org/grpc@v1.45.0/server.go:919 +0x294
[2022-04-22T13:57:34.281Z] 
[2022-04-22T13:57:34.281Z] Error: The terraform-provider-aws_v4.11.0_x5 plugin crashed!
[2022-04-22T13:57:34.281Z] 
[2022-04-22T13:57:34.281Z] This is always indicative of a bug within the plugin. It would be immensely
[2022-04-22T13:57:34.281Z] helpful if you could report the crash with the plugin's maintainers so that it
[2022-04-22T13:57:34.281Z] can be fixed. The output above should help diagnose the issue.
[2022-04-22T13:57:34.281Z] 
[2022-04-22T13:57:34.281Z] time=2022-04-22T13:57:34Z level=info msg=Executing hook: after_hook
[2022-04-22T13:57:34.281Z] time=2022-04-22T13:57:34Z level=error msg=1 error occurred:
[2022-04-22T13:57:34.281Z] 	* exit status 1


```
### Steps to Reproduce

```
terraform init
terraform plan
```

**Comment by justinretzolk** [comment]
Hey @karendarm11 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, are you able to provide the debug logs (redacted as necessary) as well?

**Comment by karendarm11** [comment]
Hey @justinretzolk....Sure, here is the debug log.
[terraform_debug.txt](https://github.com/hashicorp/terraform-provider-aws/files/8543679/terraform_debug.txt)

**Comment by karendarm11** [comment]
Hey @justinretzolk, here is the deb
[terraform_debug.txt](https://github.com/hashicorp/terraform-provider-aws/files/8543716/terraform_debug.txt)
ug log

**Comment by carterjones** [comment]
This appears related to https://github.com/hashicorp/terraform-provider-aws/issues/22959. If I'm interpreting things correctly, these are possibly both due to the same underlying issue.

**Comment by carterjones** [comment]
Here is a possible workaround for `data "aws_iam_policy_document" "s3_bucket_policy"` until this is addressed:

```
source_policy_documents = length(var.bucket_policy) > 0 ? [var.bucket_policy] : null
```

and then later in `data "aws_iam_policy_document" "s3_log_bucket_policy"`:

```
source_policy_documents = length(var.log_bucket_policy) > 0 ? [var.log_bucket_policy] : null
```

I'm using that conditional logic to get around the bug for now.

**Comment by MattCWheeler** [comment]
I had hit this problem when using 4.11. As of 4.67, it has been fixed.

**Comment by justinretzolk** [comment]
With the above in mind, closing this issue out. If you encounter this issue in more recent versions of the AWS Provider, please open a new issue so that we can triage it appropriately.
