### ISSUE TITLE
Terraform crashed: "rpc error: code = Unavailable desc = transport is closing"

### ISSUE THREAD

**Issue by michael-lee-mulesoft** [hashicorp/terraform-provider-aws#24455]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform version: 0.12.31

### Panic Output

https://gitlab.com/-/snippets/2308184

### Expected Behavior

Terraform should not crash

### Actual Behavior

Terraform crashed with a clear stack trace of "nil pointer dereference"

### Steps to Reproduce

1. `terraform plan`

### Suggestions

The crash is at this line: https://github.com/hashicorp/terraform-provider-aws/blob/50631ea27815c51332e5c155c6fe8d9c6a03695f/internal/service/serverlessrepo/cloudformation_stack.go#L206

It seems the `parameterDefinitions[key]` needs a `nil` check. This will at least let terraform finish the plan instead of crash.

**Comment by ewbankkit** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference
2022-04-29T04:41:53.911Z [DEBUG] plugin.terraform-provider-aws_v3.75.1_x5: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x6d5eab0]
2022-04-29T04:41:53.911Z [DEBUG] plugin.terraform-provider-aws_v3.75.1_x5: 
2022-04-29T04:41:53.911Z [DEBUG] plugin.terraform-provider-aws_v3.75.1_x5: goroutine 120 [running]:
2022-04-29T04:41:53.911Z [DEBUG] plugin.terraform-provider-aws_v3.75.1_x5: github.com/hashicorp/terraform-provider-aws/internal/service/serverlessrepo.flattenNonDefaultServerlessApplicationCloudFormationParameters(0xc002cc1100, 0x7, 0x7, 0xc0020be060, 0x6, 0x6, 0x0)
2022-04-29T04:41:53.911Z [DEBUG] plugin.terraform-provider-aws_v3.75.1_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/serverlessrepo/cloudformation_stack.go:206 +0x130
2022-04-29T04:41:53.911Z [DEBUG] plugin.terraform-provider-aws_v3.75.1_x5: github.com/hashicorp/terraform-provider-aws/internal/service/serverlessrepo.resourceCloudFormationStackRead(0xc0024bff00, 0x834a980, 0xc00059aa80, 0xf29e950, 0xc00007e800)
2022-04-29T04:41:53.911Z [DEBUG] plugin.terraform-provider-aws_v3.75.1_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/serverlessrepo/cloudformation_stack.go:189 +0xba7
2022-04-29T04:41:53.911Z [DEBUG] plugin.terraform-provider-aws_v3.75.1_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc00096c8c0, 0xa62f778, 0xc00285b1c0, 0xc0024bff00, 0x834a980, 0xc00059aa80, 0x0, 0x0, 0x0)
2022-04-29T04:41:53.911Z [DEBUG] plugin.terraform-provider-aws_v3.75.1_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:346 +0x1ee
2022-04-29T04:41:53.911Z [DEBUG] plugin.terraform-provider-aws_v3.75.1_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00096c8c0, 0xa62f778, 0xc00285b1c0, 0xc0024c7ee0, 0x834a980, 0xc00059aa80, 0x0, 0x0, 0xc002226300, 0x0)
2022-04-29T04:41:53.911Z [DEBUG] plugin.terraform-provider-aws_v3.75.1_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:635 +0x1cb
2022-04-29T04:41:53.911Z [DEBUG] plugin.terraform-provider-aws_v3.75.1_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000135098, 0xa62f778, 0xc00285b1c0, 0xc00285b200, 0x96aa663, 0x12, 0x0)
2022-04-29T04:41:53.911Z [DEBUG] plugin.terraform-provider-aws_v3.75.1_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:576 +0x47d
2022-04-29T04:41:53.911Z [DEBUG] plugin.terraform-provider-aws_v3.75.1_x5: github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc00019c700, 0xa62f820, 0xc00285b1c0, 0xc002b10180, 0x0, 0x0, 0x0)
2022-04-29T04:41:53.911Z [DEBUG] plugin.terraform-provider-aws_v3.75.1_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:553 +0x322
2022-04-29T04:41:53.911Z [DEBUG] plugin.terraform-provider-aws_v3.75.1_x5: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x940c880, 0xc00019c700, 0xa62f820, 0xc00220f470, 0xc002b10120, 0x0, 0xa62f820, 0xc00220f470, 0xc00249a800, 0x3b6)
2022-04-29T04:41:53.911Z [DEBUG] plugin.terraform-provider-aws_v3.75.1_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
2022-04-29T04:41:53.911Z [DEBUG] plugin.terraform-provider-aws_v3.75.1_x5: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000334700, 0xa65c538, 0xc000dfa180, 0xc002872000, 0xc000def8f0, 0xf25ec30, 0x0, 0x0, 0x0)
2022-04-29T04:41:53.911Z [DEBUG] plugin.terraform-provider-aws_v3.75.1_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
2022-04-29T04:41:53.911Z [DEBUG] plugin.terraform-provider-aws_v3.75.1_x5: google.golang.org/grpc.(*Server).handleStream(0xc000334700, 0xa65c538, 0xc000dfa180, 0xc002872000, 0x0)
2022-04-29T04:41:53.911Z [DEBUG] plugin.terraform-provider-aws_v3.75.1_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
2022-04-29T04:41:53.911Z [DEBUG] plugin.terraform-provider-aws_v3.75.1_x5: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0006ae3b0, 0xc000334700, 0xa65c538, 0xc000dfa180, 0xc002872000)
2022-04-29T04:41:53.911Z [DEBUG] plugin.terraform-provider-aws_v3.75.1_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
2022-04-29T04:41:53.911Z [DEBUG] plugin.terraform-provider-aws_v3.75.1_x5: created by google.golang.org/grpc.(*Server).serveStreams.func1
2022-04-29T04:41:53.911Z [DEBUG] plugin.terraform-provider-aws_v3.75.1_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
```
