### ISSUE TITLE
aws_ce_cost_category fails to apply with `INHERITED_VALUE`

### ISSUE THREAD

**Issue by TechIsCool** [hashicorp/terraform-provider-aws#24709]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```
$ terraform --version
Terraform v1.1.9
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.13.0
```

### Affected Resource(s)

* aws_ce_cost_category

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_ce_cost_category" "application" {
  name         = "Application"
  rule_version = "CostCategoryExpression.v1"

  rule {
    type = "INHERITED_VALUE"

    inherited_value {
      dimension_key  = "Application"
      dimension_name = "TAG"
    }
  }
}
```

### Debug Output
```
$ tf apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_ce_cost_category.application will be created
  + resource "aws_ce_cost_category" "application" {
      + arn             = (known after apply)
      + effective_end   = (known after apply)
      + effective_start = (known after apply)
      + id              = (known after apply)
      + name            = "Application"
      + rule_version    = "CostCategoryExpression.v1"

      + rule {
          + type = "INHERITED_VALUE"

          + inherited_value {
              + dimension_key  = "Application"
              + dimension_name = "TAG"
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_ce_cost_category.application: Creating...
╷
│ Error: Plugin did not respond
│
│   with aws_ce_cost_category.application,
│   on test.tf line 15, in resource "aws_ce_cost_category" "application":
│   15: resource "aws_ce_cost_category" "application" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵



```

### Panic Output

```
Stack trace from the terraform-provider-aws_v4.13.0_x5 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 109 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/ce.expandCostCategoryRule(0x140021196e0)
	github.com/hashicorp/terraform-provider-aws/internal/service/ce/cost_category.go:509 +0x504
github.com/hashicorp/terraform-provider-aws/internal/service/ce.expandCostCategoryRules({0x14002123630, 0x1, 0x1})
	github.com/hashicorp/terraform-provider-aws/internal/service/ce/cost_category.go:666 +0x90
github.com/hashicorp/terraform-provider-aws/internal/service/ce.resourceCostCategoryCreate({0x10d445c08, 0x14002124480}, 0x140013e2700, {0x10ba9eb20, 0x14000ffca80})
	github.com/hashicorp/terraform-provider-aws/internal/service/ce/cost_category.go:386 +0x118
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1400059d880, {0x10d445c40, 0x140020e5e30}, 0x140013e2700, {0x10ba9eb20, 0x14000ffca80})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:707 +0x118
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1400059d880, {0x10d445c40, 0x140020e5e30}, 0x14000891e10, 0x140013e2580, {0x10ba9eb20, 0x14000ffca80})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:837 +0xc14
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1400000c2e8, {0x10d445b98, 0x140002471c0}, 0x140002b1a40)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/grpc_provider.go:1021 +0xedc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x140008a6140, {0x10d445c40, 0x140020e5680}, 0x140001a6310)
	github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:812 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x10cc8fc20, 0x140008a6140}, {0x10d445c40, 0x140020e5680}, 0x14001249080, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400023cfc0, {0x10d54f690, 0x14000e476c0}, 0x140012faea0, 0x140008a2660, 0x113027cc0, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1282 +0xc5c
google.golang.org/grpc.(*Server).handleStream(0x1400023cfc0, {0x10d54f690, 0x14000e476c0}, 0x140012faea0, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1619 +0xa34
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x14001960660, 0x1400023cfc0, {0x10d54f690, 0x14000e476c0}, 0x140012faea0)
	google.golang.org/grpc@v1.45.0/server.go:921 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.45.0/server.go:919 +0x1f0

Error: The terraform-provider-aws_v4.13.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior

Apply should occur successfully

### Actual Behavior

Crash

### Steps to Reproduce

1. `terraform apply`

### References

- https://github.com/hashicorp/terraform-provider-aws/pull/24402

**Comment by michaelpegg** [comment]
Tried v4.12.0 and v4.15.0. same error.

**Comment by dr-yd** [comment]
I just ran into the same issue with v4.27.0. Is there any way to implement this currently or are inherited values (wt least with tags) currently unusable?

**Comment by mmclane** [comment]
I am experiencing the same
```
aws_ce_cost_category.stack: Modifying... [id=arn:aws:ce::878788551012:costcategory/2be0abf3-779d-4275-a40e-1113b75c774a]
╷
│ Error: Plugin did not respond
│ 
│   with aws_ce_cost_category.stack,
│   on tags_catagories.tf line 18, in resource "aws_ce_cost_category" "stack":
│   18: resource "aws_ce_cost_category" "stack" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-aws_v4.29.0_x5 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 411 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/ce.expandCostCategoryRule(0xc002a9b890)
        github.com/hashicorp/terraform-provider-aws/internal/service/ce/cost_category.go:522 +0x426
github.com/hashicorp/terraform-provider-aws/internal/service/ce.expandCostCategoryRules({0xc002888b50?, 0x1, 0x2?})
        github.com/hashicorp/terraform-provider-aws/internal/service/ce/cost_category.go:679 +0x8c
github.com/hashicorp/terraform-provider-aws/internal/service/ce.resourceCostCategoryUpdate({0xaec6328, 0xc00320df20}, 0xc0031c1100, {0x8b8ca00?, 0xc00062c000?})
        github.com/hashicorp/terraform-provider-aws/internal/service/ce/cost_category.go:465 +0x1f7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc000ea2000, {0xaec6360, 0xc002a4e690}, 0xd?, {0x8b8ca00, 0xc00062c000})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/resource.go:741 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000ea2000, {0xaec6360, 0xc002a4e690}, 0xc00318ef70, 0xc0031c0880, {0x8b8ca00, 0xc00062c000})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/resource.go:847 +0x82c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000cdb0, {0xaec6360?, 0xc002a45e60?}, 0xc002bbaaa0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc001bfa360, 0xc001bfa930, {0xc003446ba0, 0x2, 0x2}, 0xc001bfa780, 0xc0015a2900, 0xc002fee2d0, 0xc001bfa9f0}, {0xaec6360, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.7.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0x142
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00178db80, {0xaec6360?, 0xc002a376b0?}, 0xc001dfd030)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x9dfd280?, 0xc00178db80}, {0xaec6360, 0xc002a376b0}, 0xc001dfcee0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0034a2000, {0xaecba78, 0xc0005c21a0}, 0xc003182c60, 0xc003497200, 0x1059e9e0, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc0034a2000, {0xaecba78, 0xc0005c21a0}, 0xc003182c60, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-aws_v4.29.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

**Comment by jbcom** [comment]
Can confirm this is still an issue with v4.34:

```shell
goroutine 378 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/ce.expandCostCategoryRule(0xc002f87ad0)
	github.com/hashicorp/terraform-provider-aws/internal/service/ce/cost_category.go:522 +0x426
github.com/hashicorp/terraform-provider-aws/internal/service/ce.expandCostCategoryRules({0xc0045824c0?, 0x4, 0xc003202a88?})
	github.com/hashicorp/terraform-provider-aws/internal/service/ce/cost_category.go:679 +0x8c
github.com/hashicorp/terraform-provider-aws/internal/service/ce.resourceCostCategoryCreate({0xbcf83e8?, 0xc0041b80c0}, 0xc002915f80, {0x9ba6440?, 0xc000929500})
	github.com/hashicorp/terraform-provider-aws/internal/service/ce/cost_category.go:380 +0x256
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000ee9340, {0xbcf8420, 0xc002e98030}, 0xd?, {0x9ba6440, 0xc000929500})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000ee9340, {0xbcf8420, 0xc002e98030}, 0xc003161860, 0xc002915e00, {0x9ba6440, 0xc000929500})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0005cc9c0, {0xbcf8420?, 0xc002d53920?}, 0xc0020238b0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc002451470, 0xc0024516e0, {0xc003e10e20, 0x2, 0x2}, 0xc002451620, 0xc0002338a0, 0xc0039a69e0, 0xc002451aa0}, {0xbcf8420, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.7.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0x142
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc001e2b720, {0xbcf8420?, 0xc002d52a50?}, 0xc00166b2d0)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xac40b40?, 0xc001e2b720}, {0xbcf8420, 0xc002d52a50}, 0xc00166b260, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc003091a40, {0xbcfdda0, 0xc0011f2680}, 0xc003156a20, 0xc003e62bd0, 0x114a7600, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc003091a40, {0xbcfdda0, 0xc0011f2680}, 0xc003156a20, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-aws_v4.34.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by gavinclarkeuk** [comment]
Still an issue with v4.40

**Comment by borjatur** [comment]
I can confirm that this is still failing in v4.50

**Comment by jeroenhabets** [comment]
@DrFaust92 As a complete Go-n00b, I am puzzled how this line that looks like a solid guard clause:

https://github.com/hashicorp/terraform-provider-aws/blob/453e5cc57aa215d14ce781c842d030ef6fa47c28/internal/service/ce/cost_category.go#L522

can cause a `panic: runtime error: index out of range [0] with length 0 ?` here...

(As I get the same stacktrace w/ error in line 522 as https://github.com/hashicorp/terraform-provider-aws/issues/24709#issuecomment-1276727947)

**Comment by jeroenhabets** [comment]
Update: I was now able to upgrade to 4.51.0 and it now fails on line 531 which makes a bit more sense (though also my terraform does not have any `rule` as sibling to `inherited_value` so why is L530 true?):
https://github.com/hashicorp/terraform-provider-aws/blob/453e5cc57aa215d14ce781c842d030ef6fa47c28/internal/service/ce/cost_category.go#L530-L531

**Comment by RoyMaunders** [comment]
Just hit this

expandCostExpressions can return nil so the code doesn't appear to be great.

rule and inherited_value appear to be mutually exclusive but with that said not sure how much logic you would want to build into this.
