### ISSUE TITLE
plugin crash when using aws_appstream_fleet resource with undefined 

### ISSUE THREAD

**Issue by jsnellink** [hashicorp/terraform-provider-aws#24798]
The `aws_appstream_image_builder` resource is able to be passed empty values for following arguments and the image builder is successfully built, but this same block when used on the `aws_appstream_fleet` resources causes an error:
```
  domain_join_info {
    directory_name                         = ""
    organizational_unit_distinguished_name = ""
  }
```

Below is the output received while when the error takes place:
```
Stack trace from the terraform-provider-aws_v4.14.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 105 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/appstream.expandDomainJoinInfo(...)
	github.com/hashicorp/terraform-provider-aws/internal/service/appstream/fleet.go:559
github.com/hashicorp/terraform-provider-aws/internal/service/appstream.resourceFleetCreate({0x10cda3ce0, 0x14002a794d0}, 0x14002a9c280, {0x10b3f7020, 0x14000efca80})
	github.com/hashicorp/terraform-provider-aws/internal/service/appstream/fleet.go:217 +0x1984
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x14000b2b5e0, {0x10cda3ce0, 0x14002a794d0}, 0x14002a9c280, {0x10b3f7020, 0x14000efca80})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:702 +0x70
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x14000b2b5e0, {0x10cda3ce0, 0x14002a794d0}, 0x14001a13860, 0x14002a9c100, {0x10b3f7020, 0x14000efca80})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:837 +0xc14
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1400000cd38, {0x10cda3c38, 0x14002a57640}, 0x14002a5b0e0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/grpc_provider.go:1021 +0xedc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x1400192b360, {0x10cda3ce0, 0x14002a78d20}, 0x14001ab51f0)
	github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:812 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x10c5ebdc0, 0x1400192b360}, {0x10cda3ce0, 0x14002a78d20}, 0x14002a19aa0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x140000e0e00, {0x10ceadbb0, 0x14000696680}, 0x14002a73d40, 0x1400193e600, 0x1129afca0, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1282 +0xc5c
google.golang.org/grpc.(*Server).handleStream(0x140000e0e00, {0x10ceadbb0, 0x14000696680}, 0x14002a73d40, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1619 +0xa34
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x14000642500, 0x140000e0e00, {0x10ceadbb0, 0x14000696680}, 0x14002a73d40)
	google.golang.org/grpc@v1.45.0/server.go:921 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.45.0/server.go:919 +0x1f0

Error: The terraform-provider-aws_v4.14.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/2bae1fb8aef3178c170f71667ba29b9adff020ac/internal/service/appstream/fleet.go#L552-L568
