### ISSUE TITLE
aws provider plugin >4.13 crashes if trying to activate iam client_authentication in existing aws_msk_cluster ressource

### ISSUE THREAD

**Issue by yurchella** [hashicorp/terraform-provider-aws#24898]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
terraform 1.0.7 
aws provider plugin 4.13, 4.14, 4.15

### Affected Resource(s)

* aws_msk_cluster

### Terraform Configuration Files
```
resource "aws_msk_cluster" "main" {
  cluster_name           = "msk-test" 
  kafka_version          = "2.4.1.1"             
  number_of_broker_nodes = 4
  enhanced_monitoring    = "PER_BROKER" 
  logging_info {
    broker_logs {
      cloudwatch_logs {
        enabled   = true
        log_group = aws_cloudwatch_log_group.it.name
      }
    }
  }
  broker_node_group_info {
    instance_type   = var.scaling.instance_type
    ebs_volume_size = var.scaling.ebs_volume_size
    client_subnets  = var.vpc.subnet_ids_main_private
    security_groups = [aws_security_group.kafka-broker-internal-security-group.id]
  }
  configuration_info {
    arn      = aws_msk_configuration.main.arn
    revision = aws_msk_configuration.main.latest_revision
  }
  encryption_info {
    encryption_at_rest_kms_key_arn = aws_kms_key.rest-key.arn
    encryption_in_transit {
      client_broker = "TLS" 
      in_cluster    = "true"
    }
  }

  client_authentication{
    unauthenticated = true
    sasl {
      iam   = true
      scram = false
    }
    tls {}
  }

  lifecycle {
    prevent_destroy = true
  }
}
```

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output
```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.msk.aws_msk_cluster.main will be updated in-place
  ~ resource "aws_msk_cluster" "main" {
        id                       = "arn:aws-cn:kafka:cn-north-1:424845081913:cluster/vedc-main/e8ee708d-a560-4a66-8931-54fa12d302bf-3"
        tags                     = {
            "Account_type"            = "main"
            "Bluegreen"               = "green"
            "Group"                   = "vedc"
            "Hub"                     = "tsp"
            "Stack"                   = "app"
            "Stage"                   = "e2e"
            "bmw:app-id"              = "app-17865"
            "bmw:app-name"            = "VSD Event Receiver Dispatcher"
            "bmw:compass-id"          = "msk"
            "bmw:env"                 = "e2e"
            "bmw:functional-resource" = "02_msk"
            "bmw:hub"                 = "tsp"
            "bmw:project"             = "vedc"
        }
        # (9 unchanged attributes hidden)


      + client_authentication {
          + unauthenticated = true

          + sasl {
              + iam   = true
              + scram = false
            }

          + tls {}
        }




        # (5 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Changes to Outputs:
  ~ bootstrap_brokers_tls = "b-2.vedc-main.l9qh31.c3.kafka.cn-north-1.amazonaws.com.cn:9094,b-3.vedc-main.l9qh31.c3.kafka.cn-north-1.amazonaws.com.cn:9094,b-4.vedc-main.l9qh31.c3.kafka.cn-north-1.amazonaws.com.cn:9094" -> "b-1.vedc-main.l9qh31.c3.kafka.cn-north-1.amazonaws.com.cn:9094,b-3.vedc-main.l9qh31.c3.kafka.cn-north-1.amazonaws.com.cn:9094,b-4.vedc-main.l9qh31.c3.kafka.cn-north-1.amazonaws.com.cn:9094"
╷
-----------------------------------------------------
2022-05-20T11:41:54.435+0200 [DEBUG] [aws-sdk-go] DEBUG: Response s3/PutObject Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Connection: close
Content-Length: 0
Date: Fri, 20 May 2022 09:41:55 GMT
Etag: "958deeef0e2be2c125d12447e97e702e"
Server: AmazonS3
X-Amz-Id-2: 0YdJFU8QyxQvVAbuZjZy3LkKN1x0K/pPOWoTDmeDQo+ds3PWHCvjvUdlAyBdWM5dfFV8U99KRGg=
X-Amz-Request-Id: ABEJ36WJ2QM5FBG4
X-Amz-Server-Side-Encryption: aws:kms
X-Amz-Server-Side-Encryption-Aws-Kms-Key-Id: arn:aws:kms:eu-central-1:530536451095:key/d0cb684e-0189-49f4-87f8-ddc5ce2ec7b7


-----------------------------------------------------
2022-05-20T11:41:54.435+0200 [DEBUG] [aws-sdk-go]
╷
│ Warning: Applied changes may be incomplete
│
│ The plan was created with the -target option in effect, so some changes
│ requested in the configuration may have been ignored and the output values
│ may not be fully updated. Run the following command to verify that no other
│ changes are pending:
│     terraform plan
│
│ Note that the -target option is not suitable for routine use, and is
│ provided only for exceptional situations such as recovering from errors or
│ mistakes, or when Terraform specifically suggests to use it as part of an
│ error message.
╵
╷
│ Warning: Argument is deprecated
│
│   with module.msk.aws_msk_cluster.main,
│   on .terraform\modules\msk\modules\msk-cluster-creator\main.tf line 144, in resource "aws_msk_cluster" "main":
│  144:     ebs_volume_size = var.scaling.ebs_volume_size
│
│ use 'storage_info' argument instead
╵
╷
│ Error: Plugin did not respond
│
│   with module.msk.aws_msk_cluster.main,
│   on .terraform\modules\msk\modules\msk-cluster-creator\main.tf line 129, in resource "aws_msk_cluster" "main":
│  129: resource "aws_msk_cluster" "main" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-aws_v4.15.0_x5.exe plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 103 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/kafka.expandClientAuthentication(0xc00214b710)
        github.com/hashicorp/terraform-provider-aws/internal/service/kafka/cluster.go:1052 +0x374
github.com/hashicorp/terraform-provider-aws/internal/service/kafka.resourceClusterUpdate({0xadfeb60, 0xc001f30ba0}, 0xc001f4f600, {0x88a3f20, 0xc000018a80})
        github.com/hashicorp/terraform-provider-aws/internal/service/kafka/cluster.go:853 +0x3afd
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xadfeb60, {0xadfeb60, 0xc001f30ba0}, 0xd, {0x88a3f20, 0xc000018a80})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:736 +0x87
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000fccb60, {0xadfeb60, 0xc001f30ba0}, 0xc001f54410, 0xc001f4f080, {0x88a3f20, 0xc000018a80})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:847 +0x9e5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000004c18, {0xadfeab8, 0xc001f18900}, 0xc001f34280)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0019ff5e0, {0xadfeb60, 0xc001f303c0}, 0xc001e74540)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:812 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x9a9ffc0, 0xc0019ff5e0}, {0xadfeb60, 0xc001f303c0}, 0xc001ece660, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002448c0, {0xaf0ad30, 0xc000b9e1a0}, 0xc001f2aea0, 0xc001a18d80, 0x10b09c80, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0002448c0, {0xaf0ad30, 0xc000b9e1a0}, 0xc001f2aea0, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1619 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.45.0/server.go:919 +0x294

Error: The terraform-provider-aws_v4.15.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

2022-05-20T11:41:54.444+0200 [DEBUG] provider: plugin exited

```

### Expected Behavior
Reasonable understandable error mesage

### Actual Behavior
AWS plugin crash

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
We have an existing msk-cluster which was applyed with the AWS provider 3.75 and now we trying to activate the iam auth.
We added the following block to the aws_msk_cluster (see tf-code above) and updated the aws provider to version 4.15

```
  client_authentication{
    unauthenticated = true
    sasl {
      iam   = true
      scram = false
    }
    tls {}
  }
```
Now we trying to apply the changes

### References

* #0000

**Comment by yurchella** [comment]
The reason is the empty block "tls {}".
After deleting it the tf apply worked and the aws iam got activated

**Comment by ewbankkit** [comment]
@yurchella Thanks for raising this issue.
It has already been noticed in #24881. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
