### ISSUE TITLE
aws_mq_broker | panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by valugi** [hashicorp/terraform-provider-aws#26000]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
hashicorp/terraform:0.11.11 

### Affected Resource(s)

* aws_mq_broker

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_mq_broker" "aws_mq_rabbit_dev" {
  broker_name = "TEST-MQ"
  engine_type        = "RabbitMQ"
  engine_version     = "3.8.6"
  host_instance_type = "mq.t3.micro"
  user {
    username = "admin"
    password = "${var.rabbitmq_password}"
    console_access = true
  }
  apply_immediately          = true
  auto_minor_version_upgrade = false
  deployment_mode    = "SINGLE_INSTANCE"
  maintenance_window_start_time {
    day_of_week = "SUNDAY"
    time_of_day = "02:00"
    time_zone = "CET"
  }
  publicly_accessible  = false
  security_groups    = ["${aws_security_group.mq_sg.id}"]
  subnet_ids         = ["${module.network.private_subnets[0]}"]
  
}

```

### Panic Output

I cannot put all the output as it has too much confidential information, but here is the partial one.
```
2022-07-27T08:53:04.048Z [DEBUG] plugin.terraform-provider-aws_v2.40.0_x4: 2022/07/27 08:53:04 [TRACE] Waiting 10s before next try
2022/07/27 08:53:05 [TRACE] dag/walk: vertex "root", waiting for: "provider.aws (close)"
2022/07/27 08:53:05 [TRACE] dag/walk: vertex "provider.aws (close)", waiting for: "aws_mq_broker.aws_mq_rabbit_dev"
2022/07/27 08:53:05 [TRACE] dag/walk: vertex "meta.count-boundary (count boundary fixup)", waiting for: "aws_mq_broker.aws_mq_rabbit_dev"
2022/07/27 08:53:10 [TRACE] dag/walk: vertex "root", waiting for: "provider.aws (close)"
2022/07/27 08:53:10 [TRACE] dag/walk: vertex "provider.aws (close)", waiting for: "aws_mq_broker.aws_mq_rabbit_dev"
2022/07/27 08:53:10 [TRACE] dag/walk: vertex "meta.count-boundary (count boundary fixup)", waiting for: "aws_mq_broker.aws_mq_rabbit_dev"
2022-07-27T08:53:14.192Z [DEBUG] plugin.terraform-provider-aws_v2.40.0_x4: 2022/07/27 08:53:14 [INFO] Reading MQ Broker: b-0a6f4659-40b2-[removed]
2022-07-27T08:53:14.380Z [DEBUG] plugin.terraform-provider-aws_v2.40.0_x4: panic: runtime error: invalid memory address or nil pointer dereference
2022-07-27T08:53:14.380Z [DEBUG] plugin.terraform-provider-aws_v2.40.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x389089c]
2022-07-27T08:53:14.380Z [DEBUG] plugin.terraform-provider-aws_v2.40.0_x4: 
2022-07-27T08:53:14.380Z [DEBUG] plugin.terraform-provider-aws_v2.40.0_x4: goroutine 3534 [running]:
2022-07-27T08:53:14.380Z [DEBUG] plugin.terraform-provider-aws_v2.40.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsMqBrokerRead(0xc0004b4310, 0x3f79d80, 0xc0002ee000, 0x0, 0x0)
2022-07-27T08:53:14.380Z [DEBUG] plugin.terraform-provider-aws_v2.40.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_mq_broker.go:352 +0xbcc
2022-07-27T08:53:14.380Z [DEBUG] plugin.terraform-provider-aws_v2.40.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsMqBrokerCreate(0xc0004b4310, 0x3f79d80, 0xc0002ee000, 0xc0004b4310, 0x0)
2022-07-27T08:53:14.380Z [DEBUG] plugin.terraform-provider-aws_v2.40.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_mq_broker.go:302 +0xc7e
2022-07-27T08:53:14.380Z [DEBUG] plugin.terraform-provider-aws_v2.40.0_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc001145b00, 0xc0006b68c0, 0xc00077dc20, 0x3f79d80, 0xc0002ee000, 0xc00075e801, 0xc00083aba8, 0x40be26)
2022-07-27T08:53:14.380Z [DEBUG] plugin.terraform-provider-aws_v2.40.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.3.0/helper/schema/resource.go:305 +0x365
2022-07-27T08:53:14.380Z [DEBUG] plugin.terraform-provider-aws_v2.40.0_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000b97880, 0xc00151c680, 0xc0006b68c0, 0xc00077dc20, 0xc000da0d20, 0xc000604120, 0x18)
2022-07-27T08:53:14.380Z [DEBUG] plugin.terraform-provider-aws_v2.40.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.3.0/helper/schema/provider.go:294 +0x99
2022-07-27T08:53:14.380Z [DEBUG] plugin.terraform-provider-aws_v2.40.0_x4: github.com/hashicorp/terraform-plugin-sdk/plugin.(*ResourceProviderServer).Apply(0xc0007bcea0, 0xc00077d7e0, 0xc000693f20, 0x0, 0x0)
2022-07-27T08:53:14.380Z [DEBUG] plugin.terraform-provider-aws_v2.40.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.3.0/plugin/resource_provider.go:530 +0x57
2022-07-27T08:53:14.380Z [DEBUG] plugin.terraform-provider-aws_v2.40.0_x4: reflect.Value.call(0xc0005c5380, 0xc000ddcd00, 0x13, 0x50269cd, 0x4, 0xc00083af18, 0x3, 0x3, 0x40523a, 0x42ca1a, ...)
2022-07-27T08:53:14.380Z [DEBUG] plugin.terraform-provider-aws_v2.40.0_x4: 	/opt/goenv/versions/1.13.4/src/reflect/value.go:460 +0x5f6
2022-07-27T08:53:14.380Z [DEBUG] plugin.terraform-provider-aws_v2.40.0_x4: reflect.Value.Call(0xc0005c5380, 0xc000ddcd00, 0x13, 0xc001038718, 0x3, 0x3, 0x0, 0xc000be1880, 0x0)
2022-07-27T08:53:14.380Z [DEBUG] plugin.terraform-provider-aws_v2.40.0_x4: 	/opt/goenv/versions/1.13.4/src/reflect/value.go:321 +0xb4
2022-07-27T08:53:14.380Z [DEBUG] plugin.terraform-provider-aws_v2.40.0_x4: net/rpc.(*service).call(0xc000c34e80, 0xc000ab53b0, 0xc0007c9db0, 0xc0007c9dc0, 0xc000b97a80, 0xc0007bcf00, 0x3f78780, 0xc00077d7e0, 0x16, 0x3f787c0, ...)
2022-07-27T08:53:14.380Z [DEBUG] plugin.terraform-provider-aws_v2.40.0_x4: 	/opt/goenv/versions/1.13.4/src/net/rpc/server.go:377 +0x16f
2022-07-27T08:53:14.380Z [DEBUG] plugin.terraform-provider-aws_v2.40.0_x4: created by net/rpc.(*Server).ServeCodec
2022-07-27T08:53:14.380Z [DEBUG] plugin.terraform-provider-aws_v2.40.0_x4: 	/opt/goenv/versions/1.13.4/src/net/rpc/server.go:474 +0x42b
2022/07/27 08:53:14 [TRACE] root: eval: *terraform.EvalWriteState
2022/07/27 08:53:14 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2022/07/27 08:53:14 [TRACE] root: eval: *terraform.EvalIf
2022/07/27 08:53:14 [TRACE] root: eval: *terraform.EvalWriteState
2022/07/27 08:53:14 [TRACE] root: eval: *terraform.EvalWriteDiff
2022/07/27 08:53:14 [TRACE] root: eval: *terraform.EvalApplyPost
2022/07/27 08:53:14 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* aws_mq_broker.aws_mq_rabbit_dev: unexpected EOF
2022/07/27 08:53:14 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* aws_mq_broker.aws_mq_rabbit_dev: unexpected EOF
2022/07/27 08:53:14 [TRACE] [walkApply] Exiting eval tree: aws_mq_broker.aws_mq_rabbit_dev
2022/07/27 08:53:14 [TRACE] dag/walk: upstream errored, not walking "provider.aws (close)"
2022/07/27 08:53:14 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2022/07/27 08:53:14 [TRACE] dag/walk: upstream errored, not walking "root"
2022-07-27T08:53:14.384Z [DEBUG] plugin: plugin process exited: path=/data/environments/[removed].terraform/plugins/linux_amd64/terraform-provider-aws_v2.40.0_x4
2022/07/27 08:53:14 [TRACE] Preserving existing state lineage "d16e054b-e8c1-a36d-2a1a-85ad53e93292"
2022/07/27 08:53:14 [TRACE] Preserving existing state lineage "d16e054b-e8c1-a36d-2a1a-85ad53e93292"
2022/07/27 08:53:14 [TRACE] Preserving existing state lineage "d16e054b-e8c1-a36d-2a1a-85ad53e93292"
2022/07/27 08:53:14 [DEBUG] Uploading remote state to S3: {
  Body: buffer(0xc000e47aa0),
  Bucket: "[removed]",
  ContentLength: 473863,
  ContentType: "application/json",
  Key: "[removed]/terraform.tfstate",
  ServerSideEncryption: "AES256"
}
2022/07/27 08:53:14 [DEBUG] plugin: waiting for all plugin processes to complete...
2022-07-27T08:53:14.554Z [WARN ] plugin: error closing client during Kill: err="connection is shut down"
2022-07-27T08:53:14.555Z [DEBUG] plugin.terraform-provider-random_v2.3.1_x4: 2022/07/27 08:53:14 [ERR] plugin: plugin server: accept unix /tmp/plugin465421246: use of closed network connection
2022-07-27T08:53:14.555Z [DEBUG] plugin.terraform-provider-template_v2.2.0_x4: 2022/07/27 08:53:14 [ERR] plugin: plugin server: accept unix /tmp/plugin980139679: use of closed network connection
2022-07-27T08:53:14.555Z [DEBUG] plugin.terraform-provider-random_v2.3.1_x4: 2022/07/27 08:53:14 [ERR] plugin: stream copy 'stderr' error: stream closed
2022-07-27T08:53:14.556Z [DEBUG] plugin: plugin process exited: path=/[removed]V/.terraform/plugins/linux_amd64/terraform-provider-template_v2.2.0_x4
2022-07-27T08:53:14.556Z [DEBUG] plugin: plugin process exited: path=/d[removed]/.terraform/plugins/linux_amd64/terraform-provider-random_v2.3.1_x4
```
### Expected Behavior

To create a MQ broker and finish the deployment. 

### Actual Behavior
Terraform crashes after ~ 11 minutes from 20 that it takes to create the broker. The broker is actually created - but the state is not preserved, so then next run will fail because it tries to create a new broker with the same name.

### Steps to Reproduce

1. `terraform apply`

**Comment by justinretzolk** [comment]
Hey @valugi 👋 Thank you for taking the time to raise this! I noticed that you've opened a few issues around some issues you're having with the `aws_mq_broker` resource. In looking at them, I also noticed that you're running Terraform `0.11.11` and AWS Provider version `2.40.0`. While the Terraform version is perhaps less important here, I think part of the issues you're running into may be related to the older version of the AWS Provider, for two reasons.

1. The documentation that you linked (in #25998) is for the latest version of the provider (`4.23.0`), so the arguments and attributes aren't guaranteed to be the same between the two.
2. Perhaps more importantly, any changes/bug fixes to how the resource operates will not have been back ported, and any changes to the API will not be compensated for.

I suspect you may be experiencing issues with the latter, as a (very) quick glance at the resource documentation didn't seem to indicate that there's been any major changes to the resource's arguments. Given that the AWS Provider version you're using was released nearly 3 years ago, and there's been several bug fixes to the resource since then, can you test with a later version of the provider to determine if that might resolve the issues that you're running into?

**Comment by valugi** [comment]
Indeed I am using `2.40` provider - this is a legacy environment. Upgrading the provider will have probably a lot of collateral effects. Is there a way of defining a newer provider only for these MQ resources that I am adding now?

**Comment by valugi** [comment]
3.75.2 or newer are not compatible with terraform version. I really do not like your versioning system - should be aligned only with AWS API version. You release a ton of versions, mostly backwards incompatible and have terraform versions and module version.  And on documentation page for a service aws_mq_broker there is no compatibility map.

**Comment by valugi** [comment]
Multiple provider are allowed but not for version - the versions get concatenated instead of installing 2 plugins.
`No provider "aws" plugins meet the constraint "2.40,4.23.0".`

**Comment by valugi** [comment]
To conclude - the version is important! `aws_mq_broker` with RabbitMQ is not actually supported for providers versions below 3.something and there is a direct - but not explicit - connection with the terraform version. In my particular case I need to upgrade or I need to upgrade - thanks for the support.
