### ISSUE TITLE
Provider crashes while trying to read policy

### ISSUE THREAD

**Issue by jwlogemann** [hashicorp/terraform-provider-aws#26071]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.2.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.23.0
+ provider registry.terraform.io/hashicorp/random v3.3.2

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
data "aws_iam_roles" "platformoperatorepcloudteam" {
    name_regex = "AWSReservedSSO_platformoperatorepcloudteam_.*"
}

data "aws_iam_policy_document" "kms_key_base" {
  statement {
    effect = "Allow"
    actions = [
      "kms:Create*",
      "kms:Describe*",
      "kms:Enable*",
      "kms:List*",
      "kms:Put*",
      "kms:Update*",
      "kms:Revoke*",
      "kms:Disable*",
      "kms:Get*",
      "kms:Delete*",
      "kms:ScheduleKeyDeletion",
      "kms:CancelKeyDeletion",
      "kms:Tag*",
      "kms:UntagResource"
    ]
    principals {
      type        = "AWS"
      identifiers = ["arn:aws:iam::${local.account_id}:root"]
    }
    resources = ["*"]
  }
  statement {
      effect = "Allow"
      actions = [
          "kms:Create*",
          "kms:Describe*",
          "kms:Enable*",
          "kms:List*",
          "kms:Put*",
          "kms:Update*",
          "kms:Revoke*",
          "kms:Disable*",
          "kms:Get*",
          "kms:Delete*",
          "kms:TagResource",
          "kms:UntagResource",
          "kms:ScheduleKeyDeletion",
          "kms:CancelKeyDeletion"
      ]
  principals {
          type        = "AWS"
          identifiers = data.aws_iam_roles.platformoperatorepcloudteam.arns 
          }
          resources = ["*"]
    
    }
}

data "aws_iam_policy_document" "merged_kms_policy" {
  source_policy_documents = [
    data.aws_iam_policy_document.kms_key_base.json,
    var.policy
  ]
}
```

### Panic Output

```
Stack trace from the terraform-provider-aws_v4.23.0_x5 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 572 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/iam.dataSourcePolicyDocumentRead(0x0, {0x0, 0x0})
	github.com/hashicorp/terraform-provider-aws/internal/service/iam/policy_document_data_source.go:140 +0x1194
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xab8eae0, {0xab8eae0, 0xc0020499b0}, 0xd, {0x84c7d60, 0xc000fe9500})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.19.0/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc0008d2fc0, {0xab8eae0, 0xc0020499b0}, 0xc002b36c00, {0x84c7d60, 0xc000fe9500})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.19.0/helper/schema/resource.go:943 +0x145
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc000292fc0, {0xab8eae0, 0xc0020497d0}, 0xc0025f70a0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.19.0/helper/schema/grpc_provider.go:1179 +0x408
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadDataSource({0xc0016e97d0, 0xc0016e9830, {0xc0007b53e0, 0x2, 0x2}, 0xc0016e9800, 0xc00119dc70, 0xc00296bcb0, 0xc0016e9860}, {0xab8eae0, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.7.0/tf5muxserver/mux_server_ReadDataSource.go:27 +0x142
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc0019b6140, {0xab8eae0, 0xc002056420}, 0xc00275e320)
	github.com/hashicorp/terraform-plugin-go@v0.12.0/tfprotov5/tf5server/server.go:658 +0x445
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x971ff00, 0xc0019b6140}, {0xab8eae0, 0xc002056420}, 0xc0011fcd20, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.12.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:421 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc002422380, {0xaca0a30, 0xc0007deb60}, 0xc002b83e60, 0xc00065e9c0, 0x10b7e3f0, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1295 +0xb03
google.golang.org/grpc.(*Server).handleStream(0xc002422380, {0xaca0a30, 0xc0007deb60}, 0xc002b83e60, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1636 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.48.0/server.go:930 +0x294

Error: The terraform-provider-aws_v4.23.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Operation failed: failed running terraform plan (exit 1)
```
### Expected Behavior

a terraform run

### Actual Behavior

a crash

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/0f825e7b2cb5ad90e10dec6243ddfede30c4e432/internal/service/iam/policy_document_data_source.go#L138-L142

**Comment by jwlogemann** [comment]
The problem here is the following:
```
data "aws_iam_policy_document" "merged_kms_policy" {
  source_policy_documents = [
    data.aws_iam_policy_document.kms_key_base.json,
    var.policy
  ]
}
```

If one of these inputs is not valid JSON the crash occurs at the json.Unmarshall() @ewbankkit posted above.

Valid:
```
data "aws_iam_policy_document" "test" {
}

data "aws_iam_policy_document" "merged_kms_policy" {
  source_policy_documents = [
    data.aws_iam_policy_document.kms_key_base.json,
    data.aws_iam_policy_document.test.json
  ]
}
```

Valid:
```
data "aws_iam_policy_document" "merged_kms_policy" {
  source_policy_documents = [
    data.aws_iam_policy_document.kms_key_base.json,
    "{}"
  ]
}
```

Crash:
```
data "aws_iam_policy_document" "merged_kms_policy" {
  source_policy_documents = [
    data.aws_iam_policy_document.kms_key_base.json,
    ""
  ]
}
```

I guess some input validation should be added, to test if the input is valid json, and return an error if not, instead of crashing.
