### ISSUE TITLE
r/aws_opensearch_domain: Occasional crash in `TestAccOpenSearchDomain_AdvancedSecurityOptions_disabled`

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#26249]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

[For example](https://github.com/hashicorp/terraform-provider-aws/runs/7788503055?check_suite_focus=true):

```
--- FAIL: TestAccOpenSearchDomain_AdvancedSecurityOptions_disabled (0.00s)
panic: runtime error: slice bounds out of range [:28] with length 27 [recovered]
	panic: runtime error: slice bounds out of range [:28] with length 27

goroutine 48 [running]:
testing.tRunner.func1.2({0x99e5fa0, 0xc001b7a378})
	/opt/hostedtoolcache/go/1.18.4/x64/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.18.4/x64/src/testing/testing.go:1392 +0x39f
panic({0x99e5fa0, 0xc001b7a378})
	/opt/hostedtoolcache/go/1.18.4/x64/src/runtime/panic.go:838 +0x207
github.com/hashicorp/terraform-provider-aws/internal/service/opensearch_test.TestAccOpenSearchDomain_AdvancedSecurityOptions_disabled(0xc000d00ea0)
	/home/runner/work/terraform-provider-aws/terraform-provider-aws/internal/service/opensearch/domain_test.go:798 +0x4a5
testing.tRunner(0xc000d00ea0, 0xa1b4c58)
	/opt/hostedtoolcache/go/1.18.4/x64/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.18.4/x64/src/testing/testing.go:1486 +0x35f
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/opensearch	0.744s
```

**Comment by ewbankkit** [comment]
```console
% grep ':28' internal/service/*/*_test.go
internal/service/elasticsearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/elasticsearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/elasticsearch/domain_test.go:	customEndpoint := fmt.Sprintf("%s.example.com", rName[:28])
internal/service/elasticsearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/elasticsearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/elasticsearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/elasticsearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/elasticsearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/elasticsearch/domain_test.go:				DomainName: aws.String(rName[:28]),
internal/service/elasticsearch/domain_test.go:						DomainName: aws.String(rName[:28]),
internal/service/elasticsearch/domain_test.go:					err = tfelasticsearch.WaitForDomainCreation(conn, rName[:28], 60*time.Minute)
internal/service/elasticsearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/elasticsearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/elasticsearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/elasticsearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/elasticsearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/elasticsearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/elasticsearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/elasticsearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/elasticsearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/elasticsearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/elasticsearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/elasticsearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/elasticsearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/elasticsearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/elasticsearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/elasticsearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/elasticsearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/elasticsearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/elasticsearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/elasticsearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/elasticsearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/elasticsearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/elasticsearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/elasticsearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/opensearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/opensearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/opensearch/domain_test.go:	customEndpoint := fmt.Sprintf("%s.example.com", rName[:28])
internal/service/opensearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/opensearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/opensearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/opensearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/opensearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/opensearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/opensearch/domain_test.go:				DomainName: aws.String(rName[:28]),
internal/service/opensearch/domain_test.go:						DomainName: aws.String(rName[:28]),
internal/service/opensearch/domain_test.go:					err = tfopensearch.WaitForDomainCreation(conn, rName[:28], 60*time.Minute)
internal/service/opensearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/opensearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/opensearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/opensearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/opensearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/opensearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/opensearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/opensearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/opensearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/opensearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/opensearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/opensearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/opensearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/opensearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/opensearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/opensearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/opensearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/opensearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/opensearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/opensearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/opensearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/opensearch/domain_test.go:				ImportStateId:     rName[:28],
internal/service/opensearch/domain_test.go:				ImportStateId:     rName[:28],
```
