### ISSUE TITLE
Error: The terraform-provider-aws_v4.25.0_x5.exe plugin crashed!

### ISSUE THREAD

**Issue by PatriQ1414** [hashicorp/terraform-provider-aws#26270]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

$ terraform -v

Terraform v1.2.7
on windows_386
+ provider registry.terraform.io/dome9/dome9 v1.28.0
+ provider registry.terraform.io/hashicorp/aws v4.25.0

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

provider "registry.terraform.io/dome9/dome9" {
  version = "1.28.0"
  hashes = [
    "h1:lFpCBIz16GIsOO3EfOQvbhpfQJf8Y0yM6Vn5Pp4WVoU=",
    "zh:0287e18f4e382bbc0ce7c3eaefd787ea2e839ffadb37d1f14672167bbaf3355b",
    "zh:1261c38fffcbe6a9284fd7ca811e60aa340d0b30253232e087020cc01b528e41",
    "zh:194ddc7eaafd74f4f0a66b324f637eb0f21c8af30acda28779f97b06641e2e80",
    "zh:1aac935efb033e059410b3185be2228af9c07c86228b12d7a8d9a57efab88360",
    "zh:2289dd06781e89d3067d056953bf611a788104da720da47b012119344e120b3c",
    "zh:23d5430ee4027553ab4486d534d9606e4e854162e3ea63d3b34c7d5dbc32b0c2",
    "zh:2e9bc1d85656cf3794bedc9c9219442ac40e30547968e2f5203b7ef4c9d4d826",
    "zh:334eb5d7f5490e473171a8565a47184a85f74c9900e43386a808963185cfe833",
    "zh:5e00b41ffde33cf6f97f48c5d2e8c63fabd88452325cd416b801c03342ee7a83",
    "zh:63bd2526d0e2fca6f2e8dc998b09822f0bcf14702d9b63407bc3b0217e1f7e74",
    "zh:693d8f247e25d15f6f38ede3c86dee51d9e3feed765de49cd3b93aebb0dd13cc",
    "zh:99ff169c8f6930bfc9bea15c462b3aacfeb6f8ee5fa4008a9ba3397005a8e385",
    "zh:df2b2b385fb9408f78e169a71f913916650ed1ff79ce8792219154f6424b47a5",
    "zh:ed1a3d37f0001bd80ca58e829b411d9dc4e1ed1249a9a7ac4798384ae70a41bb",
  ]
}

provider "registry.terraform.io/hashicorp/aws" {
  version     = "4.25.0"
  constraints = "~> 4.0"
  hashes = [
    "h1:ZGVigtjpzrhuGGv9amWjhnjm0wYun08VDo5J5wWcO1A=",
    "zh:51fddc33f289108f60c2de78537f758ae913b2614187abfc3f560f9dd277bc1a",
    "zh:5a2bfa0725a8941f12e775eb9c44582ec237a664321a740d8283e9b56452f2ad",
    "zh:6ca73a9f11c2a9ff8f55433c00a12c1b69c22131251cb0698d32c682229b1233",
    "zh:9b12af85486a96aedd8d7984b0ff811a4b42e3d88dad1a3fb4c0b580d04fa425",
    "zh:aeafec22947a7be418adc3c6d1eddb719ed02b5e41b6e2cc9cbdca991e2140b8",
    "zh:b043563789e32f6935bf51c3b4344482487c03cb084673f6181ce3443f956a3d",
    "zh:b0693f4295d35ae6ce3656ee2294fd69eb732f601ba7d6eb28b7fded4471c3d2",
    "zh:bccb9ec142aa11350a52142b71fd8f0332d36a94332207f45bd93ceb7297b922",
    "zh:c353fd5060cf6d86e4505d0ade84a37f91d4d8774b17eaa1290a191d9da43729",
    "zh:d07848da6940b2882b884fc24144741f7ce0442865c9833df26751c48429e11f",
    "zh:d4feeb5c394ec9528d1633e2e2c133632d8d099f6c99654e2bbd2aa112b6a08e",
    "zh:fb0a75edb943847354c759a665edb93fd7945b892be7d0511c6708785abf090c",
  ]
}

### Debug Output

│ Error: Request cancelled
│
│   with aws_vpn_gateway_route_propagation.vpn_client2["1"],
│   on vpn.tf line 13, in resource "aws_vpn_gateway_route_propagation" "vpn_client2":
│   13: resource "aws_vpn_gateway_route_propagation" "vpn_client2" {
│
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│   with aws_vpn_gateway_route_propagation.vpn_client2["0"],
│   on vpn.tf line 13, in resource "aws_vpn_gateway_route_propagation" "vpn_client2":
│   13: resource "aws_vpn_gateway_route_propagation" "vpn_client2" {
│
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

Stack trace from the terraform-provider-aws_v4.25.0_x5.exe plugin:

panic: Error reading level state: strconv.ParseInt: parsing "2554619904": value out of range

goroutine 10661 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0x217774a0, {0x23a795a8, 0x1, 0x1}, 0x8)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/resource_data.go:553 +0x279
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).State(0x217774a0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/resource_data.go:351 +0x3a5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ShimInstanceStateFromValue(0x21025f80, {{{0x99a7760, 0x23a78480}}, {0x75b0f00, 0x219806c0}})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/resource.go:599 +0x1d9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x2154cc40, {0x99a7120, 0x212ced98}, 0x21823e40)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/grpc_provider.go:587 +0x23f
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadResource({0x2156e6a0, 0x2156e6e0, {0x21dafba0, 0x2, 0x2}, 0x2156e6c0, 0x2154cdc0, 0x21a2ad70, 0x2156e700}, {0x99a7120, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.7.0/tf5muxserver/mux_server_ReadResource.go:26 +0x145
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x204c00a0, {0x99a7120, 0x212ce0c0}, 0x21584180)
        github.com/hashicorp/terraform-plugin-go@v0.13.0/tfprotov5/tf5server/server.go:747 +0x44d
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x8a870e0, 0x204c00a0}, {0x99a7120, 0x212ce0c0}, 0x2047f300, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.13.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x18a
google.golang.org/grpc.(*Server).processUnaryRPC(0x204c7e60, {0x99a9cf0, 0x20b22240}, 0x22891220, 0x21dbe120, 0xea9df68, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1295 +0xaab
google.golang.org/grpc.(*Server).handleStream(0x204c7e60, {0x99a9cf0, 0x20b22240}, 0x22891220, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1636 +0xa17
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.48.0/server.go:932 +0xb1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.48.0/server.go:930 +0x25f

Error: The terraform-provider-aws_v4.25.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Panic Output

panic: Error reading level state: strconv.ParseInt: parsing "2554619904": value out of range

### Expected Behavior

Run terraform plan successfully 

### Actual Behavior

Produces the error above 

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by PatriQ1414** [comment]
Hi, Any direction with this?

**Comment by PatriQ1414** [comment]
I was able to resolve this issue by replacing my terraform.exe file from 386 to Amd64.
Terraform init
Terraform plan
Hope this helps someone.
