### ISSUE TITLE
[Bug]: CI job "PullRequestComments" throws a Javascript exception "ERR_REQUIRE_ESM"

### ISSUE THREAD

**Issue by christophetd** [hashicorp/terraform-provider-aws#27089]
The CI job [`PullRequestComments`](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/workflows/pull_requests.yml) seems to currently fail on all PRs with the message:

```

internal/modules/cjs/loader.js:1216
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /node_modules/@octokit/graphql/index.js
require() of ES modules is not supported.
require() of /node_modules/@octokit/graphql/index.js from /node_modules/@actions/github/lib/github.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /node_modules/@octokit/graphql/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1216:13)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/node_modules/@actions/github/lib/github.js:14:19)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14) {
  code: 'ERR_REQUIRE_ESM'
}
```

Examples:
https://github.com/hashicorp/terraform-provider-aws/actions/runs/3182346480/jobs/5188171522#logs

https://github.com/hashicorp/terraform-provider-aws/actions/runs/3177802901/jobs/5178645273

**Comment by jar-b** [comment]
Hi @christophetd - thanks for reporting. This is being tracked in the upstream action repo here: https://github.com/actions/first-interaction/issues/101. There is an open PR that fixes the issue (not yet merged, disabling via #27037 is a fallback if necessary), but for now we're ignoring this check in PR reviews, so it shouldn't prevent changes from going in.

I'm going to close this issue to focus conversation in the issue/PR above.
