### ISSUE TITLE
[Repo]: Error in Pull Request Comments Job in GitHub Actions CI for New Contributors

### ISSUE THREAD

**Issue by AhmedGrati** [hashicorp/terraform-provider-aws#27209]
### Description

For the first contributors, when they open a pull request, the job `PullRequestComments` fails in the action `actions/first-interaction@v1`.
Here are the logs of the error:
```
internal/modules/cjs/loader.js:1216
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /node_modules/@octokit/graphql/index.js
require() of ES modules is not supported.
require() of /node_modules/@octokit/graphql/index.js from /node_modules/@actions/github/lib/github.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /node_modules/@octokit/graphql/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:12[16](https://github.com/hashicorp/terraform-provider-aws/actions/runs/3170021436/jobs/5162326582#step:3:17):13)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:[18](https://github.com/hashicorp/terraform-provider-aws/actions/runs/3170021436/jobs/5162326582#step:3:19))
    at Object.<anonymous> (/node_modules/@actions/github/lib/github.js:14:[19](https://github.com/hashicorp/terraform-provider-aws/actions/runs/3170021436/jobs/5162326582#step:3:20))
    at Module._compile (internal/modules/cjs/loader.js:1[20](https://github.com/hashicorp/terraform-provider-aws/actions/runs/3170021436/jobs/5162326582#step:3:21)0:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1[22](https://github.com/hashicorp/terraform-provider-aws/actions/runs/3170021436/jobs/5162326582#step:3:23)0:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14) {
  code: 'ERR_REQUIRE_ESM'
}
```

### References

Example of the pull request that raises the error: [https://github.com/hashicorp/terraform-provider-aws/pull/27057](https://github.com/hashicorp/terraform-provider-aws/pull/27057)

### Would you like to implement a fix?

Yes

**Comment by breathingdust** [comment]
Closed by #27210
