### ISSUE TITLE
[Bug]: aws_instance panic/crash with null capacity_reservation_specification

### ISSUE THREAD

**Issue by ryan-cpi** [hashicorp/terraform-provider-aws#27330]
### Terraform Core Version

1.2.4

### AWS Provider Version

4.33.0

### Affected Resource(s)

In `aws_instance` setting this

```
capacity_reservation_specification {
    capacity_reservation_preference = null
}
```
Causes terraform to panic

(I know i can avoid this with dynamic blocks)

### Expected Behavior

To be handled with the normal error handing not crashing and burning with an unhelpful traceback

### Actual Behavior

Plug in fails to respond causing a panic 

### Relevant Error/Panic Output Snippet

```shell
Error: Plugin did not respond

  with module.test_instance1.aws_instance.instance,
  on .terraform/modules/test_instance1/ec2/ec2.tf line 1, in resource "aws_instance" "instance":
   1: resource "aws_instance" "instance" {

The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
more details.

Stack trace from the terraform-provider-aws_v4.33.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 355 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.expandCapacityReservationSpecification(0xc0026e4c60)
	github.com/hashicorp/terraform-provider-aws/internal/service/ec2/ec2_instance.go:2995 +0x2fa
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.resourceInstanceUpdate(0xc0032f9400, {0x8eafb40?, 0xc00114f500})
	github.com/hashicorp/terraform-provider-aws/internal/service/ec2/ec2_instance.go:1797 +0x5945
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xafdc420?, {0xafdc420?, 0xc0026a3650?}, 0xd?, {0x8eafb40?, 0xc00114f500?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource.go:729 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000d9fb20, {0xafdc420, 0xc0026a3650}, 0xc0019fbba0, 0xc0032f8e80, {0x8eafb40, 0xc00114f500})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource.go:847 +0x82c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000d368, {0xafdc420?, 0xc0026a3530?}, 0xc0029e9d10)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc0019ab0e0, 0xc0019ab6b0, {0xc001afce60, 0x2, 0x2}, 0xc0019ab500, 0xc00107d130, 0xc002eb04f0, 0xc0019ab770}, {0xafdc420, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.7.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0x142
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc001510140, {0xafdc420?, 0xc0026a20c0?}, 0xc0019312d0)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x9f4cc80?, 0xc001510140}, {0xafdc420, 0xc0026a20c0}, 0xc001931260, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000001e0, {0xafe1cc0, 0xc002ead860}, 0xc0030770e0, 0xc001ac12f0, 0x107451c0, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc0000001e0, {0xafe1cc0, 0xc002ead860}, 0xc0030770e0, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-aws_v4.33.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Configuration Files

n/a

### Steps to Reproduce

Set null values in `capacity_reservation_specification`

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/61768353b052fba586e90a04c08c79b0073607bc/internal/service/ec2/ec2_instance.go#L2983-L2999
