### ISSUE TITLE
[Bug]: Provider crashes when provisioning or importing IPAM CIDRs

### ISSUE THREAD

**Issue by iwt-pjost** [hashicorp/terraform-provider-aws#27424]
### Terraform Core Version

1.3.3

### AWS Provider Version

4.35.0

### Affected Resource(s)

aws_vpc_ipam_pool_cidr

### Expected Behavior

I expected the pool to be created without errors

```
  + resource "aws_vpc_ipam_pool_cidr" "foo" {
      + cidr         = "10.10.10.10/10"
      + id           = (known after apply)
      + ipam_pool_id = "ipam-pool-bar"
    }

```

And here I expected the pool to be imported if it exists

`terraform import "aws_vpc_ipam_pool_cidr.foo[\"10.10.10/10\"]" "10.10.10./10_ipam-pool-bar"
`

### Actual Behavior

Output when creating the resource

```
Error: Plugin did not respond
│ 
│   with aws_vpc_ipam_pool_cidr.level_1["10.10.10./10"],
│   on main.tf line 83, in resource "aws_vpc_ipam_pool_cidr" "foo":
│   83: resource "aws_vpc_ipam_pool_cidr" "fo" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The
│ plugin logs may contain more details.
╵

╷
│ Error: Error provisioning CIDR in IPAM pool (ipam-pool-bar): IncorrectState: The specified action is not valid for ipam-pool-bar. The CIDR 10.10.10./10 is in an invalid state.
│ 	status code: 400, request id: 95fe7534-0r0r-4c4c-9d9d-ccea1c1fd5d1
│ 
│   with aws_vpc_ipam_pool_cidr.foo["10.10.10./10"],
│   on main.tf line 83, in resource "aws_vpc_ipam_pool_cidr" "foo":
│   83: resource "aws_vpc_ipam_pool_cidr" "foo" {
│ 


```

On the good news, Terraform actually created the pool. Everything is fine and as desired. When checking the pool I get a
```
{
  "IpamPoolCidrs": [
{
      "Cidr": "10.10.10./10",
      "State": "provisioned",
      "FailureReason": null
    },

```
so I thought I could just import the existing resource but when I try to import it I get the message:
```

│ Error: Cannot import non-existent remote object
│ 
│ While attempting to import an existing object to "aws_vpc_ipam_pool_cidr.foo[\"10.10.10./10\"]", the provider detected that no object exists with the given id. Only pre-existing objects can be imported; check that the
│ id is correct and that it is associated with the provider's configured region or endpoint, or use "terraform apply" to create a new remote object for this resource.
╵

```

So now I am stuck and will probably have to edit the state json directly so that TF can continue working 

### Relevant Error/Panic Output Snippet

```shell
Stack trace from the terraform-provider-aws_v4.35.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x66b670a]

goroutine 3500 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.statusIPAMPoolCIDRStatus.func1()
	github.com/hashicorp/terraform-provider-aws/internal/service/ec2/ipam_pool_cidr.go:253 +0x2a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext.func1()
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/resource/state.go:110 +0x207
created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/resource/state.go:83 +0x1d8

Error: The terraform-provider-aws_v4.35.0_x5 plugin crashed!
```

### Terraform Configuration Files

resource "aws_vpc_ipam_pool_cidr" "foo" {
  cidr = "10.10.10./10"
  ipam_pool_id  = ipam-pool-bar
}

### Steps to Reproduce

1. Have a pre-existing IPAM pool with already provisioned CIDRs
2. Try to provision additional CIDRs to the pool using `terraform apply`.

Other option

1. Provision a CIDR in a pool
2. Import it using the import command `terraform import "aws_vpc_ipam_pool_cidr.foo[\"10.10.10./10\"]" 10.10.10./10_ipam-pool-bar`

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/d3e0b7e79b4dc21e09e8c40fce902ce9e2b8e83b/internal/service/ec2/ipam_pool_cidr.go#L243-L255

**Comment by iwt-pjost** [comment]
Update: 
I just thought that, if we have to wait for a fix, I can just manipulate the state and add the existing resources into the terraform.tfstate file manually. Not the nicest way but in the end it's just a json
So I change the state to a local version so that I don't accidentally break the live state of our code and add it to the state. But even with the resource in the state, Terraform still tries to create the resource.
Is this a pagination issue? Is the pool (99 CIDRs) too big for Terraform because it tries to paginate through the pools and stops at page xxx? 

Right now the current state of things is:
- I can't create the pools because they already exist and the plugin just keeps crashing,
- I can't import it using `terraform import`, because TF will tell me the resource does not exist
- I can't edit the state manually because TF will still try to create the resource even it is in the state file

Feeling kinda stuck here

**Comment by ewbankkit** [comment]
@iwt-pjost I think you are correct in your hypothesis that it's a pagination issue. https://github.com/hashicorp/terraform-provider-aws/pull/27051 introduced pagination for the `aws_vpc_ipam_pool_cidrs` data source and we need to use that functionality for the `aws_vpc_ipam_pool_cidr` resource.

We are aiming to get this fixed for today's Terraform AWS Provider release.
