### ISSUE TITLE
[Bug]: The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.

### ISSUE THREAD

**Issue by com-tr-sitzman-lyle** [hashicorp/terraform-provider-aws#27562]
### Terraform Core Version

1.2.7

### AWS Provider Version

4.36.0

### Affected Resource(s)

aws_iam_role_policy

### Expected Behavior

Expect resource to be created

### Actual Behavior

│ Error: Request cancelled
│ 
│   with module.environment.module.service["gilgamesh"].module.role.aws_iam_role_policy.object,
│   on ../role/main.tf line 31, in resource "aws_iam_role_policy" "object":
│   31: resource "aws_iam_role_policy" "object" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.

### Relevant Error/Panic Output Snippet

```shell
Stack trace from the terraform-provider-aws_v4.36.0_x5 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 6068 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/elasticache.resourceReplicationGroupRead(0xc003410b00, {0x8ec55a0?, 0xc001604000?})
    github.com/hashicorp/terraform-provider-aws/internal/service/elasticache/replication_group.go:673 +0x1cf0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xb222a40?, {0xb222a40?, 0xc0025899b0?}, 0xd?, {0x8ec55a0?, 0xc001604000?})
    github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000e91420, {0xb222a40, 0xc0025899b0}, 0xc003d47c70, {0x8ec55a0, 0xc001604000})
    github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0001a3890, {0xb222a40?, 0xc002588d50?}, 0xc004863a00)
    github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:613 +0x497
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadResource({0xc00259ec90, 0xc00259ecf0, {0xc0022edfe0, 0x2, 0x2}, 0xc00259ecc0, 0xc000d13220, 0xc003759b50, 0xc00259ed20}, {0xb222a40, ...}, ...)
    github.com/hashicorp/terraform-plugin-mux@v0.7.0/tf5muxserver/mux_server_ReadResource.go:26 +0x142
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc001fec320, {0xb222a40?, 0xc0024944e0?}, 0xc003573da0)
    github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:748 +0x49e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xa147780?, 0xc001fec320}, {0xb222a40, 0xc0024944e0}, 0xc00122cd20, 0x0)
    github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002ca000, {0xb228880, 0xc003a7a340}, 0xc003e58d80, 0xc002131320, 0x10a2d030, 0x0)
    google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc0002ca000, {0xb228880, 0xc003a7a340}, 0xc003e58d80, 0x0)
    google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
    google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
    google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-aws_v4.36.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Configuration Files

It is difficult to try to reproduce this issue on a consistent basis which prevents us from narrowing down the specific configurations to recreate the issue.

If the panic is not enough to solve this, please close.

### Steps to Reproduce

This appears to be an arbitrary error that only occurs sometimes when running terraform.

**Comment by camlow325** [comment]
We encountered this same issue with the AWS `4.62.0` provider. Here is the stack trace we saw:

```
Stack trace from the terraform-provider-aws_v4.62.0_x5 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 344 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/elasticache.resourceReplicationGroupRead({0xe8fd3a0, 0xc0050f3e60}, 0xc004e9aa00, {0xd472920?, 0xc0003f0c00?})
	github.com/hashicorp/terraform-provider-aws/internal/service/elasticache/replication_group.go:677 +0x2827
github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0x0?, {0xd472920?, 0xc0003f0c00?})
	github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:94 +0x175
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xe8fd3a0?, {0xe8fd3a0?, 0xc0050f25d0?}, 0xd?, {0xd472920?, 0xc0003f0c00?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:719 +0x87
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000f4dea0, {0xe8fd3a0, 0xc0050f25d0}, 0xc005210000, {0xd472920, 0xc0003f0c00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc001c5e750, {0xe8fd3a0?, 0xc0050f24b0?}, 0xc004d5b900)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadResource({0xc002bd3320, 0xc002bd37a0, {0xc004d4f980, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.9.0/tf5muxserver/mux_server_ReadResource.go:26 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc002507d60, {0xe8fd3a0?, 0xc0050bf7a0?}, 0xc004e982a0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xd170720?, 0xc002507d60}, {0xe8fd3a0, 0xc0050bf7a0}, 0xc004e940e0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0044d9a40, {0xe90cc60, 0xc0005b21a0}, 0xc005083e60, 0xc004e614a0, 0x1521d770, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0044d9a40, {0xe90cc60, 0xc0005b21a0}, 0xc005083e60, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-aws_v4.62.0_x5 plugin crashed!
```

This appears to be failing [here](https://github.com/hashicorp/terraform-provider-aws/blob/v4.62.0/internal/service/elasticache/replication_group.go#L677):

```go
d.Set("replicas_per_node_group", len(rgp.NodeGroups[0].NodeGroupMembers)-1)
```

This error happened during a Terraform run which created an ElastiCache replication group. On runs where we haven't seen the failure, the response from an AWS `DescribeReplicationGroups` API call in the Terraform debug log included this:

```json
<NodeGroups>
  <NodeGroup>
    <NodeGroupMembers>
...
```

In the Terraform debug log for the apply where this crash occurred, though, there was no `<NodeGroups>` section, with `<Status>creating</Status>` in the response for the final request to AWS. Maybe AWS can omit the `<NodeGroups>` section if none of the nodes have been created yet?

The failure line still appears to exist in the latest code [here](https://github.com/hashicorp/terraform-provider-aws/blob/8bb31cfc1827facb9e4ad81414d599f682563f35/internal/service/elasticache/replication_group.go#L593). Further down in the `resourceReplicationGroupRead` function [here](https://github.com/hashicorp/terraform-provider-aws/blob/8bb31cfc1827facb9e4ad81414d599f682563f35/internal/service/elasticache/replication_group.go#L623-L626), there is some code which waits for the replication group to be "available" before attempting to derive additional data for the replication group. Maybe something similar could be done to defer populating node group info into the local resource info before it can be extracted from the AWS API?

**Comment by abustany** [comment]
Happens with `terraform-provider-aws_v5.42.0_x5` too
