### ISSUE TITLE
[Bug]: Unable to create Google Analytics connection profile

### ISSUE THREAD

**Issue by yzouyang** [hashicorp/terraform-provider-aws#27676]
### Terraform Core Version

1.2.9

### AWS Provider Version

4.23.0

### Affected Resource(s)

* aws_appflow_connector_profile

### Expected Behavior

A Google Analytics connection should had been created

### Actual Behavior

The AWS plugin crashed

### Relevant Error/Panic Output Snippet

```shell
Terraform v1.2.9
on linux_amd64
{"@level":"info","@message":"Terraform 1.2.9","@module":"terraform.ui","@timestamp":"2022-11-07T09:30:13.305249Z","terraform":"1.2.9","type":"version","ui":"1.0"}
{"@level":"info","@message":"aws_appflow_connector_profile.ga_connection: Plan to create","@module":"terraform.ui","@timestamp":"2022-11-07T09:30:14.708898Z","change":{"resource":{"addr":"aws_appflow_connector_profile.ga_connection","module":"","resource":"aws_appflow_connector_profile.ga_connection","implied_provider":"aws","resource_type":"aws_appflow_connector_profile","resource_name":"ga_connection","resource_key":null},"action":"create"},"type":"planned_change"}
{"@level":"info","@message":"aws_appflow_connector_profile.ga_connection: Creating...","@module":"terraform.ui","@timestamp":"2022-11-07T09:30:17.555856Z","hook":{"resource":{"addr":"aws_appflow_connector_profile.ga_connection","module":"","resource":"aws_appflow_connector_profile.ga_connection","implied_provider":"aws","resource_type":"aws_appflow_connector_profile","resource_name":"ga_connection","resource_key":null},"action":"create"},"type":"apply_start"}
{"@level":"info","@message":"aws_appflow_connector_profile.ga_connection: Creation errored after 0s","@module":"terraform.ui","@timestamp":"2022-11-07T09:30:17.571500Z","hook":{"resource":{"addr":"aws_appflow_connector_profile.ga_connection","module":"","resource":"aws_appflow_connector_profile.ga_connection","implied_provider":"aws","resource_type":"aws_appflow_connector_profile","resource_name":"ga_connection","resource_key":null},"action":"create","elapsed_seconds":0},"type":"apply_errored"}
{"@level":"error","@message":"Error: Plugin did not respond","@module":"terraform.ui","@timestamp":"2022-11-07T09:30:17.572190Z","diagnostic":{"severity":"error","summary":"Plugin did not respond","detail":"The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.","address":"aws_appflow_connector_profile.ga_connection","range":{"filename":"appflow.tf","start":{"line":13,"column":58,"byte":516},"end":{"line":13,"column":59,"byte":517}},"snippet":{"context":"resource \"aws_appflow_connector_profile\" \"ga_connection\"","code":"resource \"aws_appflow_connector_profile\" \"ga_connection\" {","start_line":13,"highlight_start_offset":57,"highlight_end_offset":58,"values":[]}},"type":"diagnostic"}

Stack trace from the terraform-provider-aws_v4.23.0_x5 plugin:

panic: interface conversion: interface {} is nil, not *appflow.GoogleAnalyticsConnectorProfileProperties

goroutine 366 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/appflow.expandConnectorProfileProperties(0x81a3fa0)
	github.com/hashicorp/terraform-provider-aws/internal/service/appflow/connector_profile.go:1924 +0x147d
github.com/hashicorp/terraform-provider-aws/internal/service/appflow.expandConnectorProfileConfig(0x0)
	github.com/hashicorp/terraform-provider-aws/internal/service/appflow/connector_profile.go:1505 +0xf8
github.com/hashicorp/terraform-provider-aws/internal/service/appflow.resourceConnectorProfileCreate({0xab8eae0, 0xc0024b4ba0}, 0x0, {0x84c7d60, 0xc0017b8a80})
	github.com/hashicorp/terraform-provider-aws/internal/service/appflow/connector_profile.go:1402 +0x191
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xab8eae0, {0xab8eae0, 0xc0024b4ba0}, 0xd, {0x84c7d60, 0xc0017b8a80})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.19.0/helper/schema/resource.go:702 +0x84
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00061b340, {0xab8eae0, 0xc0024b4ba0}, 0xc002f72ea0, 0xc002f0ba00, {0x84c7d60, 0xc0017b8a80})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.19.0/helper/schema/resource.go:837 +0xc29
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000ced0, {0xab8eae0, 0xc0024b47e0}, 0xc002ec3b80)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.19.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc001e639e0, 0xc001e63a40, {0xc001d693e0, 0x2, 0x2}, 0xc001e63a10, 0xc000df4540, 0xc000da0e80, 0xc001e63a70}, {0xab8eae0, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.7.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0x142
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000820d20, {0xab8eae0, 0xc0024b0ea0}, 0xc002eb4ee0)
	github.com/hashicorp/terraform-plugin-go@v0.12.0/tfprotov5/tf5server/server.go:813 +0x551
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x971ff00, 0xc000820d20}, {0xab8eae0, 0xc0024b0ea0}, 0xc002eb4e70, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.12.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc002aa4e00, {0xaca0a30, 0xc001b83520}, 0xc002f68000, 0xc002098b40, 0x10b7e3c0, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1295 +0xb03
google.golang.org/grpc.(*Server).handleStream(0xc002aa4e00, {0xaca0a30, 0xc001b83520}, 0xc002f68000, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1636 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.48.0/server.go:930 +0x294

Error: The terraform-provider-aws_v4.23.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Operation failed: failed running terraform apply (exit 1)
```

### Terraform Configuration Files

terraform {
  required_version = "~> 1.2.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.23.0"
    }
  }
}

provider "aws" {}

resource "aws_appflow_connector_profile" "ga_connection" {
  connection_mode = "Private"
  connector_type  = "Googleanalytics"
  name            = "ga-connection"
  connector_profile_config {
    connector_profile_credentials {
      google_analytics {
        client_id     = "some value"
        client_secret = "some value"
      }
    }
    connector_profile_properties {
      google_analytics {
      }
    }
  }
}

### Steps to Reproduce

Run the attached Terraform script, substituting for client_id and client_secret

### Panic Output

panic: interface conversion: interface {} is nil, not *appflow.GoogleAnalyticsConnectorProfileProperties

### Important Factoids

GA require OAuth 2.0 verification, could this be a factor?  If so, is it something that's feasible to resolve?

**Comment by ewbankkit** [comment]
Fixed in https://github.com/hashicorp/terraform-provider-aws/pull/33856.
