### ISSUE TITLE
[Bug]: aws_appmesh_virtual_router panics and crashes if listener is edited outside of terraform

### ISSUE THREAD

**Issue by nwsparks** [hashicorp/terraform-provider-aws#27724]
### Terraform Core Version

1.3.4

### AWS Provider Version

4.38.0

### Affected Resource(s)

aws_appmesh_virtual_router 

### Expected Behavior

It should bring the resource back in line with the expected configuration

### Actual Behavior

It crashes 

### Relevant Error/Panic Output Snippet

```shell
<dozens more of these grpc errors on different resources>
╷
│ Error: Plugin did not respond
│
│   with module.cert.aws_acm_certificate.cert,
│   on ../../../iqies-devops/terraform/modules/acm/acm-cert/main.tf line 1, in resource "aws_acm_certificate" "cert":
│    1: resource "aws_acm_certificate" "cert" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵

Stack trace from the terraform-provider-aws_v4.38.0_x5 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 1306 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/appmesh.flattenVirtualRouterSpec(0xc004a32dc8)
        github.com/hashicorp/terraform-provider-aws/internal/service/appmesh/flex.go:1728 +0x310
github.com/hashicorp/terraform-provider-aws/internal/service/appmesh.resourceVirtualRouterRead(0xc004b4a780, {0x9b226e0?, 0xc0007a4a80?})
        github.com/hashicorp/terraform-provider-aws/internal/service/appmesh/virtual_router.go:222 +0x8fc
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xbeb0b00?, {0xbeb0b00?, 0xc0021d43c0?}, 0xd?, {0x9b226e0?, 0xc0007a4a80?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000b4ab60, {0xbeb0b00, 0xc0021d43c0}, 0xc00512fee0, {0x9b226e0, 0xc0007a4a80})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0001bd7b8, {0xbeb0b00?, 0xc002172db0?}, 0xc002e7a780)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadResource({0xc00263e420, 0xc00263e480, {0xc003aa0980, 0x2, 0x2}, 0xc00263e450, 0xc0026526d0, 0xc0035a3d50, 0xc00263e4b0}, {0xbeb0b00, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.7.0/tf5muxserver/mux_server_ReadResource.go:26 +0x142
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc001ba0140, {0xbeb0b00?, 0xc001fa18f0?}, 0xc0036675c0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:748 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xac02a60?, 0xc001ba0140}, {0xbeb0b00, 0xc001fa18f0}, 0xc005142f50, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc003b9e000, {0xbeb8580, 0xc003c28000}, 0xc00337ab40, 0xc003ba0540, 0x119a9610, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1295 +0xb2b
google.golang.org/grpc.(*Server).handleStream(0xc003b9e000, {0xbeb8580, 0xc003c28000}, 0xc00337ab40, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1636 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-aws_v4.38.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Configuration Files

```terraform
resource "aws_appmesh_mesh" "mesh" {
  name = "mesh"

  spec {
    egress_filter {
      type = "ALLOW_ALL"
    }
  }
}

resource "aws_appmesh_virtual_router" "router" {
  name      = "-router"
  mesh_name = aws_appmesh_mesh.mesh.id

  spec {
    listener {
      port_mapping {
        port     = 8080
        protocol = "http"
      }
    }
  }
}
```

### Steps to Reproduce

create a app mesh router via tf

go into the aws console and remove the listener

run terraform plan

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/3cf15a22d8e393d5e7439c2f4d2cb75ed92d6ceb/internal/service/appmesh/flex.go#L1723-L1743

**Comment by ewbankkit** [comment]
Fixed in https://github.com/hashicorp/terraform-provider-aws/pull/27799.
