### ISSUE TITLE
[Bug]: segfault of provider

### ISSUE THREAD

**Issue by flypenguin** [hashicorp/terraform-provider-aws#27749]
### Terraform Core Version

1.2.8

### AWS Provider Version

4.38.0

### Affected Resource(s)

* probably EC2 customer gateway

### Expected Behavior

- a bunch of stuff should have been destroyed.

### Actual Behavior

- it was endlessly waiting on the destruction of an internet gateway
- following [this stackoverflow post](https://stackoverflow.com/a/45031134), i manually deleted some hosts _while_ terraform was running
- suddenly it continued, but then segfaulted.

### Relevant Error/Panic Output Snippet

```shell
Stack trace from the terraform-provider-aws_v4.38.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x7c4e29e]

goroutine 2416 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.resourceInstanceUpdate(0xc0035c6b80, {0xa722960?, 0xc000f78a80})
	github.com/hashicorp/terraform-provider-aws/internal/service/ec2/ec2_instance.go:1486 +0x685e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xcab0d60?, {0xcab0d60?, 0xc002967950?}, 0xd?, {0xa722960?, 0xc000f78a80?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:729 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000eb21c0, {0xcab0d60, 0xc002967950}, 0xc0029b15f0, 0xc0035c6880, {0xa722960, 0xc000f78a80})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:847 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000210090, {0xcab0d60?, 0xc0029677a0?}, 0xc00322b720)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc002760750, 0xc0027607b0, {0xc001c9d340, 0x2, 0x2}, 0xc002760780, 0xc001c256f0, 0xc003a42910, 0xc0027607e0}, {0xcab0d60, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.7.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0x142
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc003aa4140, {0xcab0d60?, 0xc002966810?}, 0xc000a50150)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xb8034a0?, 0xc003aa4140}, {0xcab0d60, 0xc002966810}, 0xc000a500e0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003523c0, {0xcab8860, 0xc00276e820}, 0xc0000d8c60, 0xc0012ed140, 0x125ae820, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1295 +0xb2b
google.golang.org/grpc.(*Server).handleStream(0xc0003523c0, {0xcab8860, 0xc00276e820}, 0xc0000d8c60, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1636 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-aws_v4.38.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Configuration Files

too many

### Steps to Reproduce

too many.

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/3cf15a22d8e393d5e7439c2f4d2cb75ed92d6ceb/internal/service/ec2/ec2_instance.go#L1485-L1489

whereas above

https://github.com/hashicorp/terraform-provider-aws/blob/3cf15a22d8e393d5e7439c2f4d2cb75ed92d6ceb/internal/service/ec2/ec2_instance.go#L1441-L1444
