### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ptdel** [hashicorp/terraform-provider-aws#27827]
### Terraform Core Version

1.3.4

### AWS Provider Version

4.39.0_x5

### Affected Resource(s)

`aws_kms_key`

### Expected Behavior

a new KMS Key should have been provisioned

### Actual Behavior

```
 Error: Plugin did not respond
│ 
│   with module.kms_key.aws_kms_key.this[0],
│   on .terraform/modules/kms_key/main.tf line 8, in resource "aws_kms_key" "this":
│    8: resource "aws_kms_key" "this" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
```

### Relevant Error/Panic Output Snippet

```shell
Stack trace from the terraform-provider-aws_v4.39.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x74ed33a]

goroutine 361 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/kms.resourceKeyRead(0xc003921380, {0x9bbf240?, 0xc0011ba000?})
        github.com/hashicorp/terraform-provider-aws/internal/service/kms/key.go:201 +0x2da
github.com/hashicorp/terraform-provider-aws/internal/service/kms.resourceKeyCreate(0xc003921380, {0x9bbf240?, 0xc0011ba000})
        github.com/hashicorp/terraform-provider-aws/internal/service/kms/key.go:180 +0xdf2
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xbf71660?, {0xbf71660?, 0xc0034446f0?}, 0xd?, {0x9bbf240?, 0xc0011ba000?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00158ad20, {0xbf71660, 0xc0034446f0}, 0xc005870d00, 0xc003921080, {0x9bbf240, 0xc0011ba000})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0000113c8, {0xbf71660?, 0xc0034445d0?}, 0xc0021fd220)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc003118870, 0xc0031188d0, {0xc004581ea0, 0x2, 0x2}, 0xc0031188a0, 0xc003134490, 0xc0041d2730, 0xc003118900}, {0xbf71660, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.7.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0x142
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc001d42e60, {0xbf71660?, 0xc003400c90?}, 0xc000a482a0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xacaaea0?, 0xc001d42e60}, {0xbf71660, 0xc003400c90}, 0xc000a48230, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc003fab4a0, {0xbf7b860, 0xc004706680}, 0xc000173320, 0xc0046b9560, 0x11ab8720, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1295 +0xb2b
google.golang.org/grpc.(*Server).handleStream(0xc003fab4a0, {0xbf7b860, 0xc004706680}, 0xc000173320, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1636 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-aws_v4.39.0_x5 plugin crashed!
```
```


### Terraform Configuration Files

```
module "kms_key" {
  source = "terraform-aws-modules/kms/aws"

  description         = var.kms_description
  key_usage           = var.kms_key_usage
  is_enabled          = var.kms_key_is_enabled
  enable_key_rotation = var.kms_enable_key_rotation
  multi_region        = var.kms_multi_region

  # Roles / Policies
  enable_default_policy = var.kms_enable_default_policy
  key_users             = var.kms_iam_user_roles
  key_service_users     = [module.kms_key_iam_role.iam_role_arn]

  # Aliases
  aliases                 = var.kms_aliases
  aliases_use_name_prefix = var.kms_aliases_use_name_prefix

  tags = {
    Terraform   = "true"
    Environment = "${var.environment}"
  }
}
```

### Steps to Reproduce

```
terraform init
terraform apply
```

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

the panic occurs in two scenarios:
* if I am deploying into an AWS account
* if I am testing locally with `tflocal` and `localstack`

### References

_No response_

### Would you like to implement a fix?

_No response_

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/fbcd3ac85fcb598b217aca7118f278a1cc96fe63/internal/service/kms/key.go#L200

**Comment by kenlefeb** [comment]
Taking a clue from @ewbankkit's comment, I changed my key to `multi_region = false` and this error went away.
