### ISSUE TITLE
[Bug]:  The terraform-provider-aws_v4.43.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by SOft26** [hashicorp/terraform-provider-aws#28327]
### Terraform Core Version

Terraform v1.3.6

### AWS Provider Version

aws v4.43.0

### Affected Resource(s)

All imported resources

### Expected Behavior

After running terraform plan, it is expected to have shown me if I'm good to go 

### Actual Behavior

But instead i got a series of errors

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "4.43.0"
    }
  }
}






provider "aws"  {
    region = "eu-west-2"
   
}













resource "aws_db_parameter_group" "pgroup" {
  name= "default-mysql5-7"
  family = "mysql5.7"
}


resource "aws_db_security_group" "sgroup" {
  name = "default"
  ingress {}
}


resource "aws_db_subnet_group" "subngroup" {
  subnet_ids = [aws_subnet.kc-prod-eu-west2a, aws_subnet.kc-prod-eu-west-2b, aws_subnet.kc-prod-eu-west-2c]
}

resource "aws_db_option_group" "optgroup" {
  name                     = "default-mysql-5-7"
  engine_name              = "MySQL Community"
  major_engine_version     = "5.7"

}


resource "aws_redshift_parameter_group" "pgroup" {
  name        = "default-redshift-1-0"
  family      = "redshift-1.0"
  
}


resource "aws_security_group" "launch-wizard-1" {
  name        = "launch-wizard-1"
  description = "launch-wizard-1"
  vpc_id      = "vpc-7a750812"

 
}


resource "aws_security_group" "default" {
  name        = "default"
  description = "default VPC security group"
  vpc_id      = "vpc-7a750812"

 
}


resource "aws_vpc" "kc-prod" {
  cidr_block = "172.31.0.0/16"

}



resource "aws_subnet" "kc-prod-eu-west2a" {
  vpc_id     =  aws_vpc.kc-prod.id

}



resource "aws_subnet" "kc-prod-eu-west-2b" {
  vpc_id     =  aws_vpc.kc-prod.id

}





resource "aws_subnet" "kc-prod-eu-west-2c" {
  vpc_id     =  aws_vpc.kc-prod.id

}


resource "aws_vpc_dhcp_options" "options" {
  domain_name          = "eu-west-2.compute.internal"

}


resource "aws_internet_gateway" "gw" {
  vpc_id = aws_vpc.kc-prod.id
}




resource "aws_default_network_acl" "default" {
  default_network_acl_id = aws_vpc.kc-prod.default_network_acl_id
}


resource "aws_route_table" "rt" {
  vpc_id = aws_vpc.kc-prod.id
}



resource "aws_organizations_account" "account-1" {
  name  = "Klasconnect-AWSCloud"
  email = "info@cyberfleetng.com"
}



resource "aws_organizations_account" "account-2" {
  name  = "Japaanow-AWSCloud"
  email = "sojiadvanced@gmail.com"
}


resource "aws_organizations_organization" "root" {
}

# Cloud trail/Formation and Event section


resource "aws_cloudwatch_event_rule" "console" {
  name        = "rootaccount-login-detection-RootActivityRule"
  description = "Events rule for monitoring root AWS Console Sign In activity"
  schedule_expression = "rate(5 minutes)"
}





resource "aws_cloudtrail" "kcstore" {
  name                          = "kc-store-trail"
  s3_bucket_name                = aws_s3_bucket.kcstoretest
}


resource "aws_cloudformation_stack" "stack" {
  name = "rootaccount-login-detection"
}

 
# Resource keys section


resource "aws_kms_key" "rds" {

}


resource "aws_kms_key" "sqs" {

}


resource "aws_kms_key" "fsx" {

}


resource "aws_kms_key" "s3" {

}



resource "aws_s3_bucket" "aussncc" {
  bucket = "auss-ncc-kc"


}


resource "aws_s3_bucket" "kcstoretest" {
  bucket = "kc-store-test"


}

resource "aws_s3_bucket" "bomgssncc" {
  bucket = "bomgss-ncc"


}


resource "aws_s3_bucket" "bomgssncckc" {
  bucket = "bomgss-ncc-kc"


}


resource "aws_s3_bucket" "dataleum-1" {
  bucket = "dataleum"


}


resource "aws_s3_bucket" "dvsbookit" {
  bucket = "dvs-bookit"


}


resource "aws_s3_bucket" "gcdssncckc" {
  bucket = "gcdss-ncc-kc"


}



resource "aws_s3_bucket" "gssncckc" {
  bucket = "gss-ncc-kc"


}


resource "aws_s3_bucket" "gssspyakasa" {
  bucket = "gssspyakasa-ncc-kc"


}



resource "aws_s3_bucket" "gssspyncckc" {
  bucket = "gssspy-ncc-kc"


}



resource "aws_s3_bucket" "highschooltest" {
  bucket = "highschooltest-kc"


}



resource "aws_s3_bucket" "hsbookit" {
  bucket = "hs-bookit"


}


resource "aws_s3_bucket" "kcproddb" {
  bucket = "kc-prod-db"


}


resource "aws_s3_bucket" "kcstore" {
  bucket = "kc-store"


}



resource "aws_s3_bucket" "kctestkc" {
  bucket = "kctest-kc"


}


resource "aws_s3_bucket" "khadstore" {
  bucket = "khad-store"


}



resource "aws_s3_bucket" "luapulas" {
  bucket = "luapula"


}


resource "aws_s3_bucket" "luwis" {
  bucket = "luwi"


}


resource "aws_s3_bucket" "ogsncckc" {
  bucket = "ogs-ncc-kc"


}




resource "aws_s3_bucket" "petchas" {
  bucket = "petcha"


}



resource "aws_s3_bucket" "schooldb" {
  bucket = "school-db-backup"


}


resource "aws_s3_bucket" "the-pillars" {
  bucket = "thepillars"


}
 ```

### Steps to Reproduce

Terraform init
Terraform plan

### Debug Output

```
Error: Plugin did not respond
│
│   with aws_security_group.launch-wizard-1,
│   on Compute.tf line 3, in resource "aws_security_group" "launch-wizard-1":
│    3: resource "aws_security_group" "launch-wizard-1" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin    
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_subnet.kc-prod-eu-west2a,
│   on Compute.tf line 28, in resource "aws_subnet" "kc-prod-eu-west2a":
│   28: resource "aws_subnet" "kc-prod-eu-west2a" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin    
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_subnet.kc-prod-eu-west-2b,
│   on Compute.tf line 35, in resource "aws_subnet" "kc-prod-eu-west-2b":
│   35: resource "aws_subnet" "kc-prod-eu-west-2b" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin    
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with aws_subnet.kc-prod-eu-west-2c,
│   on Compute.tf line 44, in resource "aws_subnet" "kc-prod-eu-west-2c":
│   44: resource "aws_subnet" "kc-prod-eu-west-2c" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin    
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_internet_gateway.gw,
│   on Compute.tf line 56, in resource "aws_internet_gateway" "gw":
│   56: resource "aws_internet_gateway" "gw" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin    
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_default_network_acl.default,
│   on Compute.tf line 63, in resource "aws_default_network_acl" "default":
│   63: resource "aws_default_network_acl" "default" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin    
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_route_table.rt,
│   on Compute.tf line 68, in resource "aws_route_table" "rt":
│   68: resource "aws_route_table" "rt" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_organizations_account.account-1,
│   on Compute.tf line 74, in resource "aws_organizations_account" "account-1":
│   74: resource "aws_organizations_account" "account-1" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin    
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_organizations_account.account-2,
│   on Compute.tf line 81, in resource "aws_organizations_account" "account-2":
│   81: resource "aws_organizations_account" "account-2" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may   
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_organizations_organization.root,
│   on Compute.tf line 87, in resource "aws_organizations_organization" "root":
│   87: resource "aws_organizations_organization" "root" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may   
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_cloudwatch_event_rule.console,
│   on Compute.tf line 93, in resource "aws_cloudwatch_event_rule" "console":
│   93: resource "aws_cloudwatch_event_rule" "console" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may   
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_cloudformation_stack.stack,
│   on Compute.tf line 109, in resource "aws_cloudformation_stack" "stack":
│  109: resource "aws_cloudformation_stack" "stack" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin    
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_kms_key.rds,
│   on Compute.tf line 117, in resource "aws_kms_key" "rds":
│  117: resource "aws_kms_key" "rds" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin    
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_kms_key.sqs,
│   on Compute.tf line 122, in resource "aws_kms_key" "sqs":
│  122: resource "aws_kms_key" "sqs" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ValidateResourceConfig call. The plugin  
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_kms_key.s3,
│   on Compute.tf line 132, in resource "aws_kms_key" "s3":
│  132: resource "aws_kms_key" "s3" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin    
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_db_parameter_group.pgroup,
│   on Database.tf line 3, in resource "aws_db_parameter_group" "pgroup":
│    3: resource "aws_db_parameter_group" "pgroup" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin    
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_db_security_group.sgroup,
│   on Database.tf line 9, in resource "aws_db_security_group" "sgroup":
│    9: resource "aws_db_security_group" "sgroup" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).PlanResourceChange call. The plugin logs 
│ may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_sns_topic.ROOT-AWS,
│   on Database.tf line 58, in resource "aws_sns_topic" "ROOT-AWS":
│   58: resource "aws_sns_topic" "ROOT-AWS" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin    
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_sns_topic.dynamo-db,
│   on Database.tf line 63, in resource "aws_sns_topic" "dynamo-db":
│   63: resource "aws_sns_topic" "dynamo-db" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin    
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_s3_bucket.kcstoretest,
│   on S3buckets.tf line 10, in resource "aws_s3_bucket" "kcstoretest":
│   10: resource "aws_s3_bucket" "kcstoretest" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may   
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_s3_bucket.bomgssncc,
│   on S3buckets.tf line 16, in resource "aws_s3_bucket" "bomgssncc":
│   16: resource "aws_s3_bucket" "bomgssncc" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin    
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_s3_bucket.bomgssncckc,
│   on S3buckets.tf line 23, in resource "aws_s3_bucket" "bomgssncckc":
│   23: resource "aws_s3_bucket" "bomgssncckc" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may   
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_s3_bucket.dataleum-1,
│   on S3buckets.tf line 30, in resource "aws_s3_bucket" "dataleum-1":
│   30: resource "aws_s3_bucket" "dataleum-1" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may   
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_s3_bucket.dvsbookit,
│   on S3buckets.tf line 37, in resource "aws_s3_bucket" "dvsbookit":
│   37: resource "aws_s3_bucket" "dvsbookit" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may   
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_s3_bucket.gcdssncckc,
│   on S3buckets.tf line 44, in resource "aws_s3_bucket" "gcdssncckc":
│   44: resource "aws_s3_bucket" "gcdssncckc" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin    
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_s3_bucket.gssncckc,
│   on S3buckets.tf line 52, in resource "aws_s3_bucket" "gssncckc":
│   52: resource "aws_s3_bucket" "gssncckc" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin    
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_s3_bucket.gssspyakasa,
│   on S3buckets.tf line 59, in resource "aws_s3_bucket" "gssspyakasa":
│   59: resource "aws_s3_bucket" "gssspyakasa" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin    
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_s3_bucket.highschooltest,
│   on S3buckets.tf line 75, in resource "aws_s3_bucket" "highschooltest":
│   75: resource "aws_s3_bucket" "highschooltest" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may   
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_s3_bucket.hsbookit,
│   on S3buckets.tf line 83, in resource "aws_s3_bucket" "hsbookit":
│   83: resource "aws_s3_bucket" "hsbookit" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_s3_bucket.kcproddb,
│   on S3buckets.tf line 90, in resource "aws_s3_bucket" "kcproddb":
│   90: resource "aws_s3_bucket" "kcproddb" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin    
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with aws_s3_bucket.kcstore,
│   on S3buckets.tf line 97, in resource "aws_s3_bucket" "kcstore":
│   97: resource "aws_s3_bucket" "kcstore" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin    
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_s3_bucket.kctestkc,
│   on S3buckets.tf line 105, in resource "aws_s3_bucket" "kctestkc":
│  105: resource "aws_s3_bucket" "kctestkc" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin    
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_s3_bucket.luapulas,
│   on S3buckets.tf line 120, in resource "aws_s3_bucket" "luapulas":
│  120: resource "aws_s3_bucket" "luapulas" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin    
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_s3_bucket.luwis,
│   on S3buckets.tf line 127, in resource "aws_s3_bucket" "luwis":
│  127: resource "aws_s3_bucket" "luwis" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may   
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_s3_bucket.ogsncckc,
│   on S3buckets.tf line 134, in resource "aws_s3_bucket" "ogsncckc":
│  134: resource "aws_s3_bucket" "ogsncckc" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin    
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_s3_bucket.schooldb,
│   on S3buckets.tf line 151, in resource "aws_s3_bucket" "schooldb":
│  151: resource "aws_s3_bucket" "schooldb" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin    
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_s3_bucket.the-pillars,
│   on S3buckets.tf line 158, in resource "aws_s3_bucket" "the-pillars":
│  158: resource "aws_s3_bucket" "the-pillars" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin    
│ logs may contain more details.
╵
```

### Panic Output

stack trace from the terraform-provider-aws_v4.43.0_x5 plugin:

```
panic: interface conversion: interface {} is nil, not map[string]interface {}
goroutine 1175 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/rds.resourceSecurityGroupIngressHash({0x0?, 0x0?})
        github.com/hashicorp/terraform-provider-aws/internal/service/rds/security_group.go:322 +0x336
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).hash(0x4512a9?, {0x0?, 0x0?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/set.go:218 +0x2c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).add(0xc0068b0380, {0x0?, 0x0}, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/set.go:198 +0x96
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ConfigFieldReader).readSet(0xc004a24450, {0xc0068a7b00, 0x1, 0x1}, 
0x0?)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_reader_config.go:284 +0x4aa
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ConfigFieldReader).readField(0xc004a24450, {0xc0068a7b00?, 0x1, 0x1}, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_reader_config.go:107 +0x55b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ConfigFieldReader).ReadField(0x9d60380?, {0xc0068a7b00?, 0xb732bab?, 0x6?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_reader_config.go:29 +0xbc
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MultiLevelFieldReader).ReadFieldExact(0xc0068a7af0?, {0xc0068a7b00, 0x1, 0x1}, {0xb732bab, 0x6})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/field_reader_multi.go:31 +0xa8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0xc003d45f00, {0xc0068a7b00, 0x1, 0x1}, 0x0?)    
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource_data.go:548 +0x145
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).getChange(0xc0068af180?, {0xb735835?, 0x7?}, 0x50?, 0x7a?)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource_data.go:524 +0x1b8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).diffChange(0x91ccde0?, {0xb735835?, 0xc0068a7ae0?})  
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource_data.go:501 +0x76
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diffSet(0xc004a242d0?, {0xc81c520, 0xc0049d7230}, {0xb735835, 0x7}, 0xc0012e8500, 0xc0044ccba8, {0xc824eb0?, 0xc003d45f00?}, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/schema.go:1413 +0x90
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diff(0x6?, {0xc81c520, 0xc0049d7230}, {0xb735835, 0x7}, 0xc0012e8500, 0xc003d45e80, {0xc824eb0?, 0xc003d45f00}, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/schema.go:1135 +0x265
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc0012c9980, {0xc81c520, 0xc0049d7230}, 0xc003f73ee0, 0xc004a241b0, 0xb99daa0, {0xa74e140, 0xc000402400}, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/schema.go:679 +0x353
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0xc81d438?, {0xc81c520?, 0xc0049d7230?}, 0xc003f73ee0, 0x9d60da0?, {0xa74e140?, 0xc000402400?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:890 +0x6c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0xc00012d3e0, {0xc81c520?, 0xc0049d7110?}, 0xc0036021e0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:741 +0x9c9
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.PlanResourceChange({0xc002f85a10, 0xc002f85a70, {0xc0046e6e60, 
0x2, 0x2}, 0xc002f85a40, 0xc002fa1f80, 0xc00425d560, 0xc002f85aa0}, {0xc81c520, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.7.0/tf5muxserver/mux_server_PlanResourceChange.go:27 +0x142
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).PlanResourceChange(0xc002059e00, {0xc81c520?, 0xc0049d68a0?}, 0xc003e34b60)
        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:783 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler({0xb446d00?, 0xc002059e00}, {0xc81c520, 0xc0049d68a0}, 0xc003e34af0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:367 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00412cf00, {0xc826da0, 0xc0032741a0}, 0xc00436a900, 0xc0047c5980, 0x12614848, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc00412cf00, {0xc826da0, 0xc0032741a0}, 0xc00436a900, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.50.1/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.50.1/server.go:963 +0x28a

Error: The terraform-provider-aws_v4.43.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/7b598fa06476af5b8db4c19bfa7604367d82db0a/internal/service/rds/security_group.go#L320-L341

**Comment by SOft26** [comment]
Okay @ewbankkit , let me remove the config file and run a terraform plan again

**Comment by SOft26** [comment]
Everything works perfectly fine after removing the offending resource block @ewbankkit
Thankss a lot

**Comment by SOft26** [comment]
The issue has been resolved
