### ISSUE TITLE
[Bug]: terraform provider 4.46.0 crashes when importing opensearch inbound connection

### ISSUE THREAD

**Issue by LeonD9** [hashicorp/terraform-provider-aws#28347]
### Terraform Core Version

1.1.3

### AWS Provider Version

4.46.0

### Affected Resource(s)

aws_opensearch_inbound_connection_accepter

### Expected Behavior

Import finishing successfully

### Actual Behavior

When trying to import Opensearch connection between USE and EUC/APS regions the provider crashes

### Relevant Error/Panic Output Snippet

```shell
│ Error: Request cancelled
│
│ The plugin.(*GRPCProvider).ReadResource request was cancelled.
╵

Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-aws_v4.46.0_x5 plugin:

panic: interface conversion: interface {} is nil, not *opensearchservice.InboundConnection

goroutine 21 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/opensearch.resourceInboundConnectionRead({0xe71f7c8, 0xc000876360}, 0xc003414500, {0xc7f8d80?, 0xc0003b6c00?})
	github.com/hashicorp/terraform-provider-aws/internal/service/opensearch/inbound_connection_accepter.go:86 +0x2a8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc001826d20, {0xe71f800, 0xc003aaf830}, 0xd?, {0xc7f8d80, 0xc0003b6c00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc001826d20, {0xe71f800, 0xc003aaf830}, 0xc003420680, {0xc7f8d80, 0xc0003b6c00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000011470, {0xe71f800?, 0xc003aaf710?}, 0xc003fee600)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadResource({0xc0030f7830, 0xc0030f7890, {0xc00448dc60, 0x2, 0x2}, 0xc0030f7860, 0xc00312c480, 0xc00404cb90, 0xc0030f78c0}, {0xe71f800, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.7.0/tf5muxserver/mux_server_ReadResource.go:26 +0x142
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc001d88fa0, {0xe71f800?, 0xc003aae3c0?}, 0xc000876060)
	github.com/hashicorp/terraform-plugin-go@v0.14.2/tfprotov5/tf5server/server.go:748 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xd161ce0?, 0xc001d88fa0}, {0xe71f800, 0xc003aae3c0}, 0xc00340e000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.2/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc003f44d20, {0xe72a200, 0xc0006c8680}, 0xc00087a000, 0xc0045b6c00, 0x14acbbf0, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc003f44d20, {0xe72a200, 0xc0006c8680}, 0xc00087a000, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-aws_v4.46.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

ERRO[0026] 1 error occurred:
	* exit status 1
```

### Terraform Configuration Files

resource "aws_opensearch_outbound_connection" "main" {
  connection_alias = var.name
  local_domain_info {
    owner_id    = var.account_id
    region      = var.region
    domain_name = var.local_os_name
  }

  remote_domain_info {
    owner_id    = var.account_id
    region      = var.remote_region
    domain_name = var.remote_os_name
  }
}

resource "aws_opensearch_inbound_connection_accepter" "main" {
  connection_id = aws_opensearch_outbound_connection.main.id
}

### Steps to Reproduce

Try importing opensearch inbound connection between different regions in AWS.
 ```
 terragrunt import aws_opensearch_inbound_connection_accepter.main <connection-id>
 ```

### Would you like to implement a fix?

None

**Comment by jar-b** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/08e008d7d40a5c8aabf8d30e462e6a3e779a6829/internal/service/opensearch/inbound_connection_accepter.go#L80-L86

**Comment by jar-b** [comment]
Fixed by #33612 (specifically cb8bdfafb010cd1ff3c51b0691991f963ec3be2e).
