### ISSUE TITLE
[Bug]: AWS provider v4.53.0 crashes during destroy operation 

### ISSUE THREAD

**Issue by brandocorp** [hashicorp/terraform-provider-aws#29308]
### Terraform Core Version

1.1.9

### AWS Provider Version

4.53.0

### Affected Resource(s)

I'm not sure if this is specific to a particular resource.

### Expected Behavior

The destroy operation completes successfully.

### Actual Behavior

The AWS provider plugin crashes during the destroy operation.

### Relevant Error/Panic Output Snippet

```shell
╷
 │ Error: Plugin did not respond
 │ 
 │ The plugin encountered an error, and failed to respond to the
 │ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
 │ contain more details.
 ╵
```

### Terraform Configuration Files

I can provide a link to the private repo

### Steps to Reproduce

1. Clone the repo
2. Execute the tests

### Panic Output

```shell
 ╷
 │ Error: Plugin did not respond
 │ 
 │ The plugin encountered an error, and failed to respond to the
 │ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
 │ contain more details.
 ╵
 
 Stack trace from the terraform-provider-aws_v4.53.0_x5 plugin:
 
 fatal error: concurrent map writes
 
 goroutine 460 [running]:
 github.com/hashicorp/terraform-plugin-log/tflog.SetField.func1(...)
 	github.com/hashicorp/terraform-plugin-log@v0.7.0/internal/logging/options.go:212
 github.com/hashicorp/terraform-plugin-log/tflog.SetField({0xe25bd00, 0xc00454a960}, {0xce35f74, 0x7}, {0xa619820?, 0xe174450})
 	github.com/hashicorp/terraform-plugin-log@v0.7.0/tflog/provider.go:18 +0x111
 github.com/hashicorp/aws-sdk-go-base/v2/awsv1shim/v2.setAWSFields({0xe25bd00?, 0xc00454a960?}, 0xc004cce000)
 	github.com/hashicorp/aws-sdk-go-base/v2/awsv1shim/v2@v2.0.0-beta.23/logger.go:39 +0x4c
 github.com/hashicorp/aws-sdk-go-base/v2/awsv1shim/v2.logRequest(0xc004cce000)
 	github.com/hashicorp/aws-sdk-go-base/v2/awsv1shim/v2@v2.0.0-beta.23/logger.go:69 +0x5f
 github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0xc004cce228, 0xc004cce000)
 	github.com/aws/aws-sdk-go@v1.44.191/aws/request/handlers.go:267 +0x9a
 github.com/aws/aws-sdk-go/aws/request.(*Request).sendRequest(0xc004cce000)
 	github.com/aws/aws-sdk-go@v1.44.191/aws/request/request.go:602 +0xbf
 github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0xc004cce000)
 	github.com/aws/aws-sdk-go@v1.44.191/aws/request/request.go:555 +0x156
 github.com/aws/aws-sdk-go/aws/request.(*Pagination).Next(0xc00691dbf0)
 	github.com/aws/aws-sdk-go@v1.44.191/aws/request/request_pagination.go:107 +0xb3
 github.com/aws/aws-sdk-go/service/ec2.(*EC2).DescribeNetworkInterfacesPagesWithContext(0xc000dc2fe0, {0xe25bd00?, 0xc00454a960}, 0xc0026f7e50, 0xc00691dd20, {0x0, 0x0, 0x0})
 	github.com/aws/aws-sdk-go@v1.44.191/service/ec2/api.go:26518 +0x19d
 github.com/hashicorp/terraform-provider-aws/internal/service/ec2.FindNetworkInterfaces({0xe25bd00?, 0xc00454a960?}, 0x48?, 0xc0026f7e50)
 	github.com/hashicorp/terraform-provider-aws/internal/service/ec2/find.go:1526 +0x8b
 github.com/hashicorp/terraform-provider-aws/internal/service/ec2.FindNetworkInterface({0xe25bd00?, 0xc00454a960?}, 0xc0068ad3c0?, 0xc0026f7e50)
 	github.com/hashicorp/terraform-provider-aws/internal/service/ec2/find.go:1506 +0x2c
 github.com/hashicorp/terraform-provider-aws/internal/service/ec2.FindNetworkInterfaceByID({0xe25bd00, 0xc00454a960}, 0x2540be400?, {0xc004c348e8, 0x15})
 	github.com/hashicorp/terraform-provider-aws/internal/service/ec2/find.go:1559 +0x10c
 github.com/hashicorp/terraform-provider-aws/internal/service/ec2.StatusNetworkInterfaceStatus.func1()
 	github.com/hashicorp/terraform-provider-aws/internal/service/ec2/status.go:1123 +0x31
 github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext.func1()
 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/resource/state.go:110 +0x1ff
 created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext
 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/resource/state.go:83 +0x1d8
 
 goroutine 1 [select, 3 minutes]:
 github.com/hashicorp/go-plugin.Serve(0xc004dc95c0)
 	github.com/hashicorp/go-plugin@v1.4.8/server.go:471 +0x14f7
 github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.Serve({0xcf5e0a9, 0x23}, 0xc0045c5290, {0x0, 0x0, 0x0})
 	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:312 +0xba5
 main.main()
 	github.com/hashicorp/terraform-provider-aws/main.go:32 +0x18d
 
 goroutine 348 [select, 3 minutes]:
 github.com/hashicorp/go-plugin.(*gRPCBrokerServer).Recv(0xc0004e4fa0?)
 	github.com/hashicorp/go-plugin@v1.4.8/grpc_broker.go:121 +0x67
 github.com/hashicorp/go-plugin.(*GRPCBroker).Run(0xc0049f3130)
 	github.com/hashicorp/go-plugin@v1.4.8/grpc_broker.go:411 +0x44
 created by github.com/hashicorp/go-plugin.(*GRPCServer).Init
 	github.com/hashicorp/go-plugin@v1.4.8/grpc_server.go:85 +0x46a
 
 goroutine 349 [IO wait, 3 minutes]:
 internal/poll.runtime_pollWait(0x7ff42e31be90, 0x72)
 	runtime/netpoll.go:305 +0x89
 internal/poll.(*pollDesc).wait(0xc004dc9a40?, 0xc00169e000?, 0x1)
 	internal/poll/fd_poll_runtime.go:84 +0x32
 internal/poll.(*pollDesc).waitRead(...)
 	internal/poll/fd_poll_runtime.go:89
 internal/poll.(*FD).Read(0xc004dc9a40, {0xc00169e000, 0x1000, 0x1000})
 	internal/poll/fd_unix.go:167 +0x25a
 os.(*File).read(...)
 	os/file_posix.go:31
 os.(*File).Read(0xc004ba9cb0, {0xc00169e000?, 0x400?, 0xa6ff020?})
 	os/file.go:118 +0x5e
 bufio.(*Reader).Read(0xc0004e5740, {0xc0016a0000, 0x400, 0x0?})
 	bufio/bufio.go:237 +0x1bb
 github.com/hashicorp/go-plugin.copyChan({0xe284db0, 0xc00499cf30}, 0x0?, {0xe19eae0?, 0xc004ba9cb0?})
 	github.com/hashicorp/go-plugin@v1.4.8/grpc_stdio.go:181 +0x1f6
 created by github.com/hashicorp/go-plugin.newGRPCStdioServer
 	github.com/hashicorp/go-plugin@v1.4.8/grpc_stdio.go:37 +0xf5
 
 goroutine 350 [IO wait, 3 minutes]:
 internal/poll.runtime_pollWait(0x7ff42e31bcb0, 0x72)
 	runtime/netpoll.go:305 +0x89
 internal/poll.(*pollDesc).wait(0xc004dc9b00?, 0xc00169f000?, 0x1)
 	internal/poll/fd_poll_runtime.go:84 +0x32
 internal/poll.(*pollDesc).waitRead(...)
 	internal/poll/fd_poll_runtime.go:89
 internal/poll.(*FD).Read(0xc004dc9b00, {0xc00169f000, 0x1000, 0x1000})
 	internal/poll/fd_unix.go:167 +0x25a
 os.(*File).read(...)
 	os/file_posix.go:31
 os.(*File).Read(0xc004ba9cc0, {0xc00169f000?, 0x400?, 0xa6ff020?})
 	os/file.go:118 +0x5e
 bufio.(*Reader).Read(0xc0004e5f40, {0xc0016a0400, 0x400, 0x0?})
 	bufio/bufio.go:237 +0x1bb
 github.com/hashicorp/go-plugin.copyChan({0xe284db0, 0xc00499cf30}, 0x0?, {0xe19eae0?, 0xc004ba9cc0?})
 	github.com/hashicorp/go-plugin@v1.4.8/grpc_stdio.go:181 +0x1f6
 created by github.com/hashicorp/go-plugin.newGRPCStdioServer
 	github.com/hashicorp/go-plugin@v1.4.8/grpc_stdio.go:38 +0x185
 
 goroutine 353 [syscall, 3 minutes]:
 os/signal.signal_recv()
 	runtime/sigqueue.go:152 +0x2f
 os/signal.loop()
 	os/signal/signal_unix.go:23 +0x19
 created by os/signal.Notify.func1.1
 	os/signal/signal.go:151 +0x2a
 
 goroutine 354 [chan receive, 3 minutes]:
 github.com/hashicorp/go-plugin.Serve.func3()
 	github.com/hashicorp/go-plugin@v1.4.8/server.go:436 +0x75
 
 Error: The terraform-provider-aws_v4.53.0_x5 plugin crashed!
 
 This is always indicative of a bug within the plugin. It would be immensely
 helpful if you could report the crash with the plugin's maintainers so that it
 can be fixed. The output above should help diagnose the issue.
```

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
@brandocorp Thanks for raising this issue.
It has already been noticed in #29236. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
