### ISSUE TITLE
[Bug]: AWS Lambda Destruction No Longer Waiting for Destruction of NICs

### ISSUE THREAD

**Issue by bradhandy** [hashicorp/terraform-provider-aws#29306]
### Terraform Core Version

1.1.9

### AWS Provider Version

4.53.0

### Affected Resource(s)

* aws_lambda_function
* aws_security_group

### Expected Behavior

When destroying an AWS Lambda Function, the provider should wait until the attached NICs are also destroyed to allow for the security group to be destroyed. This a documented feature for the aws_lambda_function: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function

### Actual Behavior

The lambda destruction took seconds and then the security group failed to be destroyed due to an error.

### Relevant Error/Panic Output Snippet

```shell
aws_transfer_workflow.sftp (deposed object 3782f093): Destroying... [id=w-b85f1b5dc5b73cb50]
aws_security_group.sftp-server (deposed object 328680cf): Destroying... [id=sg-0e3b9134f545631ab]
aws_transfer_workflow.sftp: Destruction complete after 0s
aws_lambda_function.sftp-workflow (deposed object 1ab8c125): Destroying... [id=int-SftpWorkflowFunction]
aws_lambda_function.sftp-workflow: Destruction complete after 1s
aws_security_group.sftp-efs (deposed object d0e5b3ba): Destroying... [id=sg-017a1ccd6848965fd]
aws_security_group.sftp_lambda (deposed object 649513cd): Destroying... [id=sg-0ef2f16a073108399]
aws_iam_role.workflow-function-execution-role (deposed object 82d27f2b): Destroying... [id=int-XfrWorkflowLambdaExecutionRole]
aws_security_group.sftp-server: Destruction complete after 1s
aws_iam_role.workflow-function-execution-role: Destruction complete after 0s
aws_security_group.sftp-efs: Destruction complete after 0s
aws_security_group.sftp_lambda: Still destroying... [id=sg-0ef2f16a073108399, 10s elapsed]
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
Stack trace from the terraform-provider-aws_v4.53.0_x5 plugin:
fatal error: concurrent map writes
fatal error: concurrent map writes
goroutine 2178 [running]:
github.com/hashicorp/terraform-plugin-log/tflog.SetField.func1(...)
	github.com/hashicorp/terraform-plugin-log@v0.7.0/internal/logging/options.go:212
github.com/hashicorp/terraform-plugin-log/tflog.SetField({0xe25bd00, 0xc00445b9b0}, {0xce35f74, 0x7}, {0xa619820?, 0xe174450})
	github.com/hashicorp/terraform-plugin-log@v0.7.0/tflog/provider.go:18 +0x111
github.com/hashicorp/aws-sdk-go-base/v2/awsv1shim/v2.setAWSFields({0xe25bd00?, 0xc00445b9b0?}, 0xc003dae000)
	github.com/hashicorp/aws-sdk-go-base/v2/awsv1shim/v2@v2.0.0-beta.23/logger.go:39 +0x4c
github.com/hashicorp/aws-sdk-go-base/v2/awsv1shim/v2.logRequest(0xc003dae000)
	github.com/hashicorp/aws-sdk-go-base/v2/awsv1shim/v2@v2.0.0-beta.23/logger.go:69 +0x5f
github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0xc003dae228, 0xc003dae000)
	github.com/aws/aws-sdk-go@v1.44.191/aws/request/handlers.go:267 +0x9a
github.com/aws/aws-sdk-go/aws/request.(*Request).sendRequest(0xc003dae000)
	github.com/aws/aws-sdk-go@v1.44.191/aws/request/request.go:602 +0xbf
github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0xc003dae000)
	github.com/aws/aws-sdk-go@v1.44.191/aws/request/request.go:555 +0x156
github.com/aws/aws-sdk-go/aws/request.(*Pagination).Next(0xc003299bf0)
	github.com/aws/aws-sdk-go@v1.44.191/aws/request/request_pagination.go:107 +0xb3
github.com/aws/aws-sdk-go/service/ec2.(*EC2).DescribeNetworkInterfacesPagesWithContext(0xc002a85640, {0xe25bd00?, 0xc00445b9b0}, 0xc00050c8c0, 0xc003299d20, {0x0, 0x0, 0x0})
	github.com/aws/aws-sdk-go@v1.44.191/service/ec2/api.go:26518 +0x19d
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.FindNetworkInterfaces({0xe25bd00?, 0xc00445b9b0?}, 0x48?, 0xc00050c8c0)
	github.com/hashicorp/terraform-provider-aws/internal/service/ec2/find.go:1526 +0x8b
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.FindNetworkInterface({0xe25bd00?, 0xc00445b9b0?}, 0xc0057d3ba0?, 0xc00050c8c0)
	github.com/hashicorp/terraform-provider-aws/internal/service/ec2/find.go:1506 +0x2c
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.FindNetworkInterfaceByID({0xe25bd00, 0xc00445b9b0}, 0xc003286e28?, {0xc0016d6828, 0x15})
	github.com/hashicorp/terraform-provider-aws/internal/service/ec2/find.go:1559 +0x10c
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.StatusNetworkInterfaceStatus.func1()
	github.com/hashicorp/terraform-provider-aws/internal/service/ec2/status.go:1123 +0x31
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext.func1()
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/resource/state.go:110 +0x1ff
created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/resource/state.go:83 +0x1d8
goroutine 1 [select, 4 minutes]:
github.com/hashicorp/go-plugin.Serve(0xc0033bbc20)
	github.com/hashicorp/go-plugin@v1.4.8/server.go:471 +0x14f7
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.Serve({0xcf5e0a9, 0x23}, 0xc002aa0210, {0x0, 0x0, 0x0})
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:312 +0xba5
main.main()
	github.com/hashicorp/terraform-provider-aws/main.go:32 +0x18d
goroutine 327 [select, 4 minutes]:
github.com/hashicorp/go-plugin.(*gRPCBrokerServer).Recv(0xc0000b17a0?)
	github.com/hashicorp/go-plugin@v1.4.8/grpc_broker.go:121 +0x67
github.com/hashicorp/go-plugin.(*GRPCBroker).Run(0xc0027e4b40)
	github.com/hashicorp/go-plugin@v1.4.8/grpc_broker.go:[MASKED]1 +0x44
created by github.com/hashicorp/go-plugin.(*GRPCServer).Init
	github.com/hashicorp/go-plugin@v1.4.8/grpc_server.go:85 +0x46a
goroutine 328 [IO wait, 4 minutes]:
internal/poll.runtime_pollWait(0x7f7261544ed0, 0x72)
	runtime/netpoll.go:305 +0x89
internal/poll.(*pollDesc).wait(0xc00347c120?, 0xc0010d8000?, 0x1)
	internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00347c120, {0xc0010d8000, 0x1000, 0x1000})
	internal/poll/fd_unix.go:167 +0x25a
os.(*File).read(...)
	os/file_posix.go:31
os.(*File).Read(0xc002a845b0, {0xc0010d8000?, 0x400?, 0xa6ff020?})
	os/file.go:118 +0x5e
bufio.(*Reader).Read(0xc0000b1f40, {0xc0010da000, 0x400, 0x0?})
	bufio/bufio.go:237 +0x1bb
github.com/hashicorp/go-plugin.copyChan({0xe284db0, 0xc0045adef0}, 0x0?, {0xe19eae0?, 0xc002a845b0?})
	github.com/hashicorp/go-plugin@v1.4.8/grpc_stdio.go:181 +0x1f6
created by github.com/hashicorp/go-plugin.newGRPCStdioServer
	github.com/hashicorp/go-plugin@v1.4.8/grpc_stdio.go:37 +0xf5
goroutine 329 [IO wait, 4 minutes]:
internal/poll.runtime_pollWait(0x7f7261544cf0, 0x72)
	runtime/netpoll.go:305 +0x89
internal/poll.(*pollDesc).wait(0xc00347c1e0?, 0xc002aa4000?, 0x1)
	internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00347c1e0, {0xc002aa4000, 0x1000, 0x1000})
	internal/poll/fd_unix.go:167 +0x25a
os.(*File).read(...)
	os/file_posix.go:31
os.(*File).Read(0xc002a845c0, {0xc002aa4000?, 0x400?, 0xa6ff020?})
	os/file.go:118 +0x5e
bufio.(*Reader).Read(0xc0000b2740, {0xc002aa6000, 0x400, 0x0?})
	bufio/bufio.go:237 +0x1bb
github.com/hashicorp/go-plugin.copyChan({0xe284db0, 0xc0045adef0}, 0x0?, {0xe19eae0?, 0xc002a845c0?})
	github.com/hashicorp/go-plugin@v1.4.8/grpc_stdio.go:181 +0x1f6
created by github.com/hashicorp/go-plugin.newGRPCStdioServer
	github.com/hashicorp/go-plugin@v1.4.8/grpc_stdio.go:38 +0x185
goroutine 331 [syscall, 4 minutes]:
os/signal.signal_recv()
	runtime/sigqueue.go:152 +0x2f
os/signal.loop()
	os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
	os/signal/signal.go:151 +0x2a
goroutine 332 [chan receive, 4 minutes]:
github.com/hashicorp/go-plugin.Serve.func3()
Error: The terraform-provider-aws_v4.53.0_x5 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
Cleaning up project directory and file based variables 00:01
ERROR: Job failed: exit code 1
```

### Terraform Configuration Files

The attached file is encrypted with the public GPG key.

[sircon-sftp.tgz](https://github.com/hashicorp/terraform-provider-aws/files/10689447/sircon-sftp.tgz)

### Steps to Reproduce

* Create a security group to assign to multiple Lambda functions.
* Create a Lambda Function to be used as a transfer family instance's custom authentication provider.
* Create a transfer family instance using a Lambda function for custom authentication. (Not sure if this is required to reproduce the bug, but my lambdas implemented a custom authentication provider and a workflow step.)
* Create a workflow with a single custom workflow step to execute a lambda function.
* Change the name of the lambda function and the security group, then apply changes.

### Important Factoids

Terraform was executed within a container running the 1.1.9 image. The pipeline was executed on a runner in our VPC in AWS and invoked via the Gitlab CI.

### Would you like to implement a fix?

No

**Comment by bradhandy** [comment]
I'm sure this will be observed in the configuration, but I figured I would mention it here.

The `aws_security_group` resources are configured with the `lifecycle` property `create_before_destroy` set to `true`.

**Comment by bradhandy** [comment]
I've reverted back to a version I know works (4.31.0) and the functionality is working as expected. However, I was mistaken on which resource was waiting for destruction. The security group is the resource that takes a long time to be destroyed because the NICs associated with the old Lambda remain IN-USE for quite a while.

**Comment by ewbankkit** [comment]
@bradhandy Thanks for raising this issue.
It has already been noticed in #29236. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
