### ISSUE TITLE
[Bug]: aws_launch_template panic error with InstanceMarketOptionsRequest 

### ISSUE THREAD

**Issue by 91vikash** [hashicorp/terraform-provider-aws#29374]
### Terraform Core Version

1.3.6

### AWS Provider Version

v4.20.1 

### Affected Resource(s)

* aws_launch_template

### Expected Behavior

launch template should have created.

```terraform
resource "aws_launch_template" "bastion-lt" {
  name_prefix   = "${var.environment}-bastion-"
  image_id      = data.aws_ami.bastion-ubuntu.id
  instance_type = var.bastion-instance-type

  iam_instance_profile {
    name = aws_iam_instance_profile.instance-profile.name
  }

  user_data = base64encode(templatefile("${path.module}/scripts/userdata.sh", {
    service          = "${var.environment}-${var.region}-bastion"
    initubuntuserver = base64encode(file("../../shared/userdata/userdata-no-packer-boxes-v2.sh"))
    createusers      = base64encode(file("../../shared/userdata/create-users.sh"))
  }))

  block_device_mappings {
    device_name = "/dev/sda1"
    ebs {
      delete_on_termination = true
      volume_size           = "8"
      volume_type           = "standard"
    }
  }
  network_interfaces {
    associate_public_ip_address = true
    security_groups             = [var.bastion-sg-id]

  }

  instance_market_options {
    market_type = "spot"
    spot_options {
      max_price = var.environment == "prod" ? "" : var.spot_price
    }
  }
}`
```

### Actual Behavior

A launch template should have created. 

### Relevant Error/Panic Output Snippet

```shell
Error: Plugin did not respond
│ 
│   with module.bastion.aws_launch_template.bastion-lt,
│   on ../../modules/bastion/main.tf line 1, in resource "aws_launch_template" "bastion-lt":
│    1: resource "aws_launch_template" "bastion-lt" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-aws_v4.20.1_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 220 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.expandLaunchTemplateInstanceMarketOptionsRequest(0xc0030596e0)
	github.com/hashicorp/terraform-provider-aws/internal/service/ec2/ec2_launch_template.go:1557 +0x18a
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.expandRequestLaunchTemplateData(0x968dccd, 0x96918c1)
	github.com/hashicorp/terraform-provider-aws/internal/service/ec2/ec2_launch_template.go:1247 +0x1125
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.resourceLaunchTemplateUpdate(0xc002154080, {0x81d8920, 0xc00002f500})
	github.com/hashicorp/terraform-provider-aws/internal/service/ec2/ec2_launch_template.go:1092 +0x31b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xa7b93c0, {0xa7b93c0, 0xc002d2e300}, 0xd, {0x81d8920, 0xc00002f500})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/resource.go:729 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0012f40e0, {0xa7b93c0, 0xc002d2e300}, 0xc000e0e270, 0xc002e23f00, {0x81d8920, 0xc00002f500})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/resource.go:847 +0x9e5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0003049a8, {0xa7b9318, 0xc00243f400}, 0xc00353a960)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0022ef220, {0xa7b93c0, 0xc0001dbc20}, 0xc002ade230)
	github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/tf5server/server.go:812 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x93fbb40, 0xc0022ef220}, {0xa7b93c0, 0xc0001dbc20}, 0xc001f227e0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00029cfc0, {0xa8c7690, 0xc002180340}, 0xc001571c20, 0xc0022f8db0, 0x105f9640, 0x0)
	google.golang.org/grpc@v1.46.0/server.go:1283 +0xcf2
google.golang.org/grpc.(*Server).handleStream(0xc00029cfc0, {0xa8c7690, 0xc002180340}, 0xc001571c20, 0x0)
	google.golang.org/grpc@v1.46.0/server.go:1620 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.46.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.46.0/server.go:920 +0x294

Error: The terraform-provider-aws_v4.20.1_x5 plugin crashed!
```

### Terraform Configuration Files

I am not able to reproduce this error in other AWS account. We do have multiple aws account, all runs fine except in one AWS account which is `prod`, we are seeing this issues.

### Steps to Reproduce

terraform plan 
terraform apply

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @91vikash 👋 This appears to be due to the ternary function here:

```terraform
 max_price = var.environment == "prod" ? "" : var.spot_price
```

When `max_price` is an empty string and none of the other `spot_options` arguments are passed, `spot_options` is an empty block, leading to this error. You should be able to get around this by utilizing a [dynamic block](https://developer.hashicorp.com/terraform/language/expressions/dynamic-blocks) based on the `var.environment` variable.

**Comment by starlightromero** [comment]
I'm getting a similar error when using the [EKS module](https://github.com/terraform-aws-modules/terraform-aws-eks) and not passing in any `instance_market_options`
