### ISSUE TITLE
[Bug]: Error: Plugin did not respond

### ISSUE THREAD

**Issue by rickychew77** [hashicorp/terraform-provider-aws#29508]
### Terraform Core Version

1.1.7

### AWS Provider Version

4.55.0

### Affected Resource(s)

aws_cognito_risk_configuration

### Expected Behavior

Able to apply to config aws_cognito_risk_configuration

### Actual Behavior

Gives error as below

### Relevant Error/Panic Output Snippet

```shell
Stack trace from the terraform-provider-aws_v4.55.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 356 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/cognitoidp.expandRiskExceptionConfiguration({0xc003e6d620?, 0xdbc5711?, 0x0?})
        github.com/hashicorp/terraform-provider-aws/internal/service/cognitoidp/risk_configuration.go:384 +0x177
github.com/hashicorp/terraform-provider-aws/internal/service/cognitoidp.resourceRiskConfigurationPut({0xef1e2e0, 0xc003bd9860}, 0x0?, {0xdaa2c00?, 0xc000659c00?})
        github.com/hashicorp/terraform-provider-aws/internal/service/cognitoidp/risk_configuration.go:292 +0x2d1
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xef1e2e0?, {0xef1e2e0?, 0xc003bd9860?}, 0xd?, {0xdaa2c00?, 0xc000659c00?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:702 +0x84
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000b510a0, {0xef1e2e0, 0xc003bd9860}, 0xc005bccc30, 0xc005bc4500, {0xdaa2c00, 0xc000659c00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000127470, {0xef1e2e0?, 0xc003bd9050?}, 0xc0056b3a40)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc00308ac60, 0xc00308acc0, {0xc0047d32a0, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.9.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc001dc8320, {0xef1e2e0?, 0xc0030dde90?}, 0xc0056c5340)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xd7bf9c0?, 0xc001dc8320}, {0xef1e2e0, 0xc0030dde90}, 0xc0056c52d0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00404fe00, {0xef2d560, 0xc0048bf040}, 0xc005bbd0e0, 0xc004833d10, 0x1555db40, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc00404fe00, {0xef2d560, 0xc0048bf040}, 0xc005bbd0e0, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-aws_v4.55.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Configuration Files

``` terraform
resource "aws_cognito_risk_configuration" "risk_config" {
  user_pool_id = aws_cognito_user_pool.pool.id
  client_id    = var.client_id

  account_takeover_risk_configuration {
    notify_configuration {
      dynamic block_email {
        for_each = var.block_email != null ? [1] : []

        content {
          html_body = lookup(var.block_email, "html_body")
          subject   = lookup(var.block_email, "subject")
          text_body = lookup(var.block_email, "text_body")
        }
      }
      dynamic mfa_email {
        for_each = var.mfa_email != null ? [1] : []

        content {
          html_body = lookup(var.mfa_email, "html_body")
          subject   = lookup(var.mfa_email, "subject")
          text_body = lookup(var.mfa_email, "text_body")
        }
      }
      dynamic no_action_email {
        for_each = var.no_action_email != null ? [1] : []
        
        content {
          html_body = lookup(var.no_action_email, "html_body")
          subject   = lookup(var.no_action_email, "subject")
          text_body = lookup(var.no_action_email, "text_body")
        }
      }

      from     = var.from
      reply_to = var.reply_to
      source_arn = "arn:aws:cognito-idp:ap-southeast-1:829891530814:userpool/ap-southeast-1_5CpSmHS2n"
    }
    actions {
      dynamic high_action {
        for_each = var.high_action != null ? [1] : []

        content {
          event_action = lookup(var.high_action, "event_action")
          notify       = lookup(var.high_action, "notify")
        }
      }

      dynamic medium_action {
        for_each = var.medium_action != null ? [1] : []

        content {
          event_action = lookup(var.medium_action, "event_action")
          notify       = lookup(var.medium_action, "notify")
        }
      }

      dynamic low_action {
        for_each = var.low_action != null ? [1] : []

        content {
          event_action = lookup(var.low_action, "event_action")
          notify       = lookup(var.low_action, "notify")
        }
      }

    }
  }

  compromised_credentials_risk_configuration {
    event_filter = var.event_filter
    actions {
      event_action = var.event_action
    }
  }

  risk_exception_configuration {
    blocked_ip_range_list = var.block_ip
    skipped_ip_range_list = var.skipped_ip
  }

  depends_on = [aws_cognito_user_pool.pool]
}

### Steps to Reproduce

Am using terragrunt.

terragrunt plan - no issue
terragrunt apply

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

**Comment by gdavison** [comment]
Hi @rickychew77, thanks for submitting this. I see that your configuration includes

```terraform
risk_exception_configuration {
  blocked_ip_range_list = var.block_ip
  skipped_ip_range_list = var.skipped_ip
}
```

and that the error is when handling `risk_exception_configuration`. Are `var.block_ip` and `var.skipped_ip` set to `null`?

**Comment by rickychew77** [comment]
nope, the default value was set to `[]` in `variables.tf`
