### ISSUE TITLE
[Bug]: Cannot create custom connector profile

### ISSUE THREAD

**Issue by yzouyang** [hashicorp/terraform-provider-aws#29507]
### Terraform Core Version

1.3.9

### AWS Provider Version

4.54.0

### Affected Resource(s)

- aws_appflow_connector_profile

### Expected Behavior

Custom connector profile created

### Actual Behavior

Plugin crashed

### Relevant Error/Panic Output Snippet

```shell
module.appflow_facebook.aws_appflow_connector_profile.custom_connector_profile: Creating...

Stack trace from the terraform-provider-aws_v4.54.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 358 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/appflow.expandConnectorProfileConfig(0x0?)
        github.com/hashicorp/terraform-provider-aws/internal/service/appflow/connector_profile.go:1518 +0x15c
github.com/hashicorp/terraform-provider-aws/internal/service/appflow.resourceConnectorProfileCreate({0x1110c7740, 0x140059c0ff0}, 0x0?, {0x110f86360?, 0x1400037b800})
        github.com/hashicorp/terraform-provider-aws/internal/service/appflow/connector_profile.go:1416 +0x154
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1110c7740?, {0x1110c7740?, 0x140059c0ff0?}, 0xd?, {0x110f86360?, 0x1400037b800?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:702 +0x64
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x14000de5500, {0x1110c7740, 0x140059c0ff0}, 0x140026b69c0, 0x140059e6a00, {0x110f86360, 0x1400037b800})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:837 +0x86c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1400011e3a8, {0x1110c7740?, 0x140059c0ed0?}, 0x140059e42d0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1021 +0xb70
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0x140031e3950, 0x140031e39b0, {0x140047dee40, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0xdc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x14001a1f400, {0x1110c7740?, 0x140059c0150?}, 0x140025ae070)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x3b8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x110ca3900?, 0x14001a1f400}, {0x1110c7740, 0x140059c0150}, 0x140025ae000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x140000710e0, {0x1110d6600, 0x140039c41a0}, 0x14005b06120, 0x140048b8750, 0x11761cac0, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1336 +0xb7c
google.golang.org/grpc.(*Server).handleStream(0x140000710e0, {0x1110d6600, 0x140039c41a0}, 0x14005b06120, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1704 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.53.0/server.go:965 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.53.0/server.go:963 +0x290

Error: The terraform-provider-aws_v4.54.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Configuration Files

```terraform
provider "aws" {
  region = ap-southeast-1
}
provider "awscc" {
  region = ap-southeast-1
}

terraform {
  required_version = "~> 1.3.9"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.54.0"
    }
    awscc = {
      source  = "hashicorp/awscc"
      version = "~> 0.46.0"
    }
  }
}

```

### Steps to Reproduce

Prerequisite: a custom AppFlow connector labelled as "Custom_Destination_Connector" has been registered with custom authentication type

```terraform
resource "aws_appflow_connector_profile" "custom_connector_profile" {
  connection_mode = "Public"
  connector_type  = "CustomConnector"
  connector_label = "Custom_Destination_Connector"
  name            = "custom_connector_profile"
  connector_profile_config {
    connector_profile_credentials {
      custom_connector {
        authentication_type = "CUSTOM"
        custom {
          custom_authentication_type = "custom-type"
          credentials_map = {
            key1 = "value1"
            key2 = "value2"
          }
        }
      }
    }
    connector_profile_properties {}
  }
}
```

### Would you like to implement a fix?

None

**Comment by rnordmanASU** [comment]
@justinretzolk 

Hi, I'm a completely different person, but I seem to be having the same issue.  Here's some things I've tried and the corresponding errors.

Include custom_connector block, but leave it empty.  This should work since both of the custom_connector's arguments are optional:
```
connector_profile_properties {
  custom_connector {}
}
```
however, this still results in a panic.
<details><summary>Stack Trace</summary>
<p>

```
Stack trace from the terraform-provider-aws_v5.7.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 406 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/appflow.expandConnectorProfileProperties(0xc298960?)
	github.com/hashicorp/terraform-provider-aws/internal/service/appflow/connector_profile.go:1933 +0x12d4
github.com/hashicorp/terraform-provider-aws/internal/service/appflow.expandConnectorProfileConfig(0xc0005e2c38?)
	github.com/hashicorp/terraform-provider-aws/internal/service/appflow/connector_profile.go:1522 +0xf4
github.com/hashicorp/terraform-provider-aws/internal/service/appflow.resourceConnectorProfileCreate({0xf354260, 0xc00211c9c0}, 0xe03eea0?, {0xe03eea0?, 0xc00173c410?})
	github.com/hashicorp/terraform-provider-aws/internal/service/appflow/connector_profile.go:1420 +0x19b
github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0x0?, {0xe03eea0?, 0xc00173c410?})
	github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:111 +0x34b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xf354260?, {0xf354260?, 0xc0022aaf30?}, 0xd?, {0xe03eea0?, 0xc00173c410?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:728 +0x87
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000bcb0a0, {0xf354260, 0xc0022aaf30}, 0xc001b0bba0, 0xc0001fc580, {0xe03eea0, 0xc00173c410})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:864 +0xa7e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0017bb2d8, {0xf354260?, 0xc0022aae10?}, 0xc0026201e0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/grpc_provider.go:1024 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc0020b9500, 0xc001c5c2f0, 0xc0020b9530, 0xc0020b9560, {0xc00358fc40, 0x2, 0x2}}, {0xf354260?, 0xc0022aaae0?}, 0xc0026201e0)
	github.com/hashicorp/terraform-plugin-mux@v0.11.1/tf5muxserver/mux_server_ApplyResourceChange.go:30 +0x139
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0037be0a0, {0xf354260?, 0xc0022aa270?}, 0xc00175e1c0)
	github.com/hashicorp/terraform-plugin-go@v0.17.0/tfprotov5/tf5server/server.go:821 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xdd205a0?, 0xc0037be0a0}, {0xf354260, 0xc0022aa270}, 0xc00175e150, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.17.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:422 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000986000, {0xf361020, 0xc001b48000}, 0xc0026cc000, 0xc0020df500, 0x16211480, 0x0)
	google.golang.org/grpc@v1.56.1/server.go:1337 +0xdf3
google.golang.org/grpc.(*Server).handleStream(0xc000986000, {0xf361020, 0xc001b48000}, 0xc0026cc000, 0x0)
	google.golang.org/grpc@v1.56.1/server.go:1714 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.56.1/server.go:959 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.56.1/server.go:957 +0x18c

Error: The terraform-provider-aws_v5.7.0_x5 plugin crashed!
```

</p>
</details> 


Include custom_connector block, and include the profile_properties argument.  Leave it as an empty map:
```
connector_profile_properties {
  custom_connector {
    profile_properties = {}
  }
}
```
however, this still results in a panic.

<details><summary>Stack Trace</summary>
<p>

```
Stack trace from the terraform-provider-aws_v5.7.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 462 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/appflow.expandConnectorProfileProperties(0xc298960?)
	github.com/hashicorp/terraform-provider-aws/internal/service/appflow/connector_profile.go:1933 +0x12d4
github.com/hashicorp/terraform-provider-aws/internal/service/appflow.expandConnectorProfileConfig(0xc001ff6c38?)
	github.com/hashicorp/terraform-provider-aws/internal/service/appflow/connector_profile.go:1522 +0xf4
github.com/hashicorp/terraform-provider-aws/internal/service/appflow.resourceConnectorProfileCreate({0xf354260, 0xc002158000}, 0xe03eea0?, {0xe03eea0?, 0xc0028e9c70?})
	github.com/hashicorp/terraform-provider-aws/internal/service/appflow/connector_profile.go:1420 +0x19b
github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0x0?, {0xe03eea0?, 0xc0028e9c70?})
	github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:111 +0x34b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xf354260?, {0xf354260?, 0xc001ee3da0?}, 0xd?, {0xe03eea0?, 0xc0028e9c70?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:728 +0x87
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000bc90a0, {0xf354260, 0xc001ee3da0}, 0xc001f7bad0, 0xc000539180, {0xe03eea0, 0xc0028e9c70})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:864 +0xa7e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc003581308, {0xf354260?, 0xc001ee3c80?}, 0xc00035e0f0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/grpc_provider.go:1024 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc0028ed140, 0xc001e30340, 0xc0028ed170, 0xc0028ed1a0, {0xc0028fe580, 0x2, 0x2}}, {0xf354260?, 0xc001ee3950?}, 0xc00035e0f0)
	github.com/hashicorp/terraform-plugin-mux@v0.11.1/tf5muxserver/mux_server_ApplyResourceChange.go:30 +0x139
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0028fc1e0, {0xf354260?, 0xc001ee3140?}, 0xc001252150)
	github.com/hashicorp/terraform-plugin-go@v0.17.0/tfprotov5/tf5server/server.go:821 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xdd205a0?, 0xc0028fc1e0}, {0xf354260, 0xc001ee3140}, 0xc0012520e0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.17.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:422 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000af2000, {0xf361020, 0xc002a20000}, 0xc001efb320, 0xc0029a8fc0, 0x16211480, 0x0)
	google.golang.org/grpc@v1.56.1/server.go:1337 +0xdf3
google.golang.org/grpc.(*Server).handleStream(0xc000af2000, {0xf361020, 0xc002a20000}, 0xc001efb320, 0x0)
	google.golang.org/grpc@v1.56.1/server.go:1714 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.56.1/server.go:959 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.56.1/server.go:957 +0x18c

Error: The terraform-provider-aws_v5.7.0_x5 plugin crashed!

```

</p>
</details> 

Include custom_connector block, and include the profile_properties argument.  Put at least one entry in the map:
```
connector_profile_properties {
  custom_connector {
    profile_properties = {
      foo = "bar"
    }
  }
}
```
however, this fails (though does not panic) due to including an unused property.

<details><summary>Details</summary>
<p>

```
│ Error: creating AppFlow Connector Profile: ValidationException: ConnectorRuntimeSettings foo are not required but found.
│ 
│   with aws_appflow_connector_profile.to_postgres,
│   on appflow.tf line 41, in resource "aws_appflow_connector_profile" "to_postgres":
│   41: resource "aws_appflow_connector_profile" "to_postgres" {
```

</p>
</details>

**Comment by rnordmanASU** [comment]
As far as what I think should and should not work.
---

```
connector_profile_properties {}
```

should fail, as the corresponding AWS CLI command fails as well.

```
aws appflow create-connector-profile --connector-profile-name profile-name-foo --connection-mode Public --connector-label AmazonRDSPostgreSQL --connector-type CustomConnector --connector-profile-config '{"connectorProfileProperties":{},"connectorProfileCredentials":{"CustomConnector":{"authenticationType":"CUSTOM","custom":{"customAuthenticationType":"CUSTOM","credentialsMap":{"driver":"postgresql","hostname":"terraform-20220602185354403300000006.dvvzbbcawvo4.us-west-2.rds.amazonaws.com","port":"5432","database":"primary","username":"postgres","password":"foobar"}}}}}'
```

---

```
connector_profile_properties {
  custom_connector {}
}
```

(which is your suggestion) should work, as the corresponding AWS CLI command succeeds

```
aws appflow create-connector-profile --connector-profile-name profile-name-foo --connection-mode Public --connector-label AmazonRDSPostgreSQL --connector-type CustomConnector --connector-profile-config '{"connectorProfileProperties":{"CustomConnector": {}},"connectorProfileCredentials":{"CustomConnector":{"authenticationType":"CUSTOM","custom":{"customAuthenticationType":"CUSTOM","credentialsMap":{"driver":"postgresql","hostname":"terraform-20220602185354403300000006.dvvzbbcawvo4.us-west-2.rds.amazonaws.com","port":"5432","database":"primary","username":"postgres","password":"foobar"}}}}}'
```

---

```
connector_profile_properties {
  custom_connector {
    profile_properties = {}
  }
}
```

should work, as the corresponding AWS CLI command succeeds

```
aws appflow create-connector-profile --connector-profile-name profile-name-foo --connection-mode Public --connector-label AmazonRDSPostgreSQL --connector-type CustomConnector --connector-profile-config '{"connectorProfileProperties":{"CustomConnector": {"profileProperties":{}}},"connectorProfileCredentials":{"CustomConnector":{"authenticationType":"CUSTOM","custom":{"customAuthenticationType":"CUSTOM","credentialsMap":{"driver":"postgresql","hostname":"terraform-20220602185354403300000006.dvvzbbcawvo4.us-west-2.rds.amazonaws.com","port":"5432","database":"primary","username":"postgres","password":"foobar"}}}}}'
```

---

```
connector_profile_properties {
  custom_connector {
    profile_properties = {
      foo = "bar"
    }
  }
}
```

should fail, as the corresponding AWS CLI command fails as well.

```
aws appflow create-connector-profile --connector-profile-name profile-name-foo --connection-mode Public --connector-label AmazonRDSPostgreSQL --connector-type CustomConnector --connector-profile-config '{"connectorProfileProperties":{"CustomConnector": {"profileProperties":{"foo":"bar"}}},"connectorProfileCredentials":{"CustomConnector":{"authenticationType":"CUSTOM","custom":{"customAuthenticationType":"CUSTOM","credentialsMap":{"driver":"postgresql","hostname":"terraform-20220602185354403300000006.dvvzbbcawvo4.us-west-2.rds.amazonaws.com","port":"5432","database":"primary","username":"postgres","password":"foobar"}}}}}'
```

---

So, in conclusion

The expected behavior would be:
1. custom_connector not specified -> error.
2. custom_connector specified and empty -> success.
3. custom_connector specified with an empty profile_properties attribute -> success.
4. custom_connector specified with profile_properties with unused attributes -> error.

And currently all 4 cases cause some sort of error.
1. Leads to a panic as reported by yzouyang (OP)
2. Leads to a panic as report by rnordmanASU (me)
3. Leads to a panic as report by rnordmanASU (me)
4. Leads to an error as report by rnordmanASU (me)

**Comment by ciancullinan** [comment]
I managed to get this working by passing some dummy `oauth2_properties`.  They're valid properties so pass the validation, but are never used by custom connector. 
```
    connector_profile_properties {
      custom_connector {
        oauth2_properties {
          oauth2_grant_type = "AUTHORIZATION_CODE"
          token_url = "https://localhost.com"
        }
      }
    }
```

**Comment by rnordmanASU** [comment]
I have confirmed that @ciancullinan's workaround works.  I'll use that for now.  Thank you.

**Comment by tusharpandit18** [comment]
I tried using  @ciancullinan's workaround, but it did not work for me.

**Comment by tusharpandit18** [comment]
Hi, when I click on [v5.21.0 of the Terraform AWS Provider](https://github.com/hashicorp/terraform-provider-aws/blob/v5.21.0/CHANGELOG.md), it says the version is still unreleased; 
I have a configuration as 
`terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "~> 5.0"
    }
    }`
which automatically picks the latest version; when do you think the version will be released?
