### ISSUE TITLE
[Bug]: AWS provider crashes with panic

### ISSUE THREAD

**Issue by axeladp** [hashicorp/terraform-provider-aws#29548]
### Terraform Core Version

1.3.9

### AWS Provider Version

4.55.0

### Affected Resource(s)

* aws_efs_file_system

### Expected Behavior

Terraform should display the execution plan

### Actual Behavior

Terraform crashes

### Relevant Error/Panic Output Snippet

```shell
panic: Error reading level state: strconv.ParseInt: parsing "3992352768": value out of range
```

### Terraform Configuration Files

[topology.txt](https://github.com/hashicorp/terraform-provider-aws/files/10793069/topology.txt)

### Steps to Reproduce

1. Create a aws_efs_filesystem using "terraform apply" on the attached configuration file.
2. Edit the resulting state file. Modify the value of the property aws_efs_file_system.test-fs.size_in_bytes.value to 3992352768
3. Do "terraform plan"
4. Note the panic message contains the value inserted in the tf state file in a previous step.

### Panic Output

╷
│ Error: Plugin did not respond
│ 
│   with aws_efs_file_system.test-fs,
│   on topology.tf line 15, in resource "aws_efs_file_system" "test-fs":
│   15: resource "aws_efs_file_system" "test-fs" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵

Stack trace from the terraform-provider-aws_v4.55.0_x5 plugin:

panic: Error reading level state: strconv.ParseInt: parsing "3992352768": value out of range

goroutine 358 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0x1e1a1770, {0x1d937e20, 0x1, 0x1}, 0x8)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource_data.go:553 +0x279
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).State(0x1e1a1770)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource_data.go:351 +0x3a7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ShimInstanceStateFromValue(0x1c344c40, {{{0x14471a80, 0x1d9370a8}}, {0x11702d60, 0x1d6bede0}})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:599 +0x1d9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x1d561130, {0x14471240, 0x1e5972d8}, 0x1d6be700)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:587 +0x23f
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadResource({0x1d5a09c0, 0x1d5a0a00, {0x1e49b540, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.9.0/tf5muxserver/mux_server_ReadResource.go:26 +0x151
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x1e1569b0, {0x14471240, 0x1e596f18}, 0x1de3e840)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x4c5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x12f05780, 0x1e1569b0}, {0x14471240, 0x1e596f18}, 0x1e487d80, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x18a
google.golang.org/grpc.(*Server).processUnaryRPC(0x1e17a5a0, {0x14476d70, 0x1e5e4000}, 0x1e48cc80, 0x1e530738, 0x1a55c508, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1336 +0xe22
google.golang.org/grpc.(*Server).handleStream(0x1e17a5a0, {0x14476d70, 0x1e5e4000}, 0x1e48cc80, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1704 +0xa17
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.53.0/server.go:965 +0xb1
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.53.0/server.go:963 +0x25f

Error: The terraform-provider-aws_v4.55.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Important Factoids

When working on a Mac, we do not experience this problem.

The problem was encountered when working on a Linux server using a state shared through S3
Linux lx10594 4.18.0-372.26.1.el8_6.x86_64 #1 SMP Sat Aug 27 02:44:20 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

We were able to reproduce the issue on the above Linux using the method described above, with a local state file.

### Would you like to implement a fix?

None

**Comment by axeladp** [comment]
This issue has been resolved.

The problem was that a 32 bit version of terraform was installed.
