### ISSUE TITLE
[Bug]: Modifying...Error: Plugin did not respond

### ISSUE THREAD

**Issue by daine** [hashicorp/terraform-provider-aws#29691]
### Terraform Core Version

1.3.9

### AWS Provider Version

v4.55.0_x5

### Affected Resource(s)

`aws_amplify_app`

### Expected Behavior

Changes should have been applied

### Actual Behavior

Changes have not been applied

### Relevant Error/Panic Output Snippet

```shell
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 401 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/amplify.resourceAppUpdate({0xef1e2e0, 0xc003d97c50}, 0xc000656500, {0xdaa2c00?, 0xc0003c2800})
	github.com/hashicorp/terraform-provider-aws/internal/service/amplify/app.go:489 +0x1ad1
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xef1e2e0?, {0xef1e2e0?, 0xc003d97c50?}, 0xd?, {0xdaa2c00?, 0xc0003c2800?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:736 +0x87
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000cfd960, {0xef1e2e0, 0xc003d97c50}, 0xc00065a8f0, 0xc000656380, {0xdaa2c00, 0xc0003c2800})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:847 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0001318c0, {0xef1e2e0?, 0xc003d974d0?}, 0xc0005bc500)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc003292360, 0xc0032923c0, {0xc004be0a20, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.9.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0022cf720, {0xef1e2e0?, 0xc003d7c9c0?}, 0xc000644070)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xd7bf9c0?, 0xc0022cf720}, {0xef1e2e0, 0xc003d7c9c0}, 0xc000644000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00443f860, {0xef2d560, 0xc000250680}, 0xc000628000, 0xc004ca28a0, 0x1555db40, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc00443f860, {0xef2d560, 0xc000250680}, 0xc000628000, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-aws_v4.55.0_x5 plugin crashed!
```

### Terraform Configuration Files

```
terraform {
  required_version = "= 1.3.9"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
  }
}

provider "aws" {
  region              = var.region
  allowed_account_ids = [var.account_id]
}

resource "aws_amplify_app" "test_app" {
  name       = "test app"
  repository = "https://github.com/test-app"

  access_token = var.gh_access_token

  build_spec = <<-EOT
    version: 1
    frontend:
      phases:
        preBuild:
          commands:
            - cd app
            - npm install
        build:
          commands:
            - npm run generate
      artifacts:
        baseDirectory: app/dist
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
  EOT

  # The default rewrites and redirects added by the Amplify Console.
  custom_rule {
    source = "/<*>"
    status = "404"
    target = "/index.html"
  }

  environment_variables = {
    ENV                         = var.env
    DOMAIN_EN                   = var.domain_name
    DOMAIN_FR                   = var.fr_domain_name
    GOOGLE_ANALYTICS_ID         = var.google_analytics_id
    GOOGLE_TAG_MANAGER_ID       = var.google_tag_manager_id
    SENTRY_DSN                  = var.sentry_dsn
  }

  enable_auto_branch_creation = true
  enable_branch_auto_deletion = true

  # The default patterns added by the Amplify Console.
  auto_branch_creation_patterns = [
    "feature*/",
    "release*",
    "fix*",
    "ci*"
  ]

  auto_branch_creation_config {
    # Enable auto build for the created branch.
    enable_auto_build             = true
    enable_pull_request_preview   = true
    pull_request_environment_name = "rc"
    stage                         = "PRODUCTION"
  }
}

resource "aws_amplify_branch" "main" {
  app_id      = aws_amplify_app.test_app.id
  branch_name = "main"

  framework = ""

  # Could be one of: PRODUCTION, BETA, DEVELOPMENT, EXPERIMENTAL, PULL_REQUEST
  stage = "PRODUCTION"

  display_name = "production"

  enable_pull_request_preview = false
}

resource "aws_amplify_domain_association" "test_app_en" {

  app_id      = aws_amplify_app.test_app.id
  domain_name = var.domain_name

  wait_for_verification = false

  sub_domain {
    branch_name = aws_amplify_branch.main.branch_name
    prefix      = ""
  }

  sub_domain {
    branch_name = aws_amplify_branch.main.branch_name
    prefix      = "www"
  }
}

resource "aws_amplify_domain_association" "test_app_fr" {

  app_id      = aws_amplify_app.test_app.id
  domain_name = var.fr_domain_name

  wait_for_verification = false

  sub_domain {
    branch_name = aws_amplify_branch.main.branch_name
    prefix      = ""
  }

  sub_domain {
    branch_name = aws_amplify_branch.main.branch_name
    prefix      = "www"
  }
}


resource "aws_amplify_branch" "test_app_staging" {

  app_id      = aws_amplify_app.test_app.id
  branch_name = "staging"

  framework = ""

  # Could be one of: PRODUCTION, BETA, DEVELOPMENT, EXPERIMENTAL, PULL_REQUEST
  stage = "BETA"

  display_name = "staging"

  enable_pull_request_preview = true

  pull_request_environment_name = "PULL_REQUEST"

  environment_variables = {
    ENV       = var.env
    DOMAIN_EN = "staging.${var.domain_name}"
    DOMAIN_FR = "staging.${var.fr_domain_name}"
  }
}

resource "aws_amplify_domain_association" "test_app_staging_en" {

  app_id      = aws_amplify_app.test_app.id
  domain_name = "staging.${var.domain_name}"

  wait_for_verification = false

  sub_domain {
    branch_name = aws_amplify_branch.test_app_staging.branch_name
    prefix      = ""
  }

  sub_domain {
    branch_name = aws_amplify_branch.test_app_staging.branch_name
    prefix      = "www"
  }
}

resource "aws_amplify_domain_association" "test_app_fr" {

  app_id      = aws_amplify_app.test_app.id
  domain_name = "staging.${var.fr_domain_name}"

  wait_for_verification = false

  sub_domain {
    branch_name = aws_amplify_branch.test_app_staging.branch_name
    prefix      = ""
  }

  sub_domain {
    branch_name = aws_amplify_branch.test_app_staging.branch_name
    prefix      = "www"
  }
}
```

### Steps to Reproduce

terraform plan
terraform apply

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/8af0bd79119df3f3f8e642b931b0281bef29bb39/internal/service/amplify/app.go#L488-L496
