### ISSUE TITLE
[Bug]: fatal error: concurrent map writes

### ISSUE THREAD

**Issue by Xilaew** [hashicorp/terraform-provider-aws#29986]
### Terraform Core Version

1.3.7

### AWS Provider Version

4.53.0_x5

### Affected Resource(s)

a .tftpl file has been modified

### Expected Behavior

The terraform apply command runs nicely

### Actual Behavior

The application crashed

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-aws_v4.53.0_x5 plugin:

fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 43 [running]:
github.com/hashicorp/terraform-plugin-log/tflog.SetField.func1(...)
        github.com/hashicorp/terraform-plugin-log@v0.7.0/internal/logging/options.go:212
github.com/hashicorp/terraform-plugin-log/tflog.SetField({0x111de0100, 0x14002909530}, {0x10d7f7628, 0xb}, {0x10f4c88a0?, 0x14003251230})
        github.com/hashicorp/terraform-plugin-log@v0.7.0/tflog/provider.go:18 +0xa0
github.com/hashicorp/aws-sdk-go-base/v2/awsv1shim/v2.setAWSFields({0x111de0100?, 0x1400352e570?}, 0x14003ba4500)
        github.com/hashicorp/aws-sdk-go-base/v2/awsv1shim/v2@v2.0.0-beta.23/logger.go:40 +0x88
github.com/hashicorp/aws-sdk-go-base/v2/awsv1shim/v2.logRequest(0x14003ba4500)
        github.com/hashicorp/aws-sdk-go-base/v2/awsv1shim/v2@v2.0.0-beta.23/logger.go:69 +0x58
github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0x14003ba4728, 0x14003ba4500)
        github.com/aws/aws-sdk-go@v1.44.191/aws/request/handlers.go:267 +0x88
github.com/aws/aws-sdk-go/aws/request.(*Request).sendRequest(0x14003ba4500)
        github.com/aws/aws-sdk-go@v1.44.191/aws/request/request.go:602 +0x94
github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0x14003ba4500)
        github.com/aws/aws-sdk-go@v1.44.191/aws/request/request.go:555 +0x114
github.com/aws/aws-sdk-go/aws/request.(*Pagination).Next(0x14003aa5bc8)
        github.com/aws/aws-sdk-go@v1.44.191/aws/request/request_pagination.go:107 +0xc4
github.com/aws/aws-sdk-go/service/ec2.(*EC2).DescribeNetworkInterfacesPagesWithContext(0x140023d46c0, {0x111de0100?, 0x1400352e570}, 0x140033a50e0, 0x14003aa5d00, {0x0, 0x0, 0x0})
        github.com/aws/aws-sdk-go@v1.44.191/service/ec2/api.go:26518 +0x12c
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.FindNetworkInterfaces({0x111de0100?, 0x1400352e570?}, 0x48?, 0x140033a50e0)
        github.com/hashicorp/terraform-provider-aws/internal/service/ec2/find.go:1526 +0x70
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.FindNetworkInterface({0x111de0100?, 0x1400352e570?}, 0x140000b0900?, 0x140033a50e0)
        github.com/hashicorp/terraform-provider-aws/internal/service/ec2/find.go:1506 +0x28
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.FindNetworkInterfaceByID({0x111de0100, 0x1400352e570}, 0x140000aa618?, {0x140006c2bd0, 0x15})
        github.com/hashicorp/terraform-provider-aws/internal/service/ec2/find.go:1559 +0x118
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.StatusNetworkInterfaceStatus.func1()
        github.com/hashicorp/terraform-provider-aws/internal/service/ec2/status.go:1123 +0x30
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext.func1()
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/resource/state.go:110 +0x164
created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/resource/state.go:83 +0x1a4

goroutine 1 [select]:
github.com/hashicorp/go-plugin.Serve(0x140048c7c80)
        github.com/hashicorp/go-plugin@v1.4.8/server.go:471 +0x10f0
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.Serve({0x10d90c4bf, 0x23}, 0x1400424d8c0, {0x0, 0x0, 0x0})
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:312 +0x9e0
main.main()
        github.com/hashicorp/terraform-provider-aws/main.go:32 +0x1bc

goroutine 328 [select]:
github.com/hashicorp/go-plugin.(*gRPCBrokerServer).Recv(0x140003b27e0?)
        github.com/hashicorp/go-plugin@v1.4.8/grpc_broker.go:121 +0x58
github.com/hashicorp/go-plugin.(*GRPCBroker).Run(0x14004512f50)
        github.com/hashicorp/go-plugin@v1.4.8/grpc_broker.go:411 +0x40
created by github.com/hashicorp/go-plugin.(*GRPCServer).Init
        github.com/hashicorp/go-plugin@v1.4.8/grpc_server.go:85 +0x424

goroutine 329 [IO wait]:
internal/poll.runtime_pollWait(0x143887810, 0x72)
        runtime/netpoll.go:305 +0xa0
internal/poll.(*pollDesc).wait(0x1400497c120?, 0x1400358c000?, 0x1)
        internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
        internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x1400497c120, {0x1400358c000, 0x1000, 0x1000})
        internal/poll/fd_unix.go:167 +0x1e0
os.(*File).read(...)
        os/file_posix.go:31
os.(*File).Read(0x1400483a938, {0x1400358c000?, 0x400?, 0x10f5ae180?})
        os/file.go:118 +0x5c
bufio.(*Reader).Read(0x140000a9730, {0x1400358e000, 0x400, 0x0?})
        bufio/bufio.go:237 +0x1e0
github.com/hashicorp/go-plugin.copyChan({0x111e08790, 0x14004385b00}, 0x0?, {0x111d22f60?, 0x1400483a938?})
        github.com/hashicorp/go-plugin@v1.4.8/grpc_stdio.go:181 +0x154
created by github.com/hashicorp/go-plugin.newGRPCStdioServer
        github.com/hashicorp/go-plugin@v1.4.8/grpc_stdio.go:37 +0x10c

goroutine 330 [IO wait]:
internal/poll.runtime_pollWait(0x143887630, 0x72)
        runtime/netpoll.go:305 +0xa0
internal/poll.(*pollDesc).wait(0x1400497c1e0?, 0x14000ef0000?, 0x1)
        internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
        internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x1400497c1e0, {0x14000ef0000, 0x1000, 0x1000})
        internal/poll/fd_unix.go:167 +0x1e0
os.(*File).read(...)
        os/file_posix.go:31
os.(*File).Read(0x1400483a948, {0x14000ef0000?, 0x400?, 0x10f5ae180?})
        os/file.go:118 +0x5c
bufio.(*Reader).Read(0x140000a9f30, {0x14000ef2000, 0x400, 0x0?})
        bufio/bufio.go:237 +0x1e0
github.com/hashicorp/go-plugin.copyChan({0x111e08790, 0x14004385b00}, 0x0?, {0x111d22f60?, 0x1400483a948?})
        github.com/hashicorp/go-plugin@v1.4.8/grpc_stdio.go:181 +0x154
created by github.com/hashicorp/go-plugin.newGRPCStdioServer
        github.com/hashicorp/go-plugin@v1.4.8/grpc_stdio.go:38 +0x198

goroutine 337 [syscall]:
os/signal.signal_recv()
        runtime/sigqueue.go:149 +0x2c
os/signal.loop()
        os/signal/signal_unix.go:23 +0x1c
created by os/signal.Notify.func1.1
        os/signal/signal.go:151 +0x2c

goroutine 338 [chan receive]:
github.com/hashicorp/go-plugin.Serve.func3()

Error: The terraform-provider-aws_v4.53.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Configuration Files

I cant reproduce, I hope the panic log gives you a hint.

### Steps to Reproduce

I cant reproduce, I hope the panic log gives you a hint.

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
@Xilaew Thanks for raising this issue.
It has already been noticed in #29308. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
