### ISSUE TITLE
[Bug]: Error when creating aws_scheduler_schedule

### ISSUE THREAD

**Issue by datngxtiens** [hashicorp/terraform-provider-aws#30306]
### Terraform Core Version

1.4.2

### AWS Provider Version

4.56.0

### Affected Resource(s)

aws_scheduler_schedule

### Expected Behavior

The EventBridge scheduler created successfully.

### Actual Behavior

Error creating.

### Relevant Error/Panic Output Snippet

```shell
Error: Request cancelled
│ 
│   with module.eventbridge["xxx"].aws_scheduler_schedule.this,
│   on .terraform/modules/eventbridge/event_scheduler/main.tf line 11, in resource "aws_scheduler_schedule" "this":
│   11: resource "aws_scheduler_schedule" "this" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-aws_v4.56.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 682 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/scheduler.expandTarget({0x11122afc0, 0x14003b5bb90}, 0x14003bdad50)
        github.com/hashicorp/terraform-provider-aws/internal/service/scheduler/flex.go:615 +0xc58
github.com/hashicorp/terraform-provider-aws/internal/service/scheduler.resourceScheduleCreate({0x11122afc0?, 0x14003b5bb90}, 0x0?, {0x1110e7120?, 0x140003f5400})
        github.com/hashicorp/terraform-provider-aws/internal/service/scheduler/schedule.go:475 +0x8c0
github.com/hashicorp/terraform-provider-aws/internal/provider.wrappedCreateContextFunc.func1({0x11122afc0?, 0x14003b5bb90?}, 0x0?, {0x1110e7120?, 0x140003f5400?})
        github.com/hashicorp/terraform-provider-aws/internal/provider/provider.go:2727 +0x44
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x11122afc0?, {0x11122afc0?, 0x14003b5bb90?}, 0xd?, {0x1110e7120?, 0x140003f5400?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:702 +0x64
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x140031ebce0, {0x11122afc0, 0x14003b5bb90}, 0x140058c0c30, 0x14005175d00, {0x1110e7120, 0x140003f5400})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:837 +0x86c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1400000cae0, {0x11122afc0?, 0x14003b5ba70?}, 0x14003475c70)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:1021 +0xb70
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0x140031ddf20, 0x140031ddf80, {0x14004ab95c0, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.9.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0xdc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x14001ba0780, {0x11122afc0?, 0x14003b5adb0?}, 0x1400587d570)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x3b8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x110dfc7c0?, 0x14001ba0780}, {0x11122afc0, 0x14003b5adb0}, 0x1400587d500, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400433bc20, {0x111239e40, 0x14004bac820}, 0x140058ba5a0, 0x14004b29a10, 0x117850520, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1336 +0xb7c
google.golang.org/grpc.(*Server).handleStream(0x1400433bc20, {0x111239e40, 0x14004bac820}, 0x140058ba5a0, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1704 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.53.0/server.go:965 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.53.0/server.go:963 +0x290

Error: The terraform-provider-aws_v4.56.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Configuration Files

```hcl
data "aws_caller_identity" "current" {}

data "aws_region" "current" {}

locals {
  prefix     = "${var.environment}-${var.account}-${var.project}"
  account_id = data.aws_caller_identity.current.account_id
  region     = data.aws_region.current.name
}

resource "aws_scheduler_schedule" "this" {
  name       = "${local.prefix}-${var.name_prefix}-scheduler"
  group_name = var.group_name

  flexible_time_window {
    mode                      = var.window_mode
    maximum_window_in_minutes = var.maximum_window
  }

  schedule_expression          = var.schedule_expression
  schedule_expression_timezone = var.schedule_expression_timezone
  start_date                   = var.start_date
  end_date                     = var.end_date
  state                        = var.scheduler_state

  target {
    arn      = var.target_arn
    role_arn = var.custom_policy != true ? var.default_policy_arn : aws_iam_role.this[0].arn
    input    = var.input

    dead_letter_config {
      arn = var.dead_letter_queue_arn
    }

    retry_policy {
      maximum_event_age_in_seconds = var.maximum_event_age
      maximum_retry_attempts       = var.maximum_retry_attempts
    }
  }
}
```

### Steps to Reproduce

run `terraform apply`,

output of `terraform plan`:

```
# module.eventbridge["xxx"].aws_scheduler_schedule.this will be created
  + resource "aws_scheduler_schedule" "this" {
      + arn                          = (known after apply)
      + group_name                   = "default"
      + id                           = (known after apply)
      + name                         = "xxx"
      + name_prefix                  = (known after apply)
      + schedule_expression          = "cron(0/15 5-10 * * ? *)"
      + schedule_expression_timezone = "Asia/Ho_Chi_Minh"
      + state                        = "ENABLED"

      + flexible_time_window {
          + mode = "OFF"
        }

      + target {
          + arn      = "xxx"
          + input    = jsonencode({})
          + role_arn = "xxx"

          + dead_letter_config {}

          + retry_policy {
              + maximum_event_age_in_seconds = 60
              + maximum_retry_attempts       = 0
            }
        }
    }
```

### Would you like to implement a fix?

None

**Comment by datngxtiens** [comment]
After searching around, I found that before apply, do this command `export GODEBUG=asyncpreemptoff=1` seems to fix the problem. Don't know why it helps.

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/2e39279d125e40559587302d5f56d5bec782af24/internal/service/scheduler/flex.go#LL603-L616
