### ISSUE TITLE
[Bug]: Crash when trying to change master password for RDS

### ISSUE THREAD

**Issue by jose-sky** [hashicorp/terraform-provider-aws#30383]
### Terraform Core Version

1.3.4

### AWS Provider Version

4.61.0

### Affected Resource(s)

aws_db_instance

### Expected Behavior

Changing the password should take an effect on the AWS resource and change the master password

### Actual Behavior

Crash

### Relevant Error/Panic Output Snippet

```shell
module.gitlab_postgres.aws_db_instance.postgresdb: Modifying... [id=gitlab]
╷
│ Error: Plugin did not respond
│ 
│   with module.gitlab_postgres.aws_db_instance.postgresdb,
│   on .terraform/modules/gitlab_postgres/main.tf line 6, in resource "aws_db_instance" "postgresdb":
│    6: resource "aws_db_instance" "postgresdb" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-aws_v4.61.0_x5 plugin:

panic: interface conversion: interface {} is string, not []interface {}

goroutine 419 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/rds.dbInstancePopulateModify(0xc0006061e0, 0xe0179fd?)
        github.com/hashicorp/terraform-provider-aws/internal/service/rds/instance.go:2142 +0x2074
github.com/hashicorp/terraform-provider-aws/internal/service/rds.resourceInstanceUpdate({0xf483320?, 0xc003eaed20}, 0xc000557180, {0xdf84d00?, 0xc000388c00})
        github.com/hashicorp/terraform-provider-aws/internal/service/rds/instance.go:1965 +0x3593
github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0x0?, {0xdf84d00?, 0xc000388c00?})
        github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:94 +0x175
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xf483320?, {0xf483320?, 0xc003e73230?}, 0xd?, {0xdf84d00?, 0xc000388c00?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:736 +0x87
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc001bb3500, {0xf483320, 0xc003e73230}, 0xc00129fa00, 0xc000557000, {0xdf84d00, 0xc000388c00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:847 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000250360, {0xf483320?, 0xc003e721b0?}, 0xc0055dd180)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc003478cf0, 0xc003478d50, {0xc0047ff2e0, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.9.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00213c460, {0xf483320?, 0xc003e56c30?}, 0xc00084e4d0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xdc89e80?, 0xc00213c460}, {0xf483320, 0xc003e56c30}, 0xc00084e460, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc004906000, {0xf492aa0, 0xc0046011e0}, 0xc0043ec480, 0xc00490a270, 0x15cd9f80, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc004906000, {0xf492aa0, 0xc0046011e0}, 0xc0043ec480, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-aws_v4.61.0_x5 plugin crashed!
```

### Terraform Configuration Files

N/A

### Steps to Reproduce

Create Postgres DB with aws_db_instance 
After creation try to change the master password value (password)

### Debug Output

Error: The terraform-provider-aws_v4.61.0_x5 plugin crashed!

### Would you like to implement a fix?

None

**Comment by bendotexe** [comment]
Looks like the same issue I'm having here:
https://github.com/hashicorp/terraform-provider-aws/issues/30372
Relates https://github.com/hashicorp/terraform-provider-aws/pull/28848
