### ISSUE TITLE
[Bug]: panic: interface conversion: interface {} is string, not []interface {}

### ISSUE THREAD

**Issue by jw-maynard** [hashicorp/terraform-provider-aws#30462]
### Terraform Core Version

1.4.4

### AWS Provider Version

4.61.0

### Affected Resource(s)

* aws_security_group_rule
* aws_rds_cluster

### Expected Behavior

Terraform should not have panicked and should have updated my settings

### Actual Behavior

Terraform panicked:

```
Error: Plugin did not respond
with module.tg_service.module.aurora_cluster["live"].aws_security_group_rule.allow_all_egress
on .terraform/modules/tg_service.aurora_cluster/security_groups.tf line 65, in resource "aws_security_group_rule" "allow_all_egress":
resource "aws_security_group_rule" "allow_all_egress" {
The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
```

```
Error: Plugin did not respond
with module.tg_service.module.aurora_cluster["live"].aws_rds_cluster.cluster
on .terraform/modules/tg_service.aurora_cluster/main.tf line 5, in resource "aws_rds_cluster" "cluster":
resource "aws_rds_cluster" "cluster" {
The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
```

### Relevant Error/Panic Output Snippet

```shell
Stack trace from the terraform-provider-aws_v4.61.0_x5 plugin:

panic: interface conversion: interface {} is string, not []interface {}

goroutine 424 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/rds.resourceClusterUpdate({0xe8838a0?, 0xc005fd34d0}, 0xc0051dce00, {0xd384cc0?, 0xc000473800})
github.com/hashicorp/terraform-provider-aws/internal/service/rds/cluster.go:1282 +0x37b4
github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0x0?, {0xd384cc0?, 0xc000473800?})
github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:94 +0x175
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xe8838a0?, {0xe8838a0?, 0xc005e93020?}, 0xd?, {0xd384cc0?, 0xc000473800?})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:736 +0x87
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc001944a80, {0xe8838a0, 0xc005e93020}, 0xc005eae9c0, 0xc0051dc980, {0xd384cc0, 0xc000473800})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:847 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00114d800, {0xe8838a0?, 0xc005e92f00?}, 0xc0051d4910)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc0033a5230, 0xc0033a5290, {0xc003803bc0, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
github.com/hashicorp/terraform-plugin-mux@v0.9.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc002b98640, {0xe8838a0?, 0xc005e923c0?}, 0xc0051da690)
github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xd0899e0?, 0xc002b98640}, {0xe8838a0, 0xc005e923c0}, 0xc0051da620, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000539680, {0xe892fa0, 0xc003c84b60}, 0xc0051cb440, 0xc0041d7140, 0x150d5e00, 0x0)
google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc000539680, {0xe892fa0, 0xc003c84b60}, 0xc0051cb440, 0x0)
google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-aws_v4.61.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Configuration Files

The code is to complex to list here and no specific changes were made to the code, I just imported some resources that were not entirely properly configured and was going to let Terraform bring them into compliance. I'll post the detected plan changes though:

```
module.tg_service.module.aurora_cluster["live"].aws_security_group_rule.allow_all_egress:
description : "" change to "Allow all egress traffic"
```

```
module.tg_service.module.aurora_cluster["live"].aws_rds_cluster.cluster
create apply_immediately : true
update db_cluster_parameter_group_name : "default.aurora-postgresql12" change to "live-octopusapi-aurora-postgresql12"
create enable_global_write_forwarding : false
update engine_version : "12.13" change to "12"
create final_snapshot_identifier : "live-octopusapi-aurora-postgresql-final"
create master_password : Sensitive value
update skip_final_snapshot : true change to false

update tags :
{
  update Name : "live-octopus" change to "live-octopusapi"
  update cluster_name : "live-octopus" change to "live-octopusapi"
  update responsibility : "octopus" change to "octopusapi"
}
update tags_all :
{
  update Name : "live-octopus" change to "live-octopusapi"
  update cluster_name : "live-octopus" change to "live-octopusapi"
  update responsibility : "octopus" change to "octopusapi"
}
```

### Steps to Reproduce

Not sure exactly

### Important Factoids

Important: the same config and changes work fine with v4.60.0 of the provider

### Would you like to implement a fix?

No

**Comment by jam01-lb** [comment]
Having the exact same issue with rds.db_instance after importing a resource

```
Stack trace from the terraform-provider-aws_v4.61.0_x5 plugin:

panic: interface conversion: interface {} is string, not []interface {}

goroutine 361 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/rds.dbInstancePopulateModify(0xc000490780, 0xd417cad?)
        github.com/hashicorp/terraform-provider-aws/internal/service/rds/instance.go:2142 +0x2074
github.com/hashicorp/terraform-provider-aws/internal/service/rds.resourceInstanceUpdate({0xe8838a0?, 0xc005948960}, 0xc0040c4d80, {0xd384cc0?, 0xc00043c800})
        github.com/hashicorp/terraform-provider-aws/internal/service/rds/instance.go:1965 +0x3593
github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0x0?, {0xd384cc0?, 0xc00043c800?})
        github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:94 +0x175
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xe8838a0?, {0xe8838a0?, 0xc00580a090?}, 0xd?, {0xd384cc0?, 0xc00043c800?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:736 +0x87
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00128a380, {0xe8838a0, 0xc00580a090}, 0xc0040d5450, 0xc0040c4c00, {0xd384cc0, 0xc00043c800})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:847 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0013ddaa0, {0xe8838a0?, 0xc0040e3f50?}, 0xc003c024b0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc001ef84b0, 0xc001ef8990, {0xc004d334a0, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.9.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0023274a0, {0xe8838a0?, 0xc0040e3410?}, 0xc0040e6540)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xd0899e0?, 0xc0023274a0}, {0xe8838a0, 0xc0040e3410}, 0xc0040e64d0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000490000, {0xe892fa0, 0xc00486f040}, 0xc0040f8b40, 0xc004dafa10, 0x150d5e00, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc000490000, {0xe892fa0, 0xc00486f040}, 0xc0040f8b40, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-aws_v4.61.0_x5 plugin crashed!
```

**Comment by ewbankkit** [comment]
@jw-maynard Thanks for raising this issue.
It has already been noticed in #30383 and #30372. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
