### ISSUE TITLE
[Bug]: The terraform-provider-aws_v4.61.0_x5 plugin crashed

### ISSUE THREAD

**Issue by OksanaH** [hashicorp/terraform-provider-aws#30506]
### Terraform Core Version

1.4.4

### AWS Provider Version

4.61.0

### Affected Resource(s)
I created an rds instance which was marked as tainted. I untainted it.
I tried to update the password for this rds instance and got the error

### Expected Behavior

Terraform is supposed to make necessary changes after running` terraform apply`

### Actual Behavior

I receive a Request cancelled error:

### Relevant Error/Panic Output Snippet

```shell
Stack trace from the terraform-provider-aws_v4.61.0_x5 plugin:

panic: interface conversion: interface {} is string, not []interface {}

goroutine 52 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/rds.dbInstancePopulateModify(0xc00558a000, 0xd417cad?)
        github.com/hashicorp/terraform-provider-aws/internal/service/rds/instance.go:2142 +0x2074
github.com/hashicorp/terraform-provider-aws/internal/service/rds.resourceInstanceUpdate({0xe8838a0?, 0xc003f02fc0}, 0xc00461b000, {0xd384cc0?, 0xc0003a2c00})
        github.com/hashicorp/terraform-provider-aws/internal/service/rds/instance.go:1965 +0x3593
github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0x0?, {0xd384cc0?, 0xc0003a2c00?})
        github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:94 +0x175
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xe8838a0?, {0xe8838a0?, 0xc003ebde30?}, 0xd?, {0xd384cc0?, 0xc0003a2c00?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:736 +0x87
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00178ad20, {0xe8838a0, 0xc003ebde30}, 0xc0054429c0, 0xc00461ae80, {0xd384cc0, 0xc0003a2c00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:847 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc001881a40, {0xe8838a0?, 0xc003ebdb00?}, 0xc002f40000)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc00310b470, 0xc00310b4d0, {0xc0046c4600, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.9.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc001639180, {0xe8838a0?, 0xc003ebc4b0?}, 0xc004e63110)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xd0899e0?, 0xc001639180}, {0xe8838a0, 0xc003ebc4b0}, 0xc004e630a0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0041be3c0, {0xe892fa0, 0xc003ab61a0}, 0xc0050b9200, 0xc00477c780, 0x150d5e00, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0041be3c0, {0xe892fa0, 0xc003ab61a0}, 0xc0050b9200, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-aws_v4.61.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Configuration Files

```
terraform {
  required_version = "~> 1.0"

  backend "s3" {
    encrypt = true
    bucket = "xxx"
    dynamodb_table = "xxxxx"
    role_arn = "xxxxxxx"
    region = "xxxxxx"
  }

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.33"
    }
    template = {
      version = "~> 2.1.2"
    }
  }
}

provider "aws" {
  region = "xxxxxx"
  assume_role {
    role_arn = "xxxxx"
    session_name = "terraform"
  }
}

```

### Steps to Reproduce

Create an RDS db
Deploy Terraform
Amend the db password
Attempt to deploy again

### Important Factoids

I've also tried using the older terraform version (1.3.1), and required providers version (4.10) but the result is the same.

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
@OksanaH Thanks for raising this issue.
It has already been noticed in #30383 and #30372. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
