### ISSUE TITLE
[Bug]: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by artur-coelho-planview** [hashicorp/terraform-provider-aws#30970]
### Terraform Core Version

>= 1.1.9

### AWS Provider Version

4.63.0_x5

### Affected Resource(s)

aws_codepipeline

### Expected Behavior

Update the resource

### Actual Behavior

Error: Plugin did not respond

### Relevant Error/Panic Output Snippet

```shell
Error: Plugin did not respond
│ 
│   with module.predictability_pipeline.aws_codepipeline.model_pipeline_retrigger,
│   on custom_modules/project/model-codepipeline.tf line 78, in resource "aws_codepipeline" "model_pipeline_retrigger":
│   78: resource "aws_codepipeline" "model_pipeline_retrigger" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The
│ plugin logs may contain more details.
╵

Stack trace from the terraform-provider-aws_v4.63.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x10b8249f0]

goroutine 2434 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker.FindAppByName({0x1102f9640, 0x140047d7470}, 0x14006b529c0?, {0x14004aa61ed, 0xe}, {0x14004aa61fc?, 0x7400014005894e28?}, {0x10bb135d8, 0xd}, {0x14004aa621d, ...})
        github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker/find.go:336 +0x170
github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker.resourceAppRead({0x1102f9640, 0x140047d7470}, 0x140039ec380, {0x1101a6960?, 0x140004aac00?})
        github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker/app.go:167 +0x2b0
github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0x0?, {0x1101a6960?, 0x140004aac00?})
        github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:96 +0x118
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x1102f9640?, {0x1102f9640?, 0x140047ca9c0?}, 0xd?, {0x1101a6960?, 0x140004aac00?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:719 +0x64
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x14001ad4700, {0x1102f9640, 0x140047ca9c0}, 0x14006b61ad0, {0x1101a6960, 0x140004aac00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:1015 +0x468
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x14001cb9338, {0x1102f9640?, 0x140047ca8a0?}, 0x14006b52840)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:613 +0x400
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadResource({0x1400337a690, 0x1400337a6f0, {0x140006af3c0, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.9.0/tf5muxserver/mux_server_ReadResource.go:26 +0xdc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x14002c50e60, {0x1102f9640?, 0x140047c5c80?}, 0x14005e32120)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x3e8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x10fe9d2a0?, 0x14002c50e60}, {0x1102f9640, 0x140047c5c80}, 0x14002536150, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400065e000, {0x110309440, 0x14004c2c340}, 0x14005e20a20, 0x14002095b90, 0x116c451b0, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1336 +0xb7c
google.golang.org/grpc.(*Server).handleStream(0x1400065e000, {0x110309440, 0x14004c2c340}, 0x14005e20a20, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1704 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.53.0/server.go:965 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.53.0/server.go:963 +0x290

Error: The terraform-provider-aws_v4.63.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Configuration Files

confidential

### Steps to Reproduce

attempt to update any terraform resources using the AWS plugins.
Hardcoding older versions did not fixed the issue, attempted with the following:
terraform-provider-aws_v4.62.0_x5
terraform-provider-aws_v4.60.0_x5 

### Panic Output

```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x10b8b1810]

goroutine 2380 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker.FindAppByName({0x1102e2860, 0x14002e30930}, 0x14000bb5040?, {0x14006b42a3d, 0xe}, {0x14006b42a4c?, 0x14000bb5040?}, {0x10bbb7d6b, 0xd}, {0x14006b42a6d, ...})
        github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker/find.go:336 +0x170
github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker.resourceAppRead({0x1102e2860, 0x14002e30930}, 0x14006d7a880, {0x110197fe0?, 0x140003a5400?})
        github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker/app.go:172 +0x2e0
github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0x0?, {0x110197fe0?, 0x140003a5400?})
        github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:94 +0x118
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x1102e2860?, {0x1102e2860?, 0x14002c6cb70?}, 0xd?, {0x110197fe0?, 0x140003a5400?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:719 +0x64
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x1400179cb60, {0x1102e2860, 0x14002c6cb70}, 0x14002229520, {0x110197fe0, 0x140003a5400})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:1015 +0x468
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x140007e1ef0, {0x1102e2860?, 0x14002c6c1e0?}, 0x14003b180c0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:613 +0x400
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadResource({0x140033ac120, 0x140033ac180, {0x14004dd8b00, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.9.0/tf5muxserver/mux_server_ReadResource.go:26 +0xdc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x14001dd9a40, {0x1102e2860?, 0x14002a496b0?}, 0x14004991920)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x3e8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x10fea0780?, 0x14001dd9a40}, {0x1102e2860, 0x14002a496b0}, 0x14000dd0c40, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400452da40, {0x1102f1ba0, 0x1400218e1a0}, 0x14002204d80, 0x14004e930b0, 0x116a00a10, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1336 +0xb7c
google.golang.org/grpc.(*Server).handleStream(0x1400452da40, {0x1102f1ba0, 0x1400218e1a0}, 0x14002204d80, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1704 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.53.0/server.go:965 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.53.0/server.go:963 +0x290

Error: The terraform-provider-aws_v4.60.0_x5 plugin crashed!
```

### Would you like to implement a fix?

None

**Comment by eugenvonbrawn** [comment]
Any updates on this issue? We're getting same plugin crash for AzureRM v.3.29.0

**Comment by jar-b** [comment]
This nil pointer dereference was enabled by an incorrect return value in the `listAppsByName` function here (the second check should've returned an empty result error). The downstream function assumes that the list function only returns non-nil results when there is no error.

```go
	if err != nil {
		return nil, err
	}

	if len(apps) == 0 {
		return nil, nil
	}
```

This was fixed by this commit https://github.com/hashicorp/terraform-provider-aws/commit/b2f1f5478c26e29f770c7b50948d819db9d7643a as part of #30786.
