### ISSUE TITLE
[Bug]: The terraform-provider-aws_v4.61.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by rickychew77** [hashicorp/terraform-provider-aws#31252]
### Terraform Core Version

1.1.7

### AWS Provider Version

4.61.0

### Affected Resource(s)

using this module `terraform-aws-modules/rds-aurora/aws` mainly to create `aws_rds_cluster` and `aws_rds_cluster_instance`

### Expected Behavior

Create the resources

### Actual Behavior

Plugin crashed

### Relevant Error/Panic Output Snippet

```shell
Stack trace from the terraform-provider-aws_v4.61.0_x5 plugin:

panic: interface conversion: interface {} is string, not []interface {}

goroutine 371 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/rds.resourceClusterUpdate({0xf483320?, 0xc0038e5e00}, 0xc003ffea80, {0xdf84d00?, 0xc000372c00})
        github.com/hashicorp/terraform-provider-aws/internal/service/rds/cluster.go:1282 +0x37b4
github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0x0?, {0xdf84d00?, 0xc000372c00?})
        github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:94 +0x175
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xf483320?, {0xf483320?, 0xc003850330?}, 0xd?, {0xdf84d00?, 0xc000372c00?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:736 +0x87
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc001771a40, {0xf483320, 0xc003850330}, 0xc0031ffe10, 0xc003ffe900, {0xdf84d00, 0xc000372c00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:847 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00184dc20, {0xf483320?, 0xc00384dd70?}, 0xc0005b20a0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc0031e7290, 0xc0031e72f0, {0xc004c9e740, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.9.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0028e3220, {0xf483320?, 0xc003423680?}, 0xc001da8460)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xdc89e80?, 0xc0028e3220}, {0xf483320, 0xc003423680}, 0xc001da83f0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000996000, {0xf492aa0, 0xc0048ca680}, 0xc0048deb40, 0xc002e727b0, 0x15cd9f80, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc000996000, {0xf492aa0, 0xc0048ca680}, 0xc0048deb40, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-aws_v4.61.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Configuration Files

```terraform
module "aurora" {
  source  = "terraform-aws-modules/rds-aurora/aws"
  version = "8.0.2"

  name                        = local.database_name
  engine                      = var.engine
  engine_version              = var.engine_version
  engine_mode                 = var.engine_mode
  subnets                     = local.subnet_ids
  vpc_id                      = local.vpc_id
  deletion_protection         = var.deletion_protection
  port                        = var.port
  database_name               = var.database_name
  allow_major_version_upgrade = var.allow_major_version_upgrade
  instances                   = var.instances
  instance_class              = var.instance_class
  final_snapshot_identifier   = var.final_snapshot_identifier

  # Scaling
  scaling_configuration  = var.scaling_configuration
  predefined_metric_type = var.predefined_metric_type

  # Backups
  backup_retention_period      = var.backup_retention_period
  preferred_backup_window      = var.preferred_backup_window
  preferred_maintenance_window = var.preferred_maintenance_window

  # Storage
  storage_encrypted = var.storage_encrypted
  kms_key_id        = local.db_kms_key_id

  # Security Groups
  create_security_group   = true
  security_group_rules = var.security_group_rules

  # CA Certs
  ca_cert_identifier = var.ca_cert_identifier

  # DB Subnet Group
  create_db_subnet_group = var.create_db_subnet_group
  db_subnet_group_name   = var.db_subnet_group_name

  # Parameter Group
  db_parameter_group_name         = try(aws_db_parameter_group.aurora[0].id, null)
  db_cluster_parameter_group_name = aws_rds_cluster_parameter_group.aurora.id

  # Restore from Snapshot
  snapshot_identifier = var.snapshot_identifier

  # Monitoring
  performance_insights_enabled    = var.performance_insights_enabled
  performance_insights_kms_key_id = local.db_kms_key_id

  # Logging
  enabled_cloudwatch_logs_exports = var.enabled_cloudwatch_logs_exports

  # Operations
  auto_minor_version_upgrade = var.auto_minor_version_upgrade
  apply_immediately          = var.apply_immediately

  # Required unless snapshot_identifier is defined
  master_username             = local.secret_value.username
  master_password             = local.secret_value.password
  manage_master_user_password = var.manage_master_user_password

  tags                  = module.names.tags
  copy_tags_to_snapshot = true
}
```

### Steps to Reproduce

1. Created the RDS cluster and instance with no issue
2. To update the config from using `manage_master_user_password: true` to `false` and getting password from other secret manager and this error shows.

### Would you like to implement a fix?

None

**Comment by rickychew77** [comment]
Oh thanks for pointing out. yes will try 4.62.0 version onwards.

**Comment by ewbankkit** [comment]
Fixed via https://github.com/hashicorp/terraform-provider-aws/pull/30379.
