### ISSUE TITLE
[Bug]: Empty `oauth_http_parameters` in `aws_cloudwatch_event_connection` causes Panic

### ISSUE THREAD

**Issue by acornforth** [hashicorp/terraform-provider-aws#31671]
### Terraform Core Version

1.4.6

### AWS Provider Version

4.67.0

### Affected Resource(s)

[aws_cloudwatch_event_connection](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_connection)

### Expected Behavior

The property `oauth_http_parameters` is required, and all it's children are optional.

If no additional http parameters are required, it should be legal to supply an empty block for `oauth_http_parameters` 

### Actual Behavior

Apply run (Terraform Cloud) fails with a panic.

### Relevant Error/Panic Output Snippet

```shell
Stack trace from the terraform-provider-aws_v4.67.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 404 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/events.expandConnectionHTTPParameters({0xc004d5ed80, 0x1, 0xdc5ce45?})
github.com/hashicorp/terraform-provider-aws/internal/service/events/connection.go:486 +0x245
github.com/hashicorp/terraform-provider-aws/internal/service/events.expandCreateConnectionOAuthAuthRequestParameters({0xc004d5ed60, 0x1, 0xdbcd6c9?})
github.com/hashicorp/terraform-provider-aws/internal/service/events/connection.go:457 +0x23b
github.com/hashicorp/terraform-provider-aws/internal/service/events.expandCreateConnectionAuthRequestParameters({0xc004d5ed30, 0x1, 0x40d5bf?})
github.com/hashicorp/terraform-provider-aws/internal/service/events/connection.go:399 +0x205
github.com/hashicorp/terraform-provider-aws/internal/service/events.resourceConnectionCreate({0xf0a19c0, 0xc0066c1350}, 0xc00669f880, {0xdb8cd20?, 0xc00042b800?})
github.com/hashicorp/terraform-provider-aws/internal/service/events/connection.go:270 +0x16b
github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0x0?, {0xdb8cd20?, 0xc00042b800?})
github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:95 +0x175
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xf0a19c0?, {0xf0a19c0?, 0xc00669ce40?}, 0xd?, {0xdb8cd20?, 0xc00042b800?})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:702 +0x84
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0011dce00, {0xf0a19c0, 0xc00669ce40}, 0xc0066992b0, 0xc00669e380, {0xdb8cd20, 0xc00042b800})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc002040498, {0xf0a19c0?, 0xc00669cd20?}, 0xc0033ea9b0)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc004551050, 0xc0045510b0, {0xc006814520, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc002faafa0, {0xf0a19c0?, 0xc00669c1e0?}, 0xc00652bf10)
github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xd877e80?, 0xc002faafa0}, {0xf0a19c0, 0xc00669c1e0}, 0xc00652bea0, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:419 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0062b83c0, {0xf0b21e0, 0xc0005681a0}, 0xc006696240, 0xc0068cc8a0, 0x15cfa500, 0x0)
google.golang.org/grpc@v1.54.0/server.go:1345 +0xdf0
google.golang.org/grpc.(*Server).handleStream(0xc0062b83c0, {0xf0b21e0, 0xc0005681a0}, 0xc006696240, 0x0)
google.golang.org/grpc@v1.54.0/server.go:1722 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
google.golang.org/grpc@v1.54.0/server.go:966 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
google.golang.org/grpc@v1.54.0/server.go:964 +0x28a

Error: The terraform-provider-aws_v4.67.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Configuration Files

```hcl
resource "aws_cloudwatch_event_connection" "salesforce_api" {
  authorization_type = "OAUTH_CLIENT_CREDENTIALS"
  name               = "salesforce"
  auth_parameters {
    oauth {
      authorization_endpoint = "${var.salesforce_api_url}/services/oauth2/authorize"
      http_method            = "POST"
      client_parameters {
        client_id     = var.salesforce_client_id
        client_secret = var.salesforce_client_secret
      }
      oauth_http_parameters {}
    }
  }
}
```

### Steps to Reproduce

Attempt an apply run with a resource like the above in the configuration

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/c67e7e0289a8f0443903c4d287acefc74db7f3a7/internal/service/events/connection.go#L485-L496

**Comment by acornforth** [comment]
I'm curious why the decision to make the `oauth_http_parameters` block required. wouldn't it make sense for it to be an optional block, if none of the children are required ?

**Comment by danixmarques** [comment]
I upvoted because we are having trouble with this bug when running our Terraform pipelines on Jenkins. Any updates about this issue would be great. Thanks in advance.
