### ISSUE TITLE
[Bug]: The plugin.*GRPCProvider error

### ISSUE THREAD

**Issue by sreekanth3107** [hashicorp/terraform-provider-aws#31929]
### Terraform Core Version

1.2.2

### AWS Provider Version

5.3.0

### Affected Resource(s)

aws_lambda_function
aws_lambda_layer_version

### Expected Behavior

`terraform plan/apply` executes without error

### Actual Behavior

Error running terraform plan
Error: Request cancelled
with provider["registry.terraform.io/hashicorp/aws"]
provider "aws" {
The plugin.(*GRPCProvider).ValidateProviderConfig request was cancelled

### Relevant Error/Panic Output Snippet

```shell
resource "aws_lambda_function" "n" {
The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ApplyResourceChange call
Error running terraform apply
```

### Terraform Configuration Files

terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = ">= 5.3.0"
  }
}

provider "aws" {
  region = var.awsRegion
}

resource "aws_lambda_function" "x_lambda" {
  function_name            = "test"
  filename                       = data.xx_zip.output_path
  handler                        = "main"
  role                              = data.aws_iam_role.xx.id
  runtime                        = "go1.x"
  source_code_hash     = data.xx_zip.output_base64sha256
  reserved_concurrent_executions = 1

### Steps to Reproduce

Create a Lambda function 

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @sreekanth3107 👋 Thank you for taking the time to raise this! So that we have the necessary information in order to look into this, can you supply debug logs (redacted as needed) as well?

**Comment by psaezc** [comment]
I'm getting the same error, with a Terraform Core version 1.5.0

`Stack trace from the terraform-provider-aws_v5.3.0_x5 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 1202 [running]:
github.com/hashicorp/terraform-plugin-framework/internal/fwschemadata.ValueSemanticEqualitySetElements({0xf51f820, 0xc007a26c30}, {{{0xc008eca790, 0x1, 0x1}}, {0xf52b658, 0xc007a26960}, {0xf52b658, 0xc007a26bd0}}, 0xc004adcec0)
github.com/hashicorp/terraform-plugin-framework@v1.3.0/internal/fwschemadata/value_semantic_equality_set.go:145 +0xdc8
github.com/hashicorp/terraform-plugin-framework/internal/fwschemadata.ValueSemanticEqualitySet({0xf51f820, 0xc007a26c30}, {{{0xc008eca790, 0x1, 0x1}}, {0xf52b658, 0xc007a26960}, {0xf52b658, 0xc007a26bd0}}, 0xc004adcec0)
github.com/hashicorp/terraform-plugin-framework@v1.3.0/internal/fwschemadata/value_semantic_equality_set.go:27 +0x497
github.com/hashicorp/terraform-plugin-framework/internal/fwschemadata.ValueSemanticEquality({0xf51f820, 0xc006a82840}, {{{0xc008eca790, 0x1, 0x1}}, {0xf52b658, 0xc007a26960}, {0xf52b658, 0xc007a26bd0}}, 0xc004adcec0)
github.com/hashicorp/terraform-plugin-framework@v1.3.0/internal/fwschemadata/value_semantic_equality.go:79 +0x53e
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.SchemaSemanticEquality({0xf51f820, 0xc006a82840}, {{{0xdfd3ebf, 0x5}, {0xf5392c8, 0xc007f5e0f0}, {{0xf52f530, 0xc007a1cd80}, {0xc23f280, 0xc007a133e0}}}, ...}, ...)
github.com/hashicorp/terraform-plugin-framework@v1.3.0/internal/fwserver/schema_semantic_equality.go:80 +0x39d
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0xc005c17ce0, {0xf51f820, 0xc006a82840}, 0xc006a82d20, 0xc004add3f8)
github.com/hashicorp/terraform-plugin-framework@v1.3.0/internal/fwserver/server_readresource.go:135 +0x950
github.com/hashicorp/terraform-plugin-framework/internal/proto5server.(*Server).ReadResource(0xc005c17ce0, {0xf51f820?, 0xc006a7be60?}, 0xc008b48180)
github.com/hashicorp/terraform-plugin-framework@v1.3.0/internal/proto5server/server_readresource.go:56 +0x27b
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadResource({0xc005cbcd80, 0xc005cbcde0, {0xc0083b89a0, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf5muxserver/mux_server_ReadResource.go:26 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc004505a40, {0xf51f820?, 0xc006989620?}, 0xc008b46060)
github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov5/tf5server/server.go:748 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xdc7ace0?, 0xc004505a40}, {0xf51f820, 0xc006989620}, 0xc005578700, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:383 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000abc000, {0xf530240, 0xc008504680}, 0xc008b3e480, 0xc0081fbef0, 0x162b2e30, 0x0)
google.golang.org/grpc@v1.54.0/server.go:1345 +0xdf0
google.golang.org/grpc.(*Server).handleStream(0xc000abc000, {0xf530240, 0xc008504680}, 0xc008b3e480, 0x0)
google.golang.org/grpc@v1.54.0/server.go:1722 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
google.golang.org/grpc@v1.54.0/server.go:966 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
google.golang.org/grpc@v1.54.0/server.go:964 +0x28a

Error: The terraform-provider-aws_v5.3.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.`

**Comment by shazChaudhry** [comment]
I am getting `fatal error: runtime: out of memory` .
my terraform version is v1.2.2

Is anyone able to help with this issue please?

```
14:41:33 aws_lambda_layer_version.hotels: Creating...
14:41:42 ╷
14:41:42 │ Error: Request cancelled
14:41:42 │ 
14:41:42 │   with aws_lambda_layer_version.hotels,
14:41:42 │   on main.tf line 59, in resource "aws_lambda_layer_version" "hotels":
14:41:42 │   59: resource "aws_lambda_layer_version" "hotels" {
14:41:42 │ 
14:41:42 │ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
14:41:42 ╵
14:41:42 
14:41:42 Stack trace from the terraform-provider-aws_v5.7.0_x5 plugin:
14:41:42 
14:41:42 fatal error: runtime: out of memory
14:41:42 
14:41:42 runtime stack:
14:41:42 runtime.throw({0xe11f99e?, 0x0?})
14:41:42 	runtime/panic.go:1047 +0x5d fp=0xc0000f9df8 sp=0xc0000f9dc8 pc=0x43551d
14:41:42 runtime.sysMapOS(0xc02d000000, 0x3400000?)
14:41:42 	runtime/mem_linux.go:187 +0x11b fp=0xc0000f9e40 sp=0xc0000f9df8 pc=0x417fdb
14:41:42 runtime.sysMap(0x16249280?, 0xc3ffffffff?, 0x16259418?)
14:41:42 	runtime/mem.go:142 +0x35 fp=0xc0000f9e70 sp=0xc0000f9e40 pc=0x4179b5
14:41:42 runtime.(*mheap).grow(0x16249280, 0x1994?)
14:41:42 	runtime/mheap.go:1522 +0x252 fp=0xc0000f9ee8 sp=0xc0000f9e70 pc=0x428152
14:41:42 runtime.(*mheap).allocSpan(0x16249280, 0x1994, 0x0, 0x9f?)
14:41:42 	runtime/mheap.go:1243 +0x1b7 fp=0xc0000f9f80 sp=0xc0000f9ee8 pc=0x427897
14:41:42 runtime.(*mheap).alloc.func1()
14:41:42 	runtime/mheap.go:961 +0x65 fp=0xc0000f9fc8 sp=0xc0000f9f80 pc=0x427345
14:41:42 runtime.systemstack()
14:41:42 	runtime/asm_amd64.s:496 +0x49 fp=0xc0000f9fd0 sp=0xc0000f9fc8 pc=0x466089
14:41:42 
14:41:42 goroutine 339 [running]:
14:41:42 runtime.systemstack_switch()
14:41:42 	runtime/asm_amd64.s:463 fp=0xc0013ba110 sp=0xc0013ba108 pc=0x466020
14:41:42 runtime.(*mheap).alloc(0x3328000?, 0x1994?, 0x0?)
14:41:42 	runtime/mheap.go:955 +0x65 fp=0xc0013ba158 sp=0xc0013ba110 pc=0x427285
14:41:42 runtime.(*mcache).allocLarge(0x4f5e3e?, 0x3328000, 0x1)
14:41:42 	runtime/mcache.go:234 +0x85 fp=0xc0013ba1a0 sp=0xc0013ba158 pc=0x416a45
14:41:42 runtime.mallocgc(0x3328000, 0x0, 0x0)
14:41:42 	runtime/malloc.go:1053 +0x4fe fp=0xc0013ba208 sp=0xc0013ba1a0 pc=0x40d93e
14:41:42 runtime.growslice(0x0, 0x0?, 0x0?, 0xc0013ba2a8?, 0x0?)
14:41:42 	runtime/slice.go:266 +0x4a8 fp=0xc0013ba268 sp=0xc0013ba208 pc=0x44d2a8
14:41:42 strings.(*Builder).Write(0xc0026c60c0, {0xc028d96000, 0x33262f5, 0x3328000?})
14:41:42 	strings/builder.go:90 +0x87 fp=0xc0013ba2b8 sp=0xc0013ba268 pc=0x4ff4c7
14:41:42 fmt.Fprintln({0xf268c00, 0xc0026c60c0}, {0xc0013ba360, 0x1, 0x1})
14:41:42 	fmt/print.go:305 +0x75 fp=0xc0013ba308 sp=0xc0013ba2b8 pc=0x4f32b5
14:41:42 github.com/hashicorp/aws-sdk-go-base/v2/logging.ReadTruncatedBody(0xc0013ba3f0?, 0x400)
14:41:42 	github.com/hashicorp/aws-sdk-go-base/v2@v2.0.0-beta.31/logging/http.go:224 +0xed fp=0xc0013ba380 sp=0xc0013ba308 pc=0x8f0d10d
14:41:42 github.com/hashicorp/aws-sdk-go-base/v2/logging.decomposeRequestBody(0x6?)
14:41:42 	github.com/hashicorp/aws-sdk-go-base/v2@v2.0.0-beta.31/logging/http.go:109 +0x25d fp=0xc0013ba530 sp=0xc0013ba380 pc=0x8f0b91d
14:41:42 github.com/hashicorp/aws-sdk-go-base/v2/logging.DecomposeHTTPRequest(0xf354260?)
14:41:42 	github.com/hashicorp/aws-sdk-go-base/v2@v2.0.0-beta.31/logging/http.go:42 +0x194 fp=0xc0013ba6a8 sp=0xc0013ba530 pc=0x8f0a8f4
14:41:42 github.com/hashicorp/aws-sdk-go-base/v2/awsv1shim/v2.logRequest(0xc001b6c500)
14:41:42 	github.com/hashicorp/aws-sdk-go-base/v2/awsv1shim/v2@v2.0.0-beta.32/logger.go:79 +0x14f fp=0xc0013ba788 sp=0xc0013ba6a8 pc=0x91a466f
14:41:42 github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0xc001b6c730, 0xc001b6c500)
14:41:42 	github.com/aws/aws-sdk-go@v1.44.297/aws/request/handlers.go:267 +0x9c fp=0xc0013ba818 sp=0xc0013ba788 pc=0xd05e1c
14:41:42 github.com/aws/aws-sdk-go/aws/request.(*Request).sendRequest(0xc001b6c500)
14:41:42 	github.com/aws/aws-sdk-go@v1.44.297/aws/request/request.go:602 +0xbf fp=0xc0013ba8d0 sp=0xc0013ba818 pc=0xd0979f
14:41:42 github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0xc001b6c500)
14:41:42 	github.com/aws/aws-sdk-go@v1.44.297/aws/request/request.go:555 +0x156 fp=0xc0013ba960 sp=0xc0013ba8d0 pc=0xd09016
14:41:42 github.com/aws/aws-sdk-go/service/lambda.(*Lambda).PublishLayerVersionWithContext(0xe1c47bd?, {0xf354260, 0xc002693b60}, 0x0?, {0x0, 0x0, 0x0?})
14:41:42 	github.com/aws/aws-sdk-go@v1.44.297/service/lambda/api.go:5689 +0x186 fp=0xc0013ba9b0 sp=0xc0013ba960 pc=0x6c6e466
14:41:42 github.com/hashicorp/terraform-provider-aws/internal/service/lambda.resourceLayerVersionPublish({0xf354260, 0xc002693b60}, 0xe03eea0?, {0xe03eea0?, 0xc004c9e750})
14:41:42 	github.com/hashicorp/terraform-provider-aws/internal/service/lambda/layer_version.go:198 +0x928 fp=0xc0013bac90 sp=0xc0013ba9b0 pc=0xa1a0f88
14:41:42 github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0x0?, {0xe03eea0?, 0xc004c9e750?})
14:41:42 	github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:111 +0x34b fp=0xc0013bad80 sp=0xc0013bac90 pc=0xabd5fab
14:41:42 github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xf354260?, {0xf354260?, 0xc0026926c0?}, 0xd?, {0xe03eea0?, 0xc004c9e750?})
14:41:42 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:728 +0x87 fp=0xc0013badf8 sp=0xc0013bad80 pc=0xbac847
14:41:42 github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0015e02a0, {0xf354260, 0xc0026926c0}, 0xc00268e340, 0xc004c7a200, {0xe03eea0, 0xc004c9e750})
14:41:42 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:864 +0xa7e fp=0xc0013bb178 sp=0xc0013badf8 pc=0xbadc3e
14:41:42 github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000d7d320, {0xf354260?, 0xc0026925a0?}, 0xc0025e4aa0)
14:41:42 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/grpc_provider.go:1024 +0xe8d fp=0xc0013bb418 sp=0xc0013bb178 pc=0xba630d
14:41:42 github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc004c86db0, 0xc0042d2f00, 0xc004c86de0, 0xc004c86e10, {0xc004c4fa60, 0x2, 0x2}}, {0xf354260?, 0xc002692270?}, 0xc0025e4aa0)
14:41:42 	github.com/hashicorp/terraform-plugin-mux@v0.11.1/tf5muxserver/mux_server_ApplyResourceChange.go:30 +0x139 fp=0xc0013bb4a8 sp=0xc0013bb418 pc=0xa87319
14:41:42 github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0xf3541b8?, {0xf354260?, 0xc002692270?}, 0x16?)
14:41:42 	<autogenerated>:1 +0xa9 fp=0xc0013bb540 sp=0xc0013bb4a8 pc=0xa8a129
14:41:42 github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc004c7ce60, {0xf354260?, 0xc00266d860?}, 0xc004f7f960)
14:41:42 	github.com/hashicorp/terraform-plugin-go@v0.17.0/tfprotov5/tf5server/server.go:821 +0x574 fp=0xc0013bba10 sp=0xc0013bb540 pc=0x990894
14:41:42 github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xdd205a0?, 0xc004c7ce60}, {0xf354260, 0xc00266d860}, 0xc004f7f8f0, 0x0)
14:41:42 	github.com/hashicorp/terraform-plugin-go@v0.17.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:422 +0x170 fp=0xc0013bba68 sp=0xc0013bba10 pc=0x975110
14:41:42 google.golang.org/grpc.(*Server).processUnaryRPC(0xc000320000, {0xf361020, 0xc0038aa9c0}, 0xc00267c7e0, 0xc004d3ec30, 0x16211480, 0x0)
14:41:42 	google.golang.org/grpc@v1.56.1/server.go:1337 +0xdf3 fp=0xc0013bbe48 sp=0xc0013bba68 pc=0x8f7e93
14:41:42 google.golang.org/grpc.(*Server).handleStream(0xc000320000, {0xf361020, 0xc0038aa9c0}, 0xc00267c7e0, 0x0)
14:41:42 	google.golang.org/grpc@v1.56.1/server.go:1714 +0xa36 fp=0xc0013bbf68 sp=0xc0013bbe48 pc=0x8fcfb6
14:41:42 google.golang.org/grpc.(*Server).serveStreams.func1.1()
14:41:42 	google.golang.org/grpc@v1.56.1/server.go:959 +0x98 fp=0xc0013bbfe0 sp=0xc0013bbf68 pc=0x8f5898
14:41:42 runtime.goexit()
14:41:42 	runtime/asm_amd64.s:1598 +0x1 fp=0xc0013bbfe8 sp=0xc0013bbfe0 pc=0x468101
14:41:42 created by google.golang.org/grpc.(*Server).serveStreams.func1
14:41:42 	google.golang.org/grpc@v1.56.1/server.go:957 +0x18c
14:41:42 
14:41:42 goroutine 1 [select]:
14:41:42 runtime.gopark(0xc00491fa80?, 0x2?, 0xea?, 0xf9?, 0xc00491f904?)
14:41:42 	runtime/proc.go:381 +0xd6 fp=0xc001301690 sp=0xc001301670 pc=0x438276
14:41:42 runtime.selectgo(0xc001301a80, 0xc00491f900, 0x1?, 0x0, 0xc00491fac0?, 0x1)
14:41:42 	runtime/select.go:327 +0x7be fp=0xc0013017d0 sp=0xc001301690 pc=0x447f1e
14:41:42 github.com/hashicorp/go-plugin.Serve(0xc004c44360)
14:41:42 	github.com/hashicorp/go-plugin@v1.4.10/server.go:474 +0x14e5 fp=0xc001301cb8 sp=0xc0013017d0 pc=0x92cfa5
14:41:42 github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.Serve({0xe1c870a, 0x23}, 0xc004ca80c0, {0x0, 0x0, 0x0})
14:41:42 	github.com/hashicorp/terraform-plugin-go@v0.17.0/tfprotov5/tf5server/server.go:315 +0xc0a fp=0xc001301ef8 sp=0xc001301cb8 pc=0x98a30a
14:41:42 main.main()
14:41:42 	github.com/hashicorp/terraform-provider-aws/main.go:35 +0x18e fp=0xc001301f80 sp=0xc001301ef8 pc=0xabd6c4e
14:41:42 runtime.main()
14:41:42 	runtime/proc.go:250 +0x207 fp=0xc001301fe0 sp=0xc001301f80 pc=0x437e47
14:41:42 runtime.goexit()
14:41:42 	runtime/asm_amd64.s:1598 +0x1 fp=0xc001301fe8 sp=0xc001301fe0 pc=0x468101
14:41:42 
14:41:42 goroutine 2 [force gc (idle)]:
14:41:42 runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
14:41:42 	runtime/proc.go:381 +0xd6 fp=0xc0000e4fb0 sp=0xc0000e4f90 pc=0x438276
14:41:42 runtime.goparkunlock(...)
14:41:42 	runtime/proc.go:387
14:41:42 runtime.forcegchelper()
14:41:42 	runtime/proc.go:305 +0xb0 fp=0xc0000e4fe0 sp=0xc0000e4fb0 pc=0x4380b0
14:41:42 
14:41:42 Error: The terraform-provider-aws_v5.7.0_x5 plugin crashed!
14:41:42 
14:41:42 This is always indicative of a bug within the plugin. It would be immensely
14:41:42 helpful if you could report the crash with the plugin's maintainers so that it
14:41:42 can be fixed. The output above should help diagnose the issue.
```
