### ISSUE TITLE
[Bug]: The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call.

### ISSUE THREAD

**Issue by FabianPi** [hashicorp/terraform-provider-aws#31924]
### Terraform Core Version

1.5.0

### AWS Provider Version

5.3.0

### Expected Behavior

`terraform plan` executes without error

### Actual Behavior

Running `terraform plan` with AWS provider v5.3.0 returns errors: Error: Request cancelled and Error: Plugin did not respond.

Using AWS provider v5.2.0 works fine

```
╷
│ Error: Request cancelled
│
│   with aws_ssm_default_patch_baseline.patch,
│   on main.tf line 10, in resource "aws_ssm_default_patch_baseline" "patch":
│  10: resource "aws_ssm_default_patch_baseline" "patch" {
│
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_config_conformance_pack.base,
│   on main.tf line 17, in resource "aws_config_conformance_pack" "base":
│   17: resource "aws_config_conformance_pack" "base" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
```

### Relevant Error/Panic Output Snippet

```shell
Stack trace from the terraform-provider-aws_v5.3.0_x5.exe plugin:

panic: interface conversion: *conns.AWSClient is not ssm.ssmClient: missing method SSMClient

goroutine 665 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/ssm.resourceDefaultPatchBaselineRead({0xf16dbc0, 0xc0047d18c0}, 0xc006ec3e80, {0xdbdbd60?, 0xc000305c00})
        github.com/hashicorp/terraform-provider-aws/internal/service/ssm/default_patch_baseline.go:202 +0x5d
github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0x0?, {0xdbdbd60?, 0xc000305c00?})
        github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:108 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xf16dbc0?, {0xf16dbc0?, 0xc0047d0f60?}, 0xd?, {0xdbdbd60?, 0xc000305c00?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:719 +0x87
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0040729a0, {0xf16dbc0, 0xc0047d0f60}, 0xc0071c8b60, {0xdbdbd60, 0xc000305c00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00413f098, {0xf16dbc0?, 0xc0047d0ba0?}, 0xc007291440)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadResource({0xc005ce0990, 0xc005ce09f0, {0xc008d16c20, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf5muxserver/mux_server_ReadResource.go:26 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc00283f860, {0xf16dbc0?, 0xc0044a3440?}, 0xc0071a9680)
        github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov5/tf5server/server.go:748 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xd8c35a0?, 0xc00283f860}, {0xf16dbc0, 0xc0044a3440}, 0xc00083acb0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:383 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0084d1e00, {0xf17e5e0, 0xc0005f8000}, 0xc0071cfc20, 0xc008d53f20, 0x15f0ce10, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1345 +0xdf0
google.golang.org/grpc.(*Server).handleStream(0xc0084d1e00, {0xf17e5e0, 0xc0005f8000}, 0xc0071cfc20, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1722 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.54.0/server.go:966 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.54.0/server.go:964 +0x28a

Error: The terraform-provider-aws_v5.3.0_x5.exe plugin crashed!
```

### Terraform Configuration Files

```terraform
resource "aws_ssm_default_patch_baseline" "patch" {
  baseline_id      = aws_ssm_patch_baseline.account.id
  operating_system = "WINDOWS"
}
```

### Steps to Reproduce

1. Run `terraform plan` with aws provider v5.3.0

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/e98225525b69c2b5d15183c92c9a90a1152b944d/internal/service/ssm/default_patch_baseline.go#L201-L202

Relates https://github.com/hashicorp/terraform-provider-aws/pull/31894.

**Comment by sreekanth3107** [comment]
@ewbankkit i have similar issue with creating lambda https://github.com/hashicorp/terraform-provider-aws/issues/31929
