### ISSUE TITLE
[Bug]: GRPCProvider error when creating a aws_lightsail_instance

### ISSUE THREAD

**Issue by zoenglinghou** [hashicorp/terraform-provider-aws#32430]
### Terraform Core Version

1.5.2

### AWS Provider Version

5.7.0

### Affected Resource(s)

* aws_lightsail_instance

### Expected Behavior

Instance would be created and Terraform would receive the correct feedback

### Actual Behavior

Instance created, but Terraform raises an error and the new instance is not recorded in the terraform state.

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: Request cancelled
│ 
│   with aws_lightsail_instance.nodes[0],
│   on lightsail.tf line 12, in resource "aws_lightsail_instance" "nodes":
│   12: resource "aws_lightsail_instance" "nodes" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-aws_v5.7.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xf863ba]

goroutine 31 [running]:
github.com/hashicorp/terraform-provider-aws/internal/tags.(*TagData).ValueString(...)
        github.com/hashicorp/terraform-provider-aws/internal/tags/key_value_tags.go:671
github.com/hashicorp/terraform-provider-aws/internal/tags.KeyValueTags.ResolveDuplicates(0xc00084e2a0?, {0xf354260, 0xc00280ee40}, 0x0, 0xcc?, {0x7f098e7c4098, 0xc001d96b00})
        github.com/hashicorp/terraform-provider-aws/internal/tags/key_value_tags.go:780 +0x19a
github.com/hashicorp/terraform-provider-aws/internal/provider.tagsInterceptor.run({0xc0017d7960?, 0xe330458?, 0xe330450?}, {0xf354260, 0xc00280ee40}, {0xf35f588, 0xc001d96b00}, {0xe03eea0?, 0
xc001c7e340?}, 0x2, ...)
        github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:353 +0x9c9
github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0x0?, {0xe03eea0?, 0xc001c7e340?})
        github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:120 +0x428
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xf354260?, {0xf354260?, 0xc0025ed650?}, 0xd?, {0xe03eea0?, 0xc001c7e340?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:728 +0x87
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc001864fc0, {0xf354260, 0xc0025ed650}, 0xc002e55930, 0xc001d96980, {0xe03eea0, 0xc001c7e340})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:864 +0xa7e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000551bd8, {0xf354260?, 0xc0025ed530?}, 0xc002d3e3c0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/grpc_provider.go:1024 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc001c633b0, 0xc00577b090, 0xc001c633e0, 0xc001c63410, {0xc002a27a80, 0x2, 0x2}}, {0xf354260?, 0xc0025ed
200?}, 0xc002d3e3c0)
        github.com/hashicorp/terraform-plugin-mux@v0.11.1/tf5muxserver/mux_server_ApplyResourceChange.go:30 +0x139
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc001c4fea0, {0xf354260?, 0xc0025ec810?}, 0xc000a791f0)
        github.com/hashicorp/terraform-plugin-go@v0.17.0/tfprotov5/tf5server/server.go:821 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xdd205a0?, 0xc001c4fea0}, {0xf354260, 0xc0025ec810}, 0xc000a790a0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.17.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:422 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000a26000, {0xf361020, 0xc001d1c680}, 0xc0025aa900, 0xc001d17230, 0x16211480, 0x0)
        google.golang.org/grpc@v1.56.1/server.go:1337 +0xdf3
google.golang.org/grpc.(*Server).handleStream(0xc000a26000, {0xf361020, 0xc001d1c680}, 0xc0025aa900, 0x0)
        google.golang.org/grpc@v1.56.1/server.go:1714 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.56.1/server.go:959 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.56.1/server.go:957 +0x18c

Error: The terraform-provider-aws_v5.7.0_x5 plugin crashed!
```

### Terraform Configuration Files

This is a snippet of the **relevant** resources:
```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.6.2"
    }
  }
}

terraform {
  backend "s3" {
    bucket         = "***"
    key            = "***"
    region         = "eu-central-1"
    encrypt        = true
    dynamodb_table = "***"
  }
}

locals {
  node_count = 1
  aws_region = "ap-northeast-1"
  region_bundle_map = {
    ap-northeast-1 = "2_0"
    ap-southeast-1 = "2_0"
    eu-central-1   = "2_0"
    us-west-2      = "2_0"
  }
}

provider "aws" {
  # Configuration options
  region = local.aws_region
}

resource "aws_lightsail_key_pair" "key" {
  name       = "main"
  public_key = file("~/.ssh/id_ed25519.pub")
}

resource "aws_lightsail_instance" "nodes" {
  count             = local.node_count
  name              = "node_${count.index}"
  availability_zone = "${local.aws_region}d"
  blueprint_id      = "debian_11"
  bundle_id         = "nano_${local.region_bundle_map[local.aws_region]}"
  key_pair_name     = aws_lightsail_key_pair.key.id
  tags = {
    gost = ""
  }
}
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply` -> `yes`
3. `terraform` waits 40 seconds before the error is shown, while the instance is created on lightsail:
```shell
aws_lightsail_instance.nodes[0]: Creating...
aws_lightsail_instance.nodes[0]: Still creating... [10s elapsed]
aws_lightsail_instance.nodes[0]: Still creating... [20s elapsed]
aws_lightsail_instance.nodes[0]: Still creating... [30s elapsed]
aws_lightsail_instance.nodes[0]: Still creating... [40s elapsed]
```
4. Same error when trying the import the created instance
5. Same error for 5.6.2

### Debug Output

[stderr.gpg.log](https://github.com/hashicorp/terraform-provider-aws/files/11994648/stderr.gpg.log)
[stdout.gpg.log](https://github.com/hashicorp/terraform-provider-aws/files/11994649/stdout.gpg.log)

### Would you like to implement a fix?

No

**Comment by jainamshah102** [comment]
I am fairly new to open source contribution, can I pick up this issue?

**Comment by zoenglinghou** [comment]
> I am fairly new to open source contribution, can I pick up this issue?

I mean you can follow the issue, or if you have a fix...?

**Comment by jainamshah102** [comment]
I am debugging this issue and finding some probable fix.

**Comment by zoenglinghou** [comment]
The issue still persists for version `1.13.1`

**Comment by GertBurger** [comment]
I ran into the same error when attempting to import a lightsail database and I got around the issue by removing the tags it had, which were key-only tags.

Terraform v1.6.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.31.0
