### ISSUE TITLE
[Bug]: Importing aws_opensearchserverless got invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by admin-ssg** [hashicorp/terraform-provider-aws#32758]
### Terraform Core Version

1.5.4

### AWS Provider Version

5.10.0

### Affected Resource(s)

aws_opensearchserverless_collection

### Expected Behavior

The import should work

### Actual Behavior

The plugin got crashed

### Relevant Error/Panic Output Snippet

```shell
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource
│ call. The plugin logs may contain more details.
╵

Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-aws_v5.10.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10c822e4c]

goroutine 421 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/opensearchserverless.(*resourceCollection).Read(0x119ca4f18?, {0x110c28ee0, 0x14004439830}, {{{{0x110c34dc0, 0x140044395f0}, {0x10f2ea7c0, 0x14004439500}}, {0x110c3d700, 0x140044d6640}}, 0x14003ed88a0, ...}, ...)
        github.com/hashicorp/terraform-provider-aws/internal/service/opensearchserverless/collection.go:211 +0x19c
github.com/hashicorp/terraform-provider-aws/internal/provider/fwprovider.(*wrappedResource).Read.func1({0x110c28ee0?, 0x14004439830?}, {{{{0x110c34dc0, 0x140044395f0}, {0x10f2ea7c0, 0x14004439500}}, {0x110c3d700, 0x140044d6640}}, 0x14003ed88a0, {{{0x0, ...}, ...}, ...}}, ...)
        github.com/hashicorp/terraform-provider-aws/internal/provider/fwprovider/intercept.go:205 +0xb8
github.com/hashicorp/terraform-provider-aws/internal/provider/fwprovider.interceptedHandler[...].func1({{{{0x110c34dc0?, 0x140044395f0?}, {0x10f2ea7c0, 0x14004439500}}, {0x110c3d700, 0x140044d6640}}, 0x14003ed88a0, {{{0x0, 0x0}, {0x0, ...}}, ...}}, ...)
        github.com/hashicorp/terraform-provider-aws/internal/provider/fwprovider/intercept.go:108 +0x2a4
github.com/hashicorp/terraform-provider-aws/internal/provider/fwprovider.(*wrappedResource).Read(0x140043b58c0, {0x110c28ee0, 0x14004438600}, {{{{0x110c34dc0, 0x140044395f0}, {0x10f2ea7c0, 0x14004439500}}, {0x110c3d700, 0x140044d6640}}, 0x14003ed88a0, ...}, ...)
        github.com/hashicorp/terraform-provider-aws/internal/provider/fwprovider/intercept.go:209 +0x180
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0x140027338c0, {0x110c28ee0, 0x14004438600}, 0x14004438690, 0x140044554f0)
        github.com/hashicorp/terraform-plugin-framework@v1.3.3/internal/fwserver/server_readresource.go:101 +0x508
github.com/hashicorp/terraform-plugin-framework/internal/proto5server.(*Server).ReadResource(0x140027338c0, {0x110c28ee0?, 0x140044384b0?}, 0x140043b5680)
        github.com/hashicorp/terraform-plugin-framework@v1.3.3/internal/proto5server/server_readresource.go:56 +0x314
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadResource({0x140027b5920, 0x14002a6d850, 0x140027b5950, 0x140027b5980, {0x140027da0a0, 0x2, 0x2}}, {0x110c28ee0?, 0x14004438180?}, 0x140043b5680)
        github.com/hashicorp/terraform-plugin-mux@v0.11.2/tf5muxserver/mux_server_ReadResource.go:29 +0x100
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x140027b7040, {0x110c28ee0?, 0x1400441b770?}, 0x140032810e0)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/tf5server/server.go:751 +0x3e8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x11083efc0?, 0x140027b7040}, {0x110c28ee0, 0x1400441b770}, 0x14000c5e850, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:386 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x140014a4000, {0x110c35be0, 0x1400055c680}, 0x1400442a900, 0x1400286d770, 0x116870eb0, 0x0)
        google.golang.org/grpc@v1.56.1/server.go:1337 +0xc90
google.golang.org/grpc.(*Server).handleStream(0x140014a4000, {0x110c35be0, 0x1400055c680}, 0x1400442a900, 0x0)
        google.golang.org/grpc@v1.56.1/server.go:1714 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.56.1/server.go:959 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.56.1/server.go:957 +0x16c

Error: The terraform-provider-aws_v5.10.0_x5 plugin crashed!
```
```


### Terraform Configuration Files

I ran the command 
```
terraform import module.infra.module.opensearch_serverless_ssg_events.aws_opensearchserverless_collection.oss_collection [my_id]
```

And the configuration that relavant is only
```
resource "aws_opensearchserverless_collection" "oss_collection" {
  name = var.name
  type = var.type

  tags = var.tags
}
```

### Steps to Reproduce

Running `terraform import module.infra.module.opensearch_serverless_ssg_events.aws_opensearchserverless_collection.oss_collection [my_id]`

### Debug Output

https://gist.github.com/admin-ssg/727330587e94f96d4d984ce568b3021a

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

**Comment by admin-ssg** [comment]
Ah found this error in the log
```
api error AccessDeniedException: User: arn:aws:iam::912340402538:user/ssg-async-backend is not authorized to perform: aoss:BatchGetCollection
```

**Comment by admin-ssg** [comment]
It solves the issue
