### ISSUE TITLE
[Bug]: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bmurrell-cbre** [hashicorp/terraform-provider-aws#33070]
### Terraform Core Version

1.4.0

### AWS Provider Version

5.9.0 and newer

### Affected Resource(s)

Amazon Connect

### Expected Behavior

Create/Delete TFN or DID numbers in Connect

### Actual Behavior

It will create/delete the number but error out. When you perform a run again, it acts like the resource was never created but in fact it was.

### Relevant Error/Panic Output Snippet

```shell
Stack trace from the terraform-provider-aws_v5.12.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x9545cec]

goroutine 315 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/connect.waitPhoneNumberCreated({0xe5bbae0, 0xc00147c240}, 0xd32a271?, 0x1bf08eb000, {0xc00415c3c0?, 0x0?})
github.com/hashicorp/terraform-provider-aws/internal/service/connect/wait.go:41 +0x14c
github.com/hashicorp/terraform-provider-aws/internal/service/connect.resourcePhoneNumberCreate({0xe5bbae0, 0xc00147c240}, 0xc0025cf000, {0xd2c8580?, 0xc003119a00?})
github.com/hashicorp/terraform-provider-aws/internal/service/connect/phone_number.go:159 +0xa45
github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0x0?, {0xd2c8580?, 0xc003119a00?})
github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:111 +0x34b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xe5bbae0?, {0xe5bbae0?, 0xc001470e10?}, 0xd?, {0xd2c8580?, 0xc003119a00?})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:728 +0x87
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000c7ab60, {0xe5bbae0, 0xc001470e10}, 0xc001822410, 0xc0025cee80, {0xd2c8580, 0xc003119a00})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:864 +0xa7e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc002089518, {0xe5bbae0?, 0xc001470cf0?}, 0xc004934140)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/grpc_provider.go:1024 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc0031249c0, 0xc00272ab60, 0xc0031249f0, 0xc003124a20, {0xc003134320, 0x2, 0x2}}, {0xe5bbae0?, 0xc0014709c0?}, 0xc004934140)
github.com/hashicorp/terraform-plugin-mux@v0.11.2/tf5muxserver/mux_server_ApplyResourceChange.go:30 +0x139
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0031117c0, {0xe5bbae0?, 0xc003ec7fb0?}, 0xc00142da40)
github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/tf5server/server.go:821 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xd04baa0?, 0xc0031117c0}, {0xe5bbae0, 0xc003ec7fb0}, 0xc00142d9d0, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:422 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000232780, {0xe5c8b80, 0xc00240c680}, 0xc001464a20, 0xc0031d6840, 0x146e5740, 0x0)
google.golang.org/grpc@v1.56.1/server.go:1337 +0xdf3
google.golang.org/grpc.(*Server).handleStream(0xc000232780, {0xe5c8b80, 0xc00240c680}, 0xc001464a20, 0x0)
google.golang.org/grpc@v1.56.1/server.go:1714 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.1()
google.golang.org/grpc@v1.56.1/server.go:959 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
google.golang.org/grpc@v1.56.1/server.go:957 +0x18c

Error: The terraform-provider-aws_v5.12.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Configuration Files

resource "aws_connect_phone_number" "phone_1" {
  target_arn   = aws_connect_instance.instance.arn
  description  = "TEST
  country_code = "GB"
  type         = "DID"
  prefix       = "+44113"
}

### Steps to Reproduce

Deploy Connect Instance and/or add on to a Connect instance and try to add a phone number.

### Would you like to implement a fix?

None

**Comment by bmurrell-cbre** [comment]
Updated TF version to 1.5.1 and it works
