### ISSUE TITLE
[Bug]: Error: The terraform-provider-aws_v5.13.1_x5.exe plugin crashed!

### ISSUE THREAD

**Issue by mostafaDashtiGrohe** [hashicorp/terraform-provider-aws#33131]
### Terraform Core Version

1.5.0

### AWS Provider Version

5.13.1

### Expected Behavior

A few resources should be created including VPC, API Gateway, DocumentDB, and Lambda functions. It was working last Friday and now it throws this error out.

### Actual Behavior

```
 Error: Request cancelled
│
│   with aws_api_gateway_resource.authorizer_api,
│   on api-endpoints.tf line 3, in resource "aws_api_gateway_resource" "authorizer_api":
│    3: resource "aws_api_gateway_resource" "authorizer_api" {
│
│ The plugin.(*GRPCProvider).ValidateResourceConfig request was cancelled.
```

### Relevant Error/Panic Output Snippet

```shell
Stack trace from the terraform-provider-aws_v5.13.1_x5.exe plugin:

panic: unaligned 64-bit atomic operation

goroutine 422 [running]:
runtime/internal/atomic.panicUnaligned()
        runtime/internal/atomic/unaligned.go:8 +0x2d
runtime/internal/atomic.Xadd64(0x1ec8c31c, 0x1)
        runtime/internal/atomic/atomic_386.s:125 +0x11
github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery.(*EndpointCache).Add(0x1ec8c300, {{0x21af8f00, 0x16}, {0x1e46a720, 0x1, 0x1}})
        github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery@v1.7.33/cache.go:76 +0xd1
github.com/aws/aws-sdk-go-v2/service/timestreamwrite.(*Client).handleEndpointDiscoveryFromService(0x1d0f6dd0, {0xd4765e0, 0x1e619278}, 
0x13370638, {0x21af8f00, 0x16}, {{0x0, 0x0}, 0x0, {0xd42d0fc, ...}})
        github.com/aws/aws-sdk-go-v2/service/timestreamwrite@v1.18.3/api_client.go:601 +0x52d
github.com/aws/aws-sdk-go-v2/service/timestreamwrite.(*Client).fetchOpCreateDatabaseDiscoverEndpoint(0x1d0f6dd0, {0xd4765e0, 0x1e619278}, {0xae00460, 0x1e619080}, {0x1e653f40, 0x1, 0x1})
        github.com/aws/aws-sdk-go-v2/service/timestreamwrite@v1.18.3/api_op_CreateDatabase.go:186 +0x246
github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery.(*DiscoverEndpoint).HandleSerialize(0x1e6190e0, {0xd4765e0, 0x1e619278}, {{0xae00460, 0x1e619080}, {0xc172140, 0x1e619218}}, {0xd42cfa8, 0x1e65ed40})
        github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery@v1.7.33/middleware.go:86 +0x1e4
github.com/aws/smithy-go/middleware.decoratedSerializeHandler.HandleSerialize(...)
        github.com/aws/smithy-go@v1.14.1/middleware/step_serialize.go:208
github.com/aws/aws-sdk-go-v2/service/timestreamwrite.(*opCreateDatabaseResolveEndpointMiddleware).HandleSerialize(0x1e65ec60, {0xd4765e0, 0x1e619200}, {{0xae00460, 0x1e619080}, {0xc172140, 0x1e619218}}, {0xd42cfa8, 0x1e65ed50})
        github.com/aws/aws-sdk-go-v2/service/timestreamwrite@v1.18.3/api_op_CreateDatabase.go:315 +0xd2b
github.com/aws/smithy-go/middleware.decoratedSerializeHandler.HandleSerialize(...)
        github.com/aws/smithy-go@v1.14.1/middleware/step_serialize.go:208
github.com/aws/aws-sdk-go-v2/service/timestreamwrite.(*ResolveEndpoint).HandleSerialize(0x1ec8c420, {0xd4765e0, 0x1e619200}, {{0xae00460, 0x1e619080}, {0xc172140, 0x1e619218}}, {0xd42cfa8, 0x1e65ed60})
        github.com/aws/aws-sdk-go-v2/service/timestreamwrite@v1.18.3/endpoints.go:80 +0x8dd
github.com/aws/smithy-go/middleware.decoratedSerializeHandler.HandleSerialize(...)
        github.com/aws/smithy-go@v1.14.1/middleware/step_serialize.go:208
github.com/aws/smithy-go/middleware.(*SerializeStep).HandleMiddleware(0x1e653ef0, {0xd4765e0, 0x1e619200}, {0xae00460, 0x1e619080}, {0xd42cf80, 0x1e65ecc0})
        github.com/aws/smithy-go@v1.14.1/middleware/step_serialize.go:122 +0x230
github.com/aws/smithy-go/middleware.decoratedHandler.Handle(...)
        github.com/aws/smithy-go@v1.14.1/middleware/middleware.go:57
github.com/aws/smithy-go/middleware.initializeWrapHandler.HandleInitialize(...)
        github.com/aws/smithy-go@v1.14.1/middleware/step_initialize.go:184
github.com/aws/aws-sdk-go-v2/service/timestreamwrite.(*validateOpCreateDatabase).HandleInitialize(0x13370638, {0xd4765e0, 0x1e619200}, 
{{0xae00460, 0x1e619080}}, {0xd42cfe4, 0x1e653f60})
        github.com/aws/aws-sdk-go-v2/service/timestreamwrite@v1.18.3/validators.go:50 +0xa4
github.com/aws/smithy-go/middleware.decoratedInitializeHandler.HandleInitialize(...)
        github.com/aws/smithy-go@v1.14.1/middleware/step_initialize.go:200
github.com/aws/smithy-go/middleware.(*setLogger).HandleInitialize(0x1e653f30, {0xd4765e0, 0x1e6191e8}, {{0xae00460, 0x1e619080}}, {0xd42cf94, 0x1e65ecf0})
        github.com/aws/smithy-go@v1.14.1/middleware/logging.go:45 +0x89
github.com/aws/smithy-go/middleware.decoratedInitializeHandler.HandleInitialize(...)
        github.com/aws/smithy-go@v1.14.1/middleware/step_initialize.go:200
github.com/aws/aws-sdk-go-v2/service/timestreamwrite.(*legacyEndpointContextSetter).HandleInitialize(0x1e653f28, {0xd4765e0, 0x1e6191e8}, {{0xae00460, 0x1e619080}}, {0xd42cf94, 0x1e65ed00})
        github.com/aws/aws-sdk-go-v2/service/timestreamwrite@v1.18.3/api_client.go:266 +0x9a
github.com/aws/smithy-go/middleware.decoratedInitializeHandler.HandleInitialize(...)
        github.com/aws/smithy-go@v1.14.1/middleware/step_initialize.go:200
github.com/aws/aws-sdk-go-v2/aws/middleware.RegisterServiceMetadata.HandleInitialize({{0xc2a3c80, 0x10}, {0xc26f8a2, 0xa}, {0x1e4fcf96, 0x9}, {0xc28959f, 0xe}}, {0xd4765e0, 0x1e619098}, ...)
        github.com/aws/aws-sdk-go-v2@v1.20.2/aws/middleware/metadata.go:41 +0x1ce
github.com/aws/smithy-go/middleware.decoratedInitializeHandler.HandleInitialize(...)
        github.com/aws/smithy-go@v1.14.1/middleware/step_initialize.go:200
github.com/aws/smithy-go/middleware.(*InitializeStep).HandleMiddleware(0x1e653ee0, {0xd4765e0, 0x1e619098}, {0xae00460, 0x1e619080}, {0xd42cf80, 0x1e65ecd0})
        github.com/aws/smithy-go@v1.14.1/middleware/step_initialize.go:114 +0x205
github.com/aws/smithy-go/middleware.decoratedHandler.Handle(...)
        github.com/aws/smithy-go@v1.14.1/middleware/middleware.go:57
github.com/aws/smithy-go/middleware.(*Stack).HandleMiddleware(0x1e662800, {0xd4765e0, 0x1e619098}, {0xae00460, 0x1e619080}, {0xd42d00c, 0x1e653f58})
        github.com/aws/smithy-go@v1.14.1/middleware/stack.go:109 +0x123
github.com/aws/smithy-go/middleware.decoratedHandler.Handle(...)
        github.com/aws/smithy-go@v1.14.1/middleware/middleware.go:57
github.com/aws/aws-sdk-go-v2/service/timestreamwrite.(*Client).invokeOperation(0x1d0f6dd0, {0xd4765e0, 0x1e618fc0}, {0xc28959f, 0xe}, {0xae00460, 0x1e619080}, {0x0, 0x0, 0x0}, ...)
        github.com/aws/aws-sdk-go-v2/service/timestreamwrite@v1.18.3/api_client.go:238 +0x629
github.com/aws/aws-sdk-go-v2/service/timestreamwrite.(*Client).CreateDatabase(0x1d0f6dd0, {0xd4765e0, 0x1e618fc0}, 0x1e619080, {0x0, 0x0, 0x0})
        github.com/aws/aws-sdk-go-v2/service/timestreamwrite@v1.18.3/api_op_CreateDatabase.go:31 +0xcd
github.com/hashicorp/terraform-provider-aws/internal/service/timestreamwrite.resourceDatabaseCreate({0xd4765e0, 0x1e618fc0}, 0x1e626e60, {0xc1f7d60, 0x1e39a0e0})
        github.com/hashicorp/terraform-provider-aws/internal/service/timestreamwrite/database.go:88 +0x220
github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0x1e626e60, {0xc1f7d60, 0x1e39a0e0})       
        github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:111 +0x360
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1e2a7730, {0xd4765e0, 0x1e618df8}, 0x1e626e60, {0xc1f7d60, 0x1e39a0e0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:728 +0x80
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1e2a7730, {0xd4765e0, 0x1e618df8}, 0x1ddf55e0, 0x1e626d70, {0xc1f7d60, 0x1e39a0e0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:864 +0xab4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1e2dddf0, {0xd4765e0, 0x1e618d98}, 0x1f5c1f80)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/grpc_provider.go:1024 +0xfa4
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0x1e3927e0, 0x1ea65590, 0x1e392800, 0x1e392820, {0x1e2dde00, 0x2, 0x2}}, {0xd4765e0, 0x1e618ca8}, 0x1f5c1f80)
        github.com/hashicorp/terraform-plugin-mux@v0.11.2/tf5muxserver/mux_server_ApplyResourceChange.go:30 +0x145
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x1e382870, {0xd4765e0, 0x1e6189f0}, 0x1d6a53c0)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/tf5server/server.go:821 +0x583
xd4765e0, 0x1e6189f0}, 0x1d6a5380, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:422 +0x18a
google.golang.org/grpc.(*Server).processUnaryRPC(0x1d0cc5a0, {0xd47c8fc, 0x1db2e000}, 0x1e632fa0, 0x1e41e2a0, 0x13336ca0, 0x0)
        google.golang.org/grpc@v1.57.0/server.go:1360 +0xee6
google.golang.org/grpc.(*Server).handleStream(0x1d0cc5a0, {0xd47c8fc, 0x1db2e000}, 0x1e632fa0, 0x0)
        google.golang.org/grpc@v1.57.0/server.go:1737 +0xa1e
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.57.0/server.go:982 +0xb1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.57.0/server.go:980 +0x178

Error: The terraform-provider-aws_v5.13.1_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Configuration Files

```hcl
resource "aws_api_gateway_resource" "authorizer_api" {
  rest_api_id = module.api_gateway.api_id
  parent_id   = module.api_gateway.api_root_resource_id
  path_part   = "Authentication"
}
```

### Steps to Reproduce

terraform init
terraform plan
terraform apply

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
@mostafaDashtiGrohe Thanks for raising this issue 👏.
Which operating system are you running Terraform on?

**Comment by mostafaDashtiGrohe** [comment]
Hi @ewbankkit , 
I noticed that the problem is related to the Timestream resource. When I removed that part of my code it deployed successfully on AWS. 
Here is how I used it: 
`
resource "aws_timestreamwrite_database" "timestream_db" {
  database_name = var.database_name
  tags = var.resource_tags
}
` 
FYI, I also tried to use "**5.12.0**" and "**5.13.0**" and I faced the same problem.

**Comment by mostafaDashtiGrohe** [comment]
Hi @ewbankkit , 
Is there any update regarding this issue?

**Comment by mostafaDashtiGrohe** [comment]
?

**Comment by ra100** [comment]
I am getting similar error,
OS: MacOS
terraform: 1.9.7
aws provider: 5.72.1 

```
aws_cognito_user_pool.main: Modifying... [id=us-east-XXXXXX]
╷
│ Error: Plugin did not respond
│ 
│   with aws_cognito_user_pool.main,
│   on cognito.tf line 1, in resource "aws_cognito_user_pool" "main":
│    1: resource "aws_cognito_user_pool" "main" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with aws_secretsmanager_secret.common_secrets,
│   on secrets-common.tf line 1, in resource "aws_secretsmanager_secret" "common_secrets":
│    1: resource "aws_secretsmanager_secret" "common_secrets" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-aws_v5.72.1_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 20 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/cognitoidp.resourceUserPoolSchemaHash({0x0?, 0x0?})
        github.com/hashicorp/terraform-provider-aws/internal/service/cognitoidp/user_pool.go:2294 +0x70c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).hash(0x14003ccab40?, {0x0?, 0x0?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/set.go:221 +0x34
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).add(0x14003d31200, {0x0, 0x0}, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/set.go:201 +0x6c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ConfigFieldReader).readSet(0x14003d29680, {0x14003d395c0, 0x1, 0x1}, 0x14003cca3c0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/field_reader_config.go:287 +0x298
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ConfigFieldReader).readField(0x14003d29680, {0x14003d395c0, 0x1, 0x1}, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/field_reader_config.go:110 +0x320
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ConfigFieldReader).ReadField(0x11adb49c0?, {0x14003d395c0?, 0x11789e8dd?, 0x6?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/field_reader_config.go:32 +0x84
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MultiLevelFieldReader).ReadFieldExact(0x14003d395b0?, {0x14003d395c0, 0x1, 0x1}, {0x11789e8dd, 0x6})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/field_reader_multi.go:34 +0x78
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0x14003c1a880, {0x14003d395c0, 0x1, 0x1}, 0x0?)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource_data.go:551 +0xfc
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).getChange(0x14003c1a880, {0x11789eba7?, 0x6?}, 0x1?, 0x12)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource_data.go:527 +0x150
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).diffChange(0x140034d6bc8?, {0x11789eba7?, 0x98?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource_data.go:504 +0x44
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diffSet(0x14003c91020, {0x11cd63d48, 0x1400182cd50}, {0x11789eba7, 0x6}, 0x14003cca3c0, 0x140034d6f98, {0x11cdb68a0, 0x14003c1a880}, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/schema.go:1412 +0x5c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diff(0x14003c91020, {0x11cd63d48, 0x1400182cd50}, {0x11789eba7, 0x6}, 0x14003cca3c0, 0x14003c1a800, {0x11cdb68a0, 0x14003c1a880}, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/schema.go:1134 +0x180
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0x14003c91020, {0x11cd63d48, 0x1400182cd50}, 0x14003cc6f70, 0x14003d14eb0, 0x0, {0x0, 0x0}, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/schema.go:678 +0x298
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.diffFromValues({0x11cd63d48, 0x1400182cd50}, {{{0x11cd64108?, 0x14003c4c148?}}, {0x11adb1780?, 0x14003c5c120?}}, {{{0x11cd64108?, 0x14003c4c288?}}, {0x11adb1780?, 0x14003c5d7d0?}}, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/shims.go:46 +0x208
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.DiffFromValues(...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/shims.go:23
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1400308f170, {0x11cd63d48?, 0x1400182cc90?}, 0x1400182e140)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/grpc_provider.go:1093 +0x500
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0x14000610af0, {0x11cd63d48?, 0x1400182c9c0?}, 0x1400182e140)
        github.com/hashicorp/terraform-plugin-mux@v0.16.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x184
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x14001d60000, {0x11cd63d48?, 0x1400182c1b0?}, 0x140009ac070)
        github.com/hashicorp/terraform-plugin-go@v0.24.0/tfprotov5/tf5server/server.go:865 +0x2a8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x11c88cc20, 0x14001d60000}, {0x11cd63d48, 0x1400182c1b0}, 0x14003c1a000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.24.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:545 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x14002ed2a00, {0x11cd63d48, 0x1400182c120}, {0x11cdddf20, 0x1400143fd40}, 0x14003c0a000, 0x14001254300, 0x12755b8f8, 0x0)
        google.golang.org/grpc@v1.66.2/server.go:1394 +0xb64
google.golang.org/grpc.(*Server).handleStream(0x14002ed2a00, {0x11cdddf20, 0x1400143fd40}, 0x14003c0a000)
        google.golang.org/grpc@v1.66.2/server.go:1805 +0xb20
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.66.2/server.go:1029 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 65
        google.golang.org/grpc@v1.66.2/server.go:1040 +0x13c

Error: The terraform-provider-aws_v5.72.1_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by oliverphardman** [comment]
Following. I am experiencing this when trying to modify my Cognito schema. It seems to happen for me when a custom attribute is present in Cognito which Terraform isn't aware of.
