### ISSUE TITLE
[Bug]: Error: The terraform-provider-aws_v4.67.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by VTRyo** [hashicorp/terraform-provider-aws#33169]
### Terraform Core Version

1.4.0

### AWS Provider Version

4.67.0

### Affected Resource(s)

# Overview

- We are trying to run a large terraform apply. So, we believe there are multiple problems. 
- Some resources are Terraform imported.
- This terraform apply from the local machine(M1)

## (*GRPCProvider).UpgradeResourceState

- aws_appflow_connector_profile
- aws_appflow_flow
- aws_sns_topic

## (*GRPCProvider).ApplyResourceChange call

Even resources that appear to be in good shape are failing.

- aws_cloudwatch_event_rule
- aws_iam_role
- aws_s3_bucket

### Expected Behavior

We can Terraform apply.

### Actual Behavior

```

Stack trace from the terraform-provider-aws_v4.67.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 546 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/appflow.expandConnectorProfileConfig(0x14000df8aa8?)
	github.com/hashicorp/terraform-provider-aws/internal/service/appflow/connector_profile.go:1518 +0x188
github.com/hashicorp/terraform-provider-aws/internal/service/appflow.resourceConnectorProfileUpdate({0x10e85b280, 0x140043c1da0}, 0x14007d7f880, {0x10e6ff4a0?, 0x14000286c00?})
	github.com/hashicorp/terraform-provider-aws/internal/service/appflow/connector_profile.go:1485 +0x154
github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0x0?, {0x10e6ff4a0?, 0x14000286c00?})
	github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:95 +0x118
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x10e85b280?, {0x10e85b280?, 0x140042d9710?}, 0xd?, {0x10e6ff4a0?, 0x14000286c00?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:736 +0x64
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x140008b7420, {0x10e85b280, 0x140042d9710}, 0x140081d5520, 0x14007d7f200, {0x10e6ff4a0, 0x14000286c00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:847 +0x67c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x140026f1680, {0x10e85b280?, 0x140042d9530?}, 0x140031b06e0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xb70
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0x140040e6450, 0x140040e64b0, {0x14005c7fa00, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0xdc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x14002fbfc20, {0x10e85b280?, 0x14004163560?}, 0x140084617a0)
	github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov5/tf5server/server.go:818 +0x3b8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x10e3eaa60?, 0x14002fbfc20}, {0x10e85b280, 0x14004163560}, 0x14008461730, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:419 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400544dc20, {0x10e86b9a0, 0x14000d781a0}, 0x14005611c20, 0x14005d07b90, 0x1153d6580, 0x0)
	google.golang.org/grpc@v1.54.0/server.go:1345 +0xc64
google.golang.org/grpc.(*Server).handleStream(0x1400544dc20, {0x10e86b9a0, 0x14000d781a0}, 0x14005611c20, 0x0)
	google.golang.org/grpc@v1.54.0/server.go:1722 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.54.0/server.go:966 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.54.0/server.go:964 +0x290

Error: The terraform-provider-aws_v4.67.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Relevant Error/Panic Output Snippet

```shell
Plan: 0 to add, 58 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.main.aws_cloudwatch_event_rule.appflow_execution_successful: Modifying... [id=appflow-execution-successful-event-development]
module.main.aws_cloudwatch_event_rule.glue_job_succeeded: Modifying... [id=glue-job-succeeded-event-development]
module.main.aws_iam_role.event_bridge_scheduler: Modifying... [id=Amazon_EventBridge_Scheduler_Step_Functions]
module.main.aws_glue_catalog_database.this: Modifying... [id=xxx:xxxx_bi_development]
module.main.aws_iam_role.glue_job: Modifying... [id=AWSGlueServiceRole-xxxx-development]
module.main.aws_sns_topic.appflow_notifier: Modifying... [id=arn:aws:sns:ap-northeast-1:xxxx:appflow-notifier-development]
module.main.aws_appflow_connector_profile.profile: Modifying... [id=arn:aws:appflow:ap-northeast-1:795516089875:connectorprofile/gcp-xxx-analytics]
module.main.aws_s3_bucket.appflow: Modifying... [id=xxx-appflow]
╷
│ Error: Plugin did not respond
│ 
│   with module.main.aws_appflow_connector_profile.profile,
│   on ../local-modules/main/appflow_connector.tf line 1, in resource "aws_appflow_connector_profile" "profile":
│    1: resource "aws_appflow_connector_profile" "profile" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│ 
│   with module.main.aws_appflow_flow.this["xxx-pageview-analytics-appflow"],
│   on ../local-modules/main/appflow_flow.tf line 1, in resource "aws_appflow_flow" "this":
│    1: resource "aws_appflow_flow" "this" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│   with module.main.aws_appflow_flow.this["xxx-menu-analytics-appflow"],
│   on ../local-modules/main/appflow_flow.tf line 1, in resource "aws_appflow_flow" "this":
│    1: resource "aws_appflow_flow" "this" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│   with module.main.aws_appflow_flow.this["xxxx-pageview-sub-content-analytics-appflow"],
│   on ../local-modules/main/appflow_flow.tf line 1, in resource "aws_appflow_flow" "this":
│    1: resource "aws_appflow_flow" "this" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.main.aws_appflow_flow.this["walk-pageview-analytics-appflow"],
│   on ../local-modules/main/appflow_flow.tf line 1, in resource "aws_appflow_flow" "this":
│    1: resource "aws_appflow_flow" "this" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ValidateResourceConfig call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│ 
│   with module.main.aws_appflow_flow.this["xxxx-invitation-analytics-appflow"],
│   on ../local-modules/main/appflow_flow.tf line 1, in resource "aws_appflow_flow" "this":
│    1: resource "aws_appflow_flow" "this" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│   with module.main.aws_appflow_flow.this["walk-session-analytics-appflow"],
│   on ../local-modules/main/appflow_flow.tf line 1, in resource "aws_appflow_flow" "this":
│    1: resource "aws_appflow_flow" "this" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│   with module.main.aws_appflow_flow.this["walk-time-analytics-appflow"],
│   on ../local-modules/main/appflow_flow.tf line 1, in resource "aws_appflow_flow" "this":
│    1: resource "aws_appflow_flow" "this" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.main.aws_appflow_flow.this["walk-feature-analytics-appflow"],
│   on ../local-modules/main/appflow_flow.tf line 1, in resource "aws_appflow_flow" "this":
│    1: resource "aws_appflow_flow" "this" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ValidateResourceConfig call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│ 
│   with module.main.aws_appflow_flow.this["xxxx-time-analytics-appflow"],
│   on ../local-modules/main/appflow_flow.tf line 1, in resource "aws_appflow_flow" "this":
│    1: resource "aws_appflow_flow" "this" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│   with module.main.aws_appflow_flow.this["xxx-session-analytics-appflow"],
│   on ../local-modules/main/appflow_flow.tf line 1, in resource "aws_appflow_flow" "this":
│    1: resource "aws_appflow_flow" "this" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│   with module.main.aws_cloudwatch_event_rule.appflow_execution_failed,
│   on ../local-modules/main/event_bridge.tf line 20, in resource "aws_cloudwatch_event_rule" "appflow_execution_failed":
│   20: resource "aws_cloudwatch_event_rule" "appflow_execution_failed" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.main.aws_cloudwatch_event_rule.appflow_execution_successful,
│   on ../local-modules/main/event_bridge.tf line 79, in resource "aws_cloudwatch_event_rule" "appflow_execution_successful":
│   79: resource "aws_cloudwatch_event_rule" "appflow_execution_successful" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│ 
│   with module.main.aws_cloudwatch_event_rule.glue_job_failed,
│   on ../local-modules/main/event_bridge.tf line 139, in resource "aws_cloudwatch_event_rule" "glue_job_failed":
│  139: resource "aws_cloudwatch_event_rule" "glue_job_failed" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.main.aws_cloudwatch_event_rule.glue_job_succeeded,
│   on ../local-modules/main/event_bridge.tf line 200, in resource "aws_cloudwatch_event_rule" "glue_job_succeeded":
│  200: resource "aws_cloudwatch_event_rule" "glue_job_succeeded" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.main.aws_sns_topic.appflow_notifier,
│   on ../local-modules/main/event_bridge.tf line 258, in resource "aws_sns_topic" "appflow_notifier":
│  258: resource "aws_sns_topic" "appflow_notifier" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│ 
│   with module.main.aws_sns_topic.glue_job_notifier,
│   on ../local-modules/main/event_bridge.tf line 270, in resource "aws_sns_topic" "glue_job_notifier":
│  270: resource "aws_sns_topic" "glue_job_notifier" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.main.aws_iam_role.event_bridge_scheduler,
│   on ../local-modules/main/event_bridge_scheduler_iam.tf line 1, in resource "aws_iam_role" "event_bridge_scheduler":
│    1: resource "aws_iam_role" "event_bridge_scheduler" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.main.aws_glue_catalog_database.this,
│   on ../local-modules/main/glue_catalog.tf line 1, in resource "aws_glue_catalog_database" "this":
│    1: resource "aws_glue_catalog_database" "this" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│ 
│   with module.main.aws_glue_connection.xxx_connection,
│   on ../local-modules/main/glue_connection.tf line 1, in resource "aws_glue_connection" "xxx_connection":
│    1: resource "aws_glue_connection" "xxx_connection" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.main.aws_iam_role.glue_job,
│   on ../local-modules/main/glue_iam.tf line 13, in resource "aws_iam_role" "glue_job":
│   13: resource "aws_iam_role" "glue_job" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.main.aws_s3_bucket.appflow,
│   on ../local-modules/main/s3.tf line 1, in resource "aws_s3_bucket" "appflow":
│    1: resource "aws_s3_bucket" "appflow" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│ 
│   with module.main.aws_s3_bucket.bi,
│   on ../local-modules/main/s3.tf line 19, in resource "aws_s3_bucket" "bi":
│   19: resource "aws_s3_bucket" "bi" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│   with module.main.aws_iam_role.sfn,
│   on ../local-modules/main/step_functions_iam.tf line 10, in resource "aws_iam_role" "sfn":
│   10: resource "aws_iam_role" "sfn" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

Stack trace from the terraform-provider-aws_v4.67.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 546 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/appflow.expandConnectorProfileConfig(0x14000df8aa8?)
	github.com/hashicorp/terraform-provider-aws/internal/service/appflow/connector_profile.go:1518 +0x188
github.com/hashicorp/terraform-provider-aws/internal/service/appflow.resourceConnectorProfileUpdate({0x10e85b280, 0x140043c1da0}, 0x14007d7f880, {0x10e6ff4a0?, 0x14000286c00?})
	github.com/hashicorp/terraform-provider-aws/internal/service/appflow/connector_profile.go:1485 +0x154
github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0x0?, {0x10e6ff4a0?, 0x14000286c00?})
	github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:95 +0x118
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x10e85b280?, {0x10e85b280?, 0x140042d9710?}, 0xd?, {0x10e6ff4a0?, 0x14000286c00?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:736 +0x64
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x140008b7420, {0x10e85b280, 0x140042d9710}, 0x140081d5520, 0x14007d7f200, {0x10e6ff4a0, 0x14000286c00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:847 +0x67c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x140026f1680, {0x10e85b280?, 0x140042d9530?}, 0x140031b06e0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xb70
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0x140040e6450, 0x140040e64b0, {0x14005c7fa00, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0xdc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x14002fbfc20, {0x10e85b280?, 0x14004163560?}, 0x140084617a0)
	github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov5/tf5server/server.go:818 +0x3b8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x10e3eaa60?, 0x14002fbfc20}, {0x10e85b280, 0x14004163560}, 0x14008461730, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:419 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400544dc20, {0x10e86b9a0, 0x14000d781a0}, 0x14005611c20, 0x14005d07b90, 0x1153d6580, 0x0)
	google.golang.org/grpc@v1.54.0/server.go:1345 +0xc64
google.golang.org/grpc.(*Server).handleStream(0x1400544dc20, {0x10e86b9a0, 0x14000d781a0}, 0x14005611c20, 0x0)
	google.golang.org/grpc@v1.54.0/server.go:1722 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.54.0/server.go:966 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.54.0/server.go:964 +0x290

Error: The terraform-provider-aws_v4.67.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Configuration Files

Appflow is described on behalf of many.

- aws_appflow_connector_profile

```tf
resource "aws_appflow_connector_profile" "profile" {
  name = "gcp-xxx-analytics"
  connector_type = "CustomConnector"
  connector_label = "GoogleAnalytics4"
  connection_mode = "Public"

  connector_profile_config {
    connector_profile_credentials {}

    connector_profile_properties {
      custom_connector {
        profile_properties = {}

        oauth2_properties {
          oauth2_grant_type = "AUTHORIZATION_CODE"
          token_url = "https://oauth2.googleapis.com/token"
          token_url_custom_properties = {}
        }
      }
    }
  }
}
```
- appflow

```tf
resource "aws_appflow_flow" "this" {
  for_each = toset(var.analytics_appflow_list)
  name = "${each.value}-${var.env}"

  source_flow_config {
    connector_type = "CustomConnector"
    connector_profile_name = "gcp-xxx-analytics"
    api_version = "v1beta"

    source_connector_properties {
      custom_connector {
        entity_name = substr(each.value, 0, 8) == "xxx-" ? (
          "core-reports/accounts/98180535/properties/xxxx"
        ) : (
          "core-reports/accounts/98180535/properties/xxxx"
        )
      }
    }
  }

  destination_flow_config {
    connector_type = "S3"

    destination_connector_properties {
      s3 {
        bucket_name = "${local.service}-appflow"

        s3_output_format_config {
          file_type = "CSV"
          preserve_source_data_typing = false

          aggregation_config {
            aggregation_type = "SingleFile"
          }

          prefix_config {
            prefix_format = "DAY"
            prefix_type = "PATH"
          }
        }
      }
    }
  }

  task {
    source_fields = [""]
    task_type = "Map"
  }

  trigger_config {
    trigger_type = "OnDemand"
  }

  lifecycle {
    ignore_changes = [
      task 
    ]
  }
}
```

### Steps to Reproduce

run terraform plan / terraform apply

### Would you like to implement a fix?

None

**Comment by VTRyo** [comment]
@arimal199 
Thank you for your advice. I too thought the cause was Appflow. 
I think it doesn’t "nil check" in this procedure. 
https://github.com/hashicorp/terraform-provider-aws/blob/v5.13.1/internal/service/appflow/connector_profile.go#L2077-L2089
