### ISSUE TITLE
Plugin did not respond[Bug]: 

### ISSUE THREAD

**Issue by PradiptaBehera8558** [hashicorp/terraform-provider-aws#33215]
### Terraform Core Version

1.5.6

### AWS Provider Version

5.14.0

### Affected Resource(s)

aws_timestreamwrite_database

### Expected Behavior

Resource should have created.

### Actual Behavior

plugin didn't respond error

### Relevant Error/Panic Output Snippet

```shell
aws_timestreamwrite_database.historicalData: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with aws_timestreamwrite_database.historicalData,
│   on infra.tf line 5, in resource "aws_timestreamwrite_database" "historicalData":
│    5: resource "aws_timestreamwrite_database" "historicalData" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-aws_v5.14.0_x5.exe plugin:

panic: unaligned 64-bit atomic operation

goroutine 356 [running]:
runtime/internal/atomic.panicUnaligned()
	runtime/internal/atomic/unaligned.go:8 +0x2d
runtime/internal/atomic.Xadd64(0x2009f21c, 0x1)
	runtime/internal/atomic/atomic_386.s:125 +0x11
github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery.(*EndpointCache).Add(0x2009f200, {{0x201084b0, 0x16}, {0x1e7ae768, 0x1, 0x1}})
	github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery@v1.7.35/cache.go:76 +0xd1
github.com/aws/aws-sdk-go-v2/service/timestreamwrite.(*Client).handleEndpointDiscoveryFromService(0x1e78a0d0, {0xd716e60, 0x203cfa58}, 0x136227d8, {0x201084b0, 0x16}, {{0x0, 0x0}, 0x0, {0xd6cd8bc, ...}})
	github.com/aws/aws-sdk-go-v2/service/timestreamwrite@v1.18.5/api_client.go:601 +0x52d
github.com/aws/aws-sdk-go-v2/service/timestreamwrite.(*Client).fetchOpCreateDatabaseDiscoverEndpoint(0x1e78a0d0, {0xd716e60, 0x203cfa58}, {0xb09c5a0, 0x203cf860}, {0x201e7590, 0x1, 0x1})
	github.com/aws/aws-sdk-go-v2/service/timestreamwrite@v1.18.5/api_op_CreateDatabase.go:186 +0x246
github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery.(*DiscoverEndpoint).HandleSerialize(0x203cf8c0, {0xd716e60, 0x203cfa58}, {{0xb09c5a0, 0x203cf860}, {0xc40fa20, 0x203cf9f8}}, {0xd6cd768, 0x1eacb190})
	github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery@v1.7.35/middleware.go:86 +0x1e4
github.com/aws/smithy-go/middleware.decoratedSerializeHandler.HandleSerialize(...)
	github.com/aws/smithy-go@v1.14.2/middleware/step_serialize.go:208
github.com/aws/aws-sdk-go-v2/service/timestreamwrite.(*opCreateDatabaseResolveEndpointMiddleware).HandleSerialize(0x1eacb0b0, {0xd716e60, 0x203cf9e0}, {{0xb09c5a0, 0x203cf860}, {0xc40fa20, 0x203cf9f8}}, {0xd6cd768, 0x1eacb1a0})
	github.com/aws/aws-sdk-go-v2/service/timestreamwrite@v1.18.5/api_op_CreateDatabase.go:315 +0xd2b
github.com/aws/smithy-go/middleware.decoratedSerializeHandler.HandleSerialize(...)
	github.com/aws/smithy-go@v1.14.2/middleware/step_serialize.go:208
github.com/aws/aws-sdk-go-v2/service/timestreamwrite.(*ResolveEndpoint).HandleSerialize(0x2009f320, {0xd716e60, 0x203cf9e0}, {{0xb09c5a0, 0x203cf860}, {0xc40fa20, 0x203cf9f8}}, {0xd6cd768, 0x1eacb1b0})
	github.com/aws/aws-sdk-go-v2/service/timestreamwrite@v1.18.5/endpoints.go:80 +0x8dd
github.com/aws/smithy-go/middleware.decoratedSerializeHandler.HandleSerialize(...)
	github.com/aws/smithy-go@v1.14.2/middleware/step_serialize.go:208
github.com/aws/smithy-go/middleware.(*SerializeStep).HandleMiddleware(0x201e7540, {0xd716e60, 0x203cf9e0}, {0xb09c5a0, 0x203cf860}, {0xd6cd740, 0x1eacb110})
	github.com/aws/smithy-go@v1.14.2/middleware/step_serialize.go:122 +0x230
github.com/aws/smithy-go/middleware.decoratedHandler.Handle(...)
	github.com/aws/smithy-go@v1.14.2/middleware/middleware.go:57
github.com/aws/smithy-go/middleware.initializeWrapHandler.HandleInitialize(...)
	github.com/aws/smithy-go@v1.14.2/middleware/step_initialize.go:184
github.com/aws/aws-sdk-go-v2/service/timestreamwrite.(*validateOpCreateDatabase).HandleInitialize(0x136227d8, {0xd716e60, 0x203cf9e0}, {{0xb09c5a0, 0x203cf860}}, {0xd6cd7a4, 0x201e75b0})
	github.com/aws/aws-sdk-go-v2/service/timestreamwrite@v1.18.5/validators.go:50 +0xa4
github.com/aws/smithy-go/middleware.decoratedInitializeHandler.HandleInitialize(...)
	github.com/aws/smithy-go@v1.14.2/middleware/step_initialize.go:200
github.com/aws/smithy-go/middleware.(*setLogger).HandleInitialize(0x201e7580, {0xd716e60, 0x203cf9c8}, {{0xb09c5a0, 0x203cf860}}, {0xd6cd754, 0x1eacb140})
	github.com/aws/smithy-go@v1.14.2/middleware/logging.go:45 +0x89
github.com/aws/smithy-go/middleware.decoratedInitializeHandler.HandleInitialize(...)
	github.com/aws/smithy-go@v1.14.2/middleware/step_initialize.go:200
github.com/aws/aws-sdk-go-v2/service/timestreamwrite.(*legacyEndpointContextSetter).HandleInitialize(0x201e7578, {0xd716e60, 0x203cf9c8}, {{0xb09c5a0, 0x203cf860}}, {0xd6cd754, 0x1eacb150})
	github.com/aws/aws-sdk-go-v2/service/timestreamwrite@v1.18.5/api_client.go:266 +0x9a
github.com/aws/smithy-go/middleware.decoratedInitializeHandler.HandleInitialize(...)
	github.com/aws/smithy-go@v1.14.2/middleware/step_initialize.go:200
github.com/aws/aws-sdk-go-v2/aws/middleware.RegisterServiceMetadata.HandleInitialize({{0xc5416d3, 0x10}, {0xc50d278, 0xa}, {0x1db512d0, 0xe}, {0xc526f9d, 0xe}}, {0xd716e60, 0x203cf878}, ...)
	github.com/aws/aws-sdk-go-v2@v1.21.0/aws/middleware/metadata.go:41 +0x1ce
github.com/aws/smithy-go/middleware.decoratedInitializeHandler.HandleInitialize(...)
	github.com/aws/smithy-go@v1.14.2/middleware/step_initialize.go:200
github.com/aws/smithy-go/middleware.(*InitializeStep).HandleMiddleware(0x201e7530, {0xd716e60, 0x203cf878}, {0xb09c5a0, 0x203cf860}, {0xd6cd740, 0x1eacb120})
	github.com/aws/smithy-go@v1.14.2/middleware/step_initialize.go:114 +0x205
github.com/aws/smithy-go/middleware.decoratedHandler.Handle(...)
	github.com/aws/smithy-go@v1.14.2/middleware/middleware.go:57
github.com/aws/smithy-go/middleware.(*Stack).HandleMiddleware(0x202afd40, {0xd716e60, 0x203cf878}, {0xb09c5a0, 0x203cf860}, {0xd6cd7cc, 0x201e75a8})
	github.com/aws/smithy-go@v1.14.2/middleware/stack.go:109 +0x123
github.com/aws/smithy-go/middleware.decoratedHandler.Handle(...)
	github.com/aws/smithy-go@v1.14.2/middleware/middleware.go:57
github.com/aws/aws-sdk-go-v2/service/timestreamwrite.(*Client).invokeOperation(0x1e78a0d0, {0xd716e60, 0x203cf7a0}, {0xc526f9d, 0xe}, {0xb09c5a0, 0x203cf860}, {0x0, 0x0, 0x0}, ...)
	github.com/aws/aws-sdk-go-v2/service/timestreamwrite@v1.18.5/api_client.go:238 +0x629
github.com/aws/aws-sdk-go-v2/service/timestreamwrite.(*Client).CreateDatabase(0x1e78a0d0, {0xd716e60, 0x203cf7a0}, 0x203cf860, {0x0, 0x0, 0x0})
	github.com/aws/aws-sdk-go-v2/service/timestreamwrite@v1.18.5/api_op_CreateDatabase.go:31 +0xcd
github.com/hashicorp/terraform-provider-aws/internal/service/timestreamwrite.resourceDatabaseCreate({0xd716e60, 0x203cf7a0}, 0x1d8a37c0, {0xc495680, 0x1e4f7880})
	github.com/hashicorp/terraform-provider-aws/internal/service/timestreamwrite/database.go:88 +0x220
github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0x1d8a37c0, {0xc495680, 0x1e4f7880})
	github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:111 +0x360
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1efc5180, {0xd716e60, 0x203cf5d8}, 0x1d8a37c0, {0xc495680, 0x1e4f7880})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:728 +0x80
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1efc5180, {0xd716e60, 0x203cf5d8}, 0x1e2687e0, 0x1d8a36d0, {0xc495680, 0x1e4f7880})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:864 +0xab4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1e7021c0, {0xd716e60, 0x203cf578}, 0x2009ee10)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/grpc_provider.go:1024 +0xfa4
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0x1e4e1600, 0x2026e790, 0x1e4e1620, 0x1e4e1640, {0x1e7021d0, 0x2, 0x2}}, {0xd716e60, 0x203cf488}, 0x2009ee10)
	github.com/hashicorp/terraform-plugin-mux@v0.11.2/tf5muxserver/mux_server_ApplyResourceChange.go:30 +0x145
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x1d9865f0, {0xd716e60, 0x203cf1a0}, 0x1d8e6680)
	github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/tf5server/server.go:821 +0x583
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xc37de40, 0x1d9865f0}, {0xd716e60, 0x203cf1a0}, 0x1d8e6640, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:422 +0x18a
google.golang.org/grpc.(*Server).processUnaryRPC(0x1d53c7e0, {0xd71d1bc, 0x1d876120}, 0x1e24f720, 0x1e4eb668, 0x135e8e20, 0x0)
	google.golang.org/grpc@v1.57.0/server.go:1360 +0xee6
google.golang.org/grpc.(*Server).handleStream(0x1d53c7e0, {0xd71d1bc, 0x1d876120}, 0x1e24f720, 0x0)
	google.golang.org/grpc@v1.57.0/server.go:1737 +0xa1e
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.57.0/server.go:982 +0xb1
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.57.0/server.go:980 +0x178

Error: The terraform-provider-aws_v5.14.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

ERROR:root:Error running the terraform command with: Command 'terraform apply -auto-approve' returned non-zero exit status 1.
```

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "ap-northeast-1"
}

resource "aws_timestreamwrite_database" "historicalData" {
  database_name = "Crypto_Historical_Data"
}
```

### Steps to Reproduce

NA

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Similar: https://github.com/hashicorp/terraform-provider-aws/issues/33131.

**Comment by ewbankkit** [comment]
@PradiptaBehera8558 Thanks for raising this issue 👏.
Which version of Windows are you running Terraform on?

**Comment by PradiptaBehera8558** [comment]
> @PradiptaBehera8558 Thanks for raising this issue 👏.
> Which version of Windows are you running Terraform on?

Windows 11
