### ISSUE TITLE
[Bug]: Error strconv.ParseInt - AWS data-size EFS output

### ISSUE THREAD

**Issue by org-ci-cd** [hashicorp/terraform-provider-aws#33229]
### Terraform Core Version

1.5.6

### AWS Provider Version

5.14.0

### Affected Resource(s)

aws_efs_file_system

### Expected Behavior

Plugin should handle EFS size properly

### Actual Behavior

The plugin crash because of an invalid INT parsing

### Relevant Error/Panic Output Snippet

```shell
Stack trace from the terraform-provider-aws_v5.14.0_x5 plugin:

panic: Error reading level state: strconv.ParseInt: parsing "2250913792": value out of range

goroutine 6792 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0x1dd49db0, {0x1ea57c98, 0x1, 0x1}, 0x8)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource_data.go:556 +0x279
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).State(0x1dd49db0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource_data.go:354 +0x3a7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ShimInstanceStateFromValue(0x1d16c930, {{{0x14e3ee60, 0x1ea57188}}, {0x124ef780, 0x1e4515a0}})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:625 +0x1eb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x1dbf7690, {0x14e3e380, 0x1e0adbc0}, 0x1e450f20)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/grpc_provider.go:590 +0x23f
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadResource({0x1dc236a0, 0x1dbddbf0, 0x1dc236c0, 0x1dc236e0, {0x1dbf76a0, 0x2, 0x2}}, {0x14e3e380, 0x1e0adad0}, 0x1e450f20)
        github.com/hashicorp/terraform-plugin-mux@v0.11.2/tf5muxserver/mux_server_ReadResource.go:29 +0x145
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x1d40c870, {0x14e3e380, 0x1e0ad800}, 0x1da7f530)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/tf5server/server.go:751 +0x4c5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x13ab34a0, 0x1d40c870}, {0x14e3e380, 0x1e0ad800}, 0x1cc99480, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:386 +0x18a
google.golang.org/grpc.(*Server).processUnaryRPC(0x1d051440, {0x14e446dc, 0x1c4f8480}, 0x1d364a00, 0x1dc1fb48, 0x1ad04e48, 0x0)
        google.golang.org/grpc@v1.57.0/server.go:1360 +0xee6
google.golang.org/grpc.(*Server).handleStream(0x1d051440, {0x14e446dc, 0x1c4f8480}, 0x1d364a00, 0x0)
        google.golang.org/grpc@v1.57.0/server.go:1737 +0xa1e
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.57.0/server.go:982 +0xb1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.57.0/server.go:980 +0x178

Error: The terraform-provider-aws_v5.14.0_x5 plugin crashed!
```

### Terraform Configuration Files

I was able to get the faulty Integer from my state, maybe it can help.
It's in the property **size_in_bytes**

```
> cat state.json  | grep -C30 2250913792
    {
      "module": "module.stack.module.nfs",
      "mode": "managed",
      "type": "aws_efs_file_system",
      "name": "efs",
      "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
      "instances": [
        {
          "index_key": 0,
          "schema_version": 0,
          "attributes": {
            "arn": "arn:aws:elasticfilesystem:ca-central-1:<anonymized>:file-system/fs-<anonymized>",
            "availability_zone_id": "",
            "availability_zone_name": "",
            "creation_token": "<anonymized>",
            "dns_name": "fs-<anonymized>.efs.ca-central-1.amazonaws.com",
            "encrypted": true,
            "id": "fs-<anonymized>",
            "kms_key_id": "arn:aws:kms:ca-central-1:<anonymized>:key/<anonymized>",
            "lifecycle_policy": [],
            "number_of_mount_targets": 3,
            "owner_id": "<anonymized>",
            "performance_mode": "generalPurpose",
            "provisioned_throughput_in_mibps": 40,
            "size_in_bytes": [
              {
                "value": 2250913792,
                "value_in_ia": 0,
                "value_in_standard": 2250913792
              }
            ],

```

### Steps to Reproduce

Might be hard to reproduce as the EFS drive needs to grow to a proper size, but I found this closed thread that explains the issue properly

Thread: https://github.com/hashicorp/terraform-provider-aws/issues/19910

Someone in that thread is also linking to this location as the potential root cause.
https://github.com/hashicorp/terraform-plugin-sdk/blob/112e2164c381d80e8ada3170dac9a8a5db01079a/helper/schema/field_reader.go#L313-L327

### Would you like to implement a fix?

None

**Comment by org-ci-cd** [comment]
Ah my bad, I had downloaded the 386 instead of the AMD64.

![image](https://github.com/hashicorp/terraform-provider-aws/assets/55146028/81c1ebf6-ebff-47f0-9541-b30e32ac0a0d)
