### ISSUE TITLE
[Bug]: AWS Config aws_config_configuration_recorder deployment crash.

### ISSUE THREAD

**Issue by xposix** [hashicorp/terraform-provider-aws#33742]
### Terraform Core Version

1.5.7

### AWS Provider Version

5.14.0, 5.19.0

### Affected Resource(s)

* aws_config_configuration_recorder

### Expected Behavior

Perform a deployment of an AWS Config Configuration Recorder.

### Actual Behavior

The process crashed showing this:

```shell
Error: The terraform-provider-aws_v5.19.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Relevant Error/Panic Output Snippet

```shell
module.aws_config_primary_region.aws_config_configuration_recorder.awsconfig: Creating...
module.aws_config_secondary_region.aws_config_configuration_recorder.awsconfig: Creating...
╷
│ Error: Plugin did not respond
│
│   with module.aws_config_primary_region.aws_config_configuration_recorder.awsconfig,
│   on ../../modules/awsconfig/config_recorder.tf line 1, in resource "aws_config_configuration_recorder" "awsconfig":
│    1: resource "aws_config_configuration_recorder" "awsconfig" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.aws_config_secondary_region.aws_config_configuration_recorder.awsconfig,
│   on ../../modules/awsconfig/config_recorder.tf line 1, in resource "aws_config_configuration_recorder" "awsconfig":
│    1: resource "aws_config_configuration_recorder" "awsconfig" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-aws_v5.19.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 308 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/configservice.expandRecordingGroupExclusionByResourceTypes({0x14001c16b50, 0x1, 0x10c12be77?})
	github.com/hashicorp/terraform-provider-aws/internal/service/configservice/flex.go:87 +0x100
github.com/hashicorp/terraform-provider-aws/internal/service/configservice.expandRecordingGroup(0x14001b02be8?)
	github.com/hashicorp/terraform-provider-aws/internal/service/configservice/flex.go:65 +0x11c
github.com/hashicorp/terraform-provider-aws/internal/service/configservice.resourceConfigurationRecorderPut({0x1101d8580, 0x14001c054d0}, 0x14005862b80, {0x11002e2e0?, 0x14002480620?})
	github.com/hashicorp/terraform-provider-aws/internal/service/configservice/configuration_recorder.go:124 +0x200
github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0x0?, {0x11002e2e0?, 0x14002480620?})
	github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:111 +0x28c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1101d8580?, {0x1101d8580?, 0x140058471d0?}, 0xd?, {0x11002e2e0?, 0x14002480620?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:773 +0x64
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x14000e2c7e0, {0x1101d8580, 0x140058471d0}, 0x14005868750, 0x14005862a00, {0x11002e2e0, 0x14002480620})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:909 +0x8a0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x14003b876c8, {0x1101d8580?, 0x140058470b0?}, 0x140000ca5f0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xb78
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0x1101d84d8?, {0x1101d8580?, 0x14005846d80?}, 0x140000ca5f0)
	github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x188
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x14003bd66e0, {0x1101d8580?, 0x14005846360?}, 0x140005ee230)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x3bc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x10fdb8760?, 0x14003bd66e0}, {0x1101d8580, 0x14005846360}, 0x140005ee1c0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000020780, {0x1101e5b00, 0x1400251e340}, 0x1400584c120, 0x1400250ac60, 0x1165353f8, 0x0)
	google.golang.org/grpc@v1.57.0/server.go:1360 +0xcb4
google.golang.org/grpc.(*Server).handleStream(0x14000020780, {0x1101e5b00, 0x1400251e340}, 0x1400584c120, 0x0)
	google.golang.org/grpc@v1.57.0/server.go:1737 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.57.0/server.go:982 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.57.0/server.go:980 +0x16c
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 329 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/configservice.expandRecordingGroupExclusionByResourceTypes({0x140041df030, 0x1, 0x10a463e77?})
	github.com/hashicorp/terraform-provider-aws/internal/service/configservice/flex.go:87 +0x100
github.com/hashicorp/terraform-provider-aws/internal/service/configservice.expandRecordingGroup(0x1400162cbe8?)
	github.com/hashicorp/terraform-provider-aws/internal/service/configservice/flex.go:65 +0x11c
github.com/hashicorp/terraform-provider-aws/internal/service/configservice.resourceConfigurationRecorderPut({0x10e510580, 0x1400204d4a0}, 0x14000162e80, {0x10e3662e0?, 0x14002536b60?})
	github.com/hashicorp/terraform-provider-aws/internal/service/configservice/configuration_recorder.go:124 +0x200
github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0x0?, {0x10e3662e0?, 0x14002536b60?})
	github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:111 +0x28c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x10e510580?, {0x10e510580?, 0x14002044e40?}, 0xd?, {0x10e3662e0?, 0x14002536b60?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:773 +0x64
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x14000a4ae00, {0x10e510580, 0x14002044e40}, 0x14001798750, 0x14000162d00, {0x10e3662e0, 0x14002536b60})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:909 +0x8a0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x14000953a40, {0x10e510580?, 0x14002044cf0?}, 0x14003a9fef0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xb78
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0x10e5104d8?, {0x10e510580?, 0x14002044960?}, 0x14003a9fef0)
	github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x188
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x1400095c140, {0x10e510580?, 0x14002041ec0?}, 0x14000ddd1f0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x3bc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x10e0f0760?, 0x1400095c140}, {0x10e510580, 0x14002041ec0}, 0x14000ddd180, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400015e780, {0x10e51db00, 0x1400183dd40}, 0x14001612480, 0x14002545bf0, 0x11486d3f8, 0x0)
	google.golang.org/grpc@v1.57.0/server.go:1360 +0xcb4
google.golang.org/grpc.(*Server).handleStream(0x1400015e780, {0x10e51db00, 0x1400183dd40}, 0x14001612480, 0x0)
	google.golang.org/grpc@v1.57.0/server.go:1737 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.57.0/server.go:982 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.57.0/server.go:980 +0x16c

Error: The terraform-provider-aws_v5.19.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Configuration Files

```terraform
resource "aws_config_configuration_recorder" "awsconfig" {
  name     = var.name
  role_arn = aws_iam_role.awsconfig.arn

  recording_group {
    all_supported = var.aws_config_exclude_resource_types == [] ? true : false
    exclusion_by_resource_types {
      resource_types = var.aws_config_exclude_resource_types
    }
    recording_strategy {
      use_only = "EXCLUSION_BY_RESOURCE_TYPES"
    }
  }
}

resource "aws_config_delivery_channel" "awsconfig" {
  name           = aws_config_configuration_recorder.awsconfig.name
  s3_bucket_name = aws_s3_bucket.aws_config_log_bucket.id

  snapshot_delivery_properties {
    delivery_frequency = var.delivery_frequency
  }

  sns_topic_arn = var.notification_sns_topic_arn
}

resource "aws_config_configuration_recorder_status" "awsconfig" {
  name       = aws_config_delivery_channel.awsconfig.name
  is_enabled = true
}


resource "aws_iam_role" "awsconfig" {
  name = "clz_${var.name}_awsconfig"

  assume_role_policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "config.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
POLICY
}

resource "aws_iam_role_policy_attachment" "awsconfig" {
  role       = aws_iam_role.awsconfig.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWS_ConfigRole"
}

resource "aws_iam_role_policy" "awsconfig" {
  name = "${var.name}-awsconfig"
  role = aws_iam_role.awsconfig.id

  policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "s3:*"
      ],
      "Effect": "Allow",
      "Resource": [
        "${aws_s3_bucket.aws_config_log_bucket.arn}",
        "${aws_s3_bucket.aws_config_log_bucket.arn}/*"
      ]
    }
  ]
}
POLICY
}

data "aws_region" "current" {}
data "aws_caller_identity" "current" {}
variable "name" {
  type        = string
  description = "Dedicated name for this deployment e.g: eu-west-2-nonlive-config"
}

variable "aws_config_exclude_resource_types" {
  type        = list(string)
  description = "Services to stop recording changes. More info: https://docs.aws.amazon.com/config/latest/APIReference/API_ResourceIdentifier.html#config-Type-ResourceIdentifier-resourceType"
  default     = []
}

variable "delivery_frequency" {
  type = string
  validation {
    condition     = contains(["One_Hour", "Three_Hours", "Six_Hours", "Twelve_Hours", "TwentyFour_Hours"], var.delivery_frequency)
    error_message = "This value can only be one of these options: One_Hour | Three_Hours | Six_Hours | Twelve_Hours | TwentyFour_Hours"
  }
}

variable "notification_sns_topic_arn" {
  type        = string
  description = "SNS topic ARN to send the notifications to"
}

variable "tags" {
  type        = map(any)
  description = "A key/value map containing tags to be added to all resources"
}

##############################################################################
## AWS Config Logging bucket
## 
resource "aws_s3_bucket" "aws_config_log_bucket" {
  bucket = "awsconfig-logging-${replace(var.name, "_", "-")}"
  tags   = var.tags
}

resource "aws_s3_bucket_policy" "aws_config_log_bucket" {
  bucket = aws_s3_bucket.aws_config_log_bucket.id
  policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
      {
        "Sid": "S3ServerAccessLogsPolicy",
        "Effect": "Allow",
        "Principal": {
          "Service": "logging.s3.amazonaws.com"
        },
        "Action": [
          "s3:PutObject"
        ],
        "Resource": "${aws_s3_bucket.aws_config_log_bucket.arn}/*",
        "Condition": {
          "StringEquals": {
            "aws:SourceAccount": "${data.aws_caller_identity.current.account_id}"
          }
        }
      }
  ]
}
POLICY
}

resource "aws_s3_bucket_public_access_block" "aws_config_log_bucket" {
  bucket = aws_s3_bucket.aws_config_log_bucket.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_ownership_controls" "aws_config_log_bucket" {
  bucket = aws_s3_bucket.aws_config_log_bucket.id

  rule {
    object_ownership = "BucketOwnerEnforced"
  }
}
```

### Steps to Reproduce

I had created a configuration recorder with this code:

```terraform
resource "aws_config_configuration_recorder" "awsconfig" {
  name     = var.name
  role_arn = aws_iam_role.awsconfig.arn

  recording_group {
    all_supported  = length(var.aws_config_resources_types) == 0 ? true : false
    resource_types = var.aws_config_resources_types
  }
}
```

I tried to apply the code where I exclude by resource type. It didn't work with the following message:

```shell
╷
│ Error: putting ConfigService Configuration Recorder (prod_dr_eu-west-1): InvalidRecordingGroupException: The recording group provided is not valid
│
│   with module.aws_config_secondary_region.aws_config_configuration_recorder.awsconfig,
│   on ../../modules/awsconfig/config_recorder.tf line 1, in resource "aws_config_configuration_recorder" "awsconfig":
│    1: resource "aws_config_configuration_recorder" "awsconfig" {
│
╵
╷
│ Error: putting ConfigService Configuration Recorder (prod_dr_eu-west-2): InvalidRecordingGroupException: The recording group provided is not valid
│
│   with module.aws_config_primary_region.aws_config_configuration_recorder.awsconfig,
│   on ../../modules/awsconfig/config_recorder.tf line 1, in resource "aws_config_configuration_recorder" "awsconfig":
│    1: resource "aws_config_configuration_recorder" "awsconfig" {
│
```

Then I tried to comment the code out to delete the configuration recorder. That worked fine.
I got the crash when uncommenting the code that excludes resource type and applying again.

### Would you like to implement a fix?

No

**Comment by didorins** [comment]
Hitting same issue. I've noticed that if I change resource_types from empty to non-empty list of strings it will error out.
Re-creating aws_config_configuration_recorder helps bypass the issue. Quite inconvenient for pipeline jobs. 

I'm using   
"terraform_version": "1.5.1", wtith 
provider "registry.terraform.io/hashicorp/aws" {
  version = "5.32.0"

The condition when error pops is described in this link https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/config/model/InvalidRecordingGroupException.html

**Comment by cardasac** [comment]
I am using the exact same config as stated in https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/config_configuration_recorder#periodic-recording. And I am still getting:
```
Error: putting ConfigService Configuration Recorder (recorder): InvalidRecordingGroupException: The recording group provided is not valid
```
