### ISSUE TITLE
[Bug]: [aws_appflow_connector_profile] panic: interface conversion: interface {} is nil, not map[string]interface

### ISSUE THREAD

**Issue by louis-pie** [hashicorp/terraform-provider-aws#33803]
### Terraform Core Version

1.6.0

### AWS Provider Version

5.19.0

### Affected Resource(s)

- aws_appflow_connector_profile

### Expected Behavior

Create AppFlow Connector Profile to use for connecting to GitHub

### Actual Behavior

Generates a **panic: interface conversion: interface {} is nil, not map[string]interface {}** message

I believe the crash to be related to `profile_properties = {}`

### Relevant Error/Panic Output Snippet

```shell
$ terraform apply -auto-approve

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_appflow_connector_profile.lp_tf_github will be created
  + resource "aws_appflow_connector_profile" "lp_tf_github" {
      + arn             = (known after apply)
      + connection_mode = "Public"
      + connector_label = "GitHub"
      + connector_type  = "CustomConnector"
      + credentials_arn = (known after apply)
      + id              = (known after apply)
      + kms_arn         = (known after apply)
      + name            = "lp_tf_github"

      + connector_profile_config {
          + connector_profile_credentials {
              + custom_connector {
                  + authentication_type = "CUSTOM"

                  + custom {
                      + credentials_map            = (sensitive value)
                      + custom_authentication_type = "BasicAuthPersonalAccessToken"
                    }
                }
            }
          + connector_profile_properties {
              + custom_connector {
                }
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
aws_appflow_connector_profile.lp_tf_github: Creating...
2023-10-06T15:36:33.615+0100 [ERROR] plugin.(*GRPCProvider).ApplyResourceChange: error="rpc error: code = Unavailable desc = error reading from server: EOF"
2023-10-06T15:36:33.620+0100 [ERROR] vertex "aws_appflow_connector_profile.lp_tf_github" error: Plugin did not respond
╷
│ Error: Plugin did not respond
│
│   with aws_appflow_connector_profile.lp_tf_github,
│   on github_source.tf line 22, in resource "aws_appflow_connector_profile" "lp_tf_github":
│   22: resource "aws_appflow_connector_profile" "lp_tf_github" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-aws_v5.19.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 110 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/appflow.expandConnectorProfileProperties(0x110c5b580?)
        github.com/hashicorp/terraform-provider-aws/internal/service/appflow/connector_profile.go:1933 +0x1240
github.com/hashicorp/terraform-provider-aws/internal/service/appflow.expandConnectorProfileConfig(0x1101b91a0?)
        github.com/hashicorp/terraform-provider-aws/internal/service/appflow/connector_profile.go:1522 +0xf8
github.com/hashicorp/terraform-provider-aws/internal/service/appflow.resourceConnectorProfileCreate({0x1127a0580, 0x14001d20f30}, 0x1125f62e0?, {0x1125f62e0?, 0x140034c6a80?})
        github.com/hashicorp/terraform-provider-aws/internal/service/appflow/connector_profile.go:1420 +0x160
github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0x0?, {0x1125f62e0?, 0x140034c6a80?})
        github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:111 +0x28c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1127a0580?, {0x1127a0580?, 0x14001c00cc0?}, 0xd?, {0x1125f62e0?, 0x140034c6a80?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:773 +0x64
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x14000cdd0a0, {0x1127a0580, 0x14001c00cc0}, 0x14001c11520, 0x14000725200, {0x1125f62e0, 0x140034c6a80})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:909 +0x8a0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1400176f9c8, {0x1127a0580?, 0x14001c00ba0?}, 0x140035a2730)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xb78
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0x1127a04d8?, {0x1127a0580?, 0x14001c00870?}, 0x140035a2730)
        github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x188
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x140018d48c0, {0x1127a0580?, 0x1400357fe60?}, 0x140008342a0)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x3bc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x112380760?, 0x140018d48c0}, {0x1127a0580, 0x1400357fe60}, 0x14000834230, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000188d20, {0x1127adb00, 0x1400057e680}, 0x14001a16000, 0x140035573e0, 0x118afd3f8, 0x0)
        google.golang.org/grpc@v1.57.0/server.go:1360 +0xcb4
google.golang.org/grpc.(*Server).handleStream(0x14000188d20, {0x1127adb00, 0x1400057e680}, 0x14001a16000, 0x0)
        google.golang.org/grpc@v1.57.0/server.go:1737 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.57.0/server.go:982 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.57.0/server.go:980 +0x16c

Error: The terraform-provider-aws_v5.19.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Configuration Files

```terraform
terraform {
  required_version = "~> 1.6.0"

  required_providers {
    aws = "~> 5.19.0"
  }
}

provider "aws" {
  region  = "eu-central-1"
  profile = "staging"
}

variable "GH_PERSONAL_ACCESS_TOKEN" {
  type = string
}

variable "GH_USERNAME" {
  type = string
}

resource "aws_appflow_connector_profile" "lp_tf_github" {
  name            = "lp_tf_github"
  connector_type  = "CustomConnector"
  connector_label = "GitHub"
  connection_mode = "Public"

  connector_profile_config {
    connector_profile_properties {
      custom_connector {
        profile_properties = {}
      }
    }

    connector_profile_credentials {
      custom_connector {
        authentication_type = "CUSTOM"
        custom {
          custom_authentication_type = "BasicAuthPersonalAccessToken"
          credentials_map = {
            username            = var.GH_USERNAME
            personalAccessToken = var.GH_PERSONAL_ACCESS_TOKEN
          }
        }
      }
    }
  }
}
```

### Steps to Reproduce

Besides terraform, you will need to create a GitHub personal access token
[https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens)

### Debug Output

[https://gist.github.com/louis-pie/bca251f81c5dc6748ec3609979f550c7](https://gist.github.com/louis-pie/bca251f81c5dc6748ec3609979f550c7)

### Panic Output

```shell
06T16:09:47.993+0100 [DEBUG] State storage *statemgr.Filesystem declined to persist a state snapshot
2023-10-06T16:09:47.993+0100 [ERROR] vertex "aws_appflow_connector_profile.lp_tf_github" error: Plugin did not respond
╷
│ Error: Plugin did not respond
│
│   with aws_appflow_connector_profile.lp_tf_github,
│   on github_source.tf line 22, in resource "aws_appflow_connector_profile" "lp_tf_github":
│   22: resource "aws_appflow_connector_profile" "lp_tf_github" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-aws_v5.19.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 88 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/appflow.expandConnectorProfileProperties(0x10ea7b580?)
        github.com/hashicorp/terraform-provider-aws/internal/service/appflow/connector_profile.go:1933 +0x1240
github.com/hashicorp/terraform-provider-aws/internal/service/appflow.expandConnectorProfileConfig(0x10dfd91a0?)
        github.com/hashicorp/terraform-provider-aws/internal/service/appflow/connector_profile.go:1522 +0xf8
github.com/hashicorp/terraform-provider-aws/internal/service/appflow.resourceConnectorProfileCreate({0x1105c0580, 0x140026b89c0}, 0x1104162e0?, {0x1104162e0?, 0x14001fa0540?})
        github.com/hashicorp/terraform-provider-aws/internal/service/appflow/connector_profile.go:1420 +0x160
github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0x0?, {0x1104162e0?, 0x14001fa0540?})
        github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:111 +0x28c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1105c0580?, {0x1105c0580?, 0x14002416750?}, 0xd?, {0x1104162e0?, 0x14001fa0540?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:773 +0x64
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x14000d5b0a0, {0x1105c0580, 0x14002416750}, 0x14002420b60, 0x140023c0c00, {0x1104162e0, 0x14001fa0540})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:909 +0x8a0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x14003c29950, {0x1105c0580?, 0x14002416630?}, 0x1400144d630)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xb78
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0x1105c04d8?, {0x1105c0580?, 0x14002416300?}, 0x1400144d630)
        github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x188
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x14003c745a0, {0x1105c0580?, 0x140023af8f0?}, 0x1400102e0e0)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x3bc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1101a0760?, 0x14003c745a0}, {0x1105c0580, 0x140023af8f0}, 0x1400102e070, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000118780, {0x1105cdb00, 0x140005a21a0}, 0x14002587c20, 0x14002034a20, 0x11691d3f8, 0x0)
        google.golang.org/grpc@v1.57.0/server.go:1360 +0xcb4
google.golang.org/grpc.(*Server).handleStream(0x14000118780, {0x1105cdb00, 0x140005a21a0}, 0x14002587c20, 0x0)
        google.golang.org/grpc@v1.57.0/server.go:1737 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.57.0/server.go:982 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.57.0/server.go:980 +0x16c

Error: The terraform-provider-aws_v5.19.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

2023-10-06T16:09:47.999+0100 [DEBUG] provider: plugin exited
```

### Important Factoids

A similar call from the aws cli works correctly
```shell
aws --profile=staging --region=eu-central-1 appflow create-connector-profile \
    --connector-profile-name lp_github_cli \
    --connector-type CustomConnector \
    --connector-label GitHub \
    --connection-mode Public \
    --connector-profile-config '{
                "connectorProfileProperties": {
                    "CustomConnector": {
                        "profileProperties": "{}"
                    }
                },
                "connectorProfileCredentials": {
                    "CustomConnector": {
                        "authenticationType": "CUSTOM",
                        "custom": {
                            "customAuthenticationType": "BasicAuthPersonalAccessToken",
                            "credentialsMap": {
                                "username": "XXXXXXXXXXXXX",
                                "personalAccessToken": "XXXXXXXXXXXXXXXX"
                            }
                        }
                    }
                }
            }'
```

### References

[https://docs.aws.amazon.com/appflow/latest/userguide/connectors-github.html](https://docs.aws.amazon.com/appflow/latest/userguide/connectors-github.html)

[https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens)

### Would you like to implement a fix?

None

**Comment by louis-pie** [comment]
Appears to be similar to https://github.com/hashicorp/terraform-provider-aws/issues/29507

**Comment by louis-pie** [comment]
I can confirm this workaround works https://github.com/hashicorp/terraform-provider-aws/issues/29507#issuecomment-1663883167
