### ISSUE TITLE
[Bug]: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by voroninman** [hashicorp/terraform-provider-aws#33999]
### Terraform Core Version

1.6.2

### AWS Provider Version

5.21.0

### Affected Resource(s)

* aws_dms_certificate

### Expected Behavior

Print the plan.

### Actual Behavior

Crash with the stack trace.

### Relevant Error/Panic Output Snippet

```shell
Stack trace from the terraform-provider-aws_v5.21.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x109094e8c]

goroutine 130 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/dms.dataSourceCertificateRead({0x10e260ae0, 0x14001554330}, 0x140005c1600, {0x10e0b4920?, 0x140024eb0a0})
        github.com/hashicorp/terraform-provider-aws/internal/service/dms/certificate_data_source.go:99 +0x1ac
github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0x0?, {0x10e0b4920?, 0x140024eb0a0?})
        github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:111 +0x28c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x10e260ae0?, {0x10e260ae0?, 0x140016de3c0?}, 0xd?, {0x10e0b4920?, 0x140024eb0a0?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:790 +0x64
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0x14000b72fc0, {0x10e260ae0, 0x140016de3c0}, 0x140005c1500, {0x10e0b4920, 0x140024eb0a0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:1015 +0x130
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0x14003a6bb00, {0x10e260ae0?, 0x140016de2a0?}, 0x140005b5300)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1237 +0x304
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ReadDataSource(0x10e260a38?, {0x10e260ae0?, 0x140016c7f50?}, 0x140005b5300)
        github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf5muxserver/mux_server_ReadDataSource.go:36 +0x188
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0x14003bf2140, {0x10e260ae0?, 0x140016c75c0?}, 0x140008d6a00)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:699 +0x368
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x10de3b160?, 0x14003bf2140}, {0x10e260ae0, 0x140016c75c0}, 0x14000256690, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:503 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000134780, {0x10e26e1a0, 0x14000b504e0}, 0x140019807e0, 0x14003c60150, 0x1146398a8, 0x0)
        google.golang.org/grpc@v1.57.0/server.go:1360 +0xcb4
google.golang.org/grpc.(*Server).handleStream(0x14000134780, {0x10e26e1a0, 0x14000b504e0}, 0x140019807e0, 0x0)
        google.golang.org/grpc@v1.57.0/server.go:1737 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.57.0/server.go:982 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.57.0/server.go:980 +0x16c

Error: The terraform-provider-aws_v5.21.0_x5 plugin crashed!
```

### Terraform Configuration Files

```
terraform {
  required_version = ">= 1.0.0, < 2.0.0"
  backend "s3" {
    profile = "foo-dev"
    bucket  = "foo-state"
    key     = "foo"
    region  = "eu-west-1"
  }
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.0.0, < 6.0.0"
    }
  }
}
```

### Steps to Reproduce

1. `terraform plan`

### Would you like to implement a fix?

No

**Comment by voroninman** [comment]
@ewbankkit 🌟
