### ISSUE TITLE
[Bug]: aws_opensearchserverless_collection.collection tagging failed to handle Value Conversion Error

### ISSUE THREAD

**Issue by tantonjt-aws** [hashicorp/terraform-provider-aws#34294]
### Terraform Core Version

1.6.3

### AWS Provider Version

5.24.0

### Affected Resource(s)

on resource "aws_opensearchserverless_collection" "collection":

### Expected Behavior

terraform plan should complete.
Handle tags from tagging module with the target type including null values

### Actual Behavior

Planning failed. Terraform encountered an error while generating this plan.

### Relevant Error/Panic Output Snippet

```shell
Error: Plugin did not respond
│
│   with aws_opensearchserverless_collection.collection,
│   on main.tf line 46, in resource "aws_opensearchserverless_collection" "collection":
│   46: resource "aws_opensearchserverless_collection" "collection" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).PlanResourceChange call. The plugin logs may contain
│ more details.
╵
```

### Terraform Configuration Files

```tf
module "tagger" {
  source  = "localterraform.com/thehartford/tagging/aws"
  version = ">=2.0.5, <3.0.0"

  app_id              = var.app_id
  app_name            = var.app_name
  app_tier            = var.app_tier
  data_classification = var.data_classification
  environment         = var.env
  environment_type    = var.env
  owner_email         = var.email
  pipeline            = var.pipeline
  repository          = var.repository
  resource            = "aoss"
  service_tier        = var.service_tier
  employee_id         = var.hig-owner-name 
}

resource "aws_opensearchserverless_collection" "collection" {
  name = local.hig-collection-name

  # Tagger is not working with current aws provider version
  tags = merge(
    module.tagger.tags,
    local.tf_versions_map,
    var.tags
  )
```

### Steps to Reproduce

terraform plan

### Panic Output

Planning failed. Terraform encountered an error while generating this plan.

```shell
╷
│ Error: Plugin did not respond
│
│   with aws_opensearchserverless_collection.collection,
│   on main.tf line 46, in resource "aws_opensearchserverless_collection" "collection":
│   46: resource "aws_opensearchserverless_collection" "collection" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).PlanResourceChange call. The plugin logs may contain
│ more details.
╵

Stack trace from the terraform-provider-aws_v5.24.0_x5 plugin:

panic: Value Conversion Error

An unexpected error was encountered trying to build a value. This is always an error in the provider. Please report the following to the provider developer:

Received null value, however the target type cannot handle null values. Use the corresponding `types` package type, a pointer type or a custom type that handles null values.

Path: ["PatchGroup"]
Target Type: string
Suggested `types` Type: basetypes.StringValue
Suggested Pointer Type: *string
AutoFlEx

Expand[basetypes.MapValue, *map[string]string]

goroutine 257 [running]:
github.com/hashicorp/terraform-provider-aws/internal/framework/flex.panicOnError(...)
        github.com/hashicorp/terraform-provider-aws/internal/framework/flex/bool.go:44
github.com/hashicorp/terraform-provider-aws/internal/framework/flex.ExpandFrameworkStringValueMap({0xf3ad7e0?, 0xc001d2d3b0?}, {0xf3b8cd0?, 0xc001d09840?})
        github.com/hashicorp/terraform-provider-aws/internal/framework/flex/map.go:25 +0xac
github.com/hashicorp/terraform-provider-aws/internal/tags.New({0xf3ad7e0, 0xc001d2d3b0}, {0xdd02780?, 0xc001cea398?})
        github.com/hashicorp/terraform-provider-aws/internal/tags/key_value_tags.go:647 +0x50b
github.com/hashicorp/terraform-provider-aws/internal/framework.(*ResourceWithConfigure).SetTagsAll(0xc00196f3b0, {0xf3ad7e0, 0xc001d2d3b0}, {{{{0xf3ba458, 0xc001a93ce0}, {0xc5aadc0, 0xc001a93530}}, {0xf3c3a98, 0xc001a2caf0}}, {{{0xf3ba458, ...}, ...}, ...}, ...}, ...)
        github.com/hashicorp/terraform-provider-aws/internal/framework/base.go:90 +0x3b5
github.com/hashicorp/terraform-provider-aws/internal/service/opensearchserverless.(*resourceCollection).ModifyPlan(0x0?, {0xf3ad7e0?, 0xc001d2d3b0?}, {{{{0xf3ba458, 0xc001a93ce0}, {0xc5aadc0, 0xc001a93530}}, {0xf3c3a98, 0xc001a2caf0}}, {{{0xf3ba458, ...}, ...}, ...}, ...}, ...)        github.com/hashicorp/terraform-provider-aws/internal/service/opensearchserverless/collection.go:306 +0x7b
github.com/hashicorp/terraform-provider-aws/internal/provider/fwprovider.(*wrappedResource).ModifyPlan(0xc001760800, {0xf3ad7e0, 0xc001671bc0}, {{{{0xf3ba458, 0xc001a93ce0}, {0xc5aadc0, 0xc001a93530}}, {0xf3c3a98, 0xc001a2caf0}}, {{{0xf3ba458, ...}, ...}, ...}, ...}, ...)      
        github.com/hashicorp/terraform-provider-aws/internal/provider/fwprovider/intercept.go:285 +0xff
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).PlanResourceChange(0xc002594840, {0xf3ad7e0, 0xc001671bc0}, 0xc00175ddb0, 0xc001ceb418)
        github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/fwserver/server_planresourcechange.go:280 +0x1403
github.com/hashicorp/terraform-plugin-framework/internal/proto5server.(*Server).PlanResourceChange(0xc002594840, {0xf3ad7e0?, 0xc001671a70?}, 0xc00175dd10)
        github.com/hashicorp/terraform-plugin-framework@v1.4.2/internal/proto5server/server_planresourcechange.go:55 +0x41a
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).PlanResourceChange(0xc0008d67e0, {0xf3ad7e0?, 0xc001671740?}, 0xc00175dd10)
        github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf5muxserver/mux_server_PlanResourceChange.go:73 +0x2d4
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).PlanResourceChange(0xc003cccaa0, {0xf3ad7e0?, 0xc001670f30?}, 0xc000664000)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:824 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler({0xdd0db80?, 0xc003cccaa0}, {0xf3ad7e0, 0xc001670f30}, 0xc0009d5f80, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:449 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00005f4a0, {0xf3bb400, 0xc003c7a680}, 0xc001767d40, 0xc002664d80, 0x159482e0, 0x0)     
        google.golang.org/grpc@v1.58.2/server.go:1376 +0xdd2
google.golang.org/grpc.(*Server).handleStream(0xc00005f4a0, {0xf3bb400, 0xc003c7a680}, 0xc001767d40, 0x0)
        google.golang.org/grpc@v1.58.2/server.go:1753 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.58.2/server.go:998 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.58.2/server.go:996 +0x18c

Error: The terraform-provider-aws_v5.24.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Operation failed: failed running terraform plan (exit 1)
```

### Important Factoids

Tagging the collection directly does work.

```tf
  tags = {
    app_id              = var.app_id
    app_name            = var.app_name
    app_tier            = var.app_tier
    data_classification = var.data_classification
    environment         = var.env
    environment_type    = var.env
    owner_email         = var.email
    pipeline            = var.pipeline
    repository          = var.repository
    resource            = "oass"
    service_tier        = var.service_tier
    hig-owner-name      = var.hig-owner-name
  }
```

### Would you like to implement a fix?

No

**Comment by tantonjt-aws** [comment]
One more update on issue. The tagging module includes lines like this one to tag based on service name and it uses nulls when it isn't going to use that tag on a particular resource.  This seems to be the cause of the issue.  The collection resource isn't handling nulls correctly. This tagging module is working for my teammates on other builds (resource types).

main.tf
terraform {
  # required_version = ">= 0.13.0, < 1.0.1"
}

locals {
  tags = {
     AccountType        = var.resource == "RDS" ? data.aws_ssm_parameter.account_type.value : null
  }
}
