### ISSUE TITLE
[Bug]: terraform-provider-aws_v5.20.1_x5 plugin crashed while applying changes fos aws_inspector2_enabler

### ISSUE THREAD

**Issue by sebastianobonanno** [hashicorp/terraform-provider-aws#34415]
### Terraform Core Version

1.6.3

### AWS Provider Version

5.20.1

### Affected Resource(s)

aws_inspector2_enabler

resource "aws_inspector2_enabler" "deployment" {
  account_ids    = ["xxxxxxxxxx"]
  resource_types = ["EC2", "ECR", "LAMBDA", "LAMBDA_CODE"]
}

### Expected Behavior

The enablement of aws_inspector2_enabler should go fine

### Actual Behavior

The enablement of aws_inspector2_enabler crashed with an error

### Relevant Error/Panic Output Snippet

```shell
aws_inspector2_enabler.deployment: Creating...
aws_inspector2_enabler.deployment: Still creating... [10s elapsed]
aws_inspector2_enabler.deployment: Still creating... [20s elapsed]
aws_inspector2_enabler.deployment: Still creating... [30s elapsed]
aws_inspector2_enabler.deployment: Still creating... [40s elapsed]
aws_inspector2_enabler.deployment: Still creating... [50s elapsed]
aws_inspector2_enabler.deployment: Still creating... [1m0s elapsed]
aws_inspector2_enabler.deployment: Still creating... [1m10s elapsed]
aws_inspector2_enabler.deployment: Still creating... [1m20s elapsed]
aws_inspector2_enabler.deployment: Still creating... [1m30s elapsed]
aws_inspector2_enabler.deployment: Still creating... [1m40s elapsed]
aws_inspector2_enabler.deployment: Still creating... [1m50s elapsed]
aws_inspector2_enabler.deployment: Still creating... [2m0s elapsed]
aws_inspector2_enabler.deployment: Still creating... [2m10s elapsed]
aws_inspector2_enabler.deployment: Still creating... [2m20s elapsed]
aws_inspector2_enabler.deployment: Still creating... [2m30s elapsed]
aws_inspector2_enabler.deployment: Still creating... [2m40s elapsed]
aws_inspector2_enabler.deployment: Still creating... [2m50s elapsed]
aws_inspector2_enabler.deployment: Still creating... [3m0s elapsed]
aws_inspector2_enabler.deployment: Still creating... [3m10s elapsed]
aws_inspector2_enabler.deployment: Still creating... [3m20s elapsed]
aws_inspector2_enabler.deployment: Still creating... [3m30s elapsed]
aws_inspector2_enabler.deployment: Still creating... [3m40s elapsed]
aws_inspector2_enabler.deployment: Still creating... [3m50s elapsed]
aws_inspector2_enabler.deployment: Still creating... [4m0s elapsed]
aws_inspector2_enabler.deployment: Still creating... [4m10s elapsed]
aws_inspector2_enabler.deployment: Still creating... [4m20s elapsed]
aws_inspector2_enabler.deployment: Still creating... [4m30s elapsed]
aws_inspector2_enabler.deployment: Still creating... [4m40s elapsed]
aws_inspector2_enabler.deployment: Still creating... [4m50s elapsed]
aws_inspector2_enabler.deployment: Still creating... [5m0s elapsed]
??
?? Warning: Applied changes may be incomplete
?? 
?? The plan was created with the -target option in effect, so some changes requested in the configuration may have been ignored and the output values may not be
?? fully updated. Run the following command to verify that no other changes are pending:
??     terraform plan
?? 
?? Note that the -target option is not suitable for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when
?? Terraform specifically suggests to use it as part of an error message.
??
??
?? Error: Request cancelled
?? 
??   with aws_inspector2_enabler.deployment,
??   on inspector2.tf line 1, in resource "aws_inspector2_enabler" "deployment":
??    1: resource "aws_inspector2_enabler" "deployment" {
?? 
?? The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
??

Stack trace from the terraform-provider-aws_v5.20.1_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]inspector2.AccountResourceStatus

goroutine 77 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/inspector2.waitEnabled({0xefaca80, 0xc001d00210}, 0x27?, {0xc001cb3980?, 0x0?, 0x0?}, 0x45d964b800)
        github.com/hashicorp/terraform-provider-aws/internal/service/inspector2/enabler.go:423 +0x165
github.com/hashicorp/terraform-provider-aws/internal/service/inspector2.resourceEnablerCreate({0xefaca80?, 0xc001d00210}, 0xc003093c80, {0xdbe43c0?, 0xc002ab1b20})
        github.com/hashicorp/terraform-provider-aws/internal/service/inspector2/enabler.go:164 +0x425
github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0x0?, {0xdbe43c0?, 0xc002ab1b20?})
        github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:111 +0x34b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xefaca80?, {0xefaca80?, 0xc001cacde0?}, 0xd?, {0xdbe43c0?, 0xc002ab1b20?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:773 +0x87
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0004ed260, {0xefaca80, 0xc001cacde0}, 0xc00301fe10, 0xc003093b00, {0xdbe43c0, 0xc002ab1b20})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:909 +0xa7e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00182f998, {0xefaca80?, 0xc001caccc0?}, 0xc001cae0f0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0xefac9d8?, {0xefaca80?, 0xc001cac990?}, 0xc001cae0f0)
        github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x1b5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0018728c0, {0xefaca80?, 0xc001b7ff80?}, 0xc0002ad180)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xd96e180?, 0xc0018728c0}, {0xefaca80, 0xc001b7ff80}, 0xc0002ad110, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000292d20, {0xefba1c0, 0xc002b72820}, 0xc001ca7b00, 0xc002b6c9c0, 0x153f7858, 0x0)
        google.golang.org/grpc@v1.57.0/server.go:1360 +0xe23
google.golang.org/grpc.(*Server).handleStream(0xc000292d20, {0xefba1c0, 0xc002b72820}, 0xc001ca7b00, 0x0)
        google.golang.org/grpc@v1.57.0/server.go:1737 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.57.0/server.go:982 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.57.0/server.go:980 +0x18c

Error: The terraform-provider-aws_v5.20.1_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Configuration Files

.

### Steps to Reproduce

.

### Would you like to implement a fix?

None

**Comment by sebastianobonanno** [comment]
Second run test

`aws_inspector2_enabler.deployment: Creating...
aws_inspector2_enabler.deployment: Still creating... [10s elapsed]
aws_inspector2_enabler.deployment: Still creating... [20s elapsed]
aws_inspector2_enabler.deployment: Still creating... [30s elapsed]
aws_inspector2_enabler.deployment: Still creating... [40s elapsed]
aws_inspector2_enabler.deployment: Still creating... [50s elapsed]
aws_inspector2_enabler.deployment: Still creating... [1m0s elapsed]
aws_inspector2_enabler.deployment: Still creating... [1m10s elapsed]
aws_inspector2_enabler.deployment: Still creating... [1m20s elapsed]
aws_inspector2_enabler.deployment: Still creating... [1m30s elapsed]
aws_inspector2_enabler.deployment: Still creating... [1m40s elapsed]
aws_inspector2_enabler.deployment: Still creating... [1m50s elapsed]
aws_inspector2_enabler.deployment: Still creating... [2m0s elapsed]
aws_inspector2_enabler.deployment: Still creating... [2m10s elapsed]
aws_inspector2_enabler.deployment: Still creating... [2m20s elapsed]
aws_inspector2_enabler.deployment: Still creating... [2m30s elapsed]
aws_inspector2_enabler.deployment: Still creating... [2m40s elapsed]
aws_inspector2_enabler.deployment: Still creating... [2m50s elapsed]
aws_inspector2_enabler.deployment: Still creating... [3m0s elapsed]
aws_inspector2_enabler.deployment: Still creating... [3m10s elapsed]
aws_inspector2_enabler.deployment: Still creating... [3m20s elapsed]
aws_inspector2_enabler.deployment: Still creating... [3m30s elapsed]
aws_inspector2_enabler.deployment: Still creating... [3m40s elapsed]
aws_inspector2_enabler.deployment: Still creating... [3m50s elapsed]
aws_inspector2_enabler.deployment: Still creating... [4m0s elapsed]
aws_inspector2_enabler.deployment: Still creating... [4m10s elapsed]
aws_inspector2_enabler.deployment: Still creating... [4m20s elapsed]
aws_inspector2_enabler.deployment: Still creating... [4m30s elapsed]
aws_inspector2_enabler.deployment: Still creating... [4m40s elapsed]
aws_inspector2_enabler.deployment: Still creating... [4m50s elapsed]
aws_inspector2_enabler.deployment: Still creating... [5m0s elapsed]
??
?? Warning: Applied changes may be incomplete
?? 
?? The plan was created with the -target option in effect, so some changes requested in the configuration may have been ignored and the output values may not
?? be fully updated. Run the following command to verify that no other changes are pending:
??     terraform plan
?? 
?? Note that the -target option is not suitable for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or
?? when Terraform specifically suggests to use it as part of an error message.
??
??
?? Error: Plugin did not respond
?? 
??   with aws_inspector2_enabler.deployment,
??   on inspector2.tf line 1, in resource "aws_inspector2_enabler" "deployment":
??    1: resource "aws_inspector2_enabler" "deployment" {
?? 
?? The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
??

Stack trace from the terraform-provider-aws_v5.20.1_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]inspector2.AccountResourceStatus

goroutine 92 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/inspector2.waitEnabled({0xefaca80, 0xc0037f2090}, 0x27?, {0xc000673040?, 0x0?, 0x0?}, 0x45d964b800)
        github.com/hashicorp/terraform-provider-aws/internal/service/inspector2/enabler.go:423 +0x165
github.com/hashicorp/terraform-provider-aws/internal/service/inspector2.resourceEnablerCreate({0xefaca80?, 0xc0037f2090}, 0xc0005c3780, {0xdbe43c0?, 0xc003741b20})
        github.com/hashicorp/terraform-provider-aws/internal/service/inspector2/enabler.go:164 +0x425
github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0x0?, {0xdbe43c0?, 0xc003741b20?})
        github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:111 +0x34b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xefaca80?, {0xefaca80?, 0xc000664c60?}, 0xd?, {0xdbe43c0?, 0xc003741b20?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:773 +0x87
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0016e1ea0, {0xefaca80, 0xc000664c60}, 0xc003a8c750, 0xc0005c3600, {0xdbe43c0, 0xc003741b20})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:909 +0xa7e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc001a49998, {0xefaca80?, 0xc000664b40?}, 0xc000a43040)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0xefac9d8?, {0xefaca80?, 0xc0006646f0?}, 0xc000a43040)
        github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x1b5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0005717c0, {0xefaca80?, 0xc003a63d40?}, 0xc0011c8ee0)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xd96e180?, 0xc0005717c0}, {0xefaca80, 0xc003a63d40}, 0xc0011c8e70, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000262d20, {0xefba1c0, 0xc0006661a0}, 0xc003680a20, 0xc0037f29c0, 0x153f7858, 0x0)
        google.golang.org/grpc@v1.57.0/server.go:1360 +0xe23
google.golang.org/grpc.(*Server).handleStream(0xc000262d20, {0xefba1c0, 0xc0006661a0}, 0xc003680a20, 0x0)
        google.golang.org/grpc@v1.57.0/server.go:1737 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.57.0/server.go:982 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.57.0/server.go:980 +0x18c

Error: The terraform-provider-aws_v5.20.1_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.`
