### ISSUE TITLE
[Bug]: AMQ plan crashes on 5.32.0

### ISSUE THREAD

**Issue by jorgecara** [hashicorp/terraform-provider-aws#35262]
### Terraform Core Version

1.6.4

### AWS Provider Version

1.32.0

### Affected Resource(s)

aws_mq_broker

### Expected Behavior

The plan should have worked as usual with the 5.31.0

### Actual Behavior

The plan crashes on the aws_mq_resource. Locking the provider to the previous version 5.31.0 serves as a workaround

### Relevant Error/Panic Output Snippet

```shell
11:11:55  time=2024-01-12T11:11:54+01:00 level=info msg=╷
11:11:55  │ Error: Plugin did not respond
11:11:55  │ 
11:11:55  │   with aws_mq_broker.broker,
11:11:55  │   on main.tf line 65, in resource "aws_mq_broker" "broker":
11:11:55  │   65: resource "aws_mq_broker" "broker" {
11:11:55  │ 
11:11:55  │ The plugin encountered an error, and failed to respond to the
11:11:55  │ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
11:11:55  │ details.
11:11:55  ╵
11:11:55  
11:11:55  Stack trace from the terraform-provider-aws_v5.32.0_x5 plugin:
11:11:55  
11:11:55  panic: interface conversion: interface {} is *schema.Set, not []string
11:11:55  
11:11:55  goroutine 260 [running]:
11:11:55  github.com/hashicorp/terraform-provider-aws/internal/service/mq.resourceUserHash({0xd4f9120?, 0xc00302a000})
11:11:55  	github.com/hashicorp/terraform-provider-aws/internal/service/mq/broker.go:749 +0x325
11:11:55  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).hash(0x7f3f5db925b8?, {0xd4f9120?, 0xc00302a000?})
11:11:55  	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/set.go:221 +0x2c
11:11:55  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).add(0xc00170c940, {0xd4f9120?, 0xc00302a000}, 0x0)
11:11:55  	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/set.go:201 +0x96
11:11:55  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).Add(...)
11:11:55  	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/set.go:79
11:11:55  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldReader).readSet.func1({0xc002aafce0, 0x17}, {0x58?, 0xebc1380?})
11:11:55  	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/field_reader_map.go:157 +0x2f3
11:11:55  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.BasicMapReader.Range(0xc00170b1c0?, 0xc000f9df80)
11:11:55  	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/field_reader_map.go:196 +0xa5
11:11:55  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldReader).readSet(0xc003cff158, {0xc00170b1b0?, 0x1?, 0xc00180fa40?}, 0x140?)
11:11:55  	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/field_reader_map.go:134 +0x4e5
11:11:55  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldReader).ReadField(0xc003cff158, {0xc00170b1b0, 0x1, 0x1})
11:11:55  	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/field_reader_map.go:34 +0x35a
11:11:55  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MultiLevelFieldReader).ReadFieldMerge(0xc00170c580, {0xc00170b1b0, 0x1, 0x1}, {0xf00a9a1, 0x3})
11:11:55  	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/field_reader_multi.go:48 +0x146
11:11:55  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0xc000bb4480, {0xc00170b1b0, 0x1, 0x1}, 0x8?)
11:11:55  	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource_data.go:553 +0x1b3
11:11:55  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).State(0xc000bb4480)
11:11:55  	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource_data.go:354 +0x393
11:11:55  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ShimInstanceStateFromValue(0xc0018402a0, {{{0x105e0e60?, 0xc003cd82f0?}}, {0xd4f9120?, 0xc002f73050?}})
11:11:55  	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:670 +0x1df
11:11:55  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000f1be60, {0x105df7a0?, 0xc003f4f500?}, 0xc002ebf040)
11:11:55  	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/grpc_provider.go:637 +0x20f
11:11:55  github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ReadResource(0x105df6f8?, {0x105df7a0?, 0xc003f4f1d0?}, 0xc002ebf040)
11:11:55  	github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf5muxserver/mux_server_ReadResource.go:35 +0x1b5
11:11:55  github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc00098d9a0, {0x105df7a0?, 0xc003f4e9f0?}, 0xc000f9dce0)
11:11:55  	github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov5/tf5server/server.go:789 +0x4b1
11:11:55  github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xed810e0?, 0xc00098d9a0}, {0x105df7a0, 0xc003f4e9f0}, 0xc000bb4300, 0x0)
11:11:55  	github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x170
11:11:55  google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001aed20, {0x105df7a0, 0xc003f4e960}, {0x105f42c0, 0xc002a1f040}, 0xc003cf2fc0, 0xc002967e60, 0x171d8528, 0x0)
11:11:55  	google.golang.org/grpc@v1.60.0/server.go:1372 +0xe49
11:11:55  google.golang.org/grpc.(*Server).handleStream(0xc0001aed20, {0x105f42c0, 0xc002a1f040}, 0xc003cf2fc0)
11:11:55  	google.golang.org/grpc@v1.60.0/server.go:1783 +0x1031
11:11:55  google.golang.org/grpc.(*Server).serveStreams.func2.1()
11:11:55  	google.golang.org/grpc@v1.60.0/server.go:1016 +0x68
11:11:55  created by google.golang.org/grpc.(*Server).serveStreams.func2
11:11:55  	google.golang.org/grpc@v1.60.0/server.go:1027 +0x12e
11:11:55  
11:11:55  Error: The terraform-provider-aws_v5.32.0_x5 plugin crashed!
11:11:55  
11:11:55  This is always indicative of a bug within the plugin. It would be immensely
11:11:55  helpful if you could report the crash with the plugin's maintainers so that it
11:11:55  can be fixed. The output above should help diagnose the issue.
```

### Terraform Configuration Files

.

### Steps to Reproduce

.

### Would you like to implement a fix?

None

**Comment by m477r1x** [comment]
We are also experiencing this issue since this morning

**Comment by PierreHanselmann-eaton** [comment]
Same issue as #35256

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/pull/35187.

**Comment by cs-shahin** [comment]
We are also experiencing the same issue with AMQ. Any help!!

**Comment by jorgecara** [comment]
> We are also experiencing the same issue with AMQ. Any help!!

Locking our providers version to 5.31.0 served as a workaround for us:
<img width="379" alt="Screenshot 2024-01-12 at 13 59 35" src="https://github.com/hashicorp/terraform-provider-aws/assets/24839129/b4cda834-c5c0-40e4-a109-a2c6dd51c0f5">

**Comment by gleiva-BGH** [comment]
I am experiencing the same issue. How can I change the provider version on Terraform Cloud?
