### ISSUE TITLE
[Bug]: The terraform-provider-aws_v5.29.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by b0o0b** [hashicorp/terraform-provider-aws#35326]
### Terraform Core Version

1.5.7

### AWS Provider Version

5.29.0

### Affected Resource(s)

- aws_cloudwatch_event_connection

### Expected Behavior

Event Bridge connection will be newly created.

### Actual Behavior

Event Bridge connection won't be created and ended with terraform plugin crashed error.

### Terraform Configuration Files

```
resource "aws_cloudwatch_event_connection" "default" {
  name               = "test-connection"
  authorization_type = "API_KEY"
  auth_parameters {
    api_key {
      key   = "something"
      value = "secret"
    }
    invocation_http_parameters {
    }
  }
  lifecycle {
    ignore_changes = [
      auth_parameters
    ]
  }
}
```

### Steps to Reproduce

Just run `$ terraform apply` and you'll get error.

### Debug Output

```
$ terraform apply --target module.event_bridge.aws_cloudwatch_event_connection.default

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.event_bridge.aws_cloudwatch_event_connection.default will be created
  + resource "aws_cloudwatch_event_connection" "default" {
      + arn                = (known after apply)
      + authorization_type = "API_KEY"
      + id                 = (known after apply)
      + name               = "test-connection"
      + secret_arn         = (known after apply)

      + auth_parameters {
          + api_key {
              + key   = "something"
              + value = (sensitive value)
            }
          + invocation_http_parameters {
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
╷
│ Warning: Resource targeting is in effect
│ 
│ You are creating a plan with the -target option, which means that the result of this plan may not represent all of the changes requested by the current
│ configuration.
│ 
│ The -target option is not for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform
│ specifically suggests to use it as part of an error message.
╵

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.event_bridge.aws_cloudwatch_event_connection.default: Creating...
╷
│ Warning: Applied changes may be incomplete
│ 
│ The plan was created with the -target option in effect, so some changes requested in the configuration may have been ignored and the output values may not
│ be fully updated. Run the following command to verify that no other changes are pending:
│     terraform plan
│ 
│ Note that the -target option is not suitable for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or
│ when Terraform specifically suggests to use it as part of an error message.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.event_bridge.aws_cloudwatch_event_connection.default,
│   on ../modules/event_bridge/main.tf line 95, in resource "aws_cloudwatch_event_connection" "default":
│   95: resource "aws_cloudwatch_event_connection" "default" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-aws_v5.29.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 347 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/events.expandConnectionHTTPParameters({0xc0030f8b40, 0x1, 0xe412d01?})
        github.com/hashicorp/terraform-provider-aws/internal/service/events/connection.go:489 +0x24f
github.com/hashicorp/terraform-provider-aws/internal/service/events.expandCreateConnectionAuthRequestParameters({0xc0030f8ab0, 0x1, 0xc001e8c180?})
        github.com/hashicorp/terraform-provider-aws/internal/service/events/connection.go:405 +0x295
github.com/hashicorp/terraform-provider-aws/internal/service/events.resourceConnectionCreate({0xf7cf580, 0xc001e8c180}, 0xc000c4db80, {0xe2d60e0?, 0xc0002e20f0})
        github.com/hashicorp/terraform-provider-aws/internal/service/events/connection.go:273 +0x17c
github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0x0?, {0xe2d60e0?, 0xc0002e20f0?})
        github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:111 +0x32d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xf7cf580?, {0xf7cf580?, 0xc001e55f80?}, 0xd?, {0xe2d60e0?, 0xc0002e20f0?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/resource.go:773 +0x87
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000e78380, {0xf7cf580, 0xc001e55f80}, 0xc001a91ee0, 0xc000c4da00, {0xe2d60e0, 0xc0002e20f0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/resource.go:909 +0xa7e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc002e24300, {0xf7cf580?, 0xc001e55e60?}, 0xc001e60050)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/grpc_provider.go:1072 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0xf7cf4d8?, {0xf7cf580?, 0xc001e55b30?}, 0xc001e60050)
        github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x1b5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc002e1e3c0, {0xf7cf580?, 0xc001e55140?}, 0xc0007bef50)
        github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov5/tf5server/server.go:859 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xe043d80?, 0xc002e1e3c0}, {0xf7cf580, 0xc001e55140}, 0xc000c4cf80, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000800780, {0xf7cf580, 0xc001e550b0}, {0xf7df1a0, 0xc00086b6c0}, 0xc001e57c20, 0xc002e3f890, 0x15fd0d38, 0x0)
        google.golang.org/grpc@v1.59.0/server.go:1343 +0xe49
google.golang.org/grpc.(*Server).handleStream(0xc000800780, {0xf7df1a0, 0xc00086b6c0}, 0xc001e57c20)
        google.golang.org/grpc@v1.59.0/server.go:1737 +0xca6
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.59.0/server.go:986 +0x8c
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.59.0/server.go:997 +0x15c

Error: The terraform-provider-aws_v5.29.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 62 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/events.expandConnectionHTTPParameters({0xc001b55dc0, 0x1, 0xe412d01?})
        github.com/hashicorp/terraform-provider-aws/internal/service/events/connection.go:489 +0x24f
github.com/hashicorp/terraform-provider-aws/internal/service/events.expandCreateConnectionAuthRequestParameters({0xc001b55d30, 0x1, 0xc001b5cbd0?})
        github.com/hashicorp/terraform-provider-aws/internal/service/events/connection.go:405 +0x295
github.com/hashicorp/terraform-provider-aws/internal/service/events.resourceConnectionCreate({0xf7cf580, 0xc001b5cbd0}, 0xc00028fa80, {0xe2d60e0?, 0xc0002e20f0})
        github.com/hashicorp/terraform-provider-aws/internal/service/events/connection.go:273 +0x17c
github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0x0?, {0xe2d60e0?, 0xc0002e20f0?})
        github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:111 +0x32d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xf7cf580?, {0xf7cf580?, 0xc001b189f0?}, 0xd?, {0xe2d60e0?, 0xc0002e20f0?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/resource.go:773 +0x87
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc001394620, {0xf7cf580, 0xc001b189f0}, 0xc0018736c0, 0xc00028f900, {0xe2d60e0, 0xc0002e20f0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/resource.go:909 +0xa7e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0020e5d28, {0xf7cf580?, 0xc001b188d0?}, 0xc0007486e0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/grpc_provider.go:1072 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0xf7cf4d8?, {0xf7cf580?, 0xc001b185a0?}, 0xc0007486e0)
        github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x1b5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000bff680, {0xf7cf580?, 0xc00138d4d0?}, 0xc0006a4380)
        github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov5/tf5server/server.go:859 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xe043d80?, 0xc000bff680}, {0xf7cf580, 0xc00138d4d0}, 0xc00028e080, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.19.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000552780, {0xf7cf580, 0xc00138d410}, {0xf7df1a0, 0xc003452680}, 0xc004e126c0, 0xc001bee0c0, 0x15fd0d38, 0x0)
        google.golang.org/grpc@v1.59.0/server.go:1343 +0xe49
google.golang.org/grpc.(*Server).handleStream(0xc000552780, {0xf7df1a0, 0xc003452680}, 0xc004e126c0)
        google.golang.org/grpc@v1.59.0/server.go:1737 +0xca6
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.59.0/server.go:986 +0x8c
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.59.0/server.go:997 +0x15c

Error: The terraform-provider-aws_v5.29.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### References

I updated aws provider to the current latest version of `v5.32.1` but still getting same error.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Possibly related #31671
