### ISSUE TITLE
[Bug]: Error: The terraform-provider-aws_v4.55.0_x5 plugin crashed!Error: The terraform-provider-aws_v4.55.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by olaraki** [hashicorp/terraform-provider-aws#35360]
### Terraform Core Version

1.5.4

### AWS Provider Version

4.55.0

### Affected Resource(s)

```shell
Executing pre-plan hook...

Stack trace from the terraform-provider-aws_v4.55.0_x5 plugin:

fatal error: newosproc

runtime stack:
runtime.throw({0xcef0ba8?, 0xc00010de38?})
runtime/panic.go:1047 +0x5d fp=0xc00010de00 sp=0xc00010ddd0 pc=0x43601d
runtime.newosproc(0xc0000c8c00)
runtime/os_linux.go:187 +0x185 fp=0xc00010de60 sp=0xc00010de00 pc=0x4324e5
runtime.newm1(0xc0000c8c00)
runtime/proc.go:2166 +0xcf fp=0xc00010dea0 sp=0xc00010de60 pc=0x43c78f
runtime.newm(0xc00010dee8?, 0xc00009f400, 0x1?)
runtime/proc.go:2141 +0x12c fp=0xc00010ded0 sp=0xc00010dea0 pc=0x43c64c
runtime.startm(0x0, 0x1)
runtime/proc.go:2325 +0xcf fp=0xc00010df18 sp=0xc00010ded0 pc=0x43cbcf
runtime.wakep()
runtime/proc.go:2430 +0x5a fp=0xc00010df38 sp=0xc00010df18 pc=0x43d13a
runtime.resetspinning()
runtime/proc.go:3110 +0x45 fp=0xc00010df58 sp=0xc00010df38 pc=0x43eb05
runtime.schedule()
runtime/proc.go:3220 +0xe5 fp=0xc00010df90 sp=0xc00010df58 pc=0x43ef45
runtime.park_m(0xc0001c1520?)
runtime/proc.go:3363 +0x14d fp=0xc00010dfc0 sp=0xc00010df90 pc=0x43f44d
runtime.mcall()
runtime/asm_amd64.s:448 +0x43 fp=0xc00010dfd0 sp=0xc00010dfc0 pc=0x464ce3

goroutine 1 [runnable, locked to thread]:
runtime.mapassign(0xb7707a0?, 0xc000684180?, 0xe362198?)
runtime/map.go:578 +0x532 fp=0xc000421338 sp=0xc000421330 pc=0x40f492
github.com/aws/aws-sdk-go/aws/endpoints.init()
github.com/aws/aws-sdk-go@v1.44.201/aws/endpoints/defaults.go:26098 +0x86bfd fp=0xc00043f730 sp=0xc000421338 pc=0xc2f3bd
runtime.doInit(0x148c5980)
runtime/proc.go:6329 +0x126 fp=0xc00043f860 sp=0xc00043f730 pc=0x445b26
runtime.doInit(0x148d2fe0)
runtime/proc.go:6306 +0x71 fp=0xc00043f990 sp=0xc00043f860 pc=0x445a71
runtime.doInit(0x148e5a20)
runtime/proc.go:6306 +0x71 fp=0xc00043fac0 sp=0xc00043f990 pc=0x445a71
runtime.doInit(0x148fbd00)
runtime/proc.go:6306 +0x71 fp=0xc00043fbf0 sp=0xc00043fac0 pc=0x445a71
runtime.doInit(0x148d3c60)
runtime/proc.go:6306 +0x71 fp=0xc00043fd20 sp=0xc00043fbf0 pc=0x445a71
runtime.doInit(0x148f86c0)
runtime/proc.go:6306 +0x71 fp=0xc00043fe50 sp=0xc00043fd20 pc=0x445a71
runtime.doInit(0x148c1ec0)
runtime/proc.go:6306 +0x71 fp=0xc00043ff80 sp=0xc00043fe50 pc=0x445a71
runtime.main()
runtime/proc.go:233 +0x1d3 fp=0xc00043ffe0 sp=0xc00043ff80 pc=0x438833
runtime.goexit()
runtime/asm_amd64.s:1594 +0x1 fp=0xc00043ffe8 sp=0xc00043ffe0 pc=0x466de1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
runtime/proc.go:363 +0xd6 fp=0xc0000c4fb0 sp=0xc0000c4f90 pc=0x438c36
runtime.goparkunlock(...)
runtime/proc.go:369
runtime.forcegchelper()
runtime/proc.go:302 +0xad fp=0xc0000c4fe0 sp=0xc0000c4fb0 pc=0x438acd
runtime.goexit()
runtime/asm_amd64.s:1594 +0x1 fp=0xc0000c4fe8 sp=0xc0000c4fe0 pc=0x466de1
created by runtime.init.6
runtime/proc.go:290 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
runtime/proc.go:363 +0xd6 fp=0xc0000c5790 sp=0xc0000c5770 pc=0x438c36
runtime.goparkunlock(...)
runtime/proc.go:369
runtime.bgsweep(0x0?)
runtime/mgcsweep.go:278 +0x8e fp=0xc0000c57c8 sp=0xc0000c5790 pc=0x424fae
runtime.gcenable.func1()
runtime/mgc.go:178 +0x26 fp=0xc0000c57e0 sp=0xc0000c57c8 pc=0x419c66
runtime.goexit()
runtime/asm_amd64.s:1594 +0x1 fp=0xc0000c57e8 sp=0xc0000c57e0 pc=0x466de1
created by runtime.gcenable
runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000086070?, 0xe230028?, 0x0?, 0x0?, 0x0?)
runtime/proc.go:363 +0xd6 fp=0xc0000c5f70 sp=0xc0000c5f50 pc=0x438c36
runtime.goparkunlock(...)
runtime/proc.go:369
runtime.(*scavengerState).park(0x14978d60)
runtime/mgcscavenge.go:389 +0x53 fp=0xc0000c5fa0 sp=0xc0000c5f70 pc=0x423053
runtime.bgscavenge(0x0?)
runtime/mgcscavenge.go:622 +0x65 fp=0xc0000c5fc8 sp=0xc0000c5fa0 pc=0x423645
runtime.gcenable.func2()
runtime/mgc.go:179 +0x26 fp=0xc0000c5fe0 sp=0xc0000c5fc8 pc=0x419c06
runtime.goexit()
runtime/asm_amd64.s:1594 +0x1 fp=0xc0000c5fe8 sp=0xc0000c5fe0 pc=0x466de1
created by runtime.gcenable
runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0x438fb7?, 0x438a05?, 0x0?, 0x0?, 0xc0000c4770?)
runtime/proc.go:363 +0xd6 fp=0xc0000c4628 sp=0xc0000c4608 pc=0x438c36
runtime.goparkunlock(...)
runtime/proc.go:369
runtime.runfinq()
runtime/mfinal.go:180 +0x10f fp=0xc0000c47e0 sp=0xc0000c4628 pc=0x418d6f
runtime.goexit()
runtime/asm_amd64.s:1594 +0x1 fp=0xc0000c47e8 sp=0xc0000c47e0 pc=0x466de1
created by runtime.createfing
runtime/mfinal.go:157 +0x45

Error: The terraform-provider-aws_v4.55.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior

successfull

### Actual Behavior

```shell
Executing pre-plan hook...

Stack trace from the terraform-provider-aws_v4.55.0_x5 plugin:

fatal error: newosproc

runtime stack:
runtime.throw({0xcef0ba8?, 0xc00010de38?})
runtime/panic.go:1047 +0x5d fp=0xc00010de00 sp=0xc00010ddd0 pc=0x43601d
runtime.newosproc(0xc0000c8c00)
runtime/os_linux.go:187 +0x185 fp=0xc00010de60 sp=0xc00010de00 pc=0x4324e5
runtime.newm1(0xc0000c8c00)
runtime/proc.go:2166 +0xcf fp=0xc00010dea0 sp=0xc00010de60 pc=0x43c78f
runtime.newm(0xc00010dee8?, 0xc00009f400, 0x1?)
runtime/proc.go:2141 +0x12c fp=0xc00010ded0 sp=0xc00010dea0 pc=0x43c64c
runtime.startm(0x0, 0x1)
runtime/proc.go:2325 +0xcf fp=0xc00010df18 sp=0xc00010ded0 pc=0x43cbcf
runtime.wakep()
runtime/proc.go:2430 +0x5a fp=0xc00010df38 sp=0xc00010df18 pc=0x43d13a
runtime.resetspinning()
runtime/proc.go:3110 +0x45 fp=0xc00010df58 sp=0xc00010df38 pc=0x43eb05
runtime.schedule()
runtime/proc.go:3220 +0xe5 fp=0xc00010df90 sp=0xc00010df58 pc=0x43ef45
runtime.park_m(0xc0001c1520?)
runtime/proc.go:3363 +0x14d fp=0xc00010dfc0 sp=0xc00010df90 pc=0x43f44d
runtime.mcall()
runtime/asm_amd64.s:448 +0x43 fp=0xc00010dfd0 sp=0xc00010dfc0 pc=0x464ce3

goroutine 1 [runnable, locked to thread]:
runtime.mapassign(0xb7707a0?, 0xc000684180?, 0xe362198?)
runtime/map.go:578 +0x532 fp=0xc000421338 sp=0xc000421330 pc=0x40f492
github.com/aws/aws-sdk-go/aws/endpoints.init()
github.com/aws/aws-sdk-go@v1.44.201/aws/endpoints/defaults.go:26098 +0x86bfd fp=0xc00043f730 sp=0xc000421338 pc=0xc2f3bd
runtime.doInit(0x148c5980)
runtime/proc.go:6329 +0x126 fp=0xc00043f860 sp=0xc00043f730 pc=0x445b26
runtime.doInit(0x148d2fe0)
runtime/proc.go:6306 +0x71 fp=0xc00043f990 sp=0xc00043f860 pc=0x445a71
runtime.doInit(0x148e5a20)
runtime/proc.go:6306 +0x71 fp=0xc00043fac0 sp=0xc00043f990 pc=0x445a71
runtime.doInit(0x148fbd00)
runtime/proc.go:6306 +0x71 fp=0xc00043fbf0 sp=0xc00043fac0 pc=0x445a71
runtime.doInit(0x148d3c60)
runtime/proc.go:6306 +0x71 fp=0xc00043fd20 sp=0xc00043fbf0 pc=0x445a71
runtime.doInit(0x148f86c0)
runtime/proc.go:6306 +0x71 fp=0xc00043fe50 sp=0xc00043fd20 pc=0x445a71
runtime.doInit(0x148c1ec0)
runtime/proc.go:6306 +0x71 fp=0xc00043ff80 sp=0xc00043fe50 pc=0x445a71
runtime.main()
runtime/proc.go:233 +0x1d3 fp=0xc00043ffe0 sp=0xc00043ff80 pc=0x438833
runtime.goexit()
runtime/asm_amd64.s:1594 +0x1 fp=0xc00043ffe8 sp=0xc00043ffe0 pc=0x466de1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
runtime/proc.go:363 +0xd6 fp=0xc0000c4fb0 sp=0xc0000c4f90 pc=0x438c36
runtime.goparkunlock(...)
runtime/proc.go:369
runtime.forcegchelper()
runtime/proc.go:302 +0xad fp=0xc0000c4fe0 sp=0xc0000c4fb0 pc=0x438acd
runtime.goexit()
runtime/asm_amd64.s:1594 +0x1 fp=0xc0000c4fe8 sp=0xc0000c4fe0 pc=0x466de1
created by runtime.init.6
runtime/proc.go:290 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
runtime/proc.go:363 +0xd6 fp=0xc0000c5790 sp=0xc0000c5770 pc=0x438c36
runtime.goparkunlock(...)
runtime/proc.go:369
runtime.bgsweep(0x0?)
runtime/mgcsweep.go:278 +0x8e fp=0xc0000c57c8 sp=0xc0000c5790 pc=0x424fae
runtime.gcenable.func1()
runtime/mgc.go:178 +0x26 fp=0xc0000c57e0 sp=0xc0000c57c8 pc=0x419c66
runtime.goexit()
runtime/asm_amd64.s:1594 +0x1 fp=0xc0000c57e8 sp=0xc0000c57e0 pc=0x466de1
created by runtime.gcenable
runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000086070?, 0xe230028?, 0x0?, 0x0?, 0x0?)
runtime/proc.go:363 +0xd6 fp=0xc0000c5f70 sp=0xc0000c5f50 pc=0x438c36
runtime.goparkunlock(...)
runtime/proc.go:369
runtime.(*scavengerState).park(0x14978d60)
runtime/mgcscavenge.go:389 +0x53 fp=0xc0000c5fa0 sp=0xc0000c5f70 pc=0x423053
runtime.bgscavenge(0x0?)
runtime/mgcscavenge.go:622 +0x65 fp=0xc0000c5fc8 sp=0xc0000c5fa0 pc=0x423645
runtime.gcenable.func2()
runtime/mgc.go:179 +0x26 fp=0xc0000c5fe0 sp=0xc0000c5fc8 pc=0x419c06
runtime.goexit()
runtime/asm_amd64.s:1594 +0x1 fp=0xc0000c5fe8 sp=0xc0000c5fe0 pc=0x466de1
created by runtime.gcenable
runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0x438fb7?, 0x438a05?, 0x0?, 0x0?, 0xc0000c4770?)
runtime/proc.go:363 +0xd6 fp=0xc0000c4628 sp=0xc0000c4608 pc=0x438c36
runtime.goparkunlock(...)
runtime/proc.go:369
runtime.runfinq()
runtime/mfinal.go:180 +0x10f fp=0xc0000c47e0 sp=0xc0000c4628 pc=0x418d6f
runtime.goexit()
runtime/asm_amd64.s:1594 +0x1 fp=0xc0000c47e8 sp=0xc0000c47e0 pc=0x466de1
created by runtime.createfing
runtime/mfinal.go:157 +0x45

Error: The terraform-provider-aws_v4.55.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Configuration Files

```terraform
credentials "terraform.richemont.com" {
  token = "******"
}

credentials "prd-tfe-foundation.richemont.com" {
  token = "****"
}
```

### Steps to Reproduce

it happens all the time 

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment]
Hey @olaraki 👋 Thank you for taking the time to raise this! Are you able to provide additional information about what you're attempting to do when this error occurs, [debug logging](https://developer.hashicorp.com/terraform/internals/debugging), and a sample Terraform configuration that can be used to reproduce the issue? We'll need that information in order to better investigate this.

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
