### ISSUE TITLE
[Bug]: aws service catalog provisioned product not creating product and getting timed out

### ISSUE THREAD

**Issue by kaul-abhi** [hashicorp/terraform-provider-aws#37101]
### Terraform Core Version

1.5.5

### AWS Provider Version

5.46.0

### Affected Resource(s)

aws_servicecatalog_provisioned_product

### Expected Behavior

aws_servicecatalog_provisioned_product resource should have created the product but it gets timed out. Default timeout set is 20 min. It shows "still creating" in logs but actuality it doesnt even create the resource.

### Actual Behavior

Test_SC_Portfolio 2024-04-25T08:31:58Z logger.go:66: module.service_catalog.aws_servicecatalog_provisioned_product.example["example"]: Still creating... [19m0s elapsed]
panic: test timed out after 20m0s

### Relevant Error/Panic Output Snippet

```shell
Test_SC_Portfolio 2024-04-25T08:31:58Z logger.go:66: module.service_catalog.aws_servicecatalog_provisioned_product.example["example"]: Still creating... [19m0s elapsed]
panic: test timed out after 20m0s
running tests:
	Test_SC_Portfolio (20m0s)
goroutine 27 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:2241 +0x3c5
created by time.goFunc
	/usr/local/go/src/time/sleep.go:176 +0x32
goroutine 1 [chan receive, 20 minutes]:
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1542 +0x4a5
testing.tRunner(0xc000542680, 0xc00053fc88)
	/usr/local/go/src/testing/testing.go:1582 +0x144
testing.runTests(0xc00021b900?, {0x1adb7f0, 0x1, 0x1}, {0xc00038f9a8?, 0x100c00053fd10?, 0x1af75e0?})
	/usr/local/go/src/testing/testing.go:2034 +0x489
testing.(*M).Run(0xc00021b900)
	/usr/local/go/src/testing/testing.go:1906 +0x63a
main.main()
	_testmain.go:47 +0x1aa
goroutine 11 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000110000)
	/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:292 +0xad
created by go.opencensus.io/stats/view.init.0
	/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:34 +0x96
goroutine 12 [semacquire, 20 minutes]:
sync.runtime_Semacquire(0xc00014da80?)
	/usr/local/go/src/runtime/sema.go:62 +0x27
sync.(*WaitGroup).Wait(0x3?)
	/usr/local/go/src/sync/waitgroup.go:116 +0x4b
github.com/gruntwork-io/terratest/modules/shell.readStdoutAndStderr({0x13a2ad0?, 0xc000542820}, 0x0, {0x139c868?, 0xc00013a200}, {0x139c868?, 0xc00013a210})
	/go/pkg/mod/github.com/gruntwork-io/terratest@v0.46.7/modules/shell/command.go:149 +0x5f4
github.com/gruntwork-io/terratest/modules/shell.runCommand({0x13a2ad0, 0xc000542820}, {{0x109d602, 0x9}, {0xc000164dc0, 0xc, 0x16}, {0x109dd4e, 0xa}, 0xc000149350, ...})
	/go/pkg/mod/github.com/gruntwork-io/terratest@v0.46.7/modules/shell/command.go:122 +0x285
github.com/gruntwork-io/terratest/modules/shell.RunCommandAndGetOutputE({0x13a2ad0?, 0xc000542820?}, {{0x109d602, 0x9}, {0xc000164dc0, 0xc, 0x16}, {0x109dd4e, 0xa}, 0xc000149350, ...})
	/go/pkg/mod/github.com/gruntwork-io/terratest@v0.46.7/modules/shell/command.go:58 +0x7b
github.com/gruntwork-io/terratest/modules/terraform.RunTerraformCommandE.func1()
	/go/pkg/mod/github.com/gruntwork-io/terratest@v0.46.7/modules/terraform/cmd.go:85 +0x4d
github.com/gruntwork-io/terratest/modules/retry.DoWithRetryableErrorsE.func1()
	/go/pkg/mod/github.com/gruntwork-io/terratest@v0.46.7/modules/retry/retry.go:137 +0x6c
github.com/gruntwork-io/terratest/modules/retry.DoWithRetryE.func1()
	/go/pkg/mod/github.com/gruntwork-io/terratest@v0.46.7/modules/retry/retry.go:68 +0x1d
github.com/gruntwork-io/terratest/modules/retry.DoWithRetryInterfaceE({0x13a2ad0, 0xc000542820}, {0xc0003800d0, 0xcf}, 0x0, 0x4fa345?, 0xc0004718b8)
	/go/pkg/mod/github.com/gruntwork-io/terratest@v0.46.7/modules/retry/retry.go:93 +0x1f2
github.com/gruntwork-io/terratest/modules/retry.DoWithRetryE({0x13a2ad0?, 0xc000542820?}, {0xc0003800d0?, 0xc000471990?}, 0x4fc336?, 0xc000348750?, 0xec9a80?)
	/go/pkg/mod/github.com/gruntwork-io/terratest@v0.46.7/modules/retry/retry.go:68 +0x45
github.com/gruntwork-io/terratest/modules/retry.DoWithRetryableErrorsE({0x13a2ad0, 0xc000542820}, {0xc0003800d0, 0xcf}, 0x2?, 0xec9a80?, 0xc000144300?, 0xc000471c00)
	/go/pkg/mod/github.com/gruntwork-io/terratest@v0.46.7/modules/retry/retry.go:136 +0x26b
github.com/gruntwork-io/terratest/modules/terraform.RunTerraformCommandE({0x13a2ad0, 0xc000542820}, 0x3?, {0xc000164dc0?, 0xe?, 0xc000471d78?})
	/go/pkg/mod/github.com/gruntwork-io/terratest@v0.46.7/modules/terraform/cmd.go:84 +0x293
github.com/gruntwork-io/terratest/modules/terraform.ApplyE({0x13a2ad0, 0xc000542820}, 0xc000471e68?)
	/go/pkg/mod/github.com/gruntwork-io/terratest@v0.46.7/modules/terraform/apply.go:49 +0xb0
github.com/gruntwork-io/terratest/modules/terraform.InitAndApplyE({0x13a2ad0, 0xc000542820}, 0x1?)
	/go/pkg/mod/github.com/gruntwork-io/terratest@v0.46.7/modules/terraform/apply.go:27 +0x4f
github.com/gruntwork-io/terratest/modules/terraform.InitAndApply({0x13a2ad0?, 0xc000542820}, 0x10a7fcb?)
	/go/pkg/mod/github.com/gruntwork-io/terratest@v0.46.7/modules/terraform/apply.go:14 +0x28
code.siemens.com/horizon/platform-verticals/reference/service-catalog-spoke-account.Test_SC_Portfolio(0xc000542820)
	/builds/horizon/platform-verticals/reference/service-catalog-spoke-account/sc_spoke_test.go:37 +0x398
testing.tRunner(0xc000542820, 0x1109ab8)
	/usr/local/go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1629 +0x3ea
goroutine 15 [IO wait]:
internal/poll.runtime_pollWait(0x7f0c2dba1970, 0x72)
	/usr/local/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc000150600?, 0xc000459000?, 0x1)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000150600, {0xc000459000, 0x1000, 0x1000})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x299
os.(*File).read(...)
	/usr/local/go/src/os/file_posix.go:31
os.(*File).Read(0xc00013a200, {0xc000459000?, 0xc0001461e0?, 0x2?})
	/usr/local/go/src/os/file.go:118 +0x5e
bufio.(*Reader).fill(0xc000150780)
	/usr/local/go/src/bufio/bufio.go:106 +0xff
bufio.(*Reader).ReadSlice(0xc000150780, 0x30?)
	/usr/local/go/src/bufio/bufio.go:372 +0x2f
bufio.(*Reader).collectFragments(0x138c7f0?, 0x8?)
	/usr/local/go/src/bufio/bufio.go:447 +0x74
bufio.(*Reader).ReadString(0x0?, 0x60?)
	/usr/local/go/src/bufio/bufio.go:494 +0x2b
github.com/gruntwork-io/terratest/modules/shell.readData({0x13a2ad0, 0xc000542820}, 0x0?, 0x0?, {0x1396340, 0xc000146920})
	/go/pkg/mod/github.com/gruntwork-io/terratest@v0.46.7/modules/shell/command.go:165 +0x65
github.com/gruntwork-io/terratest/modules/shell.readStdoutAndStderr.func1()
	/go/pkg/mod/github.com/gruntwork-io/terratest@v0.46.7/modules/shell/command.go:143 +0x7f
created by github.com/gruntwork-io/terratest/modules/shell.readStdoutAndStderr
	/go/pkg/mod/github.com/gruntwork-io/terratest@v0.46.7/modules/shell/command.go:141 +0x518
goroutine 16 [IO wait, 20 minutes]:
internal/poll.runtime_pollWait(0x7f0c2dba1880, 0x72)
	/usr/local/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc0001506c0?, 0xc000692000?, 0x1)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0001506c0, {0xc000692000, 0x1000, 0x1000})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x299
os.(*File).read(...)
	/usr/local/go/src/os/file_posix.go:31
os.(*File).Read(0xc00013a210, {0xc000692000?, 0x0?, 0x0?})
	/usr/local/go/src/os/file.go:118 +0x5e
bufio.(*Reader).fill(0xc0001507e0)
	/usr/local/go/src/bufio/bufio.go:106 +0xff
bufio.(*Reader).ReadSlice(0xc0001507e0, 0x0?)
	/usr/local/go/src/bufio/bufio.go:372 +0x2f
bufio.(*Reader).collectFragments(0x0?, 0x0?)
	/usr/local/go/src/bufio/bufio.go:447 +0x74
bufio.(*Reader).ReadString(0x0?, 0x0?)
	/usr/local/go/src/bufio/bufio.go:494 +0x2b
github.com/gruntwork-io/terratest/modules/shell.readData({0x13a2ad0, 0xc000542820}, 0x0?, 0x0?, {0x1396340, 0xc000146940})
	/go/pkg/mod/github.com/gruntwork-io/terratest@v0.46.7/modules/shell/command.go:165 +0x65
github.com/gruntwork-io/terratest/modules/shell.readStdoutAndStderr.func2()
	/go/pkg/mod/github.com/gruntwork-io/terratest@v0.46.7/modules/shell/command.go:147 +0x85
created by github.com/gruntwork-io/terratest/modules/shell.readStdoutAndStderr
	/go/pkg/mod/github.com/gruntwork-io/terratest@v0.46.7/modules/shell/command.go:145 +0x5e
```

### Terraform Configuration Files

[main.tf.zip](https://github.com/hashicorp/terraform-provider-aws/files/15112980/main.tf.zip)

### Steps to Reproduce

Difficult to reproduce as its working as a single deployment with hardcoded value. I use terratest go file to test the module.

### Would you like to implement a fix?

None

**Comment by kaul-abhi** [comment]
Hi team i know its not exhausive detail from my side but issue is that nothing is happening while creating resource and in logs it shows still creating. Do let me know if anything else is also required.
