### ISSUE TITLE
│ The plugin encountered an error, and failed to respond to the │ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may │ contain more details[Bug]: 

### ISSUE THREAD

**Issue by sangarole** [hashicorp/terraform-provider-aws#37325]
### Terraform Core Version

1.6.6

### AWS Provider Version

5.48.0

### Affected Resource(s)

glue

### Expected Behavior

It should create the glue job.

### Actual Behavior

```console
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-aws_v5.48.0_x5.exe plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 58 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/glue.expandNotificationProperty(...)
        github.com/hashicorp/terraform-provider-aws/internal/service/glue/job.go:455
github.com/hashicorp/terraform-provider-aws/internal/service/glue.resourceJobCreate({0x130c98e8, 0x1e0c6ee8}, 0x1d7f0e10, {0x11322ec0, 0x1e8439d0})
        github.com/hashicorp/terraform-provider-aws/internal/service/glue/job.go:239 +0xf47
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).Create.interceptedHandler[...].func8(0x1d7f0e10, {0x11322ec0, 0x1e8439d0})
        github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:113 +0x28d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1ddaa4d0, {0x130c98e8, 0x1e0c6468}, 0x1d7f0e10, {0x11322ec0, 0x1e8439d0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:773 +0x7e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1ddaa4d0, {0x130c98e8, 0x1e0c6468}, 0x1e0d03f0, 0x1d7f0d20, {0x11322ec0, 0x1e8439d0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:909 +0xac3
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1e83e6f0, {0x130c98e8, 0x1e0c6438}, 0x1d7f5d10)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/grpc_provider.go:1078 +0xeb1
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0x1d7f14a0, {0x130c98e8, 0x1e0c6378}, 0x1d7f5d10)
        github.com/hashicorp/terraform-plugin-mux@v0.15.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x1d6
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x1d1885a0, {0x130c98e8, 0x1e0c60a8}, 0x1d868880)
        github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov5/tf5server/server.go:846 +0x439
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x11231980, 0x1d1885a0}, {0x130c98e8, 0x1e0c60a8}, 0x1d868840, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:518 +0x98
google.golang.org/grpc.(*Server).processUnaryRPC(0x1d16af08, {0x130c98e8, 0x1e0c6078}, {0x130e66f4, 0x1d1b0a28}, 0x1e8a8798, 0x1e3d4b10, 0x1b376ecc, 0x0)
        google.golang.org/grpc@v1.63.2/server.go:1369 +0xf44
google.golang.org/grpc.(*Server).handleStream(0x1d16af08, {0x130e66f4, 0x1d1b0a28}, 0x1e8a8798)
        google.golang.org/grpc@v1.63.2/server.go:1780 +0x10cf
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.63.2/server.go:1019 +0xaa
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 29
        google.golang.org/grpc@v1.63.2/server.go:1030 +0x12f

Error: The terraform-provider-aws_v5.48.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Relevant Error/Panic Output Snippet

```console
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-aws_v5.48.0_x5.exe plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 58 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/glue.expandNotificationProperty(...)
        github.com/hashicorp/terraform-provider-aws/internal/service/glue/job.go:455
github.com/hashicorp/terraform-provider-aws/internal/service/glue.resourceJobCreate({0x130c98e8, 0x1e0c6ee8}, 0x1d7f0e10, {0x11322ec0, 0x1e8439d0})
        github.com/hashicorp/terraform-provider-aws/internal/service/glue/job.go:239 +0xf47
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).Create.interceptedHandler[...].func8(0x1d7f0e10, {0x11322ec0, 0x1e8439d0})
        github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:113 +0x28d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1ddaa4d0, {0x130c98e8, 0x1e0c6468}, 0x1d7f0e10, {0x11322ec0, 0x1e8439d0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:773 +0x7e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1ddaa4d0, {0x130c98e8, 0x1e0c6468}, 0x1e0d03f0, 0x1d7f0d20, {0x11322ec0, 0x1e8439d0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:909 +0xac3
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1e83e6f0, {0x130c98e8, 0x1e0c6438}, 0x1d7f5d10)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/grpc_provider.go:1078 +0xeb1
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0x1d7f14a0, {0x130c98e8, 0x1e0c6378}, 0x1d7f5d10)
        github.com/hashicorp/terraform-plugin-mux@v0.15.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x1d6
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x1d1885a0, {0x130c98e8, 0x1e0c60a8}, 0x1d868880)
        github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov5/tf5server/server.go:846 +0x439
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x11231980, 0x1d1885a0}, {0x130c98e8, 0x1e0c60a8}, 0x1d868840, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:518 +0x98
google.golang.org/grpc.(*Server).processUnaryRPC(0x1d16af08, {0x130c98e8, 0x1e0c6078}, {0x130e66f4, 0x1d1b0a28}, 0x1e8a8798, 0x1e3d4b10, 0x1b376ecc, 0x0)
        google.golang.org/grpc@v1.63.2/server.go:1369 +0xf44
google.golang.org/grpc.(*Server).handleStream(0x1d16af08, {0x130e66f4, 0x1d1b0a28}, 0x1e8a8798)
        google.golang.org/grpc@v1.63.2/server.go:1780 +0x10cf
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.63.2/server.go:1019 +0xaa
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 29
        google.golang.org/grpc@v1.63.2/server.go:1030 +0x12f

Error: The terraform-provider-aws_v5.48.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Configuration Files

Glue.tf

```hcl
resource "aws_glue_job" "glue_job" {
  name                               = "${var.application_prefix}-${var.Environment}-${var.glue_job_name}"
  role_arn                           = var.glue_job_role_arn
  glue_version                       = var.glue_job_version
  max_retries                        = var.glue_job_max_retries
  timeout                            = var.glue_job_timeout
  worker_type                        = var.glue_job_worker_type
  number_of_workers                  = var.glue_job_worker_count
  execution_property {
    max_concurrent_runs              = var.glue_job_max_concurrentruns
  }
  notification_property {
    notify_delay_after               = var.glue_job_delay_notificationtime
  }
  command {
    script_location                  = var.glue_job_script_location
    python_version                   = var.glue_job_python_version
  }
  default_arguments                  = var.glue_job_extra_args
}
```

provider.tf

```hcl
provider "aws" {
  region           = var.region
  default_tags {
   tags            = var.global_tags
   }    
  assume_role {
    role_arn = "arn:aws:iam::${var.account_id}:role/xxxxxxxx"
  } 
}

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}
```

### Steps to Reproduce

terraform init 
terraform plan
terraform apply 

### Debug Output

```console
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-aws_v5.48.0_x5.exe plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 58 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/glue.expandNotificationProperty(...)
        github.com/hashicorp/terraform-provider-aws/internal/service/glue/job.go:455
github.com/hashicorp/terraform-provider-aws/internal/service/glue.resourceJobCreate({0x130c98e8, 0x1e0c6ee8}, 0x1d7f0e10, {0x11322ec0, 0x1e8439d0})
        github.com/hashicorp/terraform-provider-aws/internal/service/glue/job.go:239 +0xf47
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).Create.interceptedHandler[...].func8(0x1d7f0e10, {0x11322ec0, 0x1e8439d0})
        github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:113 +0x28d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1ddaa4d0, {0x130c98e8, 0x1e0c6468}, 0x1d7f0e10, {0x11322ec0, 0x1e8439d0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:773 +0x7e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1ddaa4d0, {0x130c98e8, 0x1e0c6468}, 0x1e0d03f0, 0x1d7f0d20, {0x11322ec0, 0x1e8439d0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:909 +0xac3
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1e83e6f0, {0x130c98e8, 0x1e0c6438}, 0x1d7f5d10)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/grpc_provider.go:1078 +0xeb1
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0x1d7f14a0, {0x130c98e8, 0x1e0c6378}, 0x1d7f5d10)
        github.com/hashicorp/terraform-plugin-mux@v0.15.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x1d6
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x1d1885a0, {0x130c98e8, 0x1e0c60a8}, 0x1d868880)
        github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov5/tf5server/server.go:846 +0x439
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x11231980, 0x1d1885a0}, {0x130c98e8, 0x1e0c60a8}, 0x1d868840, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:518 +0x98
google.golang.org/grpc.(*Server).processUnaryRPC(0x1d16af08, {0x130c98e8, 0x1e0c6078}, {0x130e66f4, 0x1d1b0a28}, 0x1e8a8798, 0x1e3d4b10, 0x1b376ecc, 0x0)
        google.golang.org/grpc@v1.63.2/server.go:1369 +0xf44
google.golang.org/grpc.(*Server).handleStream(0x1d16af08, {0x130e66f4, 0x1d1b0a28}, 0x1e8a8798)
        google.golang.org/grpc@v1.63.2/server.go:1780 +0x10cf
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.63.2/server.go:1019 +0xaa
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 29
        google.golang.org/grpc@v1.63.2/server.go:1030 +0x12f

Error: The terraform-provider-aws_v5.48.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Panic Output

```console
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-aws_v5.48.0_x5.exe plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 58 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/glue.expandNotificationProperty(...)
        github.com/hashicorp/terraform-provider-aws/internal/service/glue/job.go:455
github.com/hashicorp/terraform-provider-aws/internal/service/glue.resourceJobCreate({0x130c98e8, 0x1e0c6ee8}, 0x1d7f0e10, {0x11322ec0, 0x1e8439d0})
        github.com/hashicorp/terraform-provider-aws/internal/service/glue/job.go:239 +0xf47
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).Create.interceptedHandler[...].func8(0x1d7f0e10, {0x11322ec0, 0x1e8439d0})
        github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:113 +0x28d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1ddaa4d0, {0x130c98e8, 0x1e0c6468}, 0x1d7f0e10, {0x11322ec0, 0x1e8439d0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:773 +0x7e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1ddaa4d0, {0x130c98e8, 0x1e0c6468}, 0x1e0d03f0, 0x1d7f0d20, {0x11322ec0, 0x1e8439d0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:909 +0xac3
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1e83e6f0, {0x130c98e8, 0x1e0c6438}, 0x1d7f5d10)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/grpc_provider.go:1078 +0xeb1
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0x1d7f14a0, {0x130c98e8, 0x1e0c6378}, 0x1d7f5d10)
        github.com/hashicorp/terraform-plugin-mux@v0.15.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x1d6
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x1d1885a0, {0x130c98e8, 0x1e0c60a8}, 0x1d868880)
        github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov5/tf5server/server.go:846 +0x439
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x11231980, 0x1d1885a0}, {0x130c98e8, 0x1e0c60a8}, 0x1d868840, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:518 +0x98
google.golang.org/grpc.(*Server).processUnaryRPC(0x1d16af08, {0x130c98e8, 0x1e0c6078}, {0x130e66f4, 0x1d1b0a28}, 0x1e8a8798, 0x1e3d4b10, 0x1b376ecc, 0x0)
        google.golang.org/grpc@v1.63.2/server.go:1369 +0xf44
google.golang.org/grpc.(*Server).handleStream(0x1d16af08, {0x130e66f4, 0x1d1b0a28}, 0x1e8a8798)
        google.golang.org/grpc@v1.63.2/server.go:1780 +0x10cf
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.63.2/server.go:1019 +0xaa
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 29
        google.golang.org/grpc@v1.63.2/server.go:1030 +0x12f

Error: The terraform-provider-aws_v5.48.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Important Factoids

NA

### Would you like to implement a fix?

Yes

**Comment by DanielRieske** [comment]
Hi @sangarole :wave:

This is most likely because the variable `var.glue_job_delay_notificationtime` was null.
I assume your variable probably looks like.

```
variable "glue_job_delay_notificationtime" {
	type        = number
	default     = null
}
```

I added a few checks to validate the value which should solve your issue.

**Comment by sangarole** [comment]
Okay thanks @DanielRieske - Do you mean the null will work?
