### ISSUE TITLE
[Bug]: Provider crashes when "principal" is empty in "aws_ram_principal_association" resource

### ISSUE THREAD

**Issue by xanderbo** [hashicorp/terraform-provider-aws#37320]
### Terraform Core Version

1.6.0

### AWS Provider Version

5.46.0, 5.48.0

### Affected Resource(s)

aws_ram_principal_association

### Expected Behavior

Display info e.g. "Account ID is missing" or "Principal is empty"

### Actual Behavior

Terraform provider crashes.

### Relevant Error/Panic Output Snippet

```shell
aws_ram_principal_association.target_account: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with aws_ram_principal_association.target_account,
│   on tgw_accounts_connections.tf line 5, in resource "aws_ram_principal_association" "target_account":
│    5: resource "aws_ram_principal_association" "target_account" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-aws_v5.48.0_x5 plugin:

panic: unexpected format for ID parts ([arn:aws:ram:eu-central-1:381492076950:resource-share/62bb4f05-f7ae-404c-80fa-232b979db9d8 ]), the following id parts indexes are blank ([1])

goroutine 47 [running]:
github.com/hashicorp/terraform-provider-aws/internal/errs.Must[...](...)
	github.com/hashicorp/terraform-provider-aws/internal/errs/must.go:13
github.com/hashicorp/terraform-provider-aws/internal/service/ram.resourcePrincipalAssociationCreate({0x1478aa28, 0xc002c29440}, 0xc000aa4300, {0x1295d200, 0xc0023fe0d0})
	github.com/hashicorp/terraform-provider-aws/internal/service/ram/principal_association.go:70 +0xa45
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).Create.interceptedHandler[...].func8(0xc000aa4300?, {0x1295d200?, 0xc0023fe0d0})
	github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:113 +0x283
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1478aa28?, {0x1478aa28?, 0xc002c28ab0?}, 0xd?, {0x1295d200?, 0xc0023fe0d0?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:773 +0x7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0031ead20, {0x1478aa28, 0xc002c28ab0}, 0xc002bb6ea0, 0xc000aa4180, {0x1295d200, 0xc0023fe0d0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:909 +0xa89
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc003554720, {0x1478aa28?, 0xc002c289f0?}, 0xc0029af310)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/grpc_provider.go:1078 +0xd5c
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0xc001989180, {0x1478aa28?, 0xc002c28720?}, 0xc0029af310)
	github.com/hashicorp/terraform-plugin-mux@v0.15.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0005fdcc0, {0x1478aa28?, 0xc002bf9ce0?}, 0xc0000370a0)
	github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov5/tf5server/server.go:846 +0x3d0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x12719720, 0xc0005fdcc0}, {0x1478aa28, 0xc002bf9ce0}, 0xc0006f7900, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:518 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0019ba000, {0x1478aa28, 0xc002bf9c50}, {0x147d22f8, 0xc0005a5500}, 0xc002c187e0, 0xc0024a26c0, 0x1d44bb18, 0x0)
	google.golang.org/grpc@v1.63.2/server.go:1369 +0xdf8
google.golang.org/grpc.(*Server).handleStream(0xc0019ba000, {0x147d22f8, 0xc0005a5500}, 0xc002c187e0)
	google.golang.org/grpc@v1.63.2/server.go:1780 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 27
	google.golang.org/grpc@v1.63.2/server.go:1030 +0x125

Error: The terraform-provider-aws_v5.48.0_x5 plugin crashed!
```

### Terraform Configuration Files

resource "aws_ram_principal_association" "target_account" {
  principal          = ""
  resource_share_arn = aws_ram_resource_share.eu_central_1.arn
}

### Steps to Reproduce

just "terraform apply" on problematic code

### Would you like to implement a fix?

No

**Comment by DanielRieske** [comment]
Hi @xanderbo 👋, I'll be happy to pick this up as part of the `ram` SDKv2 migration.
