### ISSUE TITLE
[Bug]: panic: Go Duration ValueDuration Error on apply

### ISSUE THREAD

**Issue by lbennett-stacki** [hashicorp/terraform-provider-aws#37881]
### Terraform Core Version

~> 1.0

### AWS Provider Version

~> 5.0.0

### Affected Resource(s)

hashicorp/awscc
terraform-provider-awscc_v1.1.0_x5

### Expected Behavior

Apply should succeed because no terraform source has changed and no cloud resources have changed

### Actual Behavior

Apply panics with  "Go Duration ValueDuration Error - Duration string value is null"

### Relevant Error/Panic Output Snippet

```shell
module.slack_billing_alarm.aws_budgets_budget.this[0]: Refreshing state... [id=***:organizations-slack-billing-alert]

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ConfigureProvider call. The plugin logs may contain
│ more details.
╵

Stack trace from the terraform-provider-awscc_v1.1.0_x5 plugin:

panic: Go Duration ValueDuration Error

Duration string value is null

goroutine 13 [running]:
github.com/hashicorp/terraform-provider-awscc/internal/errs.Must[...](...)
	github.com/hashicorp/terraform-provider-awscc/internal/errs/must.go:13
github.com/hashicorp/terraform-provider-awscc/internal/errs/diag.Must[...](...)
	github.com/hashicorp/terraform-provider-awscc/internal/errs/diag/must.go:17
github.com/hashicorp/terraform-provider-awscc/internal/provider.assumeRoleData.Config({{{0x0, {0x0, 0x0}}}, {0x0, {0x0, 0x0}}, {{0x0, {0x0, 0x0}}}, {{0x0, ...}, ...}, ...})
	github.com/hashicorp/terraform-provider-awscc/internal/provider/provider.go:298 +0x63d
github.com/hashicorp/terraform-provider-awscc/internal/provider.newProviderData({0x31ad308, 0xc00036e540}, 0xc0003d43c0)
	github.com/hashicorp/terraform-provider-awscc/internal/provider/provider.go:480 +0xb38
github.com/hashicorp/terraform-provider-awscc/internal/provider.(*ccProvider).Configure(0xc0003ca048, {0x31ad308, 0xc00036e540}, {{0xc000228040, 0x5}, {{{0x31b36d0, 0xc0000a7e30}, {0x2105720, 0xc0000a66f0}}, {0x31e0a88, ...}}, ...}, ...)
	github.com/hashicorp/terraform-provider-awscc/internal/provider/provider.go:373 +0x21f
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ConfigureProvider(0xc0003d4000, {0x31ad308, 0xc00036e540}, 0xc0003b2b90, 0xc0004c7b40)
	github.com/hashicorp/terraform-plugin-framework@v1.9.0/internal/fwserver/server_configureprovider.go:18 +0x132
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ConfigureProvider(0xc0003d4000, {0x31ad308?, 0xc00036e450?}, 0xc00038e0c0)
	github.com/hashicorp/terraform-plugin-framework@v1.9.0/internal/proto6server/server_configureprovider.go:39 +0x2c5
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ConfigureProvider(0xc0003d6000, {0x31ad308?, 0xc0004dbb60?}, 0xc0003b21e0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/tf6server/server.go:559 +0x35a
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ConfigureProvider_Handler({0x221e0c0, 0xc0003d6000}, {0x31ad308, 0xc0004dbb60}, 0xc0004b4f00, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:464 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003d0000, {0x31ad308, 0xc0004dbad0}, {0x31de600, 0xc000157c80}, 0xc0004d8d80, 0xc00038ac90, 0x40af130, 0x0)
	google.golang.org/grpc@v1.63.2/server.go:1369 +0xdf8
google.golang.org/grpc.(*Server).handleStream(0xc0003d0000, {0x31de600, 0xc000157c80}, 0xc0004d8d80)
	google.golang.org/grpc@v1.63.2/server.go:1780 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 12
	google.golang.org/grpc@v1.63.2/server.go:1030 +0x125

Error: The terraform-provider-awscc_v1.1.0_x5 plugin crashed!
```

### Terraform Configuration Files

terraform {
  required_version = "~> 1.0"
  backend "s3" {
    bucket               = "westbury-music-tfstate"
    key                  = "base_main_account/terraform.tfstate"
    region               = "eu-west-2"
    encrypt              = true
    workspace_key_prefix = "workspace"
    dynamodb_table       = "terraform_lock"
  }
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0.0"
    }

    awscc = {
      source  = "hashicorp/awscc"
      version = "~> 0.78"
    }
  }
}

awscc is now pinned to 0.78 so the team is not blocked.

### Steps to Reproduce

Run apply with awscc plugin later than 0.78

### References

Likely related to recent changes here https://github.com/hashicorp/terraform-provider-aws/commit/b9f0afe7be852aa2f13554e196cb23797a76a988

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @lbennett-stacki 👋 It looks like this error is coming from the `awscc` provider, so I'm going to transfer the issue over to that repository.
