### ISSUE TITLE
[Bug]: 5.54 release - panic crash when using the `aws_ami` data source

### ISSUE THREAD

**Issue by vintage-maeve** [hashicorp/terraform-provider-aws#37973]
### Terraform Core Version

1.8.3

### AWS Provider Version

5.54.0

### Affected Resource(s)

The latest release of the terraform-provider-aws plugin is experiencing a panic crash when trying to access the AWS AMI data source.

### Expected Behavior

I came across this bug when I ran my Terraform with the newest AWS provider version. The code uses the `aws_ami` data source to pick up the latest AMI version.
After downgrading the version, the issue didn't happen anymore. Seems like the problem started appearing in the latest release.

### Actual Behavior

The terraform plan came back with the following error:
`The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.`

### Relevant Error/Panic Output Snippet

```shell
Executing pre-plan hook...

Stack trace from the terraform-provider-aws_v5.54.0_x5 plugin:

panic: interface conversion: interface {} is types.ProductCodeValues, not string

goroutine 146 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.amiProductCodesHash({0x11a1c040?, 0xc002e03440})
github.com/hashicorp/terraform-provider-aws/internal/service/ec2/ec2_ami_data_source.go:456 +0x1b5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).hash(0x0?, {0x11a1c040?, 0xc002e03440?})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/set.go:221 +0x26
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).add(0xc002ec2c20, {0x11a1c040, 0xc002e03440}, 0x0)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/set.go:201 +0x85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).Add(...)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/set.go:79
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.flattenAMIProductCodes({0xc002eab740, 0x1, 0x10?})
github.com/hashicorp/terraform-provider-aws/internal/service/ec2/ec2_ami_data_source.go:391 +0x6d
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.dataSourceAMIRead({0x15778028, 0xc005011f20}, 0xc00136c180, {0x137ca7e0?, 0xc001d61ba0})
github.com/hashicorp/terraform-provider-aws/internal/service/ec2/ec2_ami_data_source.go:330 +0xc65
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedDataSource).Read.interceptedHandler[...].func7(0xc00136c180?, {0x137ca7e0?, 0xc001d61ba0})
github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:113 +0x283
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x15778028?, {0x15778028?, 0xc0047ac7b0?}, 0xd?, {0x137ca7e0?, 0xc001d61ba0?})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:818 +0x7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc0016629a0, {0x15778028, 0xc0047ac7b0}, 0xc00136c080, {0x137ca7e0, 0xc001d61ba0})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:1043 +0x13a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc0036bac78, {0x15778028?, 0xc0047ac6f0?}, 0xc0048838f0)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/grpc_provider.go:1434 +0x6b1
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ReadDataSource(0xc001a3b110, {0x15778028?, 0xc0047ac3f0?}, 0xc0048838f0)
github.com/hashicorp/terraform-plugin-mux@v0.16.0/tf5muxserver/mux_server_ReadDataSource.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc00023e140, {0x15778028?, 0xc004883140?}, 0xc00489eaa0)
github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/tf5server/server.go:688 +0x27d
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x13594e60, 0xc00023e140}, {0x15778028, 0xc004883140}, 0xc0048ce000, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:572 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000796600, {0x15778028, 0xc0047ac000}, {0x157c9300, 0xc00036a000}, 0xc004d857a0, 0xc001e60e10, 0x1e8643c0, 0x0)
google.golang.org/grpc@v1.63.2/server.go:1369 +0xdf8
google.golang.org/grpc.(*Server).handleStream(0xc000796600, {0x157c9300, 0xc00036a000}, 0xc004d857a0)
google.golang.org/grpc@v1.63.2/server.go:1780 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 67
google.golang.org/grpc@v1.63.2/server.go:1030 +0x125

Error: The terraform-provider-aws_v5.54.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Configuration Files

Using terraform version - 1.8.3
Using terraform aws provider version - 5.54.0

### Steps to Reproduce

- Run the latest version of this provider (5.54.0)
- Use a `aws_ami` data source.
- Run a terraform plan.

### Would you like to implement a fix?

None

**Comment by ctdevops** [comment]
reverting to 5.50 made it work

**Comment by brendonthiede** [comment]
#37958 is called out in the release notes as changing the `aws_ami` datasource

**Comment by vintage-maeve** [comment]
@ctdevops You don't have to rollback multiple versions; simply going back to version 5.53.0 resolved the issue for me. :)

Also, thanks @brendonthiede for directing me to the specific implementation in the code. Considering this data source's heavy use, I reckon any alterations should be made to be backwards compatible.

**Comment by David-Pickwell-Hearst** [comment]
In addition to the above error, there are also similar errors on the two following resources:
- `aws_cloudwatch_log_group`
- `aws_ebs_volume`

The output of the error are:

```bash
│ Error: Request cancelled
│
│   with module.linux_vm["rhel9"].aws_ebs_volume.ebs["/dev/sdf"],
│   on ../main.tf line 156, in resource "aws_ebs_volume" "ebs":
│  156: resource "aws_ebs_volume" "ebs" {
│
│ The plugin.(*GRPCProvider).ValidateResourceConfig request was cancelled.
```
and
```bash
│ Error: Plugin did not respond
│
│   with module.linux_vm["amazon2"].module.userdata.aws_cloudwatch_log_group.this[0],
│   on .terraform/modules/linux_vm.userdata/ssm.tf line 24, in resource "aws_cloudwatch_log_group" "this":
│   24: resource "aws_cloudwatch_log_group" "this" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).PlanResourceChange call. The plugin logs may contain
│ more details.
```
along with the original data `aws_ami`:
```bash
│ Error: Plugin did not respond
│
│   with module.linux_vm["centos7"].data.aws_ami.linux,
│   on ../main.tf line 137, in data "aws_ami" "linux":
│  137: data "aws_ami" "linux" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain
│ more details.
```

The above was obtained on Terraform version 1.8.2, and the AWS Provider 5.54.0. 

As mentioned above, rolling back to 5.53.0 resolves the error.

**Comment by ewbankkit** [comment]
@David-Pickwell-Hearst If you are seeing crashes with resources other than the `aws_ami` data source please open separate issues including the relevant stack traces. This will help maintainers keep track of any issues and focus on solutions.
Thanks.

**Comment by David-Pickwell-Hearst** [comment]
> @David-Pickwell-Hearst If you are seeing crashes with resources other than the `aws_ami` data source please open separate issues including the relevant stack traces. This will help maintainers keep track of any issues and focus on solutions. Thanks.

@ewbankkit no worries. Opened here:
* aws_cloudwatch_log_group : https://github.com/hashicorp/terraform-provider-aws/issues/37978
* aws_ebs_volume : https://github.com/hashicorp/terraform-provider-aws/issues/37979

**Comment by ewbankkit** [comment]
@David-Pickwell-Hearst Thanks for those -- looking more deeply, it's the same underlying crash. I'll close the issues as duplicates.
