### ISSUE TITLE
terraform-provider-aws_v5.54.0_x5 plugin crashed![Bug]: 

### ISSUE THREAD

**Issue by tinuz74** [hashicorp/terraform-provider-aws#37981]
### Terraform Core Version

terraform-provider-aws_v5.54.0_x5

### AWS Provider Version

terraform-provider-aws_v5.54.0_x5

### Affected Resource(s)

AWS resources deploy/upgrades.

### Expected Behavior

Complete the pipeline and update/deploy aws resources

### Actual Behavior

Error: The terraform-provider-aws_v5.54.0_x5 plugin crashed!

### Relevant Error/Panic Output Snippet

```shell
Stack trace from the terraform-provider-aws_v5.54.0_x5 plugin:
panic: interface conversion: interface {} is types.ProductCodeValues, not string
goroutine 78 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.amiProductCodesHash({0x11a1c040?, 0xc001ca9f20})
	github.com/hashicorp/terraform-provider-aws/internal/service/ec2/ec2_ami_data_source.go:456 +0x1b5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).hash(0x0?, {0x11a1c040?, 0xc001ca9f20?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/set.go:221 +0x26
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).add(0xc00255b9a0, {0x11a1c040, 0xc001ca9f20}, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/set.go:201 +0x85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).Add(...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/set.go:79
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.flattenAMIProductCodes({0xc002703640, 0x1, 0x10?})
	github.com/hashicorp/terraform-provider-aws/internal/service/ec2/ec2_ami_data_source.go:391 +0x6d
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.dataSourceAMIRead({0x15778028, 0xc0024e6d20}, 0xc000775580, {0x137ca7e0?, 0xc0025724e0})
	github.com/hashicorp/terraform-provider-aws/internal/service/ec2/ec2_ami_data_source.go:330 +0xc65
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedDataSource).Read.interceptedHandler[...].func7(0xc000775580?, {0x137ca7e0?, 0xc0025724e0})
	github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:113 +0x283
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x15778028?, {0x15778028?, 0xc0024cd230?}, 0xd?, {0x137ca7e0?, 0xc0025724e0?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:818 +0x7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc00151c9a0, {0x15778028, 0xc0024cd230}, 0xc000775480, {0x137ca7e0, 0xc0025724e0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:1043 +0x13a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc003524c78, {0x15778028?, 0xc0024cd170?}, 0xc0024cce40)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/grpc_provider.go:1434 +0x6b1
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ReadDataSource(0xc0017b5110, {0x15778028?, 0xc0024ccea0?}, 0xc0024cce40)
	github.com/hashicorp/terraform-plugin-mux@v0.16.0/tf5muxserver/mux_server_ReadDataSource.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc000720f00, {0x15778028?, 0xc0027cb920?}, 0xc00232b6d0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/tf5server/server.go:688 +0x27d
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x13594e60, 0xc000720f00}, {0x15778028, 0xc0027cb920}, 0xc00006d300, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:572 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc001223000, {0x15778028, 0xc0027cb890}, {0x157c9300, 0xc001922600}, 0xc0024b2480, 0xc00257dc20, 0x1e8643c0, 0x0)
	google.golang.org/grpc@v1.63.2/server.go:1369 +0xdf8
google.golang.org/grpc.(*Server).handleStream(0xc001223000, {0x157c9300, 0xc001922600}, 0xc0024b2480)
	google.golang.org/grpc@v1.63.2/server.go:1780 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 52
	google.golang.org/grpc@v1.63.2/server.go:1030 +0x125
Error: The terraform-provider-aws_v5.54.0_x5 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
m
Running after_script
00:01
Running after script...
$ for I in zip gz jar # collapsed multi-line command
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: exit code 1
```

### Terraform Configuration Files

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5"
    }
  }

  required_version = ">= 1"
}

### Steps to Reproduce

Rerun pipeline

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
@tinuz74 Thanks for raising this issue.
It has already been noticed in #37973. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
