### ISSUE TITLE
[Bug]: When applying an aws_cloudformation_stack_set_instance, i got an error: panic: unexpected format for ID parts ([<stackset_name>  <stack_set_instance>]), the following id parts indexes are blank ([1])

### ISSUE THREAD

**Issue by rodolfosouzastone** [hashicorp/terraform-provider-aws#38846]
### Terraform Core Version

1.5.7

### AWS Provider Version

~> 5.0, 5.62.0, 5.49.0

### Affected Resource(s)

aws_cloudformation_stack_set_instance

### Expected Behavior

Terraform must deploy the stack_set_instance to account's list, without errors.

### Actual Behavior

Actually, when terraform just create the stack_set in the root account, but when will perform the application of the stack_set_instances, in each account informed on the list of accounts on the resource **aws_cloudformation_stack_set_instance**, an error appear and the apply simple fail!

### Relevant Error/Panic Output Snippet

```shell
running "## check diferent paths to terraform in atlantis\nif [ -f \"/atlantis-data/bin/terraform$ATLANTIS_TERRAFORM_VERSION\" ]\nthen\n  /atlantis-data/bin/terraform$ATLANTIS_TERRAFORM_VERSION apply  $PLANFILE \nelse\n  /usr/local/bin/terraform$ATLANTIS_TERRAFORM_VERSION apply  $PLANFILE\nfi\n\nif [ $? -eq 0 ]; then\n  export GITHUB_DEPLOYMENT_STATUS=success\n  /opt/deployments\n  sh /opt/ddog-logs.sh >/dev/null 2>&1\nelse\n  export GITHUB_DEPLOYMENT_STATUS=failure\n  /opt/deployments\n  sh /opt/ddog-logs.sh >/dev/null 2>&1\nfi\n/opt/slack_notify >/dev/null 2>&1\nif [ $GITHUB_DEPLOYMENT_STATUS == \"failure\" ];\nthen\n  exit 1\nelse\n  exit 0\nfi\n" in "/atlantis-data/repos/stone-payments/foundation-govcloud-infrastructure/799/prd/aws/applications/iam/policies/cross-account-policies": exit status 1: running "## check diferent paths to terraform in atlantis\nif [ -f \"/atlantis-data/bin/terraform$ATLANTIS_TERRAFORM_VERSION\" ]\nthen\n  /atlantis-data/bin/terraform$ATLANTIS_TERRAFORM_VERSION apply  $PLANFILE \nelse\n  /usr/local/bin/terraform$ATLANTIS_TERRAFORM_VERSION apply  $PLANFILE\nfi\n\nif [ $? -eq 0 ]; then\n  export GITHUB_DEPLOYMENT_STATUS=success\n  /opt/deployments\n  sh /opt/ddog-logs.sh >/dev/null 2>&1\nelse\n  export GITHUB_DEPLOYMENT_STATUS=failure\n  /opt/deployments\n  sh /opt/ddog-logs.sh >/dev/null 2>&1\nfi\n/opt/slack_notify >/dev/null 2>&1\nif [ $GITHUB_DEPLOYMENT_STATUS == \"failure\" ];\nthen\n  exit 1\nelse\n  exit 0\nfi\n" in "/atlantis-data/repos/stone-payments/foundation-govcloud-infrastructure/799/prd/aws/applications/iam/policies/cross-account-policies": 
module.cross-account-policy["ssmsessionmanagerrunshelly"].aws_cloudformation_stack_set_instance.stack_set_instance_accounts_application[0]: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with module.cross-account-policy["ssmsessionmanagerrunshelly"].aws_cloudformation_stack_set_instance.stack_set_instance_accounts_application[0],
│   on ../../../../modules/stack-set/main.tf line 46, in resource "aws_cloudformation_stack_set_instance" "stack_set_instance_accounts_application":
│   46: resource "aws_cloudformation_stack_set_instance" "stack_set_instance_accounts_application" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-aws_v5.62.0_x5 plugin:

panic: unexpected format for ID parts ([ssmsessionmanagerrunshellyb48c0a7221604959  us-east-1]), the following id parts indexes are blank ([1])

goroutine 362 [running]:
github.com/hashicorp/terraform-provider-aws/internal/errs.Must[...](...)
	github.com/hashicorp/terraform-provider-aws/internal/errs/must.go:13
github.com/hashicorp/terraform-provider-aws/internal/service/cloudformation.resourceStackSetInstanceCreate({0x174f43c8, 0xc0039964b0}, 0xc00116b780, {0x15222820, 0xc0026a8680})
	github.com/hashicorp/terraform-provider-aws/internal/service/cloudformation/stack_set_instance.go:272 +0x985
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).Create.interceptedHandler[...].func8(0xc00116b780?, {0x15222820?, 0xc0026a8680})
	github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:113 +0x283
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x174f43c8?, {0x174f43c8?, 0xc0030afda0?}, 0xd?, {0x15222820?, 0xc0026a8680?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:801 +0x7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000cae8c0, {0x174f43c8, 0xc0030afda0}, 0xc002fe4d00, 0xc00116b600, {0x15222820, 0xc0026a8680})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:937 +0xa89
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0036ad0e0, {0x174f43c8?, 0xc0030afce0?}, 0xc0006cb310)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/grpc_provider.go:1153 +0xd5c
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0xc001967340, {0x174f43c8?, 0xc0030afa10?}, 0xc0006cb310)
	github.com/hashicorp/terraform-plugin-mux@v0.16.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000f8c000, {0x174f43c8?, 0xc0030af050?}, 0xc001acc0e0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/tf5server/server.go:865 +0x3d0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1500c680, 0xc000f8c000}, {0x174f43c8, 0xc0030af050}, 0xc00116ad80, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:518 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0009f8200, {0x174f43c8, 0xc0030aefc0}, {0x17559500, 0xc000506000}, 0xc0030b0b40, 0xc00274eb70, 0x20d0b618, 0x0)
	google.golang.org/grpc@v1.63.2/server.go:1369 +0xdf8
google.golang.org/grpc.(*Server).handleStream(0xc0009f8200, {0x17559500, 0xc000506000}, 0xc0030b0b40)
	google.golang.org/grpc@v1.63.2/server.go:1780 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 26
	google.golang.org/grpc@v1.63.2/server.go:1030 +0x125

Error: The terraform-provider-aws_v5.62.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

2024/08/13 09:27:03 INFO Deployment criado:  1718897256="missing value"
2024/08/13 09:27:03 INFO Deployment Status ID:  4310784725="missing value"

Dynamic environment variables added:
GOOGLE_CREDENTIALS

Dynamic environment variables added:
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
AWS_SESSION_TOKEN
```

### Terraform Configuration Files

I wrote an module, that we could use to deploy any stack_set template. It's simple and is composed by the following resources:

1. ``random_id``:  To create an random id to compose the stackset_name(cause it needs to be unique in the region)
2. ``aws_cloudformation_stack_set`` :  That create the stackset, based on an yml template, that has the content of an variable called, var.stackset.
3. ``aws_cloudformation_stack_set_instance "stack_set_instance_org_application" ``: Responsible for deployment of stackset in the target accounts in the entire organization
4. ``aws_cloudformation_stack_set_instance "stack_set_instance_accounts_application"``:  Responsible for deployment of stackset in the target accounts individualy.

I'm attaching the module created and the calling module that i've made to work with it.

[calling_module.zip](https://github.com/user-attachments/files/16599765/calling_module.zip)
[module-stack-set.zip](https://github.com/user-attachments/files/16599769/module-stack-set.zip)

### Steps to Reproduce

1. Get the module and the calling module and unpack it in some folder.
2. Configure the backend and provider credencials, in the calling module.
3. Change the reference for the source in the calling module, to get to the source of the module-stack-set
4. With all changes done, verify the .yml file in the ``cross-account-policies.d``, the var.stackset get the values from there
5. With everything ok, just plan in the folder of calling module.
6. The plan, must be ok
7. Then try to apply
8. You'll get the error that i've specified earlier.

### Panic Output

```console
running "## check diferent paths to terraform in atlantis\nif [ -f \"/atlantis-data/bin/terraform$ATLANTIS_TERRAFORM_VERSION\" ]\nthen\n  /atlantis-data/bin/terraform$ATLANTIS_TERRAFORM_VERSION apply  $PLANFILE \nelse\n  /usr/local/bin/terraform$ATLANTIS_TERRAFORM_VERSION apply  $PLANFILE\nfi\n\nif [ $? -eq 0 ]; then\n  export GITHUB_DEPLOYMENT_STATUS=success\n  /opt/deployments\n  sh /opt/ddog-logs.sh >/dev/null 2>&1\nelse\n  export GITHUB_DEPLOYMENT_STATUS=failure\n  /opt/deployments\n  sh /opt/ddog-logs.sh >/dev/null 2>&1\nfi\n/opt/slack_notify >/dev/null 2>&1\nif [ $GITHUB_DEPLOYMENT_STATUS == \"failure\" ];\nthen\n  exit 1\nelse\n  exit 0\nfi\n" in "/atlantis-data/repos/stone-payments/foundation-govcloud-infrastructure/799/prd/aws/applications/iam/policies/cross-account-policies": exit status 1: running "## check diferent paths to terraform in atlantis\nif [ -f \"/atlantis-data/bin/terraform$ATLANTIS_TERRAFORM_VERSION\" ]\nthen\n  /atlantis-data/bin/terraform$ATLANTIS_TERRAFORM_VERSION apply  $PLANFILE \nelse\n  /usr/local/bin/terraform$ATLANTIS_TERRAFORM_VERSION apply  $PLANFILE\nfi\n\nif [ $? -eq 0 ]; then\n  export GITHUB_DEPLOYMENT_STATUS=success\n  /opt/deployments\n  sh /opt/ddog-logs.sh >/dev/null 2>&1\nelse\n  export GITHUB_DEPLOYMENT_STATUS=failure\n  /opt/deployments\n  sh /opt/ddog-logs.sh >/dev/null 2>&1\nfi\n/opt/slack_notify >/dev/null 2>&1\nif [ $GITHUB_DEPLOYMENT_STATUS == \"failure\" ];\nthen\n  exit 1\nelse\n  exit 0\nfi\n" in "/atlantis-data/repos/stone-payments/foundation-govcloud-infrastructure/799/prd/aws/applications/iam/policies/cross-account-policies": 
module.cross-account-policy["ssmsessionmanagerrunshelly"].aws_cloudformation_stack_set_instance.stack_set_instance_accounts_application[0]: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with module.cross-account-policy["ssmsessionmanagerrunshelly"].aws_cloudformation_stack_set_instance.stack_set_instance_accounts_application[0],
│   on ../../../../modules/stack-set/main.tf line 46, in resource "aws_cloudformation_stack_set_instance" "stack_set_instance_accounts_application":
│   46: resource "aws_cloudformation_stack_set_instance" "stack_set_instance_accounts_application" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-aws_v5.62.0_x5 plugin:

panic: unexpected format for ID parts ([ssmsessionmanagerrunshellyb48c0a7221604959  us-east-1]), the following id parts indexes are blank ([1])

goroutine 362 [running]:
github.com/hashicorp/terraform-provider-aws/internal/errs.Must[...](...)
	github.com/hashicorp/terraform-provider-aws/internal/errs/must.go:13
github.com/hashicorp/terraform-provider-aws/internal/service/cloudformation.resourceStackSetInstanceCreate({0x174f43c8, 0xc0039964b0}, 0xc00116b780, {0x15222820, 0xc0026a8680})
	github.com/hashicorp/terraform-provider-aws/internal/service/cloudformation/stack_set_instance.go:272 +0x985
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).Create.interceptedHandler[...].func8(0xc00116b780?, {0x15222820?, 0xc0026a8680})
	github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:113 +0x283
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x174f43c8?, {0x174f43c8?, 0xc0030afda0?}, 0xd?, {0x15222820?, 0xc0026a8680?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:801 +0x7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000cae8c0, {0x174f43c8, 0xc0030afda0}, 0xc002fe4d00, 0xc00116b600, {0x15222820, 0xc0026a8680})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:937 +0xa89
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0036ad0e0, {0x174f43c8?, 0xc0030afce0?}, 0xc0006cb310)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/grpc_provider.go:1153 +0xd5c
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0xc001967340, {0x174f43c8?, 0xc0030afa10?}, 0xc0006cb310)
	github.com/hashicorp/terraform-plugin-mux@v0.16.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000f8c000, {0x174f43c8?, 0xc0030af050?}, 0xc001acc0e0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/tf5server/server.go:865 +0x3d0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1500c680, 0xc000f8c000}, {0x174f43c8, 0xc0030af050}, 0xc00116ad80, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:518 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0009f8200, {0x174f43c8, 0xc0030aefc0}, {0x17559500, 0xc000506000}, 0xc0030b0b40, 0xc00274eb70, 0x20d0b618, 0x0)
	google.golang.org/grpc@v1.63.2/server.go:1369 +0xdf8
google.golang.org/grpc.(*Server).handleStream(0xc0009f8200, {0x17559500, 0xc000506000}, 0xc0030b0b40)
	google.golang.org/grpc@v1.63.2/server.go:1780 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 26
	google.golang.org/grpc@v1.63.2/server.go:1030 +0x125

Error: The terraform-provider-aws_v5.62.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

2024/08/13 09:27:03 INFO Deployment criado:  1718897256="missing value"
2024/08/13 09:27:03 INFO Deployment Status ID:  4310784725="missing value"
```

Dynamic environment variables added:
GOOGLE_CREDENTIALS

Dynamic environment variables added:
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
AWS_SESSION_TOKEN

### Important Factoids

I use atlantis tool to perform terraform plan and apply

### Would you like to implement a fix?

None

**Comment by theipster** [comment]
I can also confirm that the underlying AWS CloudFormation API itself does support this use-case (i.e. using `DeploymentTargets.Accounts` without any `DeploymentTargets.OrganizationalUnitIds`), but only for self-managed stack sets not service-managed.

This can be verified via AWS CLI, with the same results via the org management account or via a delegated admin account (adjust CLI args as necessary):

```console
# SELF-MANAGED

$ aws cloudformation create-stack-set --permission-model SELF_MANAGED [...]
{
  "StackSetId": "..."
}

$ aws cloudformation create-stack-instances --deployment-targets Accounts=0123456789012 [...]
{
  "OperationId": "..."
}

# SERVICE-MANAGED

$ aws cloudformation create-stack-set --permission-model SERVICE_MANAGED [...]
{
  "StackSetId": "..."
}

$ aws cloudformation create-stack-instances --deployment-targets Accounts=0123456789012 [...]
An error occurred (ValidationError) when calling the CreateStackInstances operation: OrganizationalUnitIds are required
```

**Comment by jar-b** [comment]
Thanks for the bug report, @rodolfosouzastone and the additional context @theipster. I believe there are two issues here.

1. The create method is (incorrectly) assuming that when `deployment_targets` are provided, organizational unit IDs are required and attempts to use those values in the composite identifier. As noted in the comment above, this is not the case for self-managed stack sets, and the provider should prefer account ID for this section of the identifier instead.
2. The step to create the composite ID is unnecessarily wrapped by a panic. Because of ☝️ , part of the composite identifier is currently left empty when deployment target without an OU is configured. However, this should result in an error diagnostic, not a crash of the plugin.

I'm working on a fix for both issues, but wanted to provide some context for the behavior observed here.
