### ISSUE TITLE
[Bug]: Simple Email Service SES configuration set crash

### ISSUE THREAD

**Issue by ckhsponge** [hashicorp/terraform-provider-aws#38934]
### Terraform Core Version

1.8.4

### AWS Provider Version

5.63.0

### Affected Resource(s)

I believe the error is from: aws_ses_configuration_set

I was also applying these at the same time as the crash:
aws_ses_domain_identity
aws_dynamodb_table
aws_iam_role
aws_route53_record
aws_ses_email_identity
aws_ses_receipt_rule_set
aws_iam_user
aws_iam_policy
aws_s3_bucket

### Expected Behavior

I expected resources to be created.

### Actual Behavior

Crash.

### Relevant Error/Panic Output Snippet

```shell
Stack trace from the terraform-provider-aws_v5.63.0_x5 plugin:

panic: interface conversion: interface {} is bool, not *bool

goroutine 101 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/ses.resourceConfigurationSetCreate({0x119d3aa28, 0x140044fc510}, 0x1400449cf00, {0x119a611e0, 0x14003cdd2b0})
	github.com/hashicorp/terraform-provider-aws/internal/service/ses/configuration_set.go:130 +0xc4c
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).Create.interceptedHandler[...].func8(0x1400449cf00?, {0x119a611e0?, 0x14003cdd2b0})
	github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:113 +0x1d8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x119d3aa28?, {0x119d3aa28?, 0x140044e94d0?}, 0xd?, {0x119a611e0?, 0x14003cdd2b0?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:801 +0x64
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1400258ce00, {0x119d3aa28, 0x140044e94d0}, 0x140044aba00, 0x1400449cd80, {0x119a611e0, 0x14003cdd2b0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:937 +0x884
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1400263d1b8, {0x119d3aa28?, 0x140044e9410?}, 0x14004486f50)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/grpc_provider.go:1153 +0xaa4
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0x1400103ff10, {0x119d3aa28?, 0x140044e9140?}, 0x14004486f50)
	github.com/hashicorp/terraform-plugin-mux@v0.16.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x184
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x140001c2960, {0x119d3aa28?, 0x140044e8960?}, 0x14000e2d880)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/tf5server/server.go:865 +0x2b4
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x119869d20, 0x140001c2960}, {0x119d3aa28, 0x140044e8960}, 0x1400449ca80, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:518 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x140001ffc00, {0x119d3aa28, 0x140044e88d0}, {0x119da5aa0, 0x14001b14780}, 0x140044ea5a0, 0x14003d803c0, 0x1234baff8, 0x0)
	google.golang.org/grpc@v1.63.2/server.go:1369 +0xb58
google.golang.org/grpc.(*Server).handleStream(0x140001ffc00, {0x119da5aa0, 0x14001b14780}, 0x140044ea5a0)
	google.golang.org/grpc@v1.63.2/server.go:1780 +0xb20
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.63.2/server.go:1019 +0x8c
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 16
	google.golang.org/grpc@v1.63.2/server.go:1030 +0x13c

Error: The terraform-provider-aws_v5.63.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Configuration Files

Here is the module:
https://github.com/ckhsponge/ckhtech-modules/tree/main/email

`
module email {
  source = "https://github.com/ckhsponge/ckhtech-modules/tree/main/email"

  aws_region = "us-east-1"
  environment = "production"
  service    = "crash"
  namespace = "email"
  domain     = "mydomain.com"
  from = "bob@mydomain.com"
  forward_to = "charlie@mydomain.com"
}
`

### Steps to Reproduce

Apply the module.

### Would you like to implement a fix?

None

**Comment by jar-b** [comment]
Hi @ckhsponge 👋 - thanks for the report! This has been fixed via #38921, and will ship with the next release. I'm going to close this out and tag it with the appropriate milestone.
