### ISSUE TITLE
[Bug]: Error: The terraform-provider-aws_v5.65.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by rahul-aryan** [hashicorp/terraform-provider-aws#39343]
### Terraform Core Version

1.9.5

### AWS Provider Version

5.65

### Affected Resource(s)

aws_vpc_dhcp_options

### Expected Behavior

the plan is getting successfull, so ideally the resource should have been created but insted it threw me error

### Actual Behavior

Plugin crashed on apply while creating the resource aws vpc dhcp options.

### Relevant Error/Panic Output Snippet

```shell
Error: Plugin did not respond
│
│   with module.vpc["vpc_1"].aws_vpc_dhcp_options.dhcp_options["config1"],
│   on terraform-aws-vpc/main.tf line 13, in resource "aws_vpc_dhcp_options" "dhcp_options":
│   13: resource "aws_vpc_dhcp_options" "dhcp_options" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.vpc["vpc_1"].aws_vpc.vpc,
│   on terraform-aws-vpc/main.tf line 1, in resource "aws_vpc" "vpc":
│    1: resource "aws_vpc" "vpc" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-aws_v5.65.0_x5 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 90 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.(*dhcpOptionsMap).resourceDataToDHCPConfigurations(0xc003135110?, 0xc002001580)
        github.com/hashicorp/terraform-provider-aws/internal/service/ec2/vpc_dhcp_options.go:301 +0x657
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.resourceVPCDHCPOptionsCreate({0x17dffe88, 0xc0028348a0}, 0xc002001580, {0x15d3bce0, 0xc003135110})
        github.com/hashicorp/terraform-provider-aws/internal/service/ec2/vpc_dhcp_options.go:113 +0xa5
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).Create.interceptedHandler[...].func8(0xc002001580?, {0x15d3bce0?, 0xc003135110})
        github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:113 +0x283
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x17dffe88?, {0x17dffe88?, 0xc00281d4d0?}, 0xd?, {0x15d3bce0?, 0xc003135110?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:801 +0x7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00102e2a0, {0x17dffe88, 0xc00281d4d0}, 0xc0028265b0, 0xc002001400, {0x15d3bce0, 0xc003135110})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:937 +0xa69
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc004317140, {0x17dffe88?, 0xc00281d410?}, 0xc001e8c500)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/grpc_provider.go:1153 +0xd5c
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0xc000dd17a0, {0x17dffe88?, 0xc00281d140?}, 0xc001e8c500)
        github.com/hashicorp/terraform-plugin-mux@v0.16.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc001d40be0, {0x17dffe88?, 0xc00281c780?}, 0xc001b61730)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/tf5server/server.go:865 +0x3bc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x15b56640, 0xc001d40be0}, {0x17dffe88, 0xc00281c780}, 0xc002000c00, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:518 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003c5600, {0x17dffe88, 0xc00281c6f0}, {0x17e6e0a0, 0xc003244000}, 0xc002824b40, 0xc0031df4a0, 0x217cb5b8, 0x0)
        google.golang.org/grpc@v1.66.0/server.go:1393 +0xe11
google.golang.org/grpc.(*Server).handleStream(0xc0003c5600, {0x17e6e0a0, 0xc003244000}, 0xc002824b40)
        google.golang.org/grpc@v1.66.0/server.go:1804 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.66.0/server.go:1029 +0x7f
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 23
        google.golang.org/grpc@v1.66.0/server.go:1040 +0x125


Error: The terraform-provider-aws_v5.65.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Operation failed: failed running terraform apply (exit 1)
```

### Terraform Configuration Files

```hcl
 terraform {
   required_providers {
     aws = {
       source  = "hashicorp/aws"
       version = "~> 5"
     }
   }
 
   cloud {
     organization = "Planview"
     workspaces {
       name = "<workspace_name>"
     }
   }
 }
```

### Steps to Reproduce

terraform init
terraform plan
terraform apply

### Debug Output

```
Error: Plugin did not respond
│
│   with module.vpc["vpc_1"].aws_vpc_dhcp_options.dhcp_options["config1"],
│   on terraform-aws-vpc/main.tf line 13, in resource "aws_vpc_dhcp_options" "dhcp_options":
│   13: resource "aws_vpc_dhcp_options" "dhcp_options" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.vpc["vpc_1"].aws_vpc.vpc,
│   on terraform-aws-vpc/main.tf line 1, in resource "aws_vpc" "vpc":
│    1: resource "aws_vpc" "vpc" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-aws_v5.65.0_x5 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 90 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.(*dhcpOptionsMap).resourceDataToDHCPConfigurations(0xc003135110?, 0xc002001580)
        github.com/hashicorp/terraform-provider-aws/internal/service/ec2/vpc_dhcp_options.go:301 +0x657
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.resourceVPCDHCPOptionsCreate({0x17dffe88, 0xc0028348a0}, 0xc002001580, {0x15d3bce0, 0xc003135110})
        github.com/hashicorp/terraform-provider-aws/internal/service/ec2/vpc_dhcp_options.go:113 +0xa5
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).Create.interceptedHandler[...].func8(0xc002001580?, {0x15d3bce0?, 0xc003135110})
        github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:113 +0x283
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x17dffe88?, {0x17dffe88?, 0xc00281d4d0?}, 0xd?, {0x15d3bce0?, 0xc003135110?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:801 +0x7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00102e2a0, {0x17dffe88, 0xc00281d4d0}, 0xc0028265b0, 0xc002001400, {0x15d3bce0, 0xc003135110})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:937 +0xa69
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc004317140, {0x17dffe88?, 0xc00281d410?}, 0xc001e8c500)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/grpc_provider.go:1153 +0xd5c
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0xc000dd17a0, {0x17dffe88?, 0xc00281d140?}, 0xc001e8c500)
        github.com/hashicorp/terraform-plugin-mux@v0.16.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc001d40be0, {0x17dffe88?, 0xc00281c780?}, 0xc001b61730)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/tf5server/server.go:865 +0x3bc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x15b56640, 0xc001d40be0}, {0x17dffe88, 0xc00281c780}, 0xc002000c00, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:518 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003c5600, {0x17dffe88, 0xc00281c6f0}, {0x17e6e0a0, 0xc003244000}, 0xc002824b40, 0xc0031df4a0, 0x217cb5b8, 0x0)
        google.golang.org/grpc@v1.66.0/server.go:1393 +0xe11
google.golang.org/grpc.(*Server).handleStream(0xc0003c5600, {0x17e6e0a0, 0xc003244000}, 0xc002824b40)
        google.golang.org/grpc@v1.66.0/server.go:1804 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.66.0/server.go:1029 +0x7f
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 23
        google.golang.org/grpc@v1.66.0/server.go:1040 +0x125


Error: The terraform-provider-aws_v5.65.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Operation failed: failed running terraform apply (exit 1)

### Panic Output

Error: Plugin did not respond
│
│   with module.vpc["vpc_1"].aws_vpc_dhcp_options.dhcp_options["config1"],
│   on terraform-aws-vpc/main.tf line 13, in resource "aws_vpc_dhcp_options" "dhcp_options":
│   13: resource "aws_vpc_dhcp_options" "dhcp_options" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.vpc["vpc_1"].aws_vpc.vpc,
│   on terraform-aws-vpc/main.tf line 1, in resource "aws_vpc" "vpc":
│    1: resource "aws_vpc" "vpc" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-aws_v5.65.0_x5 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 90 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.(*dhcpOptionsMap).resourceDataToDHCPConfigurations(0xc003135110?, 0xc002001580)
        github.com/hashicorp/terraform-provider-aws/internal/service/ec2/vpc_dhcp_options.go:301 +0x657
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.resourceVPCDHCPOptionsCreate({0x17dffe88, 0xc0028348a0}, 0xc002001580, {0x15d3bce0, 0xc003135110})
        github.com/hashicorp/terraform-provider-aws/internal/service/ec2/vpc_dhcp_options.go:113 +0xa5
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).Create.interceptedHandler[...].func8(0xc002001580?, {0x15d3bce0?, 0xc003135110})
        github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:113 +0x283
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x17dffe88?, {0x17dffe88?, 0xc00281d4d0?}, 0xd?, {0x15d3bce0?, 0xc003135110?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:801 +0x7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00102e2a0, {0x17dffe88, 0xc00281d4d0}, 0xc0028265b0, 0xc002001400, {0x15d3bce0, 0xc003135110})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:937 +0xa69
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc004317140, {0x17dffe88?, 0xc00281d410?}, 0xc001e8c500)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/grpc_provider.go:1153 +0xd5c
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0xc000dd17a0, {0x17dffe88?, 0xc00281d140?}, 0xc001e8c500)
        github.com/hashicorp/terraform-plugin-mux@v0.16.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc001d40be0, {0x17dffe88?, 0xc00281c780?}, 0xc001b61730)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/tf5server/server.go:865 +0x3bc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x15b56640, 0xc001d40be0}, {0x17dffe88, 0xc00281c780}, 0xc002000c00, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:518 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003c5600, {0x17dffe88, 0xc00281c6f0}, {0x17e6e0a0, 0xc003244000}, 0xc002824b40, 0xc0031df4a0, 0x217cb5b8, 0x0)
        google.golang.org/grpc@v1.66.0/server.go:1393 +0xe11
google.golang.org/grpc.(*Server).handleStream(0xc0003c5600, {0x17e6e0a0, 0xc003244000}, 0xc002824b40)
        google.golang.org/grpc@v1.66.0/server.go:1804 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.66.0/server.go:1029 +0x7f
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 23
        google.golang.org/grpc@v1.66.0/server.go:1040 +0x125


Error: The terraform-provider-aws_v5.65.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Operation failed: failed running terraform apply (exit 1)
```

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/b4a786003ca62e6755e8f1f68c9f62f20c445dcc/internal/service/ec2/vpc_dhcp_options.go#L298-L305
