### ISSUE TITLE
[Bug]: Crash Whilst Updating Amplify Domain Association

### ISSUE THREAD

**Issue by Obliie** [hashicorp/terraform-provider-aws#39890]
### Terraform Core Version

1.9.7

### AWS Provider Version

5.70.0

### Affected Resource(s)

module.amplify_app.aws_amplify_domain_association

### Expected Behavior

Update the domain association of an Amplify app branch

### Actual Behavior

The terraform provider crashed

### Relevant Error/Panic Output Snippet

```shell
module.amplify_app.aws_amplify_domain_association.default["XXXXXXXXXXXXXXX.com"]: Modifying... [id=XXXXXXXXXXXXXXX/XXXXXXXXXXXXXXX.com]
╷
│ Error: Plugin did not respond
│ 
│   with module.amplify_app.aws_amplify_domain_association.default["XXXXXXXXXXXXXXX.com"],
│   on .terraform/modules/amplify_app/main.tf line 99, in resource "aws_amplify_domain_association" "default":
│   99: resource "aws_amplify_domain_association" "default" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.lambda_report_service.module.lambda_service.module.lambda_function.aws_lambda_function.this[0],
│   on .terraform/modules/lambda_report_service.lambda_service.lambda_function/main.tf line 24, in resource "aws_lambda_function" "this":
│   24: resource "aws_lambda_function" "this" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.lambda_user_service.module.lambda_service.module.lambda_function.aws_lambda_function.this[0],
│   on .terraform/modules/lambda_user_service.lambda_service.lambda_function/main.tf line 24, in resource "aws_lambda_function" "this":
│   24: resource "aws_lambda_function" "this" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-aws_v5.70.0_x5 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 354 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/amplify.resourceDomainAssociationUpdate({0x1ae18ee8, 0xc0060c82a0}, 0xc005fea680, {0x18a35220, 0xc0013bd5f0})
        github.com/hashicorp/terraform-provider-aws/internal/service/amplify/domain_association.go:216 +0xbaf
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).Update.interceptedHandler[...].func10(0xc005fea680?, {0x18a35220?, 0xc0013bd5f0})
        github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:113 +0x283
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x1ae18ee8?, {0x1ae18ee8?, 0xc006088c90?}, 0xd?, {0x18a35220?, 0xc0013bd5f0?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:835 +0x7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003a3b20, {0x1ae18ee8, 0xc006088c90}, 0xc005fc9930, 0xc005fea500, {0x18a35220, 0xc0013bd5f0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:947 +0x81a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc003a214b8, {0x1ae18ee8?, 0xc006088bd0?}, 0xc005ffa870)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/grpc_provider.go:1153 +0xd5c
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0xc0014931f0, {0x1ae18ee8?, 0xc006088900?}, 0xc005ffa870)
        github.com/hashicorp/terraform-plugin-mux@v0.16.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0006aa000, {0x1ae18ee8?, 0xc006088120?}, 0xc005fbeaf0)
        github.com/hashicorp/terraform-plugin-go@v0.24.0/tfprotov5/tf5server/server.go:865 +0x3bc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1887ce20, 0xc0006aa000}, {0x1ae18ee8, 0xc006088120}, 0xc005fea180, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.24.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:545 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0020ee200, {0x1ae18ee8, 0xc006088090}, {0x1ae90860, 0xc0041ba000}, 0xc005f0ea20, 0xc001e8b1d0, 0x256da7f8, 0x0)
        google.golang.org/grpc@v1.66.2/server.go:1394 +0xe2b
google.golang.org/grpc.(*Server).handleStream(0xc0020ee200, {0x1ae90860, 0xc0041ba000}, 0xc005f0ea20)
        google.golang.org/grpc@v1.66.2/server.go:1805 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.66.2/server.go:1029 +0x7f
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 68
        google.golang.org/grpc@v1.66.2/server.go:1040 +0x125

Error: The terraform-provider-aws_v5.70.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Configuration Files

context.tf https://gist.github.com/Obliie/40be4db1389306455472d35f3871c8b3
amplify.tf https://gist.github.com/Obliie/077a6747b78afcfad17abd23d6aa4a46

### Steps to Reproduce

1. Create an Amplify app with a branch that has a custom domain association via terraform
2. Manually create a new branch and change the domain association to point to that branch
3. Terraform plan, apply. The provider will crash when trying to change the domain association back to the original branch

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/575959be1d26aba89fd5bf150d79de945066d9ed/internal/service/amplify/domain_association.go#L215-L217

**Comment by taraspos** [comment]
Just got the same panic on 5.77.0


```go
Stack trace from the terraform-provider-aws_v5.77.0_x5 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 58 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/amplify.resourceDomainAssociationUpdate({0x1b78a528, 0xc003382690}, 0xc0033d4e00, {0x192ebd20, 0xc001bfe300})
	github.com/hashicorp/terraform-provider-aws/internal/service/amplify/domain_association.go:216 +0xbaf
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).Update.interceptedHandler[...].func11(0xc0033d4e00?, {0x192ebd20?, 0xc001bfe300})
	github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:113 +0x283
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x1b78a528?, {0x1b78a528?, 0xc003144330?}, 0xd?, {0x192ebd20?, 0xc001bfe300?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.35.0/helper/schema/resource.go:835 +0x7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0002fda40, {0x1b78a528, 0xc003144330}, 0xc001fe71e0, 0xc0033d4c80, {0x192ebd20, 0xc001bfe300})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.35.0/helper/schema/resource.go:947 +0x81a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc002d7c420, {0x1b78a528?, 0xc003144270?}, 0xc00310c780)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.35.0/helper/schema/grpc_provider.go:1155 +0xd5c
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0xc0006b7580, {0x1b78a528?, 0xc003123f20?}, 0xc00310c780)
	github.com/hashicorp/terraform-plugin-mux@v0.17.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc001395400, {0x1b78a528?, 0xc003123740?}, 0xc0009c4fc0)
	github.com/hashicorp/terraform-plugin-go@v0.25.0/tfprotov5/tf5server/server.go:865 +0x3bc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x19180620, 0xc001395400}, {0x1b78a528, 0xc003123740}, 0xc0033d4900, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.25.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:611 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc001651200, {0x1b78a528, 0xc0031236b0}, {0x1b80aaa0, 0xc002d81520}, 0xc0030a0ea0, 0xc002dbde00, 0x2655bd38, 0x0)
	google.golang.org/grpc@v1.68.0/server.go:1394 +0xe2b
google.golang.org/grpc.(*Server).handleStream(0xc001651200, {0x1b80aaa0, 0xc002d81520}, 0xc0030a0ea0)
	google.golang.org/grpc@v1.68.0/server.go:1805 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.68.0/server.go:1029 +0x7f
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 15
	google.golang.org/grpc@v1.68.0/server.go:1040 +0x125

Error: The terraform-provider-aws_v5.77.0_x5 plugin crashed!
```

**Comment by taraspos** [comment]
I tried to work-around the issue by setting:
```
  certificate_settings {
    type                   = "AMPLIFY_MANAGED"
    custom_certificate_arn = null
  }
```

However, instead of the panic I'm getting:
> │ Error: creating Amplify Domain Association (REDACTED): operation error Amplify: CreateDomainAssociation, https response error StatusCode: 400, RequestID: b3f06e4c-6648-4982-bbdb-f9a6e493a309, api error ValidationException: 1 validation error detected: Value '' at 'certificateSettings.customCertificateArn' failed to satisfy constraint: Member must satisfy regular expression pattern: ^arn:aws:acm:[a-z0-9-]+:\d{12}:certificate\/.+$

**Comment by taraspos** [comment]
I have fix for this issue in:
- https://github.com/hashicorp/terraform-provider-aws/pull/40351

Would appreciate if someone could take a look - @ewbankkit @johnsonaj
