### ISSUE TITLE
[Bug]: Error: The terraform-provider-aws_v5.73.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by DoyleDev** [hashicorp/terraform-provider-aws#39936]
### Terraform Core Version

1.7.1

### AWS Provider Version

5.46.0

### Affected Resource(s)

aws_route53_record: 

```hcl
resource "aws_route53_record" "example_east_record" {
  zone_id  = data.aws_route53_zone.example_domain.zone_id
  name     = "example_name"
  type     = "A"

  alias {
    name                   = aws_lb.example.dns_name
    zone_id                = aws_lb.example.zone_id
    evaluate_target_health = true
  }

  set_identifier = "us-east-2"

  geolocation_routing_policy {
    country = "US"
  }
}
```

### Expected Behavior

Route 53 record is made with geolocation_routing_policy

### Actual Behavior

```console
Stack trace from the terraform-provider-aws_v5.73.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 113 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/route53.expandResourceRecordSet(0xc0044e6f00, {0xc000cf5450, 0xf})
github.com/hashicorp/terraform-provider-aws/internal/service/route53/record.go:950 +0x1405
github.com/hashicorp/terraform-provider-aws/internal/service/route53.resourceRecordCreate({0x1b1757e8, 0xc004996990}, 0xc0044e6f00, {0x18d4bce0, 0xc002c9d2b0})
github.com/hashicorp/terraform-provider-aws/internal/service/route53/record.go:360 +0x1fd
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).Create.interceptedHandler[...].func9(0xc0044e6f00?, {0x18d4bce0?, 0xc002c9d2b0})
github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:113 +0x283
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1b1757e8?, {0x1b1757e8?, 0xc004859440?}, 0xd?, {0x18d4bce0?, 0xc002c9d2b0?})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:801 +0x7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc002e27b20, {0x1b1757e8, 0xc004859440}, 0xc004817d40, 0xc0044e6d80, {0x18d4bce0, 0xc002c9d2b0})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:937 +0xa69
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc002ca0348, {0x1b1757e8?, 0xc004859380?}, 0xc00486c230)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/grpc_provider.go:1153 +0xd5c
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0xc000a124d0, {0x1b1757e8?, 0xc0048590b0?}, 0xc00486c230)
github.com/hashicorp/terraform-plugin-mux@v0.16.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc001f02b40, {0x1b1757e8?, 0xc0048588d0?}, 0xc001c6bf10)
github.com/hashicorp/terraform-plugin-go@v0.24.0/tfprotov5/tf5server/server.go:865 +0x3bc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x18b8fe60, 0xc001f02b40}, {0x1b1757e8, 0xc0048588d0}, 0xc0044e6b00, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.24.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:545 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000e06600, {0x1b1757e8, 0xc004858840}, {0x1b1f2800, 0xc002c25a00}, 0xc004870120, 0xc000ff97d0, 0x25c5b298, 0x0)
google.golang.org/grpc@v1.66.2/server.go:1394 +0xe2b
google.golang.org/grpc.(*Server).handleStream(0xc000e06600, {0x1b1f2800, 0xc002c25a00}, 0xc004870120)
google.golang.org/grpc@v1.66.2/server.go:1805 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
google.golang.org/grpc@v1.66.2/server.go:1029 +0x7f
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 50
google.golang.org/grpc@v1.66.2/server.go:1040 +0x125

Error: The terraform-provider-aws_v5.73.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Relevant Error/Panic Output Snippet

```console
Stack trace from the terraform-provider-aws_v5.73.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 113 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/route53.expandResourceRecordSet(0xc0044e6f00, {0xc000cf5450, 0xf})
github.com/hashicorp/terraform-provider-aws/internal/service/route53/record.go:950 +0x1405
github.com/hashicorp/terraform-provider-aws/internal/service/route53.resourceRecordCreate({0x1b1757e8, 0xc004996990}, 0xc0044e6f00, {0x18d4bce0, 0xc002c9d2b0})
github.com/hashicorp/terraform-provider-aws/internal/service/route53/record.go:360 +0x1fd
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).Create.interceptedHandler[...].func9(0xc0044e6f00?, {0x18d4bce0?, 0xc002c9d2b0})
github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:113 +0x283
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1b1757e8?, {0x1b1757e8?, 0xc004859440?}, 0xd?, {0x18d4bce0?, 0xc002c9d2b0?})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:801 +0x7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc002e27b20, {0x1b1757e8, 0xc004859440}, 0xc004817d40, 0xc0044e6d80, {0x18d4bce0, 0xc002c9d2b0})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:937 +0xa69
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc002ca0348, {0x1b1757e8?, 0xc004859380?}, 0xc00486c230)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/grpc_provider.go:1153 +0xd5c
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0xc000a124d0, {0x1b1757e8?, 0xc0048590b0?}, 0xc00486c230)
github.com/hashicorp/terraform-plugin-mux@v0.16.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc001f02b40, {0x1b1757e8?, 0xc0048588d0?}, 0xc001c6bf10)
github.com/hashicorp/terraform-plugin-go@v0.24.0/tfprotov5/tf5server/server.go:865 +0x3bc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x18b8fe60, 0xc001f02b40}, {0x1b1757e8, 0xc0048588d0}, 0xc0044e6b00, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.24.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:545 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000e06600, {0x1b1757e8, 0xc004858840}, {0x1b1f2800, 0xc002c25a00}, 0xc004870120, 0xc000ff97d0, 0x25c5b298, 0x0)
google.golang.org/grpc@v1.66.2/server.go:1394 +0xe2b
google.golang.org/grpc.(*Server).handleStream(0xc000e06600, {0x1b1f2800, 0xc002c25a00}, 0xc004870120)
google.golang.org/grpc@v1.66.2/server.go:1805 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
google.golang.org/grpc@v1.66.2/server.go:1029 +0x7f
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 50
google.golang.org/grpc@v1.66.2/server.go:1040 +0x125

Error: The terraform-provider-aws_v5.73.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Configuration Files

```hcl
resource "aws_route53_record" "example_east_record" {
  zone_id  = data.aws_route53_zone.example_domain.zone_id
  name     = "example_name"
  type     = "A"

  alias {
    name                   = aws_lb.example.dns_name
    zone_id                = aws_lb.example.zone_id
    evaluate_target_health = true
  }

  set_identifier = "us-east-2"

  geolocation_routing_policy {
    country = "US"
  }
}
```

### Steps to Reproduce

Terraform plan
Terraform apply

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/1977363a134f59ecfe3ebbd90c97dd8fad94336d/internal/service/route53/record.go#L948-L957

**Comment by ewbankkit** [comment]
I can reproduce this with an empty (`""`) value for `geolocation_routing_policy.country`.
