### ISSUE TITLE
[Bug]: terraform-provider-aws_v5.76.0_x5 plugin crashed for eks_addon

### ISSUE THREAD

**Issue by asimerel** [hashicorp/terraform-provider-aws#40165]
### Terraform Core Version

v1.5.7

### AWS Provider Version

v5.76.0

### Affected Resource(s)

* aws_eks_addon

### Expected Behavior

Addon configuration would be changed from using irsa to pod identity

### Actual Behavior

terraform apply command is not working because plugin crashes

### Relevant Error/Panic Output Snippet

```shell
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-aws_v5.76.0_x5 plugin:

panic: interface conversion: interface {} is *schema.Set, not []interface {}

goroutine 353 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/eks.resourceAddonUpdate({0x1196189a8, 0x14001bbedb0}, 0x14006991c00, {0x1192eeb60, 0x140003aaa00})
        github.com/hashicorp/terraform-provider-aws/internal/service/eks/addon.go:289 +0xdac
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).Update.interceptedHandler[...].func11(0x14006991c00?, {0x1192eeb60?, 0x140003aaa00})
        github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:113 +0x1d8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x1196189a8?, {0x1196189a8?, 0x140019e8ea0?}, 0xd?, {0x1192eeb60?, 0x140003aaa00?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.35.0/helper/schema/resource.go:835 +0x64
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x14001899c00, {0x1196189a8, 0x140019e8ea0}, 0x140069c25b0, 0x14006991a80, {0x1192eeb60, 0x140003aaa00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.35.0/helper/schema/resource.go:947 +0x660
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x14002d944b0, {0x1196189a8?, 0x140019e8ae0?}, 0x14004cf2050)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.35.0/helper/schema/grpc_provider.go:1155 +0xaa4
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0x14001323a00, {0x1196189a8?, 0x140019e3f20?}, 0x14004cf2050)
        github.com/hashicorp/terraform-plugin-mux@v0.17.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x184
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x140021172c0, {0x1196189a8?, 0x140019dd440?}, 0x140069cf7a0)
        github.com/hashicorp/terraform-plugin-go@v0.25.0/tfprotov5/tf5server/server.go:865 +0x2a8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x119186d80, 0x140021172c0}, {0x1196189a8, 0x140019dd440}, 0x14006991700, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.25.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:611 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400159d000, {0x1196189a8, 0x140019dd170}, {0x1196985c0, 0x14002fba000}, 0x14003f85440, 0x14002dd7d40, 0x1241083f8, 0x0)
        google.golang.org/grpc@v1.67.1/server.go:1394 +0xb64
google.golang.org/grpc.(*Server).handleStream(0x1400159d000, {0x1196985c0, 0x14002fba000}, 0x14003f85440)
        google.golang.org/grpc@v1.67.1/server.go:1805 +0xb20
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.67.1/server.go:1029 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 52
        google.golang.org/grpc@v1.67.1/server.go:1040 +0x13c

Error: The terraform-provider-aws_v5.76.0_x5 plugin crashed!
```

### Terraform Configuration Files

#before
```
resource "aws_eks_addon" "aws_ebs_csi_driver" {
  cluster_name                = "some_cluster"
  addon_name                  = "aws-ebs-csi-driver"
  resolve_conflicts_on_update = "OVERWRITE"
  service_account_role_arn    = "some_role_arn"
}
```
#after
```
resource "aws_eks_addon" "aws_ebs_csi_driver" {
  cluster_name                = "some_cluster"
  addon_name                  = "aws-ebs-csi-driver"
  resolve_conflicts_on_update = "OVERWRITE"
  pod_identity_association {
    role_arn        = "some_pod_identity_role_arn"
    service_account = "ebs-csi-controller-sa"
  }
}
```

### Steps to Reproduce

Create aws eks addon with `service_account_role_arn` then change it to use pod identity with deleting `service_account_role_arn` and adding `pod_identity_association`.
The terraform apply after changing addon from using IRSA to Pod Identity crashes

### Would you like to implement a fix?

No

**Comment by jar-b** [comment]
Relates #39973
