### ISSUE TITLE
[Bug]: Unable to add resource group using resource ARN

### ISSUE THREAD

**Issue by dhruvtailor7** [hashicorp/terraform-provider-aws#40504]
### Terraform Core Version

1.10.0

### AWS Provider Version

5.80.0

### Affected Resource(s)

aws_resourcegroups_resource

### Expected Behavior

Should add resource to the resource group.

### Actual Behavior

Crash with following error

```
Stack trace from the terraform-provider-aws_v5.80.0_x5 plugin:

panic: runtime error: index out of range [1] with length 1

goroutine 90 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/resourcegroups.resourceResourceCreate({0x1bf4df28, 0xc0043964b0}, 0xc00438c480, {0x19a134a0, 0xc00183a200})
github.com/hashicorp/terraform-provider-aws/internal/service/resourcegroups/resource.go:66 +0x785
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).Create.interceptedHandler[...].func9(0xc00438c480?, {0x19a134a0?, 0xc00183a200})
github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:113 +0x283
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1bf4df28?, {0x1bf4df28?, 0xc0043878f0?}, 0xd?, {0x19a134a0?, 0xc00183a200?})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.35.0/helper/schema/resource.go:801 +0x7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc001588a80, {0x1bf4df28, 0xc0043878f0}, 0xc0040cb520, 0xc00438c300, {0x19a134a0, 0xc00183a200})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.35.0/helper/schema/resource.go:937 +0xa69
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc002d3e438, {0x1bf4df28?, 0xc004387830?}, 0xc0040f7180)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.35.0/helper/schema/grpc_provider.go:1155 +0xd5c
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0xc001824b00, {0x1bf4df28?, 0xc004387560?}, 0xc0040f7180)
github.com/hashicorp/terraform-plugin-mux@v0.17.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc001ae6000, {0x1bf4df28?, 0xc004386ba0?}, 0xc000877650)
github.com/hashicorp/terraform-plugin-go@v0.25.0/tfprotov5/tf5server/server.go:865 +0x3bc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x198a2340, 0xc001ae6000}, {0x1bf4df28, 0xc004386ba0}, 0xc00408da80, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.25.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:611 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002c6a00, {0x1bf4df28, 0xc004386b10}, {0x1bfd00a0, 0xc002ebe1a0}, 0xc0043886c0, 0xc002ea2cc0, 0x27050dd8, 0x0)
google.golang.org/grpc@v1.68.0/server.go:1394 +0xe2b
google.golang.org/grpc.(*Server).handleStream(0xc0002c6a00, {0x1bfd00a0, 0xc002ebe1a0}, 0xc0043886c0)
google.golang.org/grpc@v1.68.0/server.go:1805 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
google.golang.org/grpc@v1.68.0/server.go:1029 +0x7f
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 75
google.golang.org/grpc@v1.68.0/server.go:1040 +0x125

Error: The terraform-provider-aws_v5.80.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Configuration Files

resource "aws_resourcegroups_group" "test_1" {
  name = "resources-group-1"

  resource_query {
    query = jsonencode({
      ResourceTypeFilters = [
        "AWS::ApiGatewayV2::Api",
        "AWS::CloudFront::Distribution",
        "AWS::S3::Bucket",
        "AWS::CodeBuild::Project"
      ]
      TagFilters = [
        {
          Key    = "Project"
          Values = "value"
        },
        {
          Key    = "Environment"
          Values = "value"
        }
      ]
    })
  }
}

resource "aws_secretsmanager_secret" "test_1" {
  name = "secret-d"
}

 resource "aws_resourcegroups_resource" "dev_secret" {
   group_arn    = aws_resourcegroups_group.test_1.arn
   resource_arn = aws_secretsmanager_secret.test_1.arn
}

### Steps to Reproduce

Run `terraform apply`

### Panic Output

Stack trace from the terraform-provider-aws_v5.80.0_x5 plugin:

panic: runtime error: index out of range [1] with length 1

goroutine 90 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/resourcegroups.resourceResourceCreate({0x1bf4df28, 0xc0043964b0}, 0xc00438c480, {0x19a134a0, 0xc00183a200})
github.com/hashicorp/terraform-provider-aws/internal/service/resourcegroups/resource.go:66 +0x785
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).Create.interceptedHandler[...].func9(0xc00438c480?, {0x19a134a0?, 0xc00183a200})
github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:113 +0x283
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1bf4df28?, {0x1bf4df28?, 0xc0043878f0?}, 0xd?, {0x19a134a0?, 0xc00183a200?})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.35.0/helper/schema/resource.go:801 +0x7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc001588a80, {0x1bf4df28, 0xc0043878f0}, 0xc0040cb520, 0xc00438c300, {0x19a134a0, 0xc00183a200})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.35.0/helper/schema/resource.go:937 +0xa69
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc002d3e438, {0x1bf4df28?, 0xc004387830?}, 0xc0040f7180)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.35.0/helper/schema/grpc_provider.go:1155 +0xd5c
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0xc001824b00, {0x1bf4df28?, 0xc004387560?}, 0xc0040f7180)
github.com/hashicorp/terraform-plugin-mux@v0.17.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc001ae6000, {0x1bf4df28?, 0xc004386ba0?}, 0xc000877650)
github.com/hashicorp/terraform-plugin-go@v0.25.0/tfprotov5/tf5server/server.go:865 +0x3bc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x198a2340, 0xc001ae6000}, {0x1bf4df28, 0xc004386ba0}, 0xc00408da80, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.25.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:611 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002c6a00, {0x1bf4df28, 0xc004386b10}, {0x1bfd00a0, 0xc002ebe1a0}, 0xc0043886c0, 0xc002ea2cc0, 0x27050dd8, 0x0)
google.golang.org/grpc@v1.68.0/server.go:1394 +0xe2b
google.golang.org/grpc.(*Server).handleStream(0xc0002c6a00, {0x1bfd00a0, 0xc002ebe1a0}, 0xc0043886c0)
google.golang.org/grpc@v1.68.0/server.go:1805 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
google.golang.org/grpc@v1.68.0/server.go:1029 +0x7f
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 75
google.golang.org/grpc@v1.68.0/server.go:1040 +0x125

Error: The terraform-provider-aws_v5.80.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Would you like to implement a fix?

None

**Comment by jar-b** [comment]
Failure to split these ARN inputs should be handled instead of implicitly trusted to be the correct format.

https://github.com/hashicorp/terraform-provider-aws/blob/97d16066f80edb193abe7123454919b7a2d0a40d/internal/service/resourcegroups/resource.go#L66

**Comment by stefanfreitag** [comment]
Hi @jar-b ,
I was going through the list of open issues and noticed that with #40458 we may have a duplicate.
The provider is crashing at same line of code with same reason: assuming that resource ARNs have an "/".

I am not sure how such a handling could look like based on the variations of ARNs that could show up (here we have SecretsManager Secrets, in the other ticket it is a Lambda function, but to my understanding also SNS topics and SQS queues are affected).

**Comment by jar-b** [comment]
I'm of the opinion we should just make the `id` a comma-delimited string of group ARN and resource ARN. This resource does not (currently) support import so we aren't breaking any workflows by changing the format.
